In [1]:
!git config --global user.email "clement.dilasser@croix-rouge.fr"
!git clone https://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@github.com/clementsouk-aloun-dot/Code-PAT.git

Cloning into 'Code-PAT'...
remote: Enumerating objects: 1458, done.
remote: Counting objects: 100% (197/197), done.
remote: Compressing objects: 100% (153/153), done.
remote: Total 1458 (delta 94), reused 68 (delta 44), pack-reused 1261 (from 2)
Receiving objects: 100% (1458/1458), 8.34 MiB | 5.08 MiB/s, done.
Resolving deltas: 100% (976/976), done.

In [4]:
%cd Code-PAT
!git checkout GAIA-+-NOMINATION-+-impact

[Errno 2] No such file or directory: 'Code-PAT'
/content/Code-PAT
error: pathspec 'GAIA-+-NOMINATION-+-impact' did not match any file(s) known to git

In [5]:
!git add .

In [7]:
!git commit -m "ajout vérification GAIA IMPACT NOMINATION"

[main a5e968c] ajout vérification GAIA IMPACT NOMINATION
 3 files changed, 93 insertions(+), 3 deletions(-)

In [ ]:
!git fetch origin

remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 26 (delta 16), reused 11 (delta 6), pack-reused 0 (from 0)
Unpacking objects: 100% (26/26), 44.70 KiB | 594.00 KiB/s, done.
From https://github.com/clementsouk-aloun-dot/Code-PAT
   62d77d1..b55b60c  GAIA-+-NOMINATION-+-impact -> origin/GAIA-+-NOMINATION-+-impact
   4100e22..ede9011  Domiciliation         -> origin/Domiciliation
   671f580..0d32fe1  Données-manuelles-ACA -> origin/Données-manuelles-ACA

In [ ]:
!git config pull.rebase true

In [ ]:
!git pull

Successfully rebased and updated refs/heads/GAIA-+-NOMINATION-+-impact.

In [8]:
!git push

Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 2 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 1.63 KiB | 1.63 MiB/s, done.
Total 6 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To https://github.com/clementsouk-aloun-dot/Code-PAT.git
   c09ad98..a5e968c  main -> main

#INSTALL PACKAGE

In [9]:
!pip install PyPDF2
!pip install reportlab
!pip install PyMuPDF tools
!pip install xlsxwriter

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 5.8 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1
Collecting reportlab
  Downloading reportlab-4.4.10-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.4)
Downloading reportlab-4.4.10-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 23.1 MB/s eta 0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-4.4.10
Collecting PyMuPDF
  Downloading pymupdf-1.27.1-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Collecting tools
  Downloading tools-1.0.23-py3-none-any.whl.metadata (1.3 kB)
Downloading pymupdf-1.27.1-cp310-abi3-manylinux_2_28_x86_64.whl (24.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 MB 61.4 MB/s eta 0:00:00
Downloading tools-1.0.23-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 3.1 MB/s eta 0:00:00
Installing collected packages: tools, PyMuPDF
Successfully installed PyMuPDF-1.27.1 tools-1.0.23
Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 4.6 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9

In [10]:
import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import sys
import io
import re
import shutil
import zipfile
from google.colab import drive, files

from google.colab import auth
from google.auth import default
import unicodedata
import re
import torch
from sentence_transformers import SentenceTransformer, util

Imports des fichiers .py

In [11]:
sys.path.append(os.path.abspath("/content/Code-PAT/scripts_data"))
sys.path.append(os.path.abspath("/content/Code-PAT"))

from pegass import *
from financier import *
from mobilite import *
from manuelles import *
from utils import *
from nomination import *
from impact import *
from gaia import *

#AUTHENTIFICATION

#AUTHENTIFICATION

In [12]:
from google.colab import auth
!gcloud auth application-default login

from google.cloud import bigquery
import pandas as pd

PROJECT_ID = "crf-pat"
client = bigquery.Client(project=PROJECT_ID)

query_ref_nomination = """
SELECT *
FROM crf-pat.dataset_PAT_2025.crf_nomination_ref_nomination
"""

query_nomination = """
SELECT *
FROM crf-pat.dataset_PAT_2025.crf_pat_2025_nomination
"""

query_ref_impact = """
SELECT *
FROM crf-pat.dataset_PAT_2025.crf_impact_ref_indicateur
"""

query_impact = """
SELECT *
FROM crf-pat.dataset_PAT_2025.crf_pat_2025_impact_indicateur_suivi
"""

query_gaia = """
SELECT *
FROM crf-pat.dataset_PAT_2025.crf_pat_2025_rattachement_benevole
"""

Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=4yDNqoqZDrGtsim1GgnTVuf93EVpze&prompt=consent&token_usage=remote&access_type=offline&code_challenge=G_ERxwXHwiURQjC11bEWPSQZy01nBBu-7cFZ8OL7uW0&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0ASc3gC1loFD1UzaCDEDRRO5h6QEF0aWvCAq_RVKkwrIulERpIzVTC__wPO7RvMYvDbsvsA

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.


To take a quick anonymous survey, run:
  $ gcloud survey

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [13]:
# Etape 0 : Préparation de l'environnement

CREDENTIALS_JSON = """
{
  "type": "service_account",
  "project_id": "alexandrevalent",
  "private_key_id": "dba39c84ba4135ce5ede6479a186ad8cde499dee",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvGU4ZJFrBwCBb\nu8s4aPA5bQTOKDkPZEVdNyY//RneR6RC9JPrcbfVfIUaQU7A036sfdhDGFKJbw20\nTZ55fafcH9yCMiUO+Nzek0eogON4TXrXsh8UFtdw8BOuaVkFitU5yg8kFhTnEZtd\ntPfZHW3Aqhd/aDoTOBNgRuF/hVTKQ2ytbCbE77fL2/pz9kvpZ2Zrz3u1lmksSJls\nHIolNwX9R05YqmrkpZ/TMAULFk4bT0VRQng5pmN9AeB61eJLWhlLaEdeu79NWV4B\n7tZd6RzzTFors804aJkmXHM63VRtvGD0UlR0O7w1QlI3ymUxpy5hrjbz6n9bmpMI\nfebvydLnAgMBAAECggEADipn7RTJ2t7mP0WkHT4wIRU2zE7ovtwH2JC7oXWigB8f\npOMQjH24t6bJReR+sI7rspzDwDnZg5DedPXKml2WFPLm7gmMgfeUNtWHeJRk0rjB\n9W1NolxutY5WqUeQkig3M+Oq8epvano8LYqUepYs6OdZ207dU+y3dJSHbb+lqm9D\ntQZR2oBj7W1iZ8fJ+SQLSjU5BztS1CvWuayRd/tLd9Spp0NUn5uQFTKwel9Gazmz\n28IsPPm6SudplFhaGd4kCPvhcg0jGEKe61VYdgHoBzp+EXRWXUvQ+SbMafXtMvoB\nLoUH4X3creKzJQKXnjlDpAzRHMYhJTvHinHXaggdcQKBgQDcJszFOECfSovXFZNq\nMyQOWbesyDb2OQhJLFZCD2QraZm3jPaIPeMfFkmFAumcVal6EzpR5IE8g9jBuLo+\ng6j3NTo5jbGO9WEn4361yEotb+S8t3/DTHvWqXBK7HdUB/KHlyGtctm8yErdMZQB\nvzo03aTwwStNTeFG8GzT1Nd7JQKBgQDLnHIMbx9iAG3K21XCq0Dot2Q63hklJC26\nsJlrTkdXMOIlhpwJ6LTOJe2paHbR56IrKOHQCuLxQFhRd8Eidz1ahjO7D8fKr/TG\nS8/V32FrpONyxhKinLsccSb86S3vvpKCI265z5EEjk/1qnx3TOo6oqA/2DQLv0Q4\nYinmNSOeGwKBgHGjYY3n9IuE6lwy2e42ycTSkNoSWzSLyfgjd78PvNAf6WXy0IsR\nDvzL/1U2ZKn7GclWxYLiJce78xZEKXb9dSluA0kUF/RIO0dgydZBtfBwUq0LN1rz\nTvVGbx1tpEbu90UAQTUMFNK6vNIitliUghIp2usfex+jNMbuce6Cblw1AoGBAKDH\n1gtZiFeT7R7d2jfRkXzyrBQMI6D/k5izMULZ2l3QfROS2w68EmIi8yvuEL2qApXA\nP6hPoGtPGy6huQHlVK5yANF7IZI9JbWcUe8Z6MzetLiCDl8YEmzgMSBPZXXGb9yR\n7DKP5HzLf/qG+KggNWm913ry2A5ap506bsmZNpn3AoGBAM6vvI9tb+AcNfd4ewmY\nAWSb4GLliRTaBIGHYmotfyBEBWpXZq2/0JG32RRf3rYUJWWn/r7K+zrRUqeMwlD+\nz7GuSU+OaSDzYj7fwDyuxOwTJMLrh+AkKbUYBsMF7YH1qIRjBjKNdj1LOznASQMe\nu1E4sNa9RRRujbQw4AEP3Xjl\n-----END PRIVATE KEY-----\n",
  "client_email": "crf-slidemanager@alexandrevalent.iam.gserviceaccount.com",
  "client_id": "101959630014487618959",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/crf-slidemanager%40alexandrevalent.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly']


# Authentification
credentials = service_account.Credentials.from_service_account_info(json.loads(CREDENTIALS_JSON, strict=False), scopes=SCOPES)

# Initialisation des services
slides_service = build('slides', 'v1', credentials=credentials)
drive_service = build('drive', 'v3', credentials=credentials)
gspread_client  = gspread.authorize(credentials)

# Variables globales

In [14]:
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

# CHARGEMENT DE TOUTES LES DONNEES PAR TABLE

# 0. Ref_structure

In [15]:
df_ref_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw/').worksheet('Feuille 1'))

In [16]:
df_ref_structure = renommer_par_nom_table(df_ref_structure, "AS_Informations_structures", mapping_df)
df_ref_structure['n_structure'] = df_ref_structure['n_structure'].astype(int).astype(str)
df_ref_structure.head()

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,Structure_de_rattachement,Rattachements_successifs,DT_de_rattachement,lon,lat
0,2615,ANTENNE LOCALE - AL,AL DE DELLE,90100.0,90033,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",90,2010-02-08 00:00:00,NaT,95 - DT DU TERRITOIRE DE BELFORT,AL 2615,95 - DT DU TERRITOIRE DE BELFORT,7.000705,47.506725
1,2669,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43220.0,43087,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2669,48 - DT DE LA HAUTE LOIRE,4.346423,45.214392
2,2670,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43600.0,43224,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2670,48 - DT DE LA HAUTE LOIRE,4.235474,45.242445
3,2671,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43300.0,43112,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2671,48 - DT DE LA HAUTE LOIRE,3.495645,45.098285
4,2672,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43000.0,43157,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2672,48 - DT DE LA HAUTE LOIRE,3.879748,45.044677

In [17]:
df_ref_structure_DT = df_ref_structure[df_ref_structure['nom_structure'].str.contains('DT')].astype(str)

# 1. PEGASS

In [ ]:
# EXEMPLE :  Charger le DataFrame
# spreadsheet = gspread_client.open_by_url("https://docs.google.com/spreadsheets/d/1WEoWR3dnhy7NL5ISoD6o-58krsttfHkiqaJz30Vvg74/")
# worksheet = spreadsheet.worksheet("Feuille 1")
# df_raw = get_as_dataframe(worksheet)

## 1.1. rattachement_court

In [18]:
rattachement_court = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU/edit?usp=sharing').worksheet('Feuille 1'))

## 1.2. Activité_benevole ref activité

In [ ]:
Ref_activité_benevole = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1rf1gXTylNEHEt72UfwZO62gIfgzf9eY8lPqhXLJ5hs8/edit').worksheet('Feuille 1'))

## 1.3. Pegass_activite / Activite

In [ ]:
Pegass_activite = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13Ygh1goryIgp2UCh19tKaTv3AWkfsSMInuS8-VMbmeU/edit').worksheet('Feuille 1'))

## 1.4. PegassInscription / Inscription

In [ ]:
Pegass_inscription = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1wCYPGwDVKZC6BBuMnOc7kB98agof5IMkdn9W7xn5UUg/edit').worksheet('Feuille 1'))

## 1.5. PREPARATION DE LA BASE DE DONNEES

In [ ]:
Pegass_inscription, Pegass_activite, Ref_activité_benevole = clean_pegass(Pegass_inscription,Pegass_activite,Ref_activité_benevole, mapping_df)

# 2. GAIA

In [19]:
df_gaia_rattachement_benevole = client.query(query_gaia).to_dataframe()
df_gaia_rattachement_benevole.head()

,rattachement_benevole_nivol_id_fk,rattachement_benevole_structure_id_fk,rattachement_benevole_date_debut,rattachement_benevole_date_fin
0,eNozMDAwMDQwsDC1NAoFAA80An8=,1,2010-04-19,NaT
1,eNozMDQ0MDA0MjSwMPMDAA8bAnM=,1,2023-12-29,NaT
2,eNozMDAwMDI0tjSxNPUBAA9TAn4=,1,2018-10-18,NaT
3,eNozMDQ0AAITM2NzXwAPIQJ0,1,2019-05-15,NaT
4,eNozMDAwMDIyNrc0NvcDAA9YAoA=,1,2019-02-08,NaT

# 3. NOMINATION

## 3.1. NOMINATION_ref_nomination

In [20]:
df_ref_nomination = client.query(query_ref_nomination).to_dataframe()
df_ref_nomination.head()

,nomination_id_pk,groupe_nomination_id_fk,nomination_libelle,nomination_libcourt
0,388,1,Responsable Territorial de la Jeunesse,RTJ
1,389,1,Responsable Territorial de la Jeunesse Adjoint,RTJA
2,17,1,Referent departemental jeunesse,RD.J
3,18,1,Referent departemental jeunesse adjoint,RD.J.A
4,49,1,Responsable Local de la Jeunesse,RL.J

## 3.2 NOMINATION_nomination

In [21]:
df_nomination = client.query(query_nomination).to_dataframe()
df_nomination.head()

,nomination_nivol_id_fk,nomination_structure_id_fk,nomination_nomination_id_fk,nomination_date_debut_nomination,nomination_date_fin_nomination
0,eNozMAACIyMTC2MLXwAPMAJ5,305,40,2010-01-01,2025-02-22
1,eNozMAABQxNTcwNfAA8MAm8=,373,40,2010-01-01,2025-04-01
2,eNozMAABI0NjExNHAA7uAmA=,681,40,2010-01-01,2025-07-11
3,eNozMAADYxNLo3AADxECeg==,3697,40,2010-01-01,NaT
4,eNozMAABQyNTEwM3AA7yAmM=,639,40,2013-01-01,NaT

# 4. IMPACT

## 4.1 ref_IMPACT

In [22]:
df_ref_impact = client.query(query_ref_impact).to_dataframe()
df_ref_impact.head()

,impact_indicateur_id_pk,impact_indicateur_libelle,impact_indicateur_groupe_action_id_fk,impact_indicateur_action_id_fk,impact_indicateur_activite_benevole_id_fk,impact_indicateur_type
0,38,Nb beneficiaires pour chaque type d'activite,2,95,10041,Nombre
1,39,Nb total de jours de vacances des beneficiaire...,2,95,10041,Nombre
2,40,Public concerne,2,95,10041,Liste de valeurs
3,280,Nombre de sorties culturelles ou loisirs organ...,2,95,10041,Nombre
4,281,Nombre total de beneficiaires des sorties cult...,2,95,10041,Nombre

## 4.2 Suivi_indicateurs_IMPACT

In [23]:
df_impact = client.query(query_impact).to_dataframe()
df_impact.head()

,impact_activite_benevole_id_fk,impact_activite_benevole_seance_id_fk,impact_structure_id_fk,impact_date_debut,impact_date_fin,impact_indicateur_id_fk,impact_reponse
0,10010,2673433,87,2025-01-21,2025-01-21,815,'35.00'
1,10010,3171022,87,2025-11-27,2025-11-27,815,'51.00'
2,10010,3232551,893,2025-12-17,2025-12-17,815,'42.00'
3,10011,3186164,80,2025-11-13,2025-11-13,815,'7.50'
4,10012,3148887,80,2025-10-30,2025-10-30,815,'18.00'

In [ ]:
df_impact.dtypes

impact_activite_benevole_id_fk            Int64
impact_activite_benevole_seance_id_fk     Int64
impact_structure_id_fk                    Int64
impact_date_debut                        dbdate
impact_date_fin                          dbdate
impact_indicateur_id_fk                   Int64
impact_reponse                           object
dtype: object

In [27]:
clean_gaia(client)

,rattachement_benevole_nivol_id_fk,rattachement_benevole_structure_id_fk,rattachement_benevole_date_debut,rattachement_benevole_date_fin
0,eNozMDAwMDQwsDC1NAoFAA80An8=,1,2010-04-19,NaT
1,eNozMDQ0MDA0MjSwMPMDAA8bAnM=,1,2023-12-29,NaT
2,eNozMDAwMDI0tjSxNPUBAA9TAn4=,1,2018-10-18,NaT
3,eNozMDQ0AAITM2NzXwAPIQJ0,1,2019-05-15,NaT
4,eNozMDAwMDIyNrc0NvcDAA9YAoA=,1,2019-02-08,NaT
...,...,...,...,...
100412,eNozMAACM1MLY3ODEAAPYQKC,3974,2024-10-09,2026-02-03
100413,eNozMDAwMDSyMDYwNnUGAA8nAmo=,3995,2018-01-07,2026-02-03
100414,eNozMDQ0MDAwN7O0MHcGAA9mAns=,4736,2024-05-23,2026-02-03
100415,eNozMDQ0MDA0NDUxMA4FAA8iAnY=,4736,2024-05-23,2026-02-03
100416,eNozMDQ0MDAwMzIwNw0FAA8zAnw=,4736,2024-05-23,2026-02-03

In [28]:
clean_nomination(client)

(     nomination_id_pk  groupe_nomination_id_fk  \
 0                 388                        1
 1                 389                        1
 2                  17                        1
 3                  18                        1
 4                  49                        1
 ..                ...                      ...
 380               299                       17
 381               300                       17
 382               301                       17
 383               391                       17
 384               405                       17

                                     nomination_libelle nomination_libcourt
 0               Responsable Territorial de la Jeunesse                 RTJ
 1       Responsable Territorial de la Jeunesse Adjoint                RTJA
 2                      Referent departemental jeunesse                RD.J
 3              Referent departemental jeunesse adjoint              RD.J.A
 4                     Responsable Local de la Jeunesse                RL.J
 ..                                                 ...                 ...
 380                                 Referent Log-Admin           REF LOGAD
 381                                    Referent Relief          REF RELIEF
 382                                    Referent Watsan          REF WATSAN
 383  Responsable Territorial Action Internationale ...               RTAID
 384  Responsable Local Action Internationale Decent...               RLAID

 [385 rows x 4 columns],
              nomination_nivol_id_fk  nomination_structure_id_fk  \
 0          eNozMAACIyMTC2MLXwAPMAJ5                         305
 1          eNozMAABQxNTcwNfAA8MAm8=                         373
 2          eNozMAABI0NjExNHAA7uAmA=                         681
 3          eNozMAADYxNLo3AADxECeg==                        3697
 4          eNozMAABQyNTEwM3AA7yAmM=                         639
 ...                             ...                         ...
 10672  eNozMDAwMDQyMzAzMQ8GAA87An4=                         860
 10673      eNozMDQAASNLEzMvAA8XAnE=                        1236
 10674  eNozMDAwMLS0MDC1tIgAAA-KApE=                        1242
 10675      eNozMAACI0tLC2NDZwAPWwJ0                        4654
 10676      eNozMAACC2MLc0tDFwAPawJ5                         687

        nomination_nomination_id_fk nomination_date_debut_nomination  \
 0                               40                       2010-01-01
 1                               40                       2010-01-01
 2                               40                       2010-01-01
 3                               40                       2010-01-01
 4                               40                       2013-01-01
 ...                            ...                              ...
 10672                         1019                       2025-12-18
 10673                         1019                       2025-12-21
 10674                         1019                       2025-12-25
 10675                         1019                       2025-12-26
 10676                         1019                       2025-12-31

       nomination_date_fin_nomination
 0                         2025-02-22
 1                         2025-04-01
 2                         2025-07-11
 3                                NaT
 4                                NaT
 ...                              ...
 10672                            NaT
 10673                            NaT
 10674                            NaT
 10675                     2025-12-26
 10676                            NaT

 [10677 rows x 5 columns])

In [29]:
clean_impact(client)

(     impact_indicateur_id_pk  \
 0                         38
 1                         39
 2                         40
 3                        280
 4                        281
 ..                       ...
 755                      838
 756                      839
 757                      817
 758                        2
 759                        8

                              impact_indicateur_libelle  \
 0         Nb beneficiaires pour chaque type d'activite
 1    Nb total de jours de vacances des beneficiaire...
 2                                      Public concerne
 3    Nombre de sorties culturelles ou loisirs organ...
 4    Nombre total de beneficiaires des sorties cult...
 ..                                                 ...
 755                                 Nombre de sessions
 756                                    Tranches d’age
 757      Nombre d'heures de benevolat issues de Pegass
 758                  Nombre de personnes sensibilisees
 759                                               Lieu

      impact_indicateur_groupe_action_id_fk  impact_indicateur_action_id_fk  \
 0                                        2                              95
 1                                        2                              95
 2                                        2                              95
 3                                        2                              95
 4                                        2                              95
 ..                                     ...                             ...
 755                                     10                             122
 756                                     10                             122
 757                                     10                            <NA>
 758                                     14                              93
 759                                     14                              93

      impact_indicateur_activite_benevole_id_fk impact_indicateur_type
 0                                        10041                 Nombre
 1                                        10041                 Nombre
 2                                        10041       Liste de valeurs
 3                                        10041                 Nombre
 4                                        10041                 Nombre
 ..                                         ...                    ...
 755                                       <NA>                 Nombre
 756                                       <NA>       Liste de valeurs
 757                                       <NA>                 Nombre
 758                                      10010                 Nombre
 759                                      10012       Liste de valeurs

 [760 rows x 6 columns],
         impact_activite_benevole_id_fk  impact_activite_benevole_seance_id_fk  \
 0                                10010                                2673433
 1                                10010                                3171022
 2                                10010                                3232551
 3                                10011                                3186164
 4                                10012                                3148887
 ...                                ...                                    ...
 369520                           11177                                3054150
 369521                           11177                                3054150
 369522                           11177                                3054150
 369523                           11180                                3205194
 369524                           11180                                3206563

         impact_structure_id_fk impact_date_debut impact_date_fin  \
 0                           87        2025-01-21      2025-01-21
 1                           87        2025-11-27      2025-11-27
 2                          893        2025-12-17      2025-12-17
 3                           80        2025-11-13      2025-11-13
 4                           80        2025-10-30      2025-10-30
 ...                        ...               ...             ...
 369520                     725        2025-11-04      2025-11-04
 369521                     725        2025-11-04      2025-11-04
 369522                     725        2025-11-04      2025-11-04
 369523                     883        2025-12-10      2025-12-10
 369524                     883        2025-11-01      2025-11-01

         impact_indicateur_id_fk impact_reponse
 0                           815        '35.00'
 1                           815        '51.00'
 2                           815        '42.00'
 3                           815         '7.50'
 4                           815        '18.00'
 ...                         ...            ...
 369520                      826         '6.00'
 369521                      828       'Autres'
 369522                      817         '2.00'
 369523                      815         '5.00'
 369524                      815         '5.00'

 [369525 rows x 7 columns])

# 5. Données financières

In [ ]:
financier = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c')

In [ ]:
dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute, dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute = import_clean_donnees_financieres(financier,df_ref_structure,mapping_df)

In [ ]:
# 6. Mobilité

mobilite = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1dvxT58WR-FqdT-4r-A9ca4vaA9FG7IXHJJaTbnjio8A/')

In [ ]:
df_mobilite = filtres_mobilite(mobilite,mapping_df)

## 5.2 Financier DPS

In [ ]:
financier_DPS = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/145xeh1LkmYzTSW2zeAwHqmLyjmw_tobICHf-oXZmUFI/').worksheet('Base Smtw 03.03.25'))

## 5.3 Financier FGP

In [ ]:
financier_FGP = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13J2zfbmLTILtGYtE_sM-ME8B0pNEwBeGJ1Gg5vKLeOc/').worksheet('DT_Prod'))

In [ ]:
financier_FGP

,Région,Dptmt,N° Structure,N° Smartview,Nom Structure,Réalisé 2021 Total Année,Réalisé 2022 Total Année,Réalisé 2023 Total Année,Reprévision 9 2024 Total Année,Réalisé 2024 Total Année,Unnamed: 10,Unnamed: 11,Variation Réel 24/Réel 23\n\nen €uros,Variation Reprev24 /Réel 24\n\nen €uros
0,AUVERGNE RHONE ALPES,D,01,ORDD001,AIN,922778.39,959737.28,881847.34,8.082371e+05,869883.02,ok,OR,-11964.32,61645.950000
1,AUVERGNE RHONE ALPES,D,03,ORDD003,ALLIER,258032.19,242334.13,274750.70,2.632936e+05,281212.64,ok,OR,6461.94,17919.026667
2,AUVERGNE RHONE ALPES,D,07,ORDD007,ARDÈCHE,164466.54,243465.22,179073.48,2.361657e+05,250747.99,ok,OR,71674.51,14582.330000
3,AUVERGNE RHONE ALPES,D,15,ORDD015,CANTAL,63757.95,50073.56,42236.30,4.410800e+04,98744.62,ok,OR,56508.32,54636.620000
4,AUVERGNE RHONE ALPES,D,26,ORDD026,DRÔME,1074799.56,1163770.36,1061919.22,1.070820e+06,1060115.15,ok,OR,-1804.07,-10704.984667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,PAYS DE LA LOIRE,D,53,ORDD053,MAYENNE,261102.40,338528.21,339095.64,3.418158e+05,395031.88,ok,OR,55936.24,53216.062560
105,PAYS DE LA LOIRE,D,72,ORDD072,SARTHE,2527791.69,2127549.90,2086597.24,2.181244e+06,2215727.76,ok,OR,129130.52,34483.472222
106,PAYS DE LA LOIRE,D,85,ORDD085,VENDÉE,1001149.17,909276.26,572137.51,7.227897e+05,719197.19,ok,OR,147059.68,-3592.550000
107,NaN,NaN,NaN,NaN,Total,88643547.32,88521273.77,90179785.56,8.549541e+07,91388923.98,ok,NaN,NaN,NaN
108,NaN,NaN,Source: Smartview-Mise à jour 24 mars 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ok,NaN,NaN,NaN

# 7. Données manuelles

## 7.1 OCR

In [ ]:
df_OCR = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ccRoyPycFDwvQvacvmHjfE87LtnlzUgtoRbITkC0pVQ/').worksheet('Feuille 1'))

## 7.2 PST

In [ ]:
df_PST = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1yifNna4Hsn5RihkRg50g9h1yKjuRjfolrjsWonEHnrQ').worksheet('Données'))

## 7.3 Déclenchements

In [ ]:
df_declenchement = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1y9jehT5fStcEWCF0pxAP7BdiI62VY3JM_hQzFftbcZA').worksheet('Feuille 1'))

## 7.4 RedCall

In [ ]:
df_redcall = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1EQzq0K8RY2Liyq-jtggX0bTlnOk9cwUTmf4t6c5_CiI').worksheet('structure-stats_2025-01-01_2025-12-31_min-1 (1)'))

## 7.5 CHAI CHU CMCC

In [ ]:
df_CAICHUCMCC = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/12nZY2leRCMn71NGAEUUtA0Pes598gOfeufDStxSCcnY').worksheet('Toutes données'))

## 7.6 Conventions

In [ ]:
df_conventions = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1OYSSkUhWwVpWne9EygH1EEz8EJnFjSeAOEpQQe9utiM').worksheet('Feuille 1'))

## 7.7 Textile

In [ ]:
df_raw_Textile = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1QYuKZo5lVI0HN4BWtk0v7bVFY2a2p4c72a0gU0ltWac/').worksheet('Liste des PAV'))

In [ ]:
def sheet_to_dataframe(client, url, sheet_index=0, sheet_name=None, header_row=1, show_all_sheet = False):
    """
    Ouvre une feuille Google Sheets et crée un DataFrame Pandas à partir de ses données.

    Cette fonction prend en entrée l'URL de la feuille Google Sheets, un client Google Sheets autorisé,
    l'index de la page souhaitée ou le nom de la feuille, et la ligne utilisée comme en-tête. Elle renvoie les données de la
    feuille sous forme de DataFrame Pandas.

    Args:
        url (str): L'URL de la feuille Google Sheets.
        client (gspread.Client): Client Google Sheets autorisé.
        sheet_index (int, optional): L'index de la page à ouvrir dans la feuille. Par défaut, 0 (première page).
        sheet_name (str, optional): Le nom de la feuille à ouvrir. Si fourni, prioritaire sur sheet_index.
        header_row (int, optional): Le numéro de la ligne à utiliser comme en-têtes de colonnes pour le DataFrame.
                                   Par défaut, 1 (la première ligne de données après l'en-tête de feuille).

    Returns:
        pd.DataFrame: Un DataFrame Pandas contenant les données de la feuille avec la première ligne spécifiée
                      comme en-tête des colonnes.
    """

    # Ouvre la feuille Google Sheets à partir de l'URL
    sheet = client.open_by_url(url)

    # Affiche les feuilles existantes
    worksheets = sheet.worksheets()
    if show_all_sheet:
      print("Feuilles existantes :")
      for idx, worksheet in enumerate(worksheets):
          print(f"    {idx}: {worksheet.title}")

    # Sélectionne la page (worksheet) souhaitée
    if sheet_name:
        worksheet = sheet.worksheet(sheet_name)
    else:
        worksheet = sheet.get_worksheet(sheet_index)

    # Récupère toutes les valeurs de la page
    data = worksheet.get_all_values()

    # Crée le DataFrame en utilisant la ligne spécifiée comme en-tête
    df = pd.DataFrame(data[header_row:], columns=data[header_row - 1])

    print(f"✅ Chargement des données réalisées")
    print(f"    Sheet : {sheet.title}")
    print(f"    Feuille {sheet_index + 1 if not sheet_name else ''} : {worksheet.title} ({len(data) - header_row} lignes et {len(data[header_row - 1])} colonnes)\n")

    return df

In [ ]:
### IMPORT DES DONNEES ###

# Création du DataFrame
df_raw_ProdResTextile = sheet_to_dataframe(gspread_client, "https://docs.google.com/spreadsheets/d/1l7KMjiav3usmLVJIbE2uENfNQCeQuxVeU1h13Cep3qk/",sheet_name="Compil Détail",header_row=7)

df_raw_ProdResTextile

✅ Chargement des données réalisées
    Sheet : Résultat Textile_2020-2024_V1_13 févr 2025
    Feuille  : Compil Détail (1338 lignes et 29 colonnes)

,,,PRODUITS EXPLOITATION,CHARGES EXPLOITATION,RESULTAT EXPLOITATION,GEN RESULTAT NET,,PRODUITS EXPLOITATION,CHARGES EXPLOITATION,RESULTAT EXPLOITATION,...,RESULTAT EXPLOITATION,GEN RESULTAT NET,,PRODUITS EXPLOITATION,CHARGES EXPLOITATION,RESULTAT EXPLOITATION,GEN RESULTAT NET,,Ch action sociale 2024 hors textile,REX 2024/Ch action sociale hors textile 2024
0,ORDRG09,DELEGATIONS REGION AUVERGNE RHONE ALPES,1 662 079,788 403,873 675,873 675,,2 088 213,782 602,1 305 612,...,1 386 425,1 390 150,,2 499 810,943 052,1 556 757,1 538 681,,2 806 579,50%
1,ORDD001,DELEGATIONS DE L'AIN,220 571,87 595,132 976,132 976,,260 724,78 908,181 815,...,200 594,200 594,,313 905,81 514,232 391,232 391,,292 284,69%
2,OR04328,04328 ESPACE PLAINE DE L'AIN,25 717,2 428,23 289,23 289,,28 373,2 214,26 159,...,24 590,24 590,,35 784,10 211,25 574,25 574,,9 761,252%
3,OR04327,04327 ESPACE BASSIN OYONNAXIEN,3 273,2 402,871,871,,6 937,1 847,5 091,...,4 654,4 654,,10 725,4 223,6 503,6 503,,-,
4,OR04326,04326 ESPACE BASSIN BELLEGARDIEN,14 988,1 129,13 859,13 859,,17 097,1 767,15 330,...,16 658,16 658,,24 524,3 036,21 488,21 488,,6 333,263%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,OR01051,01051 MAISON DE LA ROCHE SUR YON,51 440,20 384,31 056,29 248,,57 682,11 995,45 687,...,46 327,46 327,,115 826,73 999,41 827,41 827,,17 813,260%
1334,OR01050,01050 MAISON DE FONTENAY LE COMTE,18 159,6 901,11 259,11 259,,35 703,15 472,20 231,...,40 556,40 556,,60 390,17 619,42 771,42 771,,29 491,138%
1335,OR01049,01049 MAISON DE CHALLANS,40 902,19 755,21 146,21 146,,50 991,19 262,31 729,...,37 216,37 216,,49 550,15 873,33 677,33 677,,52 638,71%
1336,OR00090,00090 DT DE VENDEE,-,-,-,-,,-,-,-,...,-,-,,-,-,-,-,,53 881,0%
1337,,,,,,,,,,,...,,,,,,,,,26 471 599,44%

## 7.7 Préparation

In [ ]:
df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions, df_raw_Textile, df_raw_ProdResTextile = clean_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement, df_redcall, df_CAICHUCMCC, df_conventions, df_raw_Textile, df_raw_ProdResTextile)

Point d'apport possible :  ['Boutique - La Boutique' 'Conteneur' 'Vestiaire' 'Boutique  - Mobile'
 'Autres' 'Boutique - Bébé' 'Boutique - Chez Henry' 'Ressourcerie CRi'
 'Boutique - Recylcerie / Meuble' 'Déchetterie' 'conteneur']

/content/Code-PAT/scripts_data/manuelles.py:103: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['Grand Total', 'Exercice']] = df[['Grand Total', 'Exercice']].fillna(0)
/content/Code-PAT/scripts_data/manuelles.py:156: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Département"] = df["Département"].str.replace(
/content/Code-PAT/scripts_data/manuelles.py:193: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Departement"] = df["Departement"].str.replace(
/content/Code-PAT/scripts_data/manuelles.py:215: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[colonnes_oui_non] = df[colonnes_oui_non].applymap(
/content/Code-PAT/scripts_data/manuelles.py:215: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[colonnes_oui_non] = df[colonnes_oui_non].applymap(
/content/Code-PAT/scripts_data/manuelles.py:219: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Dispositifs_d_urgence Nb_conventions_operateurs'] = (

# FUSION DES TABLES

## 1. Fusion PEGASS activité, inscription, ref_activité_bénévole, rattachement_court

In [ ]:
df2 = fusion_pegass(Pegass_inscription, Pegass_activite, Ref_activité_benevole)

## 2. Fusion GAIA rattachement_action, action, act_str, structure

In [33]:
df_GAIA = fusion_gaia(GAIA_action, GAIA_rattachement_action, GAIA_contact, GAIA_structure, GAIA_act_str)

NameError: name 'fusion_gaia' is not defined

## 3. Fusion NOMINATION nomination, attribution_nomination

In [35]:
df_NOMINATION = fusion_nomination(df_nomination, df_ref_nomination)
df_NOMINATION.head()

AttributeError: Can only use .dt accessor with datetimelike values

## 4. Fusion IMPACT

In [26]:
df_IMPACT = fusion_impact(df_impact, df_ref_impact)

AttributeError: Can only use .dt accessor with datetimelike values

## 5. Fusion Données financières

### 5.1 Fusion des tables

In [ ]:
df_financier_DT, df_financier_DT_UL = fusion_donnees_financieres(dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute,dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute)

### 5.2 Vérifications

In [ ]:
verifier_n_dept(df_financier_DT,df_ref_structure)

 ✅ Aucun doublon
 ✅ Pas de département manquant

In [ ]:
verifier_colonne_structure(df_financier_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

# Calcul des indicateurs

## PEGASS

- Nombre de bénévoles par activité benevole

## Nombre de bénévoles par activité benevole

In [ ]:
Nb_benevoles_distincts, Nb_benevoles_Distribution_alimentaire, Nb_benevoles_Distribution_alimentaire1, Nb_benevoles_Distribution_alimentaire2, Nb_benevoles_Distribution_alimentaire3, Nb_benevoles_Distribution_alimentaire4 = indicateurs_pegass(df2)

## GAIA

- Nombre de bénévoles

In [36]:
nb_benevoles = indicateurs_gaia(df_gaia_rattachement_benevole)

AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
nb_nvx_benevoles = indicateurs_gaia_nvx(df_gaia_rattachement_benevole)

In [ ]:
nb_benevoles_DT = indicateurs_gaia_DT(nb_benevoles,rattachement_court)

In [ ]:
nb_nvx_benevoles_DT = indicateurs_gaia_nvx_DT(nb_nvx_benevoles, rattachement_court)

KeyError: 'Column not found: Nb_nvx_Benevoles_2025'

## NOMINATION

- RTAEO & RLAEO
- RTOCR & RLOCR

In [ ]:
referents_AEO = indicateurs_nomination_AEO(df_NOMINATION, annee=2025)
referents_AEO

   nomination_structure_id_fk  AEO Nb_responsables
0                          34                    1
1                         725                    1
2                         897                    1
3                         960                    1
4                         976                    1
5                         977                    1

In [ ]:
referents_OCR = indicateurs_nomination_OCR(df_NOMINATION, annee=2025)
referents_OCR

    nomination_structure_id_fk  OCR Nb_referents
0                           18                 1
1                           34                 1
2                           42                 1
3                           44                 1
4                           76                 1
5                           81                 1
6                           83                 1
7                           96                 1
8                          103                 1
9                          512                 1
10                         860                 1
11                         883                 1
12                         897                 2
13                         969                 1
14                         976                 1
15                        3945                 1
16                        3959                 1
17                        3986                 1
18                        4062                 1
19                        4394                 1

### DT_Responsables_AEO

In [ ]:
referents_AEO_DT = indicateurs_nominationAEO_DT(referents_AEO, rattachement_court)
referents_AEO_DT

DT_de_rattachement
34 - DT DU FINISTERE    1
64 - DT DU NORD         1
80 - DT DE PARIS        1
83 - DT DES YVELINES    3
Name: AEO Nb_responsables, dtype: int64

### DT_Responsables_OCR

In [ ]:
referents_OCR_DT = indicateurs_nominationOCR_DT(referents_OCR, rattachement_court)
referents_OCR_DT

DT_de_rattachement
103 - DT DE LA MARTINIQUE       1
18 - DT DU CALVADOS             1
34 - DT DU FINISTERE            1
3959 - DT DE LA REUNION         2
3986 - DT DE LA SAVOIE          1
42 - DT D'INDRE ET LOIRE        1
4394 - DT DE HAUTE SAONE        1
44 - DT DU JURA                 2
74 - DT DU RHONE                1
76 - DT DE SAONE ET LOIRE       2
79 - DT DE LA HAUTE SAVOIE      1
80 - DT DE PARIS                2
81 - DT DE LA SEINE MARITIME    1
83 - DT DES YVELINES            3
96 - DT DE L'ESSONNE            1
Name: OCR Nb_referents, dtype: int64

## IMPACT

- Nombre d'agréments territoriaux (Dispos d'urgence)
- Nombre de personnes prises en charge (Dispos d'urgence)

In [ ]:
IMPACT_ppc = indicateurs_impact_ppc(df_IMPACT)
IMPACT_ppc

/content/Code-PAT/scripts_data/impact.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (

     impact_structure_id_fk  Dispositifs_d_urgence Nb_personnes_prises_charge
0                        10                                                40
1                        12                                                38
2                        17                                                 0
3                        18                                               222
4                        20                                                23
..                      ...                                               ...
103                    4082                                                 9
104                    4394                                                 0
105                    4441                                                 4
106                    4631                                                51
107                    4649                                                 0

[108 rows x 2 columns]

In [ ]:
IMPACT_agrementAB = indicateurs_impact_agrementAB(df_IMPACT)
IMPACT_agrementAB

/content/Code-PAT/scripts_data/impact.py:107: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (

    impact_structure_id_fk Dispositifs_d_urgence Nb_agrements
0                       10                                  0
1                       12                                  0
2                       17                                  0
3                       18                                  0
4                       20                                  0
..                     ...                                ...
69                    4082                                  0
70                    4394                                  0
71                    4395                                  0
72                    4631                                  0
73                    4649                                  0

[74 rows x 2 columns]

In [ ]:
IMPACT_agrementDPS = indicateurs_impact_agrementDPS(df_IMPACT)
IMPACT_agrementDPS

/content/Code-PAT/scripts_data/impact.py:136: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMPACT_Urgences['impact_reponse'] = (

    impact_structure_id_fk Secours Nb_agrements_DPS_2025
0                       12                             0
1                       26                             0
2                       33                             0
3                       39                             0
4                       42                             0
5                       47                             0
6                       50                             0
7                       55                             0
8                       59                             0
9                       62                             0
10                      72                             0
11                      73                             0
12                      76                             0
13                      77                             0
14                      83                             0
15                      85                             0
16                      87                             0
17                      89                             0
18                      94                             0
19                      95                             0
20                      97                             0
21                      99                             0
22                     102                             0
23                     241                             0
24                     385                             0
25                     603                             0
26                     832                             0
27                     852                             0
28                     858                             0
29                     870                             0
30                     889                             0
31                     923                             0
32                     967                             0
33                    1010                             0
34                    1162                             0
35                    1167                             0
36                    1214                             0
37                    2570                             0
38                    3959                             0
39                    3968                             0
40                    3986                             0
41                    3997                             0
42                    4017                             0
43                    4082                             0
44                    4394                             0
45                    4395                             0
46                    4631                             0

In [ ]:
df_IMPACT

,impact_activite_benevole_id_fk,impact_activite_benevole_seance_id_fk,impact_structure_id_fk,impact_date_debut,impact_date_fin,impact_indicateur_id_fk,impact_reponse,impact_indicateur_id_pk,impact_indicateur_libelle,impact_indicateur_groupe_action_id_fk,impact_indicateur_action_id_fk,impact_indicateur_activite_benevole_id_fk,impact_indicateur_type
0,10010,2673433,87,2025-01-21,2025-01-21,815,'35.00',<NA>,NaN,<NA>,<NA>,<NA>,NaN
1,10010,3171022,87,2025-11-27,2025-11-27,815,'51.00',<NA>,NaN,<NA>,<NA>,<NA>,NaN
2,10010,3232551,893,2025-12-17,2025-12-17,815,'42.00',<NA>,NaN,<NA>,<NA>,<NA>,NaN
3,10011,3186164,80,2025-11-13,2025-11-13,815,'7.50',<NA>,NaN,<NA>,<NA>,<NA>,NaN
4,10012,3148887,80,2025-10-30,2025-10-30,815,'18.00',<NA>,NaN,<NA>,<NA>,<NA>,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369419,11177,3054150,725,2025-11-04,2025-11-04,826,'6.00',<NA>,NaN,<NA>,<NA>,<NA>,NaN
369420,11177,3054150,725,2025-11-04,2025-11-04,828,'Autres',<NA>,NaN,<NA>,<NA>,<NA>,NaN
369421,11177,3054150,725,2025-11-04,2025-11-04,817,'2.00',<NA>,NaN,<NA>,<NA>,<NA>,NaN
369422,11180,3205194,883,2025-12-10,2025-12-10,815,'5.00',<NA>,NaN,<NA>,<NA>,<NA>,NaN
369423,11180,3206563,883,2025-11-01,2025-11-01,815,'5.00',<NA>,NaN,<NA>,<NA>,<NA>,NaN

In [ ]:
IMPACT_ppc_DT = indicateurs_IMPACTppc_DT(IMPACT_ppc, rattachement_court)
IMPACT_ppc_DT

DT_de_rattachement
10 - DT DES ALPES MARITIMES                40
100 - DT DU VAL D'OISE                    126
12 - DT DES ARDENNES                       38
15 - DT DE L'AUDE                           0
17 - DT DES BOUCHES DU RHONE                0
18 - DT DU CALVADOS                       222
20 - DT DE LA CHARENTE                     23
23 - DT DE LA CORREZE                       0
26 - DT DE LA COTE D'OR                     0
31 - DT DE LA DROME                         0
33 - DT D'EURE ET LOIR                   1000
35 - DT DU GARD                            32
37 - DT DU GERS                          1573
38 - DT DE LA GIRONDE                       0
39 - DT DE L'HERAULT                      345
3959 - DT DE LA REUNION                    54
3968 - DT DE LA DORDOGNE                   49
3969 - DT DES HAUTES PYRENEES              37
3971 - DT DES COTES D'ARMOR                72
3986 - DT DE LA SAVOIE                   1507
3997 - DT DES ALPES DE HAUTE PROVENCE       0
4017 - DT DU VAR                           31
42 - DT D'INDRE ET LOIRE                 1312
43 - DT DE L'ISERE                         67
4394 - DT DE HAUTE SAONE                    0
44 - DT DU JURA                             0
4631 - DT DE SEINE SAINT DENIS             51
4649 - DT DE LA MEUSE                       0
47 - DT DE LA LOIRE                         0
49 - DT DE LA LOIRE ATLANTIQUE             57
50 - DT DU LOIRET                        1466
52 - DT DU LOT ET GARONNE                 427
54 - DT DU MAINE ET LOIRE                  28
55 - DT DE LA MANCHE                      133
57 - DT DE LA HAUTE MARNE                 391
59 - DT DE MEURTHE ET MOSELLE              17
61 - DT DU MORBIHAN                         0
62 - DT DE LA MOSELLE                      42
63 - DT DE LA NIEVRE                        0
64 - DT DU NORD                           220
67 - DT DU PAS DE CALAIS                  143
72 - DT DU BAS RHIN                       418
73 - DT DU HAUT RHIN                       15
76 - DT DE SAONE ET LOIRE                  10
77 - DT DE LA SARTHE                        1
80 - DT DE PARIS                          642
81 - DT DE LA SEINE MARITIME             2141
82 - DT DE LA SEINE ET MARNE               34
83 - DT DES YVELINES                      248
85 - DT DE LA SOMME                       818
86 - DT DU TARN                             1
87 - DT DU TARN ET GARONNE                  3
89 - DT DU VAUCLUSE                        78
90 - DT DE VENDEE                           0
92 - DT DE LA HAUTE VIENNE                  0
94 - DT DE L'YONNE                         65
95 - DT DU TERRITOIRE DE BELFORT          429
96 - DT DE L'ESSONNE                      144
97 - DT DES HAUTS DE SEINE                203
99 - DT DU VAL DE MARNE                   665
Name: Dispositifs_d_urgence Nb_personnes_prises_charge, dtype: int64

In [ ]:
IMPACT_agrementAB_DT = indicateurs_IMPACTagrementAB_DT(IMPACT_agrementAB, rattachement_court)
IMPACT_agrementAB

    impact_structure_id_fk Dispositifs_d_urgence Nb_agrements
0                       10                                  0
1                       12                                  0
2                       17                                  0
3                       18                                  0
4                       20                                  0
..                     ...                                ...
69                    4082                                  0
70                    4394                                  0
71                    4395                                  0
72                    4631                                  0
73                    4649                                  0

[74 rows x 2 columns]

In [ ]:
IMPACT_agrementDPS_DT = indicateurs_IMPACTagrementDPS_DT(IMPACT_agrementDPS, rattachement_court)
IMPACT_agrementDPS_DT

DT_de_rattachement
102 - DT DE LA GUADELOUPE                0
12 - DT DES ARDENNES                     0
17 - DT DES BOUCHES DU RHONE             0
2570 - DT DE LA GUYANE                   0
26 - DT DE LA COTE D'OR                  0
33 - DT D'EURE ET LOIR                   0
39 - DT DE L'HERAULT                     0
3959 - DT DE LA REUNION                  0
3968 - DT DE LA DORDOGNE                 0
3986 - DT DE LA SAVOIE                   0
3997 - DT DES ALPES DE HAUTE PROVENCE    0
4017 - DT DU VAR                         0
42 - DT D'INDRE ET LOIRE                 0
4394 - DT DE HAUTE SAONE                 0
4395 - DT DE L'AVEYRON                   0
4631 - DT DE SEINE SAINT DENIS           0
47 - DT DE LA LOIRE                      0
50 - DT DU LOIRET                        0
54 - DT DU MAINE ET LOIRE                0
55 - DT DE LA MANCHE                     0
59 - DT DE MEURTHE ET MOSELLE            0
62 - DT DE LA MOSELLE                    0
72 - DT DU BAS RHIN                      0
73 - DT DU HAUT RHIN                     0
76 - DT DE SAONE ET LOIRE                0
77 - DT DE LA SARTHE                     0
80 - DT DE PARIS                         0
81 - DT DE LA SEINE MARITIME             0
83 - DT DES YVELINES                     0
85 - DT DE LA SOMME                      0
86 - DT DU TARN                          0
87 - DT DU TARN ET GARONNE               0
89 - DT DU VAUCLUSE                      0
94 - DT DE L'YONNE                       0
95 - DT DU TERRITOIRE DE BELFORT         0
97 - DT DES HAUTS DE SEINE               0
99 - DT DU VAL DE MARNE                  0
Name: Secours Nb_agrements_DPS_2025, dtype: object

## Mobilité


Indicateurs qui nécessitent seulement les données mobilité :

- Nb de structures menant une activité AEO/AAD mobile
- Nombre de personnes accompagnées par des dispositifs AEO/AAD mobiles
<br>
Indicateurs qui nécessitent une fusion avec données AEO/AAD :

- Nombre de bénévoles impliqués dans les activités AEO ou AAD
- Nombre de bénévoles impliqués dans les activités AEO ou AAD

In [ ]:
df_mobilite_DT = indicateurs_mobilite(df_mobilite, df_ref_structure, 'DT_de_rattachement')
df_mobilite_DT_UL = indicateurs_mobilite(df_mobilite, df_ref_structure, 'n_structure')

In [ ]:
verifier_colonne_structure(df_mobilite_DT, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [ ]:
verifier_colonne_structure(df_mobilite_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## Données manuelles

In [ ]:
df_OCR_Nb_deployees, df_Dispositifs_d_urgence_PST, df_declenchement3, df_redcall2, df_CAICHUCMCC_VF, df_conventions2, df_rax_Textile, df_raw_ProdResTextile = indicateurs_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions, df_raw_Textile, df_raw_ProdResTextile, df_ref_structure)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

KeyError: "None of ['N_dept'] are in the columns"

In [ ]:
verifier_colonne_structure(df_OCR_Nb_deployees, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Dispositifs_d_urgence_PST, "n_structure", df_ref_structure)
verifier_colonne_structure(df_declenchement3, "n_structure", df_ref_structure)
verifier_colonne_structure(df_redcall2, "n_structure", df_ref_structure)
verifier_colonne_structure(df_CAICHUCMCC_VF, "n_structure", df_ref_structure)
verifier_colonne_structure(df_conventions2, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 1 code(s) non trouvés dans le référentiel : [47]

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 1 code(s) non trouvés dans le référentiel : [47]

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 761 code(s) non trouvés dans le référentiel : ['1.0', '10.0', '1000.0', '1001.0', '1002.0', '1004.0', '1005.0', '1007.0', '1008.0', '101.0', '1010.0', '1011.0', '1012.0', '1013.0', '1014.0', '1015.0', '1016.0', '1017.0', '1018.0', '1019.0', '1020.0', '1021.0', '1022.0', '1023.0', '1024.0', '1025.0', '1026.0', '1027.0', '1028.0', '1029.0', '1030.0', '1031.0', '1032.0', '1033.0', '1034.0', '1035.0', '1036.0', '1037.0', '1038.0', '1039.0', '1040.0', '1041.0', '1042.0', '1044.0', '1049.0', '105.0', '1050.0', '1051.0', '1052.0', '1053.0', '1054.0', '1055.0', '1056.0', '1058.0', '1059.0', '1060.0', '1061.0', '1062.0', '1063.0', '1064.0', '1065.0', '1066.0', '1067.0', '1068.0', '1069.0', '107.0', '1070.0', '1071.0', '1072.0', '1073.0', '1074.0', '1076.0', '1078.0', '1079.0', '108.0', '1080.0', '1081.0', '1083.0', '1084.0', '1085.0', '1086.0', '1087.0', '1089.0', '109.0', '1090.0', '1091.0', '1092.0', '1093.0', '1094.0', '1095.0', '1096.0', '1097.0', '1098.0', '1099.0', '110.0', '1100.0', '1101.0', '1102.0', '1103.0', '1104.0', '1105.0', '1106.0', '1107.0', '1108.0', '1109.0', '111.0', '1110.0', '1111.0', '1112.0', '1113.0', '1114.0', '1115.0', '1116.0', '1117.0', '1118.0', '1119.0', '112.0', '1120.0', '1121.0', '1122.0', '1123.0', '1124.0', '1126.0', '1128.0', '1129.0', '113.0', '1130.0', '1134.0', '1135.0', '1137.0', '1138.0', '1139.0', '114.0', '1141.0', '1142.0', '1143.0', '1144.0', '1145.0', '1146.0', '1147.0', '1148.0', '1149.0', '115.0', '1150.0', '1151.0', '1152.0', '1153.0', '1154.0', '1155.0', '1156.0', '1158.0', '1159.0', '116.0', '1160.0', '1161.0', '1162.0', '1163.0', '1164.0', '1165.0', '1166.0', '1167.0', '1168.0', '117.0', '1173.0', '1174.0', '1176.0', '1177.0', '1178.0', '1179.0', '118.0', '1180.0', '1181.0', '1183.0', '1184.0', '1185.0', '1187.0', '1188.0', '1189.0', '119.0', '1195.0', '1199.0', '12.0', '1200.0', '1201.0', '1202.0', '1203.0', '1207.0', '1208.0', '121.0', '1219.0', '122.0', '1221.0', '1222.0', '1223.0', '1226.0', '123.0', '1234.0', '1235.0', '1236.0', '1237.0', '1239.0', '124.0', '1240.0', '1241.0', '125.0', '126.0', '127.0', '1287.0', '129.0', '130.0', '1309.0', '131.0', '1310.0', '1315.0', '1317.0', '133.0', '1332.0', '1333.0', '1334.0', '1335.0', '1338.0', '1340.0', '1344.0', '1348.0', '1350.0', '1351.0', '1353.0', '1357.0', '1358.0', '1359.0', '1361.0', '1363.0', '1364.0', '1367.0', '138.0', '139.0', '14.0', '140.0', '141.0', '142.0', '143.0', '144.0', '145.0', '146.0', '147.0', '149.0', '15.0', '150.0', '152.0', '153.0', '155.0', '156.0', '157.0', '158.0', '159.0', '16.0', '160.0', '161.0', '162.0', '163.0', '164.0', '165.0', '166.0', '167.0', '168.0', '169.0', '170.0', '171.0', '172.0', '173.0', '174.0', '175.0', '178.0', '179.0', '180.0', '181.0', '182.0', '184.0', '185.0', '186.0', '188.0', '189.0', '19.0', '190.0', '191.0', '192.0', '193.0', '194.0', '195.0', '196.0', '197.0', '198.0', '199.0', '2.0', '20.0', '200.0', '201.0', '202.0', '203.0', '204.0', '205.0', '206.0', '207.0', '208.0', '21.0', '210.0', '211.0', '212.0', '213.0', '214.0', '215.0', '216.0', '217.0', '218.0', '219.0', '22.0', '220.0', '221.0', '223.0', '224.0', '226.0', '227.0', '23.0', '230.0', '231.0', '232.0', '234.0', '235.0', '236.0', '24.0', '26.0', '268.0', '269.0', '27.0', '28.0', '285.0', '29.0', '3.0', '30.0', '305.0', '31.0', '311.0', '312.0', '313.0', '314.0', '316.0', '317.0', '318.0', '319.0', '32.0', '320.0', '321.0', '322.0', '323.0', '324.0', '326.0', '327.0', '328.0', '33.0', '330.0', '334.0', '335.0', '336.0', '337.0', '338.0', '339.0', '340.0', '341.0', '344.0', '345.0', '346.0', '347.0', '349.0', '350.0', '351.0', '352.0', '353.0', '354.0', '355.0', '356.0', '359.0', '362.0', '363.0', '364.0', '365.0', '366.0', '367.0', '368.0', '369.0', '37.0', '370.0', '372.0', '373.0', '374.0', '375.0', '376.0', '377.0', '378.0', '379.0', '380.0', '382.0', '383.0', '384.0', '386.0', '388.0', '389.0', '39.0', '390.0', '391.0', '392.0', '393.0', '394.0', '395.0', '396.0', '397.0', '398.0', '4.0', '40.0', '401.0', '402.0', '403.0', '404.0', '405.0', '407.0', '409.0', '412.0', '413.0', '414.0', '415.0', '416.0', '417.0', '418.0', '419.0', '42.0', '420.0', '421.0', '422.0', '423.0', '424.0', '425.0', '43.0', '434.0', '439.0', '44.0', '440.0', '441.0', '442.0', '443.0', '444.0', '445.0', '446.0', '447.0', '448.0', '449.0', '450.0', '452.0', '453.0', '458.0', '459.0', '46.0', '460.0', '461.0', '462.0', '463.0', '469.0', '47.0', '472.0', '473.0', '474.0', '475.0', '476.0', '477.0', '478.0', '479.0', '480.0', '481.0', '482.0', '49.0', '490.0', '491.0', '494.0', '497.0', '499.0', '5.0', '50.0', '501.0', '502.0', '504.0', '505.0', '506.0', '507.0', '508.0', '509.0', '51.0', '510.0', '511.0', '512.0', '52.0', '522.0', '53.0', '530.0', '531.0', '532.0', '533.0', '534.0', '536.0', '537.0', '54.0', '540.0', '547.0', '55.0', '559.0', '56.0', '561.0', '562.0', '567.0', '57.0', '579.0', '58.0', '59.0', '594.0', '595.0', '6.0', '60.0', '601.0', '603.0', '604.0', '61.0', '611.0', '62.0', '620.0', '621.0', '63.0', '637.0', '64.0', '645.0', '646.0', '65.0', '654.0', '655.0', '657.0', '66.0', '661.0', '662.0', '663.0', '664.0', '67.0', '672.0', '674.0', '676.0', '678.0', '68.0', '682.0', '687.0', '688.0', '69.0', '692.0', '693.0', '696.0', '7.0', '70.0', '700.0', '702.0', '703.0', '704.0', '705.0', '706.0', '707.0', '71.0', '711.0', '716.0', '718.0', '72.0', '720.0', '721.0', '722.0', '723.0', '724.0', '725.0', '726.0', '727.0', '728.0', '729.0', '73.0', '730.0', '731.0', '732.0', '733.0', '734.0', '735.0', '737.0', '74.0', '745.0', '75.0', '751.0', '757.0', '758.0', '76.0', '768.0', '769.0', '77.0', '770.0', '771.0', '775.0', '78.0', '783.0', '785.0', '79.0', '796.0', '8.0', '80.0', '802.0', '803.0', '808.0', '809.0', '81.0', '815.0', '816.0', '817.0', '82.0', '823.0', '829.0', '83.0', '834.0', '835.0', '839.0', '84.0', '843.0', '849.0', '85.0', '850.0', '851.0', '853.0', '854.0', '855.0', '859.0', '86.0', '864.0', '865.0', '866.0', '867.0', '868.0', '869.0', '87.0', '870.0', '871.0', '872.0', '873.0', '874.0', '875.0', '876.0', '877.0', '878.0', '879.0', '88.0', '880.0', '881.0', '882.0', '883.0', '884.0', '886.0', '887.0', '888.0', '889.0', '89.0', '890.0', '891.0', '892.0', '893.0', '894.0', '895.0', '896.0', '897.0', '898.0', '9.0', '90.0', '900.0', '901.0', '902.0', '903.0', '904.0', '905.0', '906.0', '907.0', '908.0', '909.0', '91.0', '910.0', '911.0', '912.0', '913.0', '914.0', '915.0', '916.0', '917.0', '918.0', '919.0', '92.0', '920.0', '921.0', '922.0', '923.0', '924.0', '925.0', '926.0', '927.0', '929.0', '93.0', '934.0', '936.0', '937.0', '938.0', '939.0', '940.0', '941.0', '942.0', '948.0', '949.0', '950.0', '951.0', '952.0', '953.0', '954.0', '956.0', '957.0', '958.0', '959.0', '960.0', '961.0', '962.0', '964.0', '965.0', '966.0', '967.0', '968.0', '969.0', '970.0', '971.0', '972.0', '973.0', '974.0', '975.0', '981.0', '982.0', '983.0', '984.0', '985.0', '986.0', '987.0', '988.0', '989.0', '990.0', '991.0', '992.0', '993.0', '994.0', '995.0', '996.0', '997.0', '998.0', '999.0']

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [ ]:
Textile_DT, Textile_financier_DT = TEXTILE_DT(df_raw_Textile, df_raw_ProdResTextile, rattachement_court)

## Financier DPS & FGP

### DPS

In [ ]:
df_Secours_ProduitsDPS = indicateur_financier_DPS(financier_DPS, df_ref_structure)

     n_structure  Secours Produits_DPS_2024
19             5                    20998.0
44             6                    53397.0
69             7                    41440.0
94          3997                    57730.0
119            9                    15822.0
...          ...                        ...
2619        3667                        0.0
2644        3668                        NaN
2669        4303                        NaN
2694        1285                        NaN
2719         104                        NaN

[107 rows x 2 columns]

In [ ]:
financier_DPS_DT = indicateur_financier_DPS_DT(df_Secours_ProduitsDPS, rattachement_court)

### FGP

In [ ]:
financier_FGP = indicateur_financier_FGP(financier_FGP, df_ref_structure)

In [ ]:
financier_FGP_DT = indicateur_financier_FGP_DT(financier_FGP, rattachement_court)

# Enregistrement des données

In [ ]:
# Entregistrement du DataFrame
# save_dataframe_to_sheet("1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw", client, df_structure)
# save_dataframe_to_sheet("1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU", client, df_rattachement_court)