In [1]:
!git config --global user.email "clement.dilasser@croix-rouge.fr"
!git clone https://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@github.com/clementsouk-aloun-dot/Code-PAT.git

Cloning into 'Code-PAT'...
remote: Enumerating objects: 997, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 997 (delta 49), reused 33 (delta 31), pack-reused 884 (from 3)
Receiving objects: 100% (997/997), 2.67 MiB | 13.59 MiB/s, done.
Resolving deltas: 100% (617/617), done.

In [2]:
%cd Code-PAT
!git checkout Verified_DonnéesManuelles_SBO

/content/Code-PAT
Branch 'Verified_DonnéesManuelles_SBO' set up to track remote branch 'Verified_DonnéesManuelles_SBO' from 'origin'.
Switched to a new branch 'Verified_DonnéesManuelles_SBO'

In [3]:
!git add .

In [4]:
!git commit -m "Verified_DonnéesManuelles_SBO"

On branch Verified_DonnéesManuelles_SBO
Your branch is up to date with 'origin/Verified_DonnéesManuelles_SBO'.

nothing to commit, working tree clean

In [ ]:
!git fetch origin

remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (6/6), 85.70 KiB | 1.75 MiB/s, done.
From https://github.com/clementsouk-aloun-dot/Code-PAT
   87338f7..baeb842  Mobilité             -> origin/Mobilité
   ef769b4..19118fb  Données-manuelles-ACA -> origin/Données-manuelles-ACA

In [ ]:
!git config pull.rebase true

In [ ]:
!git pull

remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 16.85 KiB | 4.21 MiB/s, done.
From https://github.com/clementsouk-aloun-dot/Code-PAT
   163c996..29dc0d4  main       -> origin/main
Updating 163c996..29dc0d4
Fast-forward
 Code_CSA.ipynb | 1792 ++++++++++++++------------------------------------------
 1 file changed, 446 insertions(+), 1346 deletions(-)

In [5]:
!git push

Everything up-to-date

#INSTALL PACKAGE

In [6]:
!gcloud auth application-default login

Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=TIp7rrlFD6zoEXIwGUvzJQmUMOYnUy&prompt=consent&token_usage=remote&access_type=offline&code_challenge=BLvTV3beRy9xir7bt8ntB0sDBn4llJGBp597poI-6M0&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0ASc3gC0YQ-bikbRxo_dGrtd12gFMIByDG6ALS4Rjq8iu9rtS5pZdsqrHbXhz3ZlrxesgYQ

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.


To take a quick anonymous survey, run:
  $ gcloud survey

In [7]:
!pip install PyPDF2
!pip install reportlab
!pip install PyMuPDF tools
!pip install xlsxwriter

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 16.2 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1
Collecting reportlab
  Downloading reportlab-4.4.9-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.4)
Downloading reportlab-4.4.9-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 54.7 MB/s eta 0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-4.4.9
Collecting PyMuPDF
  Downloading pymupdf-1.26.7-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Collecting tools
  Downloading tools-1.0.23-py3-none-any.whl.metadata (1.3 kB)
Downloading pymupdf-1.26.7-cp310-abi3-manylinux_2_28_x86_64.whl (24.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 47.6 MB/s eta 0:00:00
Downloading tools-1.0.23-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 3.1 MB/s eta 0:00:00
Installing collected packages: tools, PyMuPDF
Successfully installed PyMuPDF-1.26.7 tools-1.0.23
Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 17.3 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9

In [8]:
import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import sys
import io
import re
import shutil
import zipfile
from google.colab import drive, files

from google.colab import auth
from google.auth import default
import unicodedata
import re
import torch
from sentence_transformers import SentenceTransformer, util
from google.cloud import bigquery

Imports des fichiers .py

In [18]:
sys.path.append(os.path.abspath("/content/Code-PAT/scripts_data"))
sys.path.append(os.path.abspath("/content/Code-PAT"))

from adherent import *
from alim import *
from domifa import *
from financier import *
from gaia import *
from impact import *
from manuelles import *
from mobilite import *
from nomination import *
from pegass import *

from utils import *

#AUTHENTIFICATION

In [10]:
PROJECT_ID = "crf-pat"
client = bigquery.Client(project=PROJECT_ID)

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [11]:
# Etape 0 : Préparation de l'environnement

CREDENTIALS_JSON = """
{
  "type": "service_account",
  "project_id": "alexandrevalent",
  "private_key_id": "dba39c84ba4135ce5ede6479a186ad8cde499dee",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvGU4ZJFrBwCBb\nu8s4aPA5bQTOKDkPZEVdNyY//RneR6RC9JPrcbfVfIUaQU7A036sfdhDGFKJbw20\nTZ55fafcH9yCMiUO+Nzek0eogON4TXrXsh8UFtdw8BOuaVkFitU5yg8kFhTnEZtd\ntPfZHW3Aqhd/aDoTOBNgRuF/hVTKQ2ytbCbE77fL2/pz9kvpZ2Zrz3u1lmksSJls\nHIolNwX9R05YqmrkpZ/TMAULFk4bT0VRQng5pmN9AeB61eJLWhlLaEdeu79NWV4B\n7tZd6RzzTFors804aJkmXHM63VRtvGD0UlR0O7w1QlI3ymUxpy5hrjbz6n9bmpMI\nfebvydLnAgMBAAECggEADipn7RTJ2t7mP0WkHT4wIRU2zE7ovtwH2JC7oXWigB8f\npOMQjH24t6bJReR+sI7rspzDwDnZg5DedPXKml2WFPLm7gmMgfeUNtWHeJRk0rjB\n9W1NolxutY5WqUeQkig3M+Oq8epvano8LYqUepYs6OdZ207dU+y3dJSHbb+lqm9D\ntQZR2oBj7W1iZ8fJ+SQLSjU5BztS1CvWuayRd/tLd9Spp0NUn5uQFTKwel9Gazmz\n28IsPPm6SudplFhaGd4kCPvhcg0jGEKe61VYdgHoBzp+EXRWXUvQ+SbMafXtMvoB\nLoUH4X3creKzJQKXnjlDpAzRHMYhJTvHinHXaggdcQKBgQDcJszFOECfSovXFZNq\nMyQOWbesyDb2OQhJLFZCD2QraZm3jPaIPeMfFkmFAumcVal6EzpR5IE8g9jBuLo+\ng6j3NTo5jbGO9WEn4361yEotb+S8t3/DTHvWqXBK7HdUB/KHlyGtctm8yErdMZQB\nvzo03aTwwStNTeFG8GzT1Nd7JQKBgQDLnHIMbx9iAG3K21XCq0Dot2Q63hklJC26\nsJlrTkdXMOIlhpwJ6LTOJe2paHbR56IrKOHQCuLxQFhRd8Eidz1ahjO7D8fKr/TG\nS8/V32FrpONyxhKinLsccSb86S3vvpKCI265z5EEjk/1qnx3TOo6oqA/2DQLv0Q4\nYinmNSOeGwKBgHGjYY3n9IuE6lwy2e42ycTSkNoSWzSLyfgjd78PvNAf6WXy0IsR\nDvzL/1U2ZKn7GclWxYLiJce78xZEKXb9dSluA0kUF/RIO0dgydZBtfBwUq0LN1rz\nTvVGbx1tpEbu90UAQTUMFNK6vNIitliUghIp2usfex+jNMbuce6Cblw1AoGBAKDH\n1gtZiFeT7R7d2jfRkXzyrBQMI6D/k5izMULZ2l3QfROS2w68EmIi8yvuEL2qApXA\nP6hPoGtPGy6huQHlVK5yANF7IZI9JbWcUe8Z6MzetLiCDl8YEmzgMSBPZXXGb9yR\n7DKP5HzLf/qG+KggNWm913ry2A5ap506bsmZNpn3AoGBAM6vvI9tb+AcNfd4ewmY\nAWSb4GLliRTaBIGHYmotfyBEBWpXZq2/0JG32RRf3rYUJWWn/r7K+zrRUqeMwlD+\nz7GuSU+OaSDzYj7fwDyuxOwTJMLrh+AkKbUYBsMF7YH1qIRjBjKNdj1LOznASQMe\nu1E4sNa9RRRujbQw4AEP3Xjl\n-----END PRIVATE KEY-----\n",
  "client_email": "crf-slidemanager@alexandrevalent.iam.gserviceaccount.com",
  "client_id": "101959630014487618959",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/crf-slidemanager%40alexandrevalent.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly']


# Authentification
credentials = service_account.Credentials.from_service_account_info(json.loads(CREDENTIALS_JSON, strict=False), scopes=SCOPES)

# Initialisation des services
slides_service = build('slides', 'v1', credentials=credentials)
drive_service = build('drive', 'v3', credentials=credentials)
gspread_client  = gspread.authorize(credentials)

# Variables globales

In [12]:
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

# CHARGEMENT DE TOUTES LES DONNEES PAR TABLE

# 0. Ref_structure

In [13]:
df_ref_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw/').worksheet('Feuille 1'))

In [14]:
df_ref_structure = renommer_par_nom_table(df_ref_structure, "AS_Informations_structures", mapping_df)
df_ref_structure['n_structure'] = df_ref_structure['n_structure'].astype(int).astype(str)
df_ref_structure.head()

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,Structure_de_rattachement,Rattachements_successifs,DT_de_rattachement,lon,lat
0,2615,ANTENNE LOCALE - AL,AL DE DELLE,90100.0,90033,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",90,2010-02-08 00:00:00,NaT,95 - DT DU TERRITOIRE DE BELFORT,AL 2615,95 - DT DU TERRITOIRE DE BELFORT,7.000705,47.506725
1,2669,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43220.0,43087,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2669,48 - DT DE LA HAUTE LOIRE,4.346423,45.214392
2,2670,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43600.0,43224,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2670,48 - DT DE LA HAUTE LOIRE,4.235474,45.242445
3,2671,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43300.0,43112,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2671,48 - DT DE LA HAUTE LOIRE,3.495645,45.098285
4,2672,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43000.0,43157,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2672,48 - DT DE LA HAUTE LOIRE,3.879748,45.044677

In [15]:
df_ref_structure_DT = df_ref_structure[df_ref_structure['nom_structure'].str.contains('DT')].astype(str)

# 1. PEGASS

In [ ]:
# EXEMPLE :  Charger le DataFrame
# spreadsheet = gspread_client.open_by_url("https://docs.google.com/spreadsheets/d/1WEoWR3dnhy7NL5ISoD6o-58krsttfHkiqaJz30Vvg74/")
# worksheet = spreadsheet.worksheet("Feuille 1")
# df_raw = get_as_dataframe(worksheet)

## 1.1. rattachement_court

In [ ]:
rattachement_court = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU/edit?usp=sharing').worksheet('Feuille 1'))

## 1.2. Activité_benevole ref activité

In [ ]:
Ref_activité_benevole = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1rf1gXTylNEHEt72UfwZO62gIfgzf9eY8lPqhXLJ5hs8/edit').worksheet('Feuille 1'))

## 1.3. Pegass_activite / Activite

In [ ]:
Pegass_activite = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13Ygh1goryIgp2UCh19tKaTv3AWkfsSMInuS8-VMbmeU/edit').worksheet('Feuille 1'))

## 1.4. PegassInscription / Inscription

In [ ]:
Pegass_inscription = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1wCYPGwDVKZC6BBuMnOc7kB98agof5IMkdn9W7xn5UUg/edit').worksheet('Feuille 1'))

## 1.5. PREPARATION DE LA BASE DE DONNEES

In [ ]:
Pegass_inscription, Pegass_activite, Ref_activité_benevole = clean_pegass(Pegass_inscription,Pegass_activite,Ref_activité_benevole, mapping_df)

# 2. GAIA

## 2.1. GAIA_contact

In [ ]:
GAIA_contact = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1k4-nMZqUulcZBPMplZLWHcvSTvzISqF9uMnlITdikmI/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.2. GAIA_action

In [ ]:
GAIA_action = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1XvfYhne_YxMBVfgkDUzKhhOle9-bmEP3j0gpBYZsKuo/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.3. GAIA_rattachement_action

In [ ]:
GAIA_rattachement_action = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1vtC3hpxh6RIcmhMjifVFoi169uhdi0f9fpKXP9FqEd8/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.4 GAIA_act_str

In [ ]:
GAIA_act_str = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1PrK18aa8dllTjXOEyPHXMEgqP4gm1ZeJdnCmlUG78EA/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.5. GAIA_structure

In [ ]:
GAIA_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1forcw_rC0WCcwu6K8-AUhm1sur9pp5XZX_YTCKaBA6g/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.6. Preparation de la base

### 2.6.1. Renommer les variables

In [ ]:
GAIA_action, GAIA_rattachement_action, GAIA_contact, GAIA_structure, GAIA_act_str = clean_gaia(GAIA_action, GAIA_rattachement_action, GAIA_contact, GAIA_structure, GAIA_act_str, mapping_df)

# 3. NOMINATION

## 3.1. NOMINATION_nomination

In [ ]:
NOMINATION_nomination = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ywCGFgW5eLONMNK64o4NZrQQzasqfEGnnQL6LfDXbbM/edit?gid=614834196').worksheet('NOMINATION_nomination'))

NOMINATION_nomination.head()

## 3.2 NOMINATION_attribution_nomination

In [ ]:
NOMINATION_attribution_nomination = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1BzCcfO1NLM5oMmBD1cBELIuvBvVjucsK6Wm4zPTaO-Q/').worksheet('NOMINATION_attribution_nomination'))

In [ ]:
NOMINATION_attribution_nomination.head()

## 3.3. Préparation de la base

### 3.3.1. Renommer les variables

In [ ]:
NOMINATION_nomination, NOMINATION_attribution_nomination = clean_nomination(NOMINATION_nomination, NOMINATION_attribution_nomination, mapping_df)

# 4. IMPACT

## 4.1 Impact_indicateurs

In [ ]:
IMPACT_indicateurs = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.2 Impact_indicateur_value

In [ ]:
IMPACT_indicateur_value = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.3 Impact_donnees_activite

In [ ]:
IMPACT_donnees_activite = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.4 Impact_abstract_donnees_activite

In [ ]:
IMPACT_abstract_donnees_activite = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.5. Preparation de la base

### 4.5.1. Renommer les variables

In [ ]:
IMPACT_indicateurs, IMPACT_indicateur_value, IMPACT_donnees_activite, IMPACT_abstract_donnees_activite = clean_impact(IMPACT_indicateurs, IMPACT_indicateur_value, IMPACT_donnees_activite, IMPACT_abstract_donnees_activite, mapping_df)

# 5. Données financières

In [29]:
financier = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c')

In [30]:
dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute, dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute = import_clean_donnees_financieres(financier,df_ref_structure,mapping_df)

# 6. Mobilité

In [19]:
mobilite = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1dvxT58WR-FqdT-4r-A9ca4vaA9FG7IXHJJaTbnjio8A/')

In [20]:
df_mobilite = filtres_mobilite(mobilite,mapping_df)

# 7. Données manuelles

## 7.1 OCR

In [31]:
df_OCR = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ccRoyPycFDwvQvacvmHjfE87LtnlzUgtoRbITkC0pVQ/').worksheet('Feuille 1'))

## 7.2 PST

In [32]:
df_PST = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1yifNna4Hsn5RihkRg50g9h1yKjuRjfolrjsWonEHnrQ').worksheet('Données'))

## 7.3 Déclenchements

In [33]:
df_declenchement = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1y9jehT5fStcEWCF0pxAP7BdiI62VY3JM_hQzFftbcZA').worksheet('Feuille 1'))

## 7.4 Redcall

In [34]:
df_redcall = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1EQzq0K8RY2Liyq-jtggX0bTlnOk9cwUTmf4t6c5_CiI').worksheet('structure-stats_2025-01-01_2025-12-31_min-1 (1)'))

## 7.5 CHAI CHU CMCC

In [35]:
df_CAICHUCMCC = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/12nZY2leRCMn71NGAEUUtA0Pes598gOfeufDStxSCcnY').worksheet('Toutes données'))

## 7.6 Conventions

In [36]:
df_conventions = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1OYSSkUhWwVpWne9EygH1EEz8EJnFjSeAOEpQQe9utiM').worksheet('Feuille 1'))

## 7.7 DOMIFA

In [16]:
df_domiciliation, df_rattachement_court = clean_domifa(client,df_ref_structure)

TypeError: clean_domifa() takes 1 positional argument but 2 were given

## 7.8 Préparation

In [37]:
df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions = clean_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement, df_redcall, df_CAICHUCMCC, df_conventions)

/content/Code-PAT/scripts_data/manuelles.py:103: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['Grand Total', 'Exercice']] = df[['Grand Total', 'Exercice']].fillna(0)
/content/Code-PAT/scripts_data/manuelles.py:156: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Département"] = df["Département"].str.replace(
/content/Code-PAT/scripts_data/manuelles.py:193: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Departement"] = df["Departement"].str.replace(
/content/Code-PAT/scripts_data/manuelles.py:215: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[colonnes_oui_non] = df[colonnes_oui_non].applymap(
/content/Code-PAT/scripts_data/manuelles.py:215: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[colonnes_oui_non] = df[colonnes_oui_non].applymap(
/content/Code-PAT/scripts_data/manuelles.py:219: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Dispositifs_d_urgence Nb_conventions_operateurs'] = (

# FUSION DES TABLES

## 1. Fusion PEGASS activité, inscription, ref_activité_bénévole, rattachement_court

In [ ]:
df2 = fusion_pegass(Pegass_inscription, Pegass_activite, Ref_activité_benevole)

## 2. Fusion GAIA rattachement_action, action, act_str, structure

In [ ]:
df_GAIA = fusion_gaia(GAIA_action, GAIA_rattachement_action, GAIA_contact, GAIA_structure, GAIA_act_str)

## 3. Fusion NOMINATION nomination, attribution_nomination

In [ ]:
df_NOMINATION = fusion_nomination(NOMINATION_nomination, NOMINATION_attribution_nomination)

## 4. Fusion IMPACT indicateurs, indicateurs_value, donnees_activite, abstract_donnes_activite

In [ ]:
df_IMPACT = fusion_impact(IMPACT_indicateurs, IMPACT_indicateur_value, IMPACT_donnees_activite, IMPACT_abstract_donnees_activite)

## 5. Fusion Données financières

### 5.1 Fusion des tables

In [ ]:
df_financier_DT, df_financier_DT_UL = fusion_donnees_financieres(dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute,dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute)

### 5.2 Vérifications

In [ ]:
verifier_n_dept(df_financier_DT,df_ref_structure)

 ✅ Aucun doublon
 ✅ Pas de département manquant

In [ ]:
verifier_colonne_structure(df_financier_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## 6. Fusion DOMIFA

In [ ]:
df_domiciliation = pd.merge(df_domiciliation, df_rattachement_court, on='n_structure', how="left") #a conserver dans le code principal

# Calcul des indicateurs

## PEGASS

- Nombre de bénévoles par activité benevole

## Nombre de bénévoles par activité benevole

In [ ]:
Nb_benevoles_distincts, Nb_benevoles_Distribution_alimentaire, Nb_benevoles_Distribution_alimentaire1, Nb_benevoles_Distribution_alimentaire2, Nb_benevoles_Distribution_alimentaire3, Nb_benevoles_Distribution_alimentaire4 = indicateurs_pegass(df2)

## GAIA

- Nombre de bénévoles déclarés sur une activitée

In [ ]:
NbBeneDecla_GAIA = indicateurs_gaia(df_GAIA)

## NOMINATION

- RTAEO & RLAEO
- RTOCR & RLOCR

In [ ]:
referents_AEO_mois, referents_OCR_mois = indicateurs_nomination(df_NOMINATION, annee=2025)

## IMPACT

- Nombre d'agréments territoriaux (Dispos d'urgence)
- Nombre de personnes prises en charge (Dispos d'urgence)

In [ ]:
indicateurs_impact()

## Mobilité


Indicateurs qui nécessitent seulement les données mobilité :

- Nb de structures menant une activité AEO/AAD mobile
- Nombre de personnes accompagnées par des dispositifs AEO/AAD mobiles
<br>

In [21]:
df_mobilite_DT = indicateurs_mobilite(df_mobilite, df_ref_structure, 'DT_de_rattachement')
df_mobilite_DT_UL = indicateurs_mobilite(df_mobilite, df_ref_structure, 'n_structure')

In [24]:
verifier_colonne_structure(df_mobilite_DT, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [25]:
verifier_colonne_structure(df_mobilite_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## Verification Mobilite

In [28]:
df_mobilite.shape[0]
display (df_mobilite)

df_mobilite_DT.shape[0]
display (df_mobilite_DT)
df_mobilite_DT.shape[0]

df_mobilite_DT_UL.shape[0]
display (df_mobilite_DT_UL)
len (df_mobilite_DT_UL)

lignes_vides = df_mobilite_DT[df_mobilite_DT['AEO Structure_activite_mobile'].isna() | (df_mobilite_DT['AEO Structure_activite_mobile'] == "")]
if not lignes_vides.empty:
    print(f"   ❌ {len(lignes_vides)} valeur(s) manquante(s) ou vide(s) détectée(s).")
else:
    print("   ✅ Aucun NaN ou valeur vide détecté.")

lignes_vides = df_mobilite_DT_UL[df_mobilite_DT_UL['AEO Structure_activite_mobile'].isna() | (df_mobilite_DT['AEO Structure_activite_mobile'] == "")]
if not lignes_vides.empty:
    print(f"   ❌ {len(lignes_vides)} valeur(s) manquante(s) ou vide(s) détectée(s).")
else:
    print("   ✅ Aucun NaN ou valeur vide détecté.")

# Supression de l'indicateur AEO Nb_benevoles_actifs
df_mobilite_DT_UL = df_mobilite_DT_UL.drop(columns=['AEO Nb_benevoles_actifs'])
df_mobilite_DT = df_mobilite_DT.drop(columns=['AEO Nb_benevoles_actifs'])
display(df_mobilite_DT_UL.head())
display(df_mobilite_DT.head())

  n_structure  AEO Structure_activite_mobile  AEO Nb_PA_dispos_mobiles
0         100                              4                         0
1        1013                              1                       146
2        1022                              2                        97
3         103                              1                         0
4        1041                              1                       164

  n_structure  AEO Structure_activite_mobile  AEO Nb_PA_dispos_mobiles
0         100                              5                         0
1         103                              1                         0
2          11                              1                         0
3          12                              5                        49
4        1285                              1                         0

## Données manuelles

In [38]:
df_OCR_Nb_deployees, df_Dispositifs_d_urgence_PST, df_declenchement3, df_redcall2, df_CAICHUCMCC_VF, df_conventions2 = indicateurs_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions, df_ref_structure)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
verifier_colonne_structure(df_OCR_Nb_deployees, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Dispositifs_d_urgence_PST, "n_structure", df_ref_structure)
verifier_colonne_structure(df_declenchement3, "n_structure", df_ref_structure)
verifier_colonne_structure(df_redcall2, "n_structure", df_ref_structure)
verifier_colonne_structure(df_CAICHUCMCC_VF, "n_structure", df_ref_structure)
verifier_colonne_structure(df_conventions2, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 1 code(s) non trouvés dans le référentiel : [47]

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 1 code(s) non trouvés dans le référentiel : [47]

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 761 code(s) non trouvés dans le référentiel : ['1.0', '10.0', '1000.0', '1001.0', '1002.0', '1004.0', '1005.0', '1007.0', '1008.0', '101.0', '1010.0', '1011.0', '1012.0', '1013.0', '1014.0', '1015.0', '1016.0', '1017.0', '1018.0', '1019.0', '1020.0', '1021.0', '1022.0', '1023.0', '1024.0', '1025.0', '1026.0', '1027.0', '1028.0', '1029.0', '1030.0', '1031.0', '1032.0', '1033.0', '1034.0', '1035.0', '1036.0', '1037.0', '1038.0', '1039.0', '1040.0', '1041.0', '1042.0', '1044.0', '1049.0', '105.0', '1050.0', '1051.0', '1052.0', '1053.0', '1054.0', '1055.0', '1056.0', '1058.0', '1059.0', '1060.0', '1061.0', '1062.0', '1063.0', '1064.0', '1065.0', '1066.0', '1067.0', '1068.0', '1069.0', '107.0', '1070.0', '1071.0', '1072.0', '1073.0', '1074.0', '1076.0', '1078.0', '1079.0', '108.0', '1080.0', '1081.0', '1083.0', '1084.0', '1085.0', '1086.0', '1087.0', '1089.0', '109.0', '1090.0', '1091.0', '1092.0', '1093.0', '1094.0', '1095.0', '1096.0', '1097.0', '1098.0', '1099.0', '110.0', '1100.0', '1101.0', '1102.0', '1103.0', '1104.0', '1105.0', '1106.0', '1107.0', '1108.0', '1109.0', '111.0', '1110.0', '1111.0', '1112.0', '1113.0', '1114.0', '1115.0', '1116.0', '1117.0', '1118.0', '1119.0', '112.0', '1120.0', '1121.0', '1122.0', '1123.0', '1124.0', '1126.0', '1128.0', '1129.0', '113.0', '1130.0', '1134.0', '1135.0', '1137.0', '1138.0', '1139.0', '114.0', '1141.0', '1142.0', '1143.0', '1144.0', '1145.0', '1146.0', '1147.0', '1148.0', '1149.0', '115.0', '1150.0', '1151.0', '1152.0', '1153.0', '1154.0', '1155.0', '1156.0', '1158.0', '1159.0', '116.0', '1160.0', '1161.0', '1162.0', '1163.0', '1164.0', '1165.0', '1166.0', '1167.0', '1168.0', '117.0', '1173.0', '1174.0', '1176.0', '1177.0', '1178.0', '1179.0', '118.0', '1180.0', '1181.0', '1183.0', '1184.0', '1185.0', '1187.0', '1188.0', '1189.0', '119.0', '1195.0', '1199.0', '12.0', '1200.0', '1201.0', '1202.0', '1203.0', '1207.0', '1208.0', '121.0', '1219.0', '122.0', '1221.0', '1222.0', '1223.0', '1226.0', '123.0', '1234.0', '1235.0', '1236.0', '1237.0', '1239.0', '124.0', '1240.0', '1241.0', '125.0', '126.0', '127.0', '1287.0', '129.0', '130.0', '1309.0', '131.0', '1310.0', '1315.0', '1317.0', '133.0', '1332.0', '1333.0', '1334.0', '1335.0', '1338.0', '1340.0', '1344.0', '1348.0', '1350.0', '1351.0', '1353.0', '1357.0', '1358.0', '1359.0', '1361.0', '1363.0', '1364.0', '1367.0', '138.0', '139.0', '14.0', '140.0', '141.0', '142.0', '143.0', '144.0', '145.0', '146.0', '147.0', '149.0', '15.0', '150.0', '152.0', '153.0', '155.0', '156.0', '157.0', '158.0', '159.0', '16.0', '160.0', '161.0', '162.0', '163.0', '164.0', '165.0', '166.0', '167.0', '168.0', '169.0', '170.0', '171.0', '172.0', '173.0', '174.0', '175.0', '178.0', '179.0', '180.0', '181.0', '182.0', '184.0', '185.0', '186.0', '188.0', '189.0', '19.0', '190.0', '191.0', '192.0', '193.0', '194.0', '195.0', '196.0', '197.0', '198.0', '199.0', '2.0', '20.0', '200.0', '201.0', '202.0', '203.0', '204.0', '205.0', '206.0', '207.0', '208.0', '21.0', '210.0', '211.0', '212.0', '213.0', '214.0', '215.0', '216.0', '217.0', '218.0', '219.0', '22.0', '220.0', '221.0', '223.0', '224.0', '226.0', '227.0', '23.0', '230.0', '231.0', '232.0', '234.0', '235.0', '236.0', '24.0', '26.0', '268.0', '269.0', '27.0', '28.0', '285.0', '29.0', '3.0', '30.0', '305.0', '31.0', '311.0', '312.0', '313.0', '314.0', '316.0', '317.0', '318.0', '319.0', '32.0', '320.0', '321.0', '322.0', '323.0', '324.0', '326.0', '327.0', '328.0', '33.0', '330.0', '334.0', '335.0', '336.0', '337.0', '338.0', '339.0', '340.0', '341.0', '344.0', '345.0', '346.0', '347.0', '349.0', '350.0', '351.0', '352.0', '353.0', '354.0', '355.0', '356.0', '359.0', '362.0', '363.0', '364.0', '365.0', '366.0', '367.0', '368.0', '369.0', '37.0', '370.0', '372.0', '373.0', '374.0', '375.0', '376.0', '377.0', '378.0', '379.0', '380.0', '382.0', '383.0', '384.0', '386.0', '388.0', '389.0', '39.0', '390.0', '391.0', '392.0', '393.0', '394.0', '395.0', '396.0', '397.0', '398.0', '4.0', '40.0', '401.0', '402.0', '403.0', '404.0', '405.0', '407.0', '409.0', '412.0', '413.0', '414.0', '415.0', '416.0', '417.0', '418.0', '419.0', '42.0', '420.0', '421.0', '422.0', '423.0', '424.0', '425.0', '43.0', '434.0', '439.0', '44.0', '440.0', '441.0', '442.0', '443.0', '444.0', '445.0', '446.0', '447.0', '448.0', '449.0', '450.0', '452.0', '453.0', '458.0', '459.0', '46.0', '460.0', '461.0', '462.0', '463.0', '469.0', '47.0', '472.0', '473.0', '474.0', '475.0', '476.0', '477.0', '478.0', '479.0', '480.0', '481.0', '482.0', '49.0', '490.0', '491.0', '494.0', '497.0', '499.0', '5.0', '50.0', '501.0', '502.0', '504.0', '505.0', '506.0', '507.0', '508.0', '509.0', '51.0', '510.0', '511.0', '512.0', '52.0', '522.0', '53.0', '530.0', '531.0', '532.0', '533.0', '534.0', '536.0', '537.0', '54.0', '540.0', '547.0', '55.0', '559.0', '56.0', '561.0', '562.0', '567.0', '57.0', '579.0', '58.0', '59.0', '594.0', '595.0', '6.0', '60.0', '601.0', '603.0', '604.0', '61.0', '611.0', '62.0', '620.0', '621.0', '63.0', '637.0', '64.0', '645.0', '646.0', '65.0', '654.0', '655.0', '657.0', '66.0', '661.0', '662.0', '663.0', '664.0', '67.0', '672.0', '674.0', '676.0', '678.0', '68.0', '682.0', '687.0', '688.0', '69.0', '692.0', '693.0', '696.0', '7.0', '70.0', '700.0', '702.0', '703.0', '704.0', '705.0', '706.0', '707.0', '71.0', '711.0', '716.0', '718.0', '72.0', '720.0', '721.0', '722.0', '723.0', '724.0', '725.0', '726.0', '727.0', '728.0', '729.0', '73.0', '730.0', '731.0', '732.0', '733.0', '734.0', '735.0', '737.0', '74.0', '745.0', '75.0', '751.0', '757.0', '758.0', '76.0', '768.0', '769.0', '77.0', '770.0', '771.0', '775.0', '78.0', '783.0', '785.0', '79.0', '796.0', '8.0', '80.0', '802.0', '803.0', '808.0', '809.0', '81.0', '815.0', '816.0', '817.0', '82.0', '823.0', '829.0', '83.0', '834.0', '835.0', '839.0', '84.0', '843.0', '849.0', '85.0', '850.0', '851.0', '853.0', '854.0', '855.0', '859.0', '86.0', '864.0', '865.0', '866.0', '867.0', '868.0', '869.0', '87.0', '870.0', '871.0', '872.0', '873.0', '874.0', '875.0', '876.0', '877.0', '878.0', '879.0', '88.0', '880.0', '881.0', '882.0', '883.0', '884.0', '886.0', '887.0', '888.0', '889.0', '89.0', '890.0', '891.0', '892.0', '893.0', '894.0', '895.0', '896.0', '897.0', '898.0', '9.0', '90.0', '900.0', '901.0', '902.0', '903.0', '904.0', '905.0', '906.0', '907.0', '908.0', '909.0', '91.0', '910.0', '911.0', '912.0', '913.0', '914.0', '915.0', '916.0', '917.0', '918.0', '919.0', '92.0', '920.0', '921.0', '922.0', '923.0', '924.0', '925.0', '926.0', '927.0', '929.0', '93.0', '934.0', '936.0', '937.0', '938.0', '939.0', '940.0', '941.0', '942.0', '948.0', '949.0', '950.0', '951.0', '952.0', '953.0', '954.0', '956.0', '957.0', '958.0', '959.0', '960.0', '961.0', '962.0', '964.0', '965.0', '966.0', '967.0', '968.0', '969.0', '970.0', '971.0', '972.0', '973.0', '974.0', '975.0', '981.0', '982.0', '983.0', '984.0', '985.0', '986.0', '987.0', '988.0', '989.0', '990.0', '991.0', '992.0', '993.0', '994.0', '995.0', '996.0', '997.0', '998.0', '999.0']

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## verification données manuelles

In [50]:
display (df_OCR)
display (df_OCR_Nb_deployees)
len(df_OCR_Nb_deployees)
specific_structure_OCR = df_ref_structure[df_ref_structure['n_structure'] == '3966']
display(specific_structure)
specific_structures_OCR = df_ref_structure[df_ref_structure['n_structure'].isin(['3966', '886'])]
display(specific_structures)

display (df_PST)
display (df_Dispositifs_d_urgence_PST)
specific_structure_PST = df_ref_structure[df_ref_structure['n_structure'] == '47']
display(specific_structure_PST)

,Région,Territoire,PST constitué,Médecin,Infirmier,Pharmacien,Membre du Pôle Santé,RTSP,Présence RTSP,Déploiement ECG,Référent Schiller,Type ECG,Déploiement MASH,Nombre d'AcSS,Précisions,Déploiement AcSS,N° Département,Nom structure DT
0,Auvergne Rhône Alpes,DT 01 - Ain,Oui,Dr Mounir BOUALLEGUE (mounir.bouallegue@croix-...,Marc JULIEN (marc.julien@croix-rouge.fr - 06 8...,NaN,NaN,NaN,Non,Non déployé,NaN,Non déployé,Non déployé,1.0,AcSS et SEMISS,Déployé,01,DT Ain
1,Hauts de France,DT 02 - Aisne,Oui,Dr Florentine DZOMO KENMO (florentine.dzomoken...,Annick COURTIN (annick.courtin@croix-rouge.fr ...,NaN,NaN,NaN,Non,Non déployé,NaN,Non déployé,Non déployé,NaN,NaN,Non déployé,02,DT Aisne
2,Auvergne Rhône Alpes,DT 03 - Allier,Oui,Dr Alain SURAMY (alain.suramy@croix-rouge.fr -...,Didier TARRIANT (didier.tarriant@croix-rouge.f...,NaN,NaN,NaN,Non,Non déployé,NaN,Non déployé,Non déployé,NaN,NaN,Non déployé,03,DT Allier
3,Provence-Alpes - Côte d'Azur - Corse,DT 04 - Alpes de Haute Provence,Oui,Dr Daniel MEYRAN (daniel.meyran@croix-rouge.fr...,Alain RAFFOUR (alain.raffour@croix-rouge.fr - ...,NaN,NaN,NaN,Non,Non déployé,NaN,Non déployé,Non déployé,NaN,NaN,Non déployé,04,DT Alpes de Haute Provence
4,Provence-Alpes - Côte d'Azur - Corse,DT 05 - Hautes Alpes,En cours,NaN,Amandine TEMPLIER (amandine.templier@croix-rou...,NaN,NaN,NaN,Non,Non déployé,NaN,Non déployé,Non déployé,NaN,NaN,Non déployé,05,DT Hautes Alpes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,Outre Mer,DT 976 - Mayotte,Non,NaN,NaN,NaN,NaN,NaN,Non,Non déployé,NaN,Non déployé,Non déployé,NaN,NaN,Non déployé,976,DT Mayotte
102,Outre Mer,DT 977 - Saint-Barthélémy,Oui,Dr Daniel MEYRAN (daniel.meyran@croix-rouge.fr...,Anne FUERTES (laurens.anne@yahoo.com - 06 90 7...,NaN,NaN,NaN,Non,Non déployé,NaN,Non déployé,Non déployé,NaN,NaN,Non déployé,977,DT Saint-Barthélémy
103,Outre Mer,DT 978 - Saint-Martin,Non,NaN,NaN,NaN,NaN,NaN,Non,Non déployé,NaN,Non déployé,Non déployé,NaN,NaN,Non déployé,978,DT Saint-Martin
104,Outre Mer,DT 987 - Polynésie française,Non,NaN,NaN,NaN,NaN,NaN,Non,Non déployé,NaN,Non déployé,Non déployé,NaN,NaN,Non déployé,987,DT Polynésie française
105,Outre Mer,DT 988 - Nouvelle Calédonie,Non,NaN,NaN,NaN,NaN,Jean-Christophe POURREAU (jeanchristophe.pourr...,Oui,Non déployé,NaN,Non déployé,Non déployé,NaN,NaN,Non déployé,988,DT Nouvelle Calédonie

,Territoire,PST constitué,Nom structure DT,N° Département,n_structure,nom_structure,Dispositifs_d_urgence PST
0,DT 01 - Ain,oui,DT Ain,01,5,DT DE L'AIN,oui
1,DT 02 - Aisne,oui,DT Aisne,02,6,DT DE L'AISNE,oui
2,DT 03 - Allier,oui,DT Allier,03,7,DT DE L'ALLIER,oui
3,DT 04 - Alpes de Haute Provence,oui,DT Alpes de Haute Provence,04,3997,DT DES ALPES DE HAUTE PROVENCE,oui
4,DT 05 - Hautes Alpes,en cours,DT Hautes Alpes,05,9,DT DES HAUTES ALPES,en cours
...,...,...,...,...,...,...,...
101,DT 976 - Mayotte,non,DT Mayotte,976,1286,DT DE MAYOTTE,non
102,DT 977 - Saint-Barthélémy,oui,DT Saint-Barthélémy,977,3667,DT DE ST BARTHELEMY,oui
103,DT 978 - Saint-Martin,non,DT Saint-Martin,978,3668,DT DE ST MARTIN,non
104,DT 987 - Polynésie française,non,DT Polynésie française,987,1285,,non
105,DT 988 - Nouvelle Calédonie,non,DT Nouvelle Calédonie,988,104,DT DE NOUVELLE CALEDONIE,non

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,Structure_de_rattachement,Rattachements_successifs,DT_de_rattachement,lon,lat
242,47,DELEGATION TERRITORIALE - DT,DT DE LA LOIRE,42000.0,42218,ST ETIENNE,"20 Rue BURDEAU, 42000 ST ETIENNE",42,1986-12-10 00:00:00,NaT,4457 - DR AUVERGNE RHONE ALPES,DT 47,47 - DT DE LA LOIRE,4.413167,45.445087

## DOMIFA

### Calculs

In [ ]:
df_personnes_domiciliees_struct, df_personnes_domiciliees_DT = indicateurs_domifa(df_domiciliation)

### Vérification

In [ ]:
verificiation_domifa(df_domiciliation, df_personnes_domiciliees_struct,df_personnes_domiciliees_DT,df_ref_structure,df_rattachement_court)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 30 code(s) non trouvés dans le référentiel : [np.int64(100), np.int64(346), np.int64(384), np.int64(387), np.int64(426), np.int64(474), np.int64(718), np.int64(725), np.int64(731), np.int64(775), np.int64(821), np.int64(870), np.int64(889), np.int64(892), np.int64(960), np.int64(967), np.int64(971), np.int64(972), np.int64(974), np.int64(975), np.int64(977), np.int64(1039), np.int64(1045), np.int64(1060), np.int64(1156), np.int64(1271), np.int64(2186), np.int64(3699), np.int64(3950), np.int64(4417)]

🔎 Vérification de la colonne 'DT_de_rattachement'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'Structure' et mapping associé 'n_structure'
   ✅ Mapping réalisé avec succès.
OK ✅ : sommes égales (30833) entre table struct[AEO Nb_personnes_domiciliees_crf] et table source[AEO Nb_personnes_domiciliees_crf]
OK ✅ : sommes égales (30833) entre table struct[AEO Nb_personnes_domiciliees_crf] et table source[AEO Nb_personnes_domiciliees_crf]

# Enregistrement des données

In [ ]:
# Entregistrement du DataFrame
# save_dataframe_to_sheet("1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw", client, df_structure)
# save_dataframe_to_sheet("1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU", client, df_rattachement_court)