#Imports

In [1]:
import time
start = time.time()

In [2]:


!pip install PyPDF2
!pip install reportlab
!pip install PyMuPDF tools
!pip install xlsxwriter

import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import io
import re
import shutil
import zipfile
from google.colab import drive, files

from google.colab import auth
from google.auth import default
import unicodedata
import re

import torch
from sentence_transformers import SentenceTransformer, util

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 5.4 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1
Collecting reportlab
  Downloading reportlab-4.4.9-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.4)
Downloading reportlab-4.4.9-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 19.4 MB/s eta 0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-4.4.9
Collecting PyMuPDF
  Downloading pymupdf-1.26.7-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Collecting tools
  Downloading tools-1.0.23-py3-none-any.whl.metadata (1.3 kB)
Downloading pymupdf-1.26.7-cp310-abi3-manylinux_2_28_x86_64.whl (24.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 61.5 MB/s eta 0:00:00
Downloading tools-1.0.23-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 2.9 MB/s eta 0:00:00
Installing collected packages: tools, PyMuPDF
Successfully installed PyMuPDF-1.26.7 tools-1.0.23
Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 4.3 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

#AUTHENTIFICATION

## 1. Authentification du google **service**

In [3]:


def get_google_client():
    """
    Authentifie l'utilisateur et renvoie un client Google Sheets pour interagir avec les feuilles de calcul.

    Cette fonction configure l'environnement pour désactiver l'authentification éphémère,
    authentifie l'utilisateur à l'aide de l'API de Google Colab et initialise un client Google Sheets autorisé.

    Returns:
        gspread.Client: Une instance de gspread.Client autorisée, permettant l'interaction avec Google Sheets.
    """

    # Désactive l'authentification éphémère
    os.environ['USE_AUTH_EPHEM'] = '0'

    # Authentifie l'utilisateur
    auth.authenticate_user()

    # Obtient les informations d'identification par défaut
    creds, _ = default()

    # Crée et retourne le client Google Sheets autorisé
    client = gspread.authorize(creds)

    print("🌐 Connexion au client Google réalisée")

    return client

In [4]:
# Etape 0 : Préparation de l'environnement

CREDENTIALS_JSON = """
{
  "type": "service_account",
  "project_id": "alexandrevalent",
  "private_key_id": "dba39c84ba4135ce5ede6479a186ad8cde499dee",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvGU4ZJFrBwCBb\nu8s4aPA5bQTOKDkPZEVdNyY//RneR6RC9JPrcbfVfIUaQU7A036sfdhDGFKJbw20\nTZ55fafcH9yCMiUO+Nzek0eogON4TXrXsh8UFtdw8BOuaVkFitU5yg8kFhTnEZtd\ntPfZHW3Aqhd/aDoTOBNgRuF/hVTKQ2ytbCbE77fL2/pz9kvpZ2Zrz3u1lmksSJls\nHIolNwX9R05YqmrkpZ/TMAULFk4bT0VRQng5pmN9AeB61eJLWhlLaEdeu79NWV4B\n7tZd6RzzTFors804aJkmXHM63VRtvGD0UlR0O7w1QlI3ymUxpy5hrjbz6n9bmpMI\nfebvydLnAgMBAAECggEADipn7RTJ2t7mP0WkHT4wIRU2zE7ovtwH2JC7oXWigB8f\npOMQjH24t6bJReR+sI7rspzDwDnZg5DedPXKml2WFPLm7gmMgfeUNtWHeJRk0rjB\n9W1NolxutY5WqUeQkig3M+Oq8epvano8LYqUepYs6OdZ207dU+y3dJSHbb+lqm9D\ntQZR2oBj7W1iZ8fJ+SQLSjU5BztS1CvWuayRd/tLd9Spp0NUn5uQFTKwel9Gazmz\n28IsPPm6SudplFhaGd4kCPvhcg0jGEKe61VYdgHoBzp+EXRWXUvQ+SbMafXtMvoB\nLoUH4X3creKzJQKXnjlDpAzRHMYhJTvHinHXaggdcQKBgQDcJszFOECfSovXFZNq\nMyQOWbesyDb2OQhJLFZCD2QraZm3jPaIPeMfFkmFAumcVal6EzpR5IE8g9jBuLo+\ng6j3NTo5jbGO9WEn4361yEotb+S8t3/DTHvWqXBK7HdUB/KHlyGtctm8yErdMZQB\nvzo03aTwwStNTeFG8GzT1Nd7JQKBgQDLnHIMbx9iAG3K21XCq0Dot2Q63hklJC26\nsJlrTkdXMOIlhpwJ6LTOJe2paHbR56IrKOHQCuLxQFhRd8Eidz1ahjO7D8fKr/TG\nS8/V32FrpONyxhKinLsccSb86S3vvpKCI265z5EEjk/1qnx3TOo6oqA/2DQLv0Q4\nYinmNSOeGwKBgHGjYY3n9IuE6lwy2e42ycTSkNoSWzSLyfgjd78PvNAf6WXy0IsR\nDvzL/1U2ZKn7GclWxYLiJce78xZEKXb9dSluA0kUF/RIO0dgydZBtfBwUq0LN1rz\nTvVGbx1tpEbu90UAQTUMFNK6vNIitliUghIp2usfex+jNMbuce6Cblw1AoGBAKDH\n1gtZiFeT7R7d2jfRkXzyrBQMI6D/k5izMULZ2l3QfROS2w68EmIi8yvuEL2qApXA\nP6hPoGtPGy6huQHlVK5yANF7IZI9JbWcUe8Z6MzetLiCDl8YEmzgMSBPZXXGb9yR\n7DKP5HzLf/qG+KggNWm913ry2A5ap506bsmZNpn3AoGBAM6vvI9tb+AcNfd4ewmY\nAWSb4GLliRTaBIGHYmotfyBEBWpXZq2/0JG32RRf3rYUJWWn/r7K+zrRUqeMwlD+\nz7GuSU+OaSDzYj7fwDyuxOwTJMLrh+AkKbUYBsMF7YH1qIRjBjKNdj1LOznASQMe\nu1E4sNa9RRRujbQw4AEP3Xjl\n-----END PRIVATE KEY-----\n",
  "client_email": "crf-slidemanager@alexandrevalent.iam.gserviceaccount.com",
  "client_id": "101959630014487618959",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/crf-slidemanager%40alexandrevalent.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly']


# Authentification
credentials = service_account.Credentials.from_service_account_info(json.loads(CREDENTIALS_JSON, strict=False), scopes=SCOPES)

# Initialisation des services
slides_service = build('slides', 'v1', credentials=credentials)
drive_service = build('drive', 'v3', credentials=credentials)
gspread_client  = gspread.authorize(credentials)

#FONCTIONS UTILES

#1. fonction de mensualisation

In [5]:
def monthly_parsing(df, year):
  def month_conditions(date):
    months = ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet' , 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre']
    for i in range(len(months)):
      if date.month == i+1:
        return months[i]
  df['Mois'] = df.apply(lambda x: month_conditions(x['date']), axis=1)
  df['Année'] = year
  return df

##2. Exporter le fichier de sortie en xlsx

In [6]:
def export_to_excel_download(dataframe, file_name='data.xlsx'):
    """
    Exporte un DataFrame en fichier Excel et le télécharge depuis Google Colab.

    Parameters:
        dataframe (pd.DataFrame): Le DataFrame à exporter.
        file_name (str): Le nom du fichier Excel à télécharger (par défaut 'data.xlsx').
    """
    dataframe.to_excel(file_name, index=False)
    files.download(file_name)

## 3. Ouvrir un google sheet

In [7]:
def sheet_to_dataframe(client, url, sheet_index=0, sheet_name=None, header_row=1):
    """
    Ouvre une feuille Google Sheets et crée un DataFrame Pandas à partir de ses données.

    Cette fonction prend en entrée l'URL de la feuille Google Sheets, un client Google Sheets autorisé,
    l'index de la page souhaitée ou le nom de la feuille, et la ligne utilisée comme en-tête. Elle renvoie les données de la
    feuille sous forme de DataFrame Pandas.

    Args:
        url (str): L'URL de la feuille Google Sheets.
        client (gspread.Client): Client Google Sheets autorisé.
        sheet_index (int, optional): L'index de la page à ouvrir dans la feuille. Par défaut, 0 (première page).
        sheet_name (str, optional): Le nom de la feuille à ouvrir. Si fourni, prioritaire sur sheet_index.
        header_row (int, optional): Le numéro de la ligne à utiliser comme en-têtes de colonnes pour le DataFrame.
                                   Par défaut, 1 (la première ligne de données après l'en-tête de feuille).

    Returns:
        pd.DataFrame: Un DataFrame Pandas contenant les données de la feuille avec la première ligne spécifiée
                      comme en-tête des colonnes.
    """

    # Ouvre la feuille Google Sheets à partir de l'URL
    sheet = client.open_by_url(url)

    # Sélectionne la page (worksheet) souhaitée
    if sheet_name:
        worksheet = sheet.worksheet(sheet_name)
    else:
        worksheet = sheet.get_worksheet(sheet_index)

    # Récupère toutes les valeurs de la page
    data = worksheet.get_all_values()

    # Crée le DataFrame en utilisant la ligne spécifiée comme en-tête
    df = pd.DataFrame(data[header_row:], columns=data[header_row - 1])

    print(f"✅ Chargement des données réalisées")
    print(f"    Sheet : {sheet.title}")
    print(f"    Feuille {sheet_index + 1 if not sheet_name else ''} : {worksheet.title} ({len(data) - header_row} lignes et {len(data[header_row - 1])} colonnes)\n")

    return df

##4. Défintion des filtres "classiques"

In [8]:

# #Fonction filtre simple (on met le nom de la colonne)
# def filtre(df, col, key, filters=FILTERS):
#     values = filters[col][key]
#     return df.loc[df[col].isin(values)].copy()

# #Fonction filtre et remplace
# def filtre_et_remplace(df, col, key, filters=FILTERS):
#   values = filters[col][key]
#   mask = df[col].isin(values)
#   df.drop(df.index[~mask], inplace=True)

In [9]:
# # def filtre(df, key, filters=FILTERS):
# def filtre(df, key, filters=FILTERS_PEGASS):
#     rule = filters[key]
#     col = rule["col"]
#     values = rule["values"]
#     return df.loc[df[col].isin(values)]


#Fonction filtre date

def filtre_2025(df, date_col="debut_inscription", dayfirst=True):
    s = pd.to_datetime(df[date_col], errors="coerce", dayfirst=dayfirst)
    return df.loc[s.between("2025-01-01 00:00", "2026-01-01 00:00", inclusive="left")]

#Fonction utile pour renommer automatiquement les variables
#Attention pour simplifier la fonction il faut que le nom initial de la Dataframe soit le même avec la colonne "nom tablme du dictionnaire de données :  Pegass_Inscription_rename = renommer_par_nom_table(PEGASS_PegassInscription, "PEGASS_PegassInscription", mapping_df)"

#On récupère la table qui sera la table "dictionnaire de données" = sans doute un url
def renommer_par_nom_table(df, nom_table, mapping_df=mapping_df):
    # On filtre le mapping sur cette table
    mapping_table = mapping_df[mapping_df["nom_table"] == nom_table]
    mapping_dict = dict(zip(mapping_table["nom_variable"], mapping_table["rename"]))
    return df.rename(columns=mapping_dict)

NameError: name 'mapping_df' is not defined

In [10]:
def filtre(df, key, filters=None):
    # Applique un filtre défini dans un dictionnaire de règles :
    # filters = {
    #     "nom_filtre": {"col": "nom_colonne", "values": [...]}
    # }

    # Si filters n'est pas fourni, on utilise le dict global FILTERS_PEGASS.
    # ⚠ Ici, on ne touche à FILTERS_PEGASS qu'au moment de l'APPEL, pas à la définition

    if filters is None:
        filters = globals()["FILTERS_PEGASS"]  # va chercher le dict global au moment de l'appel

    rule = filters[key]
    col = rule["col"]
    values = rule["values"]

    # si values est une seule valeur, on l'encapsule dans une liste
    if not isinstance(values, (list, tuple, set)):
        values = [values]

    return df.loc[df[col].isin(values)]

##5. Sauvegarder les données dans un sheet

In [11]:
def save_dataframe_to_sheet(spreadsheet_id, client, df):
    """
    Sauvegarde un DataFrame dans une feuille Google Sheets.

    Cette fonction ouvre une feuille Google Sheets par son identifiant, sélectionne la première page,
    supprime les données existantes, et enregistre le DataFrame fourni dans la feuille.

    Args:
        spreadsheet_id (str): L'identifiant de la feuille Google Sheets (spreadsheet key).
        client (gspread.Client): Client Google Sheets autorisé.
        df (pd.DataFrame): Le DataFrame Pandas contenant les données à sauvegarder.

    Returns:
        None

    Raises:
        gspread.exceptions.APIError: Si la feuille ou la page demandée ne peut être ouverte ou modifiée.
        ValueError: Si le DataFrame fourni est vide ou invalide.
    """
    # Étape 1: Ouvre la feuille Google Sheets par son identifiant
    spreadsheet = client.open_by_key(spreadsheet_id)

    # Étape 2: Sélectionne la première feuille
    worksheet = spreadsheet.get_worksheet(0)

    # Étape 3: Supprime les données existantes dans la feuille
    worksheet.clear()
    print(f"🗑️ Les anciennes données ont été supprimées de la feuille '{worksheet.title}'")

    # Étape 4: Convertit le DataFrame en chaînes de caractères pour éviter les erreurs de format
    df_to_save = df.copy().astype(str)

    # Étape 5: Écrit le DataFrame dans la feuille Google Sheets
    worksheet.update([df_to_save.columns.values.tolist()] + df_to_save.values.tolist())

    # Confirmation de la sauvegarde
    print(f"💾 Les nouvelles données ont été sauvegardées dans le fichier '{spreadsheet.title}', feuille '{worksheet.title}'")
    print(f"    Nombre de lignes sauvegardées : {len(df_to_save)}")
    print(f"    Nombre de colonnes sauvegardées : {len(df_to_save.columns)}")

## 6. Vérifications

In [12]:
def verifier_colonne_structure(df, col_code_structure, df_ref_structure):
    """
    Vérifie la validité d'une colonne de codes structure :
    - Présence de NaN ou de chaînes vides
    - Doublons
    - Existence dans le référentiel
    """
    print(f"\n🔎 Vérification de la colonne '{col_code_structure}'")

    # 1. Vérification des NaN ou valeurs vides
    lignes_vides = df[df[col_code_structure].isna() | (df[col_code_structure] == "")]
    if not lignes_vides.empty:
        print(f"   ❌ {len(lignes_vides)} valeur(s) manquante(s) ou vide(s) détectée(s).")
    else:
        print("   ✅ Aucun NaN ou valeur vide détecté.")

    # 2. Vérification des doublons (uniquement les codes)
    doublons_series = df[col_code_structure][df[col_code_structure].duplicated(keep=False)]
    if not doublons_series.empty:
        codes_doublons = sorted(doublons_series.value_counts().index.tolist())
        print(f"   ❌ {len(codes_doublons)} code(s) en doublon : {codes_doublons}")
    else:
        print("   ✅ Aucun doublon détecté.")

    # 3. Vérification des codes absents du référentiel
    codes_dans_df = set(df[col_code_structure].dropna().unique())
    codes_dans_ref = set(df_ref_structure[col_code_structure].dropna().unique())
    codes_manquants = codes_dans_df - codes_dans_ref

    if codes_manquants:
        print(f"   ❌ {len(codes_manquants)} code(s) non trouvés dans le référentiel : {sorted(codes_manquants)}")
    else:
        print("   ✅ Tous les codes sont présents dans le référentiel.")


def verifier_mapping(df, col_code_structure, col_libele, df_ref_structure):
    """
    Vérifie la validité d'une colonne de codes structure :
    - Présence de NaN ou de chaînes vides (affiche les libellés correspondants)
    - Doublons (affiche les codes)
    - Existence dans le référentiel (affiche les codes manquants)
    """
    print(f"\n🔎 Vérification de la colonne '{col_libele}' et mapping associé '{col_code_structure}'")

    lignes_vides = df[df[col_code_structure].isna() | (df[col_code_structure] == "")]
    if not lignes_vides.empty:
        print(f"   ❌ {len(lignes_vides)} Valeurs non mappées. Libellés associés :")
        print(sorted(lignes_vides[col_libele].dropna().unique().tolist()))
    else:
        print("   ✅ Mapping réalisé avec succès.")

## 7. Rapprochement libellés

In [13]:
def rapprochement_libelles(df_ref, df_traiter, colonne_analyser, seuil_alerte=0.8, embeddings_file='reference_embeddings.pt', silent=True):
    # Charger le modèle pré-entraîné
    model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

    # Obtenir les embeddings des libellés de référence
    reference_labels = df_ref['nom_structure'].tolist()

    # Vérifier si le fichier d'embeddings existe
    if os.path.exists(embeddings_file):
        reference_embeddings = torch.load(embeddings_file)
    else:
        reference_embeddings = model.encode(reference_labels, convert_to_tensor=True)
        torch.save(reference_embeddings, embeddings_file)

    # Dictionnaire pour mémoriser les rapprochements déjà calculés
    memo_similarities = {}

    # Fonction pour trouver le libellé de référence le plus similaire
    def find_most_similar(label, reference_embeddings, reference_labels):
        if label in memo_similarities:
            return memo_similarities[label]
        else:
            label_embedding = model.encode(label, convert_to_tensor=True)
            cosine_scores = util.pytorch_cos_sim(label_embedding, reference_embeddings)[0]
            top_result = torch.argmax(cosine_scores)
            result = (reference_labels[top_result], cosine_scores[top_result].item())
            memo_similarities[label] = result
            return result

    # Ajouter les colonnes N_structure et nom_structure au DataFrame à traiter
    df_traiter['n_structure'] = None
    df_traiter['nom_structure'] = None

    # Rapprocher chaque libellé et mettre à jour le DataFrame
    for index, row in df_traiter.iterrows():
        label_to_match = row[colonne_analyser]

        # Simplifications et corrections des libellés
        label_to_match_rework = re.sub(r'unité locale', 'UL', label_to_match, flags=re.IGNORECASE)
        label_to_match_rework = re.sub(r'direction territoriale', 'DT', label_to_match_rework, flags=re.IGNORECASE)
        label_to_match_rework = re.sub(r'antenne', 'AL', label_to_match_rework, flags=re.IGNORECASE)
        label_to_match_rework = re.sub(r'unite locale', 'UL', label_to_match_rework, flags=re.IGNORECASE)

        # Trouver le libellé de référence le plus proche
        most_similar_label, score = find_most_similar(label_to_match_rework, reference_embeddings, reference_labels)
        matching_code = df_ref[df_ref['nom_structure'] == most_similar_label]['n_structure'].values[0]

        # Condition sur le score
        if score > seuil_alerte:
            if not silent:
                print(f"✅ {label_to_match} -> {most_similar_label} (Score: {score:.2f})")
            df_traiter.at[index, 'n_structure'] = matching_code
            df_traiter.at[index, 'nom_structure'] = most_similar_label
        else:
            if not silent:
                print(f"⚠️ {label_to_match} -> {most_similar_label} (Score: {score:.2f})")
            df_traiter.at[index, 'n_structure'] = ""
            df_traiter.at[index, 'nom_structure'] = ""

    return df_traiter

# Variables globales

In [14]:
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

# CHARGEMENT DE TOUTES LES DONNEES PAR TABLE

# 0. Ref_structure

In [15]:
df_ref_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw/').worksheet('Feuille 1'))
df_ref_structure.head()

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,N_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,Structure_de_rattachement,Rattachements_successifs,DT_de_rattachement,lon,lat
0,2615.0,ANTENNE LOCALE - AL,AL DE DELLE,90100.0,90033,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",90,2010-02-08 00:00:00,NaT,95 - DT DU TERRITOIRE DE BELFORT,AL 2615,95 - DT DU TERRITOIRE DE BELFORT,7.000705,47.506725
1,2669.0,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43220.0,43087,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2669,48 - DT DE LA HAUTE LOIRE,4.346423,45.214392
2,2670.0,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43600.0,43224,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2670,48 - DT DE LA HAUTE LOIRE,4.235474,45.242445
3,2671.0,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43300.0,43112,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2671,48 - DT DE LA HAUTE LOIRE,3.495645,45.098285
4,2672.0,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43000.0,43157,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2672,48 - DT DE LA HAUTE LOIRE,3.879748,45.044677

# 1. PEGASS

In [ ]:
# EXEMPLE :  Charger le DataFrame
# spreadsheet = gspread_client.open_by_url("https://docs.google.com/spreadsheets/d/1WEoWR3dnhy7NL5ISoD6o-58krsttfHkiqaJz30Vvg74/")
# worksheet = spreadsheet.worksheet("Feuille 1")
# df_raw = get_as_dataframe(worksheet)

##1.1 rattachement_court

In [ ]:
rattachement_court = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU/edit?usp=sharing').worksheet('Feuille 1'))

In [ ]:
rattachement_court.head()

   n_structure                DT_de_rattachement
0         2615  95 - DT DU TERRITOIRE DE BELFORT
1         2669         48 - DT DE LA HAUTE LOIRE
2         2670         48 - DT DE LA HAUTE LOIRE
3         2671         48 - DT DE LA HAUTE LOIRE
4         2672         48 - DT DE LA HAUTE LOIRE

In [ ]:
rattachement_court.columns

Index(['n_structure', 'DT_de_rattachement'], dtype='object')

## 1.2 Activité_benevole ref activité

In [ ]:
Ref_activité_benevole = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1rf1gXTylNEHEt72UfwZO62gIfgzf9eY8lPqhXLJ5hs8/edit').worksheet('Feuille 1'))

In [ ]:
Ref_activité_benevole.head()

   id   libelle  actionid
0  87  M4O6DRFA        19
1  58  M85NOLCG        81
2  86  5Z7PXHVZ        32
3  39  VAO31CNW         5
4   5  GZQNTZQN        13

In [ ]:
Ref_activité_benevole.columns

Index(['id', 'libelle', 'actionid'], dtype='object')

## 1.3 Pegass_activite / Activite

In [ ]:
Pegass_activite = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13Ygh1goryIgp2UCh19tKaTv3AWkfsSMInuS8-VMbmeU/edit').worksheet('Feuille 1'))

In [ ]:
Pegass_activite.head()

,typeActiviteId,Type,externalID,id,libelle,structureMenanActiviteId,structureOrganisatriceId
0,74,3324,8171,97,JM748191,19884,1146
1,60,4879,16563,77,LZXLWE0B,7189,7252
2,65,3186,1174,45,OWLODJGL,15527,10543
3,75,16759,6861,44,E9HB7T5R,13392,1951
4,79,9846,9597,25,YFUHXPZD,10940,19260

In [ ]:
Pegass_activite.dtypes

typeActiviteId               int64
Type                         int64
externalID                   int64
id                           int64
libelle                     object
structureMenanActiviteId     int64
structureOrganisatriceId     int64
dtype: object

In [ ]:
Pegass_activite.columns

Index(['typeActiviteId', 'Type', 'externalID', 'id', 'libelle',
       'structureMenanActiviteId', 'structureOrganisatriceId'],
      dtype='object')

## 1.4 PegassInscription / Inscription

In [ ]:
Pegass_inscription = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1wCYPGwDVKZC6BBuMnOc7kB98agof5IMkdn9W7xn5UUg/edit').worksheet('Feuille 1'))

In [ ]:
Pegass_inscription.dtypes

utilisateurId    object
debut            object
fin              object
statut             bool
activite_id       int64
dtype: object

In [ ]:
Pegass_inscription.columns

Index(['utilisateurId', 'debut', 'fin', 'statut', 'activite_id'], dtype='object')

In [ ]:
Pegass_inscription.head()

  utilisateurId       debut         fin  statut  activite_id
0      UMSA0P47  2025-03-03  2025-04-27    True        17109
1      QJX4DGNL  2025-06-16  2025-09-25   False        13865
2      7XP58P25  2025-06-30  2025-02-09    True        12105
3      VDX9JSKS  2025-01-18  2025-08-07   False        12358
4      RIXHN1J3  2025-05-27  2025-04-10    True        13057

## 1.5. PREPARATION DE LA BASE DE DONNEES

##1.5.1 Renommer les variables

In [ ]:
Pegass_inscription = renommer_par_nom_table(Pegass_inscription, "Pegass_inscription", mapping_df)

In [ ]:
Pegass_inscription.head()

      nivol debut_inscription fin_inscription  statut_inscription  activite_id
0  UMSA0P47        2025-03-03      2025-04-27                True        17109
1  QJX4DGNL        2025-06-16      2025-09-25               False        13865
2  7XP58P25        2025-06-30      2025-02-09                True        12105
3  VDX9JSKS        2025-01-18      2025-08-07               False        12358
4  RIXHN1J3        2025-05-27      2025-04-10                True        13057

In [ ]:
Pegass_inscription.columns

Index(['nivol', 'debut_inscription', 'fin_inscription', 'statut_inscription',
       'activite_id'],
      dtype='object')

In [ ]:
Pegass_inscription.dtypes

nivol                 object
debut_inscription     object
fin_inscription       object
statut_inscription      bool
activite_id            int64
dtype: object

Verifier que les données soient au bon format

In [ ]:
#mettre les dates en format date
Pegass_inscription["debut_inscription"] = pd.to_datetime( Pegass_inscription["debut_inscription"])
Pegass_inscription["fin_inscription"] = pd.to_datetime( Pegass_inscription["fin_inscription"])

In [ ]:
Pegass_activite = renommer_par_nom_table(Pegass_activite, "Pegass_activite", mapping_df)
Pegass_activite.head()

,activite_benevole_id,Type,dps_id,activite_id,libelle_activite,structure_menant_activite_id,structure_organisatrice_id
0,74,3324,8171,97,JM748191,19884,1146
1,60,4879,16563,77,LZXLWE0B,7189,7252
2,65,3186,1174,45,OWLODJGL,15527,10543
3,75,16759,6861,44,E9HB7T5R,13392,1951
4,79,9846,9597,25,YFUHXPZD,10940,19260

In [ ]:
Pegass_activite.columns

Index(['activite_benevole_id', 'Type', 'dps_id', 'activite_id',
       'libelle_activite', 'structure_menant_activite_id',
       'structure_organisatrice_id'],
      dtype='object')

In [ ]:
Ref_activité_benevole = renommer_par_nom_table(Ref_activité_benevole, "Ref_activité_benevole", mapping_df)
Ref_activité_benevole.head()

   activite_benevole_id libelle_activite_benevole  action_id
0                    87                  M4O6DRFA         19
1                    58                  M85NOLCG         81
2                    86                  5Z7PXHVZ         32
3                    39                  VAO31CNW          5
4                     5                  GZQNTZQN         13

In [ ]:
Ref_activité_benevole.columns

Index(['activite_benevole_id', 'libelle_activite_benevole', 'action_id'], dtype='object')

# 2. GAIA

## 2.1. GAIA_contact

In [ ]:
GAIA_contact = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1k4-nMZqUulcZBPMplZLWHcvSTvzISqF9uMnlITdikmI/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.2. GAIA_action

In [ ]:
GAIA_action = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1XvfYhne_YxMBVfgkDUzKhhOle9-bmEP3j0gpBYZsKuo/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.3. GAIA_rattachement_action

In [ ]:
GAIA_rattachement_action = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1vtC3hpxh6RIcmhMjifVFoi169uhdi0f9fpKXP9FqEd8/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.4 GAIA_act_str

In [ ]:
GAIA_act_str = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1PrK18aa8dllTjXOEyPHXMEgqP4gm1ZeJdnCmlUG78EA/edit?usp=drive_link').worksheet('Feuille 1'))

In [ ]:
GAIA_act_str.head()

   act_id    date_fin  str_id
0    8229  2024-10-20   16706
1   15289  2023-01-10    4399
2    9045  2024-08-01     844
3     634  2024-03-29   18956
4    9445  2024-01-24    6595

## 2.5. GAIA_structure

In [ ]:
GAIA_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1forcw_rC0WCcwu6K8-AUhm1sur9pp5XZX_YTCKaBA6g/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.6. Preparation de la base

### 2.6.1. Renommer les variables

In [ ]:
GAIA_action = renommer_par_nom_table(GAIA_action, "GAIA_action", mapping_df)
GAIA_rattachement_action = renommer_par_nom_table(GAIA_rattachement_action, "GAIA_rattachement_action", mapping_df)
GAIA_contact = renommer_par_nom_table(GAIA_contact, "GAIA_contact", mapping_df)
GAIA_structure = renommer_par_nom_table(GAIA_structure, "GAIA_structure", mapping_df)
GAIA_act_str = renommer_par_nom_table(GAIA_act_str, "GAIA_act_str", mapping_df)

In [ ]:
GAIA_structure.head()

   id_structure n_structure
0          5964    DUHEF576
1         10554    B0894MQ9
2          7228    9CPRGHX3
3         19290    NLN17U9Y
4         13274    K8L0YGL2

# 3. NOMINATION

## 3.1. NOMINATION_nomination

In [ ]:
NOMINATION_nomination = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ywCGFgW5eLONMNK64o4NZrQQzasqfEGnnQL6LfDXbbM/edit?gid=614834196').worksheet('NOMINATION_nomination'))

In [ ]:
NOMINATION_nomination.head()

        id  code       nom groupe_nomination
0   5398.0  34.0  9JAZ5TZC          IRMXGWYS
1  16994.0  90.0  HRBKUXVW          JTEXZC5K
2   6624.0  59.0  SAVTNA9Z          95HU6MQS
3  17095.0  79.0  1C7EKQXD          35WAVBZL
4  10213.0  29.0  APULAIGE          RP0Y9FLP

## 3.2 NOMINATION_attribution_nomination

In [ ]:
NOMINATION_attribution_nomination = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1BzCcfO1NLM5oMmBD1cBELIuvBvVjucsK6Wm4zPTaO-Q/').worksheet('NOMINATION_attribution_nomination'))

In [ ]:
NOMINATION_attribution_nomination.head()

,structure_id,nomination_id,sous_titre,date_debut_nomination,date_fin_nomination,statut,contact_id
0,8229.0,66.0,UASOM780,2025-08-01,2025-01-21,0.0,17370.0
1,15289.0,47.0,VVSQZZOZ,2024-01-02,2025-02-06,1.0,9594.0
2,9045.0,91.0,4KAZKMBR,2024-05-07,2025-12-27,0.0,9503.0
3,634.0,76.0,RKG6NTRH,2023-11-02,2025-12-28,0.0,5711.0
4,9445.0,12.0,6OUYCPHS,2024-07-09,2025-04-03,0.0,11100.0

## 3.3. Préparation de la base

### 3.3.1. Renommer les variables

In [ ]:
NOMINATION_nomination = renommer_par_nom_table(NOMINATION_nomination, "nomination", mapping_df)
NOMINATION_attribution_nomination = renommer_par_nom_table(NOMINATION_attribution_nomination, "attribution_nomination", mapping_df)

# 4. IMPACT

## 4.1 Impact_indicateurs

In [ ]:
IMPACT_indicateurs = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

NoValidUrlKeyFound:

## 4.2 Impact_indicateur_value

In [ ]:
IMPACT_indicateur_value = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.3 Impact_donnees_activite

In [ ]:
IMPACT_donnees_activite = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.4 Impact_abstract_donnees_activite

In [ ]:
IMPACT_abstract_donnees_activite = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.5. Preparation de la base

### 4.5.1. Renommer les variables

In [ ]:
IMPACT_indicateurs = renommer_par_nom_table(IMPACT_indicateurs, "IMPACT_indicateurs", mapping_df)
IMPACT_indicateur_value = renommer_par_nom_table(IMPACT_indicateur_value, "IMPACT_indicateur_value", mapping_df)
IMPACT_donnees_activite = renommer_par_nom_table(IMPACT_donnees_activite, "IMPACT_donnees_activite", mapping_df)
IMPACT_abstract_donnees_activite = renommer_par_nom_table(IMPACT_abstract_donnees_activite, "IMPACT_abstract_donnees_activite", mapping_df)

# 5. Données financières

## 5.1 DT_Prod

In [ ]:
dt_prod = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c').worksheet('DT_Prod'), skiprows=3)
dt_prod.head()

,Région,Dptmt,N° Structure,N° Smartview,Nom Structure,Réalisé 2021 Total Année,Réalisé 2022 Total Année,Réalisé 2023 Total Année,Reprévision 9 2024 Total Année,Réalisé 2024 Total Année,Unnamed: 10,Unnamed: 11,Variation Réel 24/Réel 23\n\nen €uros,Variation Reprev24 /Réel 24\n\nen €uros
0,AUVERGNE RHONE ALPES,D,01,ORDD001,AIN,922778.39,959737.28,881847.34,8.082371e+05,869883.02,ok,OR,-11964.32,61645.950000
1,AUVERGNE RHONE ALPES,D,03,ORDD003,ALLIER,258032.19,242334.13,274750.70,2.632936e+05,281212.64,ok,OR,6461.94,17919.026667
2,AUVERGNE RHONE ALPES,D,07,ORDD007,ARDÈCHE,164466.54,243465.22,179073.48,2.361657e+05,250747.99,ok,OR,71674.51,14582.330000
3,AUVERGNE RHONE ALPES,D,15,ORDD015,CANTAL,63757.95,50073.56,42236.30,4.410800e+04,98744.62,ok,OR,56508.32,54636.620000
4,AUVERGNE RHONE ALPES,D,26,ORDD026,DRÔME,1074799.56,1163770.36,1061919.22,1.070820e+06,1060115.15,ok,OR,-1804.07,-10704.984667

## 5.2 DT_ResNet

In [ ]:
dt_resnet = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c').worksheet('DT_Res Net'), skiprows=3)
dt_resnet.head()

,Région,Dptmt,N° Structure,N° Smartview,Nom Structure,Réalisé 2021 Total Année,Réalisé 2022 Total Année,Réalisé 2023 Total Année,Reprévision 9 2024 Total Année,Réalisé 2024 Total Année,Unnamed: 10,Unnamed: 11,Variation Réel 24/Réel 23\n\nen €uros,Variation Reprev24 /Réel 24\n\nen €uros
0,AUVERGNE RHONE ALPES,D,01,ORDD001,AIN,30128.09,146820.39,120441.98,19275.296200,69803.50,ok,OR,-50638.48,50528.203800
1,AUVERGNE RHONE ALPES,D,03,ORDD003,ALLIER,46369.08,16027.98,-22595.97,-24704.237867,-13687.53,ok,OR,8908.44,11016.707867
2,AUVERGNE RHONE ALPES,D,07,ORDD007,ARDÈCHE,-15617.78,25929.70,-47265.83,-26110.144200,3324.23,ok,OR,50590.06,29434.374200
3,AUVERGNE RHONE ALPES,D,15,ORDD015,CANTAL,20964.78,-247.35,-6588.05,-7765.776800,2034.92,ok,OR,8622.97,9800.696800
4,AUVERGNE RHONE ALPES,D,26,ORDD026,DRÔME,104766.37,181771.18,91493.37,79918.185072,61579.15,ok,OR,-29914.22,-18339.035072

## 5.3 DT_ResNet Corrélé Prod

In [ ]:
dt_resnet_corr_prod = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c').worksheet('DT_Res corrélé Prod'), skiprows=3)
dt_resnet_corr_prod.head()

,Région,Dptmt,N° Structure,N° Smartview,Nom Structure,Réalisé 2021 Total Année,Réalisé 2022 Total Année,Réalisé 2023 Total Année,Reprévision 9 2024 Total Année,Réalisé 2024 Total Année,Unnamed: 10,Unnamed: 11,Variation Réel 24/Réel 23\n\nen €uros,Variation Reprev24 /Réel 24\n\nen €uros
0,AUVERGNE RHONE ALPES,D,01,ORDD001,AIN,922778.39,"=IFERROR('DT_Res Net'!G5/DT_Prod!G5;"""")","=IFERROR('DT_Res Net'!H5/DT_Prod!H5;"""")",=+'DT_Res Net'!I5/DT_Prod!$G$5,"=IFERROR('DT_Res Net'!J5/DT_Prod!J5;"""")",ok,OR,-11964.32,61645.950000
1,AUVERGNE RHONE ALPES,D,03,ORDD003,ALLIER,258032.19,"=IFERROR('DT_Res Net'!G6/DT_Prod!G6;"""")","=IFERROR('DT_Res Net'!H6/DT_Prod!H6;"""")",=+'DT_Res Net'!I6/DT_Prod!$G$5,"=IFERROR('DT_Res Net'!J6/DT_Prod!J6;"""")",ok,OR,6461.94,17919.026667
2,AUVERGNE RHONE ALPES,D,07,ORDD007,ARDÈCHE,164466.54,"=IFERROR('DT_Res Net'!G7/DT_Prod!G7;"""")","=IFERROR('DT_Res Net'!H7/DT_Prod!H7;"""")",=+'DT_Res Net'!I7/DT_Prod!$G$5,"=IFERROR('DT_Res Net'!J7/DT_Prod!J7;"""")",ok,OR,71674.51,14582.330000
3,AUVERGNE RHONE ALPES,D,15,ORDD015,CANTAL,63757.95,"=IFERROR('DT_Res Net'!G8/DT_Prod!G8;"""")","=IFERROR('DT_Res Net'!H8/DT_Prod!H8;"""")",=+'DT_Res Net'!I8/DT_Prod!$G$5,"=IFERROR('DT_Res Net'!J8/DT_Prod!J8;"""")",ok,OR,56508.32,54636.620000
4,AUVERGNE RHONE ALPES,D,26,ORDD026,DRÔME,1074799.56,"=IFERROR('DT_Res Net'!G9/DT_Prod!G9;"""")","=IFERROR('DT_Res Net'!H9/DT_Prod!H9;"""")",=+'DT_Res Net'!I9/DT_Prod!$G$5,"=IFERROR('DT_Res Net'!J9/DT_Prod!J9;"""")",ok,OR,-1804.07,-10704.984667

## 5.4 DT_Très brute

In [ ]:
dt_tres_brute = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c').worksheet('DT_Trés brute'), skiprows=3)
dt_tres_brute.head()

,Région,Dptmt,N° Structure,N° Smartview,Nom Structure,31/12/2021,31/12/2022,31/12/2023,31/12/2024,Charges d'exploitation prévisionnelles 2024,Avance trésorerie brute en mois de charges d'exploitat° 2024,Tréso nette au 31/12/2024,Avance trésorerie nette en mois de charges d'exploitat° 2024,Unnamed: 13,Unnamed: 14
0,AUVERGNE RHONE ALPES,D,01,ORDD001,AIN,1949598.57,2188992.41,2279078.18,2349996.53,858093.11,32.863518,2246300.35,31.413379,ok,OR
1,AUVERGNE RHONE ALPES,D,03,ORDD003,ALLIER,532200.79,556116.67,570233.66,656815.92,308126.96,25.579687,639970.85,24.923655,ok,OR
2,AUVERGNE RHONE ALPES,D,07,ORDD007,ARDÈCHE,481616.27,501607.55,468030.02,481073.45,256753.91,22.484103,476820.44,22.285329,ok,OR
3,AUVERGNE RHONE ALPES,D,15,ORDD015,CANTAL,72144.51,78681.62,72357.28,125079.95,98383.22,15.256254,77705.62,9.477911,ok,OR
4,AUVERGNE RHONE ALPES,D,26,ORDD026,DRÔME,1280235.33,1543451.78,1587282.81,1662079.36,1045349.28,19.079702,1653736.52,18.983931,ok,OR

## 5.5 DT-UL-Ant_Prod

In [ ]:
dt_ul_ant_prod = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c').worksheet('DT-UL-Ant_Prod'), skiprows=3)
dt_ul_ant_prod.head()

,Région,Dptmt,N° Structure,N° Smartview,Nom Structure,Réalisé 2021 Total Année,Réalisé 2022 Total Année,Réalisé 2023 Total Année,Reprévision 9 2024 Total Année,Réalisé 2024 Total Année,Unnamed: 10,Unnamed: 11,Variation Réel 24/Réel 23\n\nen €uros,Variation Reprev24 /Réel 24\n\nen €uros
0,AUVERGNE RHONE ALPES,01,00005,OR00005,DT DE L'AIN,475288.12,441280.69,353970.71,280625.96,281953.94,ok,OR,-72016.77,1327.98
1,AUVERGNE RHONE ALPES,01,00109,OR00109,UNITE LOCALE DU BASSIN BURGIEN,81361.49,73735.99,50653.17,57098.11,60121.83,ok,OR,9468.66,3023.72
2,AUVERGNE RHONE ALPES,01,00135,OR00135,UNITE LOCALE DES PAYS DE LA VEYLE,18459.87,23248.84,38058.58,35595.00,38505.24,ok,OR,446.66,2910.24
3,AUVERGNE RHONE ALPES,01,03733,OR03733,UNITE LOCALE DU VAL DE SAONE,14077.66,18169.83,23893.85,18409.00,21200.20,ok,OR,-2693.65,2791.20
4,AUVERGNE RHONE ALPES,01,03873,OR03873,UNITE LOCALE DE PORTE DE LA DOMBES,46413.87,44458.06,48324.58,47875.00,60028.10,ok,OR,11703.52,12153.10

## 5.6 DT-UL-Ant_Res Net

In [ ]:
dt_ul_ant_res_net = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c').worksheet('DT-UL-Ant_Res Net'), skiprows=3)
dt_ul_ant_res_net.head()

,Région,Dptmt,N° Structure,N° Smartview,Nom Structure,Réalisé 2021 Total Année,Réalisé 2022 Total Année,Réalisé 2023 Total Année,Reprévision 9 2024 Total Année,Réalisé 2024 Total Année,Unnamed: 10,Unnamed: 11,Variation Réel 24/Réel 23\n\nen €uros,Variation Reprev24 /Réel 24\n\nen €uros
0,AUVERGNE RHONE ALPES,01,00005,OR00005,DT DE L'AIN,-14750.42,53075.27,53370.29,-842.6146,-27576.43,ok,OR,-80946.72,-26733.8154
1,AUVERGNE RHONE ALPES,01,00109,OR00109,UNITE LOCALE DU BASSIN BURGIEN,2228.42,10988.14,-14344.23,-13361.8300,-9503.16,ok,OR,4841.07,3858.6700
2,AUVERGNE RHONE ALPES,01,00135,OR00135,UNITE LOCALE DES PAYS DE LA VEYLE,-5115.93,-4553.25,6031.11,6194.1358,3833.87,ok,OR,-2197.24,-2360.2658
3,AUVERGNE RHONE ALPES,01,03733,OR03733,UNITE LOCALE DU VAL DE SAONE,2835.48,3807.59,8319.85,-176.8114,2974.30,ok,OR,-5345.55,3151.1114
4,AUVERGNE RHONE ALPES,01,03873,OR03873,UNITE LOCALE DE PORTE DE LA DOMBES,17483.08,12079.29,14195.19,10484.8962,19796.87,ok,OR,5601.68,9311.9738

## 5.7 DT-UL-Res Net corrélé Prod

In [ ]:
dt_ul_res_net_corr_prod = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c').worksheet('DT-UL-Res corrélé Prod'), skiprows=3)
dt_ul_res_net_corr_prod.head()

,Région,Dptmt,N° Structure,N° Smartview,Nom Structure,Réalisé 2021 Total Année,Réalisé 2022 Total Année,Réalisé 2023 Total Année,Reprévision 9 2024 Total Année,Réalisé 2024 Total Année,Unnamed: 10,Unnamed: 11,Variation Réel 24/Réel 23\n\nen €uros,Variation Reprev24 /Réel 24\n\nen €uros
0,AUVERGNE RHONE ALPES,01,00005,OR00005,DT DE L'AIN,-14750.42,=IFERROR('DT-UL-Ant_Res Net'!G5/'DT-UL-Ant_Pro...,=IFERROR('DT-UL-Ant_Res Net'!H5/'DT-UL-Ant_Pro...,=+'DT-UL-Ant_Res Net'!I5/'DT-UL-Ant_Prod'!I5,=IFERROR('DT-UL-Ant_Res Net'!J5/'DT-UL-Ant_Pro...,ok,OR,-80946.72,-26733.8154
1,AUVERGNE RHONE ALPES,01,00109,OR00109,UNITE LOCALE DU BASSIN BURGIEN,2228.42,=IFERROR('DT-UL-Ant_Res Net'!G6/'DT-UL-Ant_Pro...,=IFERROR('DT-UL-Ant_Res Net'!H6/'DT-UL-Ant_Pro...,=+'DT-UL-Ant_Res Net'!I6/'DT-UL-Ant_Prod'!I6,=IFERROR('DT-UL-Ant_Res Net'!J6/'DT-UL-Ant_Pro...,ok,OR,4841.07,3858.6700
2,AUVERGNE RHONE ALPES,01,00135,OR00135,UNITE LOCALE DES PAYS DE LA VEYLE,-5115.93,=IFERROR('DT-UL-Ant_Res Net'!G7/'DT-UL-Ant_Pro...,=IFERROR('DT-UL-Ant_Res Net'!H7/'DT-UL-Ant_Pro...,=+'DT-UL-Ant_Res Net'!I7/'DT-UL-Ant_Prod'!I7,=IFERROR('DT-UL-Ant_Res Net'!J7/'DT-UL-Ant_Pro...,ok,OR,-2197.24,-2360.2658
3,AUVERGNE RHONE ALPES,01,03733,OR03733,UNITE LOCALE DU VAL DE SAONE,2835.48,=IFERROR('DT-UL-Ant_Res Net'!G8/'DT-UL-Ant_Pro...,=IFERROR('DT-UL-Ant_Res Net'!H8/'DT-UL-Ant_Pro...,=+'DT-UL-Ant_Res Net'!I8/'DT-UL-Ant_Prod'!I8,=IFERROR('DT-UL-Ant_Res Net'!J8/'DT-UL-Ant_Pro...,ok,OR,-5345.55,3151.1114
4,AUVERGNE RHONE ALPES,01,03873,OR03873,UNITE LOCALE DE PORTE DE LA DOMBES,17483.08,=IFERROR('DT-UL-Ant_Res Net'!G9/'DT-UL-Ant_Pro...,=IFERROR('DT-UL-Ant_Res Net'!H9/'DT-UL-Ant_Pro...,=+'DT-UL-Ant_Res Net'!I9/'DT-UL-Ant_Prod'!I9,=IFERROR('DT-UL-Ant_Res Net'!J9/'DT-UL-Ant_Pro...,ok,OR,5601.68,9311.9738

## 5.8 DT-UL_Tréso brute

In [ ]:
dt_ul_treso_brute = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c').worksheet('DT-UL_Tréso brute'), skiprows=3)
dt_ul_treso_brute.head()

,Région,Dptmt,N° Structure,N° Smartview,Nom Structure,31/12/2021,31/12/2022,31/12/2023,31/12/2024,Charges d'exploitation prévisionnelles 2024,Avance trésorerie brute en mois de charges d'exploitat° 2024,Tréso nette au 31/12/2024,Avance trésorerie nette en mois de charges d'exploitat° 2024,Unnamed: 13,Unnamed: 14
0,AUVERGNE RHONE ALPES,01,00005,OR00005,DT DE L'AIN,507721.26,524892.25,540923.07,552733.58,325179.10,20.397384,516666.54,19.066411,ok,OR
1,AUVERGNE RHONE ALPES,01,00109,OR00109,UNITE LOCALE DU BASSIN BURGIEN,55160.66,49839.72,55421.96,34187.15,77296.06,5.307461,24014.25,3.728146,ok,OR
2,AUVERGNE RHONE ALPES,01,00135,OR00135,UNITE LOCALE DES PAYS DE LA VEYLE,23332.45,33320.05,24313.16,29857.75,35185.08,10.183095,30275.78,10.325665,ok,OR
3,AUVERGNE RHONE ALPES,01,03733,OR03733,UNITE LOCALE DU VAL DE SAONE,85479.30,84854.09,93454.92,93249.79,20151.64,55.528854,99513.16,59.258597,ok,OR
4,AUVERGNE RHONE ALPES,01,03873,OR03873,UNITE LOCALE DE PORTE DE LA DOMBES,123278.46,132751.05,155988.05,176038.04,43497.65,48.564842,165817.00,45.745092,ok,OR

## 5.9 Préparation de la base

### 5.9.1 Renommer les variables

In [ ]:
dt_prod = renommer_par_nom_table(dt_prod, "financier", mapping_df)
dt_resnet = renommer_par_nom_table(dt_resnet, "financier", mapping_df)
dt_resnet_corr_prod = renommer_par_nom_table(dt_resnet_corr_prod, "financier", mapping_df)
dt_tres_brute = renommer_par_nom_table(dt_tres_brute, "financier", mapping_df)
dt_ul_ant_prod = renommer_par_nom_table(dt_ul_ant_prod, "financier", mapping_df)
dt_ul_ant_res_net = renommer_par_nom_table(dt_ul_ant_res_net, "financier", mapping_df)
dt_ul_res_net_corr_prod = renommer_par_nom_table(dt_ul_res_net_corr_prod, "financier", mapping_df)
dt_ul_treso_brute = renommer_par_nom_table(dt_ul_treso_brute, "financier", mapping_df)

In [ ]:
dt_prod = dt_prod[['n_structure','Réalisé 2024 Total Année']]
dt_resnet = dt_resnet[['n_structure','Réalisé 2024 Total Année']]
dt_resnet_corr_prod = dt_resnet_corr_prod[['n_structure','Réalisé 2024 Total Année']]
dt_tres_brute = dt_tres_brute[['n_structure','Tréso nette au 31/12/2024']]

dt_ul_ant_prod = dt_ul_ant_prod[['n_structure','Réalisé 2024 Total Année']]
dt_ul_ant_res_net = dt_ul_ant_res_net[['n_structure','Réalisé 2024 Total Année']]
dt_ul_res_net_corr_prod = dt_ul_res_net_corr_prod[['n_structure','Réalisé 2024 Total Année']]
dt_ul_treso_brute = dt_ul_treso_brute[['n_structure','Tréso nette au 31/12/2024']]

# FUSION DES TABLES

# 1. Fusion PEGASS activité, inscription, ref_activité_bénévole, rattachement_court

# 1.1 Filtres généraux à appliquer

In [ ]:
FILTERS = {
    "filtres_activites_ben_test": {"col": "activite_benevole_id", "values": [1, 2, 3, 4]}, #variables numeric
     "statut_inscription" : {"col": "statut_inscription", "values": [1]},
    "vulne_core": {"col": "Indicateur", "values": ["Indice de vulnérabilité global", "Revenu median"]}, #variables textuelles
}

# 1.2. Fusion des tables

In [ ]:
# left join (tous les id de df1, et ce qu'on trouve dans df2)
# left = pd.merge(df1, df2, on="id", how="left")

df1 = pd.merge(Pegass_inscription, Pegass_activite, left_on="activite_id", right_on="activite_id", how="left")

In [ ]:
df1.head()

,nivol,debut_inscription,fin_inscription,statut_inscription,activite_id,activite_benevole_id,Type,dps_id,libelle_activite,structure_menant_activite_id,structure_organisatrice_id
0,UMSA0P47,2025-03-03,2025-04-27,True,17109,NaN,NaN,NaN,NaN,NaN,NaN
1,QJX4DGNL,2025-06-16,2025-09-25,False,13865,NaN,NaN,NaN,NaN,NaN,NaN
2,7XP58P25,2025-06-30,2025-02-09,True,12105,NaN,NaN,NaN,NaN,NaN,NaN
3,VDX9JSKS,2025-01-18,2025-08-07,False,12358,NaN,NaN,NaN,NaN,NaN,NaN
4,RIXHN1J3,2025-05-27,2025-04-10,True,13057,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df2 = pd.merge(df1, Ref_activité_benevole, left_on="activite_benevole_id", right_on="activite_benevole_id", how="left")

In [ ]:
df2.head()

,nivol,debut_inscription,fin_inscription,statut_inscription,activite_id,activite_benevole_id,Type,dps_id,libelle_activite,structure_menant_activite_id,structure_organisatrice_id,libelle_activite_benevole,action_id
0,UMSA0P47,2025-03-03,2025-04-27,True,17109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,QJX4DGNL,2025-06-16,2025-09-25,False,13865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7XP58P25,2025-06-30,2025-02-09,True,12105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,VDX9JSKS,2025-01-18,2025-08-07,False,12358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,RIXHN1J3,2025-05-27,2025-04-10,True,13057,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df2.to_csv("df2.csv", index=False, encoding="utf-8-sig")

In [ ]:
df2 = df2.rename(columns={"structureMenanActiviteId": "structure_menant_activite_id"}) #renomage temporaire à  supprimer après

In [ ]:
#Merge sur la structure de ratachement
df2 = pd.merge(df2, rattachement_court, left_on="structure_menant_activite_id", right_on="n_structure", how="left").drop(columns=["n_structure"])

In [ ]:
df2.columns

Index(['nivol', 'debut_inscription', 'fin_inscription', 'statut_inscription',
       'activite_id', 'activite_benevole_id', 'Type', 'dps_id',
       'libelle_activite', 'structure_menant_activite_id',
       'structure_organisatrice_id', 'libelle_activite_benevole', 'action_id',
       'DT_de_rattachement'],
      dtype='object')

# 2. Fusion GAIA rattachement_action, action, act_str, structure

# 2.1. Filtres généraux à appliquer

In [ ]:
#FTILRE SUR ANNEE NULLE OU FIN EN 2025

# Vérification que la colonne est au format datetime
GAIA_act_str['date_fin_activite_struct'] = pd.to_datetime(GAIA_act_str['date_fin_activite_struct'], errors='coerce')

# Filtrage : date nulle ou année = 2025
GAIA_act_str = GAIA_act_str[
    GAIA_act_str['date_fin_activite_struct'].isna() | (GAIA_act_str['date_fin_activite_struct'].dt.year == 2025)
]

# 2.2. Fusion des tables

In [ ]:
# left = pd.merge(df1, df2, on="id", how="left")

# 1) Join avec action sur act_id
df_GAIA = pd.merge(GAIA_rattachement_action, GAIA_action, on="n_action_ben", how="left")

# 2) Join avec rattachement_action sur act_id + str_id
df_GAIA = pd.merge(df_GAIA, GAIA_act_str, on="n_action_ben", how="left")

# 3) Join avec contact sur cob_idrp
df_GAIA = pd.merge(df_GAIA, GAIA_structure, on="id_structure", how="left")

# df final disponible dans df_GAIA
df_GAIA.head()

,n_action_ben,id_gaia,date_fin_ratachement_ben_structure,id_structure,libelle_action_ben,n_groupe_action,date_fin_activite_struct,n_structure_x,n_structure_y
0,11940,10772,2023-11-20,19474,NaN,NaN,NaT,NaN,QVGHLEJY
1,6432,755,2025-02-14,19718,4UA9GNWT,50.0,NaT,NaN,NaN
2,9680,13409,2024-01-26,11982,NaN,NaN,NaT,NaN,NaN
3,6109,7691,2023-10-04,3539,NaN,NaN,NaT,NaN,NaN
4,11975,14276,2024-01-27,14193,EWBWNDKD,21.0,NaT,NaN,3J0LCQ2N

# 3. Fusion NOMINATION nomination, attribution_nomination

## 3.1. Filtres généraux à appliquer

In [ ]:
#FTILRE SUR ANNEE NULLE OU FIN EN 2025

# Vérification que la colonne est au format datetime
NOMINATION_attribution_nomination['date_fin_nomination'] = pd.to_datetime(NOMINATION_attribution_nomination['date_fin_nomination'], errors='coerce')
NOMINATION_attribution_nomination['date_debut_nomination'] = pd.to_datetime(NOMINATION_attribution_nomination['date_debut_nomination'], errors='coerce')

# Filtrage : date nulle ou année = 2025
NOMINATION_attribution_nomination = NOMINATION_attribution_nomination[
    NOMINATION_attribution_nomination['date_fin_nomination'].isna() | (NOMINATION_attribution_nomination['date_fin_nomination'].dt.year == 2025)
]

## 3.2. Fusion des tables

In [ ]:
# left join (tous les id de df1, et ce qu'on trouve dans df2)
# left = pd.merge(df1, df2, on="id", how="left")

df_NOMINATION = pd.merge(NOMINATION_nomination, NOMINATION_attribution_nomination,on="nomination_id", how="left") #VERIFIER LA FOREIGN KEY!

# 4. Fusion IMPACT indicateurs, indicateurs_value, donnees_activite, abstract_donnes_activite

## 4.1. Filtres généraux à appliquer

In [ ]:
#FTILRE SUR ANNEE 2025

# Vérification que la colonne est au format datetime
IMPACT_donnees_activite['date_fin_activite'] = pd.to_datetime(IMPACT_donnees_activite['date_fin_activite'], errors='coerce')
IMPACT_donnees_activite['date_debut_activite'] = pd.to_datetime(IMPACT_donnees_activite['date_debut_activite'], errors='coerce')

# Filtrage : date nulle ou année = 2025
IMPACT_donnees_activite = IMPACT_donnees_activite[ (IMPACT_donnees_activite['date_debut_activite'].dt.year == 2025)]

NameError: name 'IMPACT_donnees_activite' is not defined

## 4.2. Fusion des tables

In [ ]:
# left = pd.merge(df1, df2, on="id", how="left")

# 1) Join avec action sur act_id
df_IMPACT = pd.merge(IMPACT_indicateur_value, IMPACT_indicateurs, on="n_indicateurs", how="left")

# 2) Join avec rattachement_action sur act_id + str_id
df_IMPACT = pd.merge(df_IMPACT, IMPACT_donnees_activite, on="id_activite", how="left")

# 3) Join avec contact sur cob_idrp
df_IMPACT = pd.merge(df_IMPACT, IMPACT_abstract_donnees_activite, on="id_activite", how="left")

# df final disponible dans df_GAIA
df_IMPACT.head()

# 5. Fusion Données financières

In [ ]:
# Données par DT
df_financier_DT = pd.merge(dt_prod, dt_resnet, on="n_structure", how="left")
df_financier_DT = pd.merge(df_financier_DT, dt_resnet_corr_prod, on="n_structure", how="left")
df_financier_DT = pd.merge(df_financier_DT, dt_tres_brute, on="n_structure", how="left")

# Données par structures
df_financier_DT_UL = pd.merge(dt_ul_ant_prod,dt_ul_ant_res_net, on="n_structure", how="left")
df_financier_DT_UL = pd.merge(df_financier_DT_UL, dt_ul_res_net_corr_prod, on="n_structure", how="left")
df_financier_DT_UL = pd.merge(df_financier_DT_UL, dt_ul_treso_brute, on="n_structure", how="left")

In [ ]:
verifier_colonne_structure(df_financier_DT, "n_structure", df_ref_structure)
verifier_colonne_structure(df_financier_DT, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ❌ 1 valeur(s) manquante(s) ou vide(s) détectée(s).
   ✅ Aucun doublon détecté.
   ❌ 108 code(s) non trouvés dans le référentiel : ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '21', '22', '23', '24', '25', '26', '27', '28', '29', '2A', '2B', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '971', '972', '973', '974', '975', '976', '977', '978', '986', '987', '988', 'Source: Smartview-Mise à jour 24 mars 2025']

🔎 Vérification de la colonne 'n_structure'
   ❌ 1 valeur(s) manquante(s) ou vide(s) détectée(s).
   ✅ Aucun doublon détecté.
   ❌ 108 code(s) non trouvés dans le référentiel : ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '21', '22', '23', '24', '25', '26', '27', '28', '29', '2A', '2B', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '971', '972', '973', '974', '975', '976', '977', '978', '986', '987', '988', 'Source: Smartview-Mise à jour 24 mars 2025']

# Calcul des indicateurs

#1. Nombre de bénévoles par activité benevole

##1.1 Selection des colonnes qui nous serons utiles

### 1.1.1 Filtres génériques par indicateur

### 1.1.2 définition des filtres génériques à appliquer

In [ ]:
# NOMBRE DE BENEVOLES PAR ACTIVITE BENEVOLES
# Fonction filtre encore plus sophistiqué

FILTERS_PEGASS = {
    "filtres_activites_ben_test": {"col": "activite_benevole_id", "values": [1, 2, 3, 4]}, #variables numeric
     "statut_inscription" : {"col": "statut_inscription", "values": [1]},
    "vulne_core": {"col": "Indicateur", "values": ["Indice de vulnérabilité global", "Revenu median"]}, #variables textuelles
}

### 1.1.3 Application des filtres primaires

In [ ]:
df2 = filtre_2025(df2,date_col="debut_inscription" )

df2 = filtre(df2,"statut_inscription")

df2 = filtre(df2,"filtres_activites_ben_test")

### 1.1.4 Ajout de la variable mensuelle

In [ ]:
df2['debut_inscription'] = pd.to_datetime(df2['debut_inscription'])
df2["mois_debut_inscription"] = df2["debut_inscription"].dt.month

In [ ]:
Pegass_inscription.head()

      nivol debut_inscription fin_inscription  statut_inscription  activite_id
0  UMSA0P47        2025-03-03      2025-04-27                True        17109
1  QJX4DGNL        2025-06-16      2025-09-25               False        13865
2  7XP58P25        2025-06-30      2025-02-09                True        12105
3  VDX9JSKS        2025-01-18      2025-08-07               False        12358
4  RIXHN1J3        2025-05-27      2025-04-10                True        13057

##1.2 Definition de l'indicateur générique *annuel*

In [ ]:
# On compte le nb de NivolS unniques par Structure
Nb_benevoles_distincts = (df2.groupby('structure_menant_activite_id')['nivol'].nunique()).rename("nb_benevoles_distincts")
# A voir si on peut pas remplacer reset_index par .rename()

In [ ]:
##Definition pour calcul benevoles distincts
def nb_benevoles_distincts_gen(df, filtre=None,
                              col_structure="structure_menant_activite_id",
                              col_user="nivol",
                              out_col="nb_benevoles_distincts"):
    d = df.query(filtre) if filtre else df
    return (d.groupby(col_structure)[col_user]
              .nunique()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

In [ ]:
Nb_benevoles_distincts.head()

structure_menant_activite_id
876.0     1
880.0     3
899.0     1
908.0     1
1240.0    1
Name: nb_benevoles_distincts, dtype: int64

In [ ]:
# A faire sur la base du code de Clément D

### 1.2.1 Calcul des indicateurs un par un

In [ ]:
activite_ben_cible = "Distribution alimentaire"  # l'intitulé que l'on souhaite

Nb_benevoles_Distribution_alimentaire = (
    df2[df2['libelle_activite_benevole'] == activite_ben_cible]  # filtre sur l’intitulé
      .nunique()
      .reset_index(name='nb_benevoles_distincts')
)

In [ ]:
Nb_benevoles_Distribution_alimentaire.head()

                index  nb_benevoles_distincts
0               nivol                       0
1   debut_inscription                       0
2     fin_inscription                       0
3  statut_inscription                       0
4         activite_id                       0

### 1.2.1 Calcul indicateur avec def

In [ ]:
# 2) Indicateur avec filtre
activite_ben_cible = "Distribution alimentaire"
Nb_benevoles_Distribution_alimentaire1 = nb_benevoles_distincts_gen(
    df2,
    filtre=f"libelle_activite_benevole == @activite_ben_cible"
)

### 1.2.2 Calcul des indicateurs par type d'activités bénévole ( avec boucle)

In [ ]:
##Automatisation en créant une boucle

#Il faut prendre activite_id pour le numero d'activité mais là je teste direct avec le libellé
liste_activite_ben= [
    "Distribution alimentaire",
    "Épicerie sociale",
    "Colis alimentaire",
    "Aide d'urgence",
    "Autre dispositif"
]

In [ ]:

def make_var_name(libelle_activite_benevole):
    # Supprimer les accents
    s = unicodedata.normalize("NFKD", libelle_activite_benevole)
    s = "".join(c for c in s if not unicodedata.combining(c))
    # Minuscules + remplacer tout ce qui n'est pas lettre/chiffre par "_"
    s = s.lower()
    s = re.sub(r"[^0-9a-zA-Z]+", "_", s).strip("_")
    return f"df_{s}"

In [ ]:
for activite in liste_activite_ben:
    df_tmp = (
        df2[df2['libelle_activite_benevole'] == activite]
          .groupby('structure_menant_activite_id')['nivol']
          .nunique()
          .reset_index(name='nb_benevoles_distincts')
    )

    var_name = make_var_name(activite)
    globals()[var_name] = df_tmp  # crée une variable df_<nom_simplifié>

    print(f"Créé : {var_name} (libelle_activite_benevole = {activite})")

Créé : df_distribution_alimentaire (libelle_activite_benevole = Distribution alimentaire)
Créé : df_epicerie_sociale (libelle_activite_benevole = Épicerie sociale)
Créé : df_colis_alimentaire (libelle_activite_benevole = Colis alimentaire)
Créé : df_aide_d_urgence (libelle_activite_benevole = Aide d'urgence)
Créé : df_autre_dispositif (libelle_activite_benevole = Autre dispositif)

In [ ]:
df_distribution_alimentaire.head()

Empty DataFrame
Columns: [structure_menant_activite_id, nb_benevoles_distincts]
Index: []

## 1.3. Calcul de l'indicateur annuel par DT de rattachement

In [ ]:
##Definition pour calcul benevoles distincts
def nb_benevoles_distincts_DT_gen(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="nivol",
                              out_col="nb_benevoles_distincts"):
    d = df.query(filtre) if filtre else df
    return (d.groupby(col_structure)[col_user]
              .nunique()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

In [ ]:
# 2) Indicateur avec filtre
activite_ben_cible = "Distribution alimentaire"
Nb_benevoles_Distribution_alimentaire2 = nb_benevoles_distincts_gen(
    df2,
    filtre=f"libelle_activite_benevole == @activite_ben_cible"
)

In [ ]:
Nb_benevoles_Distribution_alimentaire2

Empty DataFrame
Columns: [structure_menant_activite_id, nb_benevoles_distincts]
Index: []

## 1.4 Calcul de l'indicateur générique mensuel

In [ ]:
##Definition pour calcul benevoles distincts
def nb_benevoles_distincts_mois_gen(df, filtre=None,
                              col_structure="structure_menant_activite_id",
                              col_user="nivol",
                              col_mois = "mois_debut_inscription",
                              out_col="nb_benevoles_distincts_mois"):
    d = df.query(filtre) if filtre else df
    return (d.groupby([col_structure, col_mois])[col_user]
              .nunique()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

In [ ]:
# 2) Indicateur avec filtre
activite_ben_cible = "Distribution alimentaire"
Nb_benevoles_Distribution_alimentaire3 = nb_benevoles_distincts_mois_gen(
    df2,
    filtre=f"libelle_activite_benevole == @activite_ben_cible"
)

In [ ]:
Nb_benevoles_Distribution_alimentaire3.head()

Empty DataFrame
Columns: [structure_menant_activite_id, mois_debut_inscription, nb_benevoles_distincts_mois]
Index: []

## 1.5 Calcul de l'indicateur mensuel par DT de rattachement

In [ ]:
##Definition pour calcul benevoles distincts
def nb_benevoles_distincts_mois_DT_gen(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="nivol",
                              col_mois = "mois_debut_inscription",
                              out_col="nb_benevoles_distincts_mois"):
    d = df.query(filtre) if filtre else df
    return (d.groupby([col_structure, col_mois])[col_user]
              .nunique()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

In [ ]:
# 2) Indicateur avec filtre
activite_ben_cible = "Distribution alimentaire"
Nb_benevoles_Distribution_alimentaire4 = nb_benevoles_distincts_mois_DT_gen(
    df2,
    filtre=f"libelle_activite_benevole == @activite_ben_cible"
)

In [ ]:
Nb_benevoles_Distribution_alimentaire4.head()

Empty DataFrame
Columns: [DT_de_rattachement, mois_debut_inscription, nb_benevoles_distincts_mois]
Index: []

# Nombre de bénévoles déclarés sur une activitée

##10.1. Calcul nb de volontaires de l'urgence

In [ ]:
# Filtre sur le libelle approprié
df_urgence = df_GAIA[df_GAIA["libelle_action_ben"] == "Urgences et autres opérations"]

In [ ]:
# On compte le nb de volontaires de l'urgence
NbBeneDecla_GAIA = (df_urgence.groupby('n_structure_x')['id_gaia'].nunique())

In [ ]:
NbBeneDecla_GAIA.head()

Series([], Name: id_gaia, dtype: int64)

# 3. RTAEO & RLAEO

In [ ]:
# Filtre sur le libelle approprié
referents_AEO = df_NOMINATION[df_NOMINATION["libelle_nomination"] == "RTAEO"]

# Filtre sur le libelle approprié
referents_OCR = df_NOMINATION[df_NOMINATION["libelle_nomination"] == "RTOCR"]

In [ ]:
# On compte le nb de RTAEO & RLAEO
referents_AEO = (referents_AEO.groupby('structure_id')['libelle_nomination'].nunique())

In [ ]:
referents_AEO

Series([], Name: libelle_nomination, dtype: int64)

In [ ]:
# DF par mois
annee = 2025

# Mois de l'année
mois = pd.date_range(
    start=f"{annee}-01-01",
    end=f"{annee}-12-01",
    freq="MS"
)

resultats = []

for m in mois:
    debut_mois = m
    fin_mois = m + pd.offsets.MonthEnd(1)

    actifs = referents_AEO[
        (referents_AEO["date_debut_nomination"] <= fin_mois) &
        (referents_AEO["date_fin_nomination"] >= debut_mois)
    ]

    comptage = (
        actifs
        .groupby("structure")
        .size()
        .reset_index(name="nb")
    )

    comptage["mois"] = m.strftime("%Y-%m")
    resultats.append(comptage)

# Concaténation
referents_AEO_mois = pd.concat(resultats)

# Tableau croisé
referents_AEO_mois = referents_AEO_mois.pivot(
    index="structure_id",
    columns="mois",
    values="nb"
).fillna(0).astype(int)

print(pivot)

KeyError: 'date_debut_nomination'

# 4. RTOCR & RLOCR

In [ ]:
# On compte le nb de RTAEO & RLAeo
referents_OCR = (referents_OCR.groupby('structure_id')['libelle_nomination'].nunique())

KeyError: 'Column not found: nom'

In [ ]:
# DF par mois
annee = 2025

# Mois de l'année
mois = pd.date_range(
    start=f"{annee}-01-01",
    end=f"{annee}-12-01",
    freq="MS"
)

resultats = []

for m in mois:
    debut_mois = m
    fin_mois = m + pd.offsets.MonthEnd(1)

    actifs = referents_OCR[
        (referents_OCR["date_debut_nomination"] <= fin_mois) &
        (referents_OCR["date_fin_nomination"] >= debut_mois)
    ]

    comptage = (
        actifs
        .groupby("structure")
        .size()
        .reset_index(name="nb")
    )

    comptage["mois"] = m.strftime("%Y-%m")
    resultats.append(comptage)

# Concaténation
referents_OCR_mois = pd.concat(resultats)

# Tableau croisé
referents_OCR_mois = referents_OCR_mois.pivot(
    index="structure_id",
    columns="mois",
    values="nb"
).fillna(0).astype(int)

print(pivot)

# Nombre d'agréments territoriaux (Dispos d'urgence)

# Nombre de personnes prises en charge (Dispos d'urgence)

#Enregistrement des données

In [ ]:
# Entregistrement du DataFrame
# save_dataframe_to_sheet("1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw", client, df_structure)
# save_dataframe_to_sheet("1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU", client, df_rattachement_court)

In [ ]:
# ... tu lances ton notebook ...
print("Temps total (min):", (time.time() - start)/60)

#CHARGEMENT DES DONNEES MANUELLES

## Chargement des données manuelles OCR

In [ ]:
df_OCR = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ccRoyPycFDwvQvacvmHjfE87LtnlzUgtoRbITkC0pVQ/').worksheet('Feuille 1'))

## Chargement des données manuelles PST

In [ ]:
df_PST = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1yifNna4Hsn5RihkRg50g9h1yKjuRjfolrjsWonEHnrQ').worksheet('Données'))

## Chargement des données manuelles Déclenchements

In [ ]:
df_declenchement = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1y9jehT5fStcEWCF0pxAP7BdiI62VY3JM_hQzFftbcZA').worksheet('Feuille 1'))

## Chargement des données manuelles RedCall

In [ ]:
df_redcall = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1EQzq0K8RY2Liyq-jtggX0bTlnOk9cwUTmf4t6c5_CiI').worksheet('structure-stats_2025-01-01_2025-12-31_min-1 (1)'))

## Chargement des données manuelles CAI CHU CMCC

In [16]:
df_CAICHUCMCC = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/12nZY2leRCMn71NGAEUUtA0Pes598gOfeufDStxSCcnY').worksheet('Toutes données'))

## Chargement des données manuelles Conventions

In [ ]:
df_conventions = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1OYSSkUhWwVpWne9EygH1EEz8EJnFjSeAOEpQQe9utiM').worksheet('Feuille 1'))

#PREPARATION BDD DONNEES MANUELLES

## Préparation BDD OCR

In [ ]:
cols = [
    "Année",
    "Statut",
    "Nom du Département",
    "Structure CRf\n(Ville)",
    "Nom Commune de l'établissement"
]

df_OCR[cols] = df_OCR[cols].astype(str)

In [ ]:
df_OCR[["N° Département", "Nom du Département"]] = (
    df_OCR["Nom du Département"]
    .str.strip().str.split("-", n=1, expand=True)
)
# Nettoyage des espaces
df_OCR["N° Département"] = df_OCR["N° Département"].str.strip()
df_OCR["Nom du Département"] = df_OCR["Nom du Département"].str.strip()

## Préparation BDD PST

In [ ]:
df_PST = df_PST.rename(
    columns={"PST constitué ": "PST constitué"}
)

In [ ]:
# Numéro de département
df_PST["N° Département"] = df_PST["Territoire"].str.extract(r"DT\s+(\d+)")

# Nouvelle colonne 'DT Ain'
df_PST["Nom structure DT"] = (
    "DT " + df_PST["Territoire"].str.extract(r"-\s*(.+)")
)

In [ ]:
cols = [
    "Territoire",
    "PST constitué",
    "N° Département",
    "Nom structure DT"
]

df_PST[cols] = df_PST[cols].astype(str)

## Préparation BDD Déclenchements

In [ ]:
#Suppression de la première ligne
df_declenchement2 = df_declenchement.drop(df_declenchement.index[0])
df_declenchement2.rename(columns={'COUNTA of Catégorie': 'Département', 'Catégorie': 'Etablissements', 'Unnamed: 2': 'Exercice', 'Unnamed: 3': 'Fonctionnement', 'Unnamed: 4': 'Opérations', 'Unnamed: 5': 'Grand Total'}, inplace=True)

In [ ]:
df_declenchement2[['Grand Total', 'Exercice']] = df_declenchement2[['Grand Total', 'Exercice']].fillna(0)

#Calcul du nb de déclenchements
df_declenchement2["nb_declenchements"] = (
    df_declenchement2["Grand Total"] - df_declenchement2["Exercice"]
)

/tmp/ipython-input-1235430848.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_declenchement2[['Grand Total', 'Exercice']] = df_declenchement2[['Grand Total', 'Exercice']].fillna(0)

In [ ]:
#Création de 2 colonnes pour le mapping structure
df_declenchement2[["N_dept", "DT"]] = (
    df_declenchement2["Département"]
    .str.split(" - ", expand=True)
)

df_declenchement2["DT"] = "DT " + df_declenchement2["DT"]

## Préparation BDD RedCall

In [ ]:
df = df_redcall.drop(columns=["Type", "Coûts", "Devise"])

In [ ]:
cols_to_sum = ["Déclenchements", "Communications", "Messages", "Questions", "Réponses", "Erreurs"]

df_RC_grouped = (
    df
    .groupby("ID de la structure", as_index=False)[cols_to_sum]
    .sum()
)

In [ ]:
df_RC_grouped

,ID de la structure,Déclenchements,Communications,Messages,Questions,Réponses,Erreurs
0,1.0,58.0,98.0,278.0,1820.0,627.0,55.0
1,2.0,73.0,80.0,12.0,141.0,18.0,0.0
2,3.0,32.0,32.0,53.0,268.0,99.0,0.0
3,4.0,2.0,2.0,1.0,1.0,0.0,0.0
4,5.0,2.0,2.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...
756,1359.0,4.0,7.0,18.0,23.0,10.0,0.0
757,1361.0,2.0,2.0,0.0,12.0,2.0,4.0
758,1363.0,2.0,2.0,62.0,0.0,0.0,3.0
759,1364.0,2.0,2.0,120.0,0.0,0.0,1.0
760,1367.0,3.0,3.0,0.0,18.0,3.0,3.0

In [ ]:
df_RC_grouped["Total"] = df_RC_grouped[["Communications", "Messages", "Questions"]].sum(axis=1)

In [ ]:
df_RC_grouped

,ID de la structure,Déclenchements,Communications,Messages,Questions,Réponses,Erreurs,Total
0,1.0,58.0,98.0,278.0,1820.0,627.0,55.0,2196.0
1,2.0,73.0,80.0,12.0,141.0,18.0,0.0,233.0
2,3.0,32.0,32.0,53.0,268.0,99.0,0.0,353.0
3,4.0,2.0,2.0,1.0,1.0,0.0,0.0,4.0
4,5.0,2.0,2.0,1.0,1.0,0.0,1.0,4.0
...,...,...,...,...,...,...,...,...
756,1359.0,4.0,7.0,18.0,23.0,10.0,0.0,48.0
757,1361.0,2.0,2.0,0.0,12.0,2.0,4.0,14.0
758,1363.0,2.0,2.0,62.0,0.0,0.0,3.0,64.0
759,1364.0,2.0,2.0,120.0,0.0,0.0,1.0,122.0
760,1367.0,3.0,3.0,0.0,18.0,3.0,3.0,21.0

In [ ]:
df_RC_grouped["Utilisation_Redcall"] = (
    df_RC_grouped["Total"]
    .gt(0)
    .map({True: "Oui", False: "Non"})
)

In [ ]:
df_RC_grouped.columns

Index(['ID de la structure', 'Déclenchements', 'Communications', 'Messages',
       'Questions', 'Réponses', 'Erreurs', 'Total', 'Utilisation_Redcall'],
      dtype='object')

## Préparation BDD CAI CHU CMCC

In [25]:
df_CAICHUCMCC2

1,Dépt,Région,Département,CAI 2023,CHU 2023,Lots CMCC 2023
0,01,Auvergne Rhône Alpes,DELEGATION TERRITORIALE DE L'AIN (01),2,2,1
1,02,HDF,DELEGATION TERRITORIALE DE L'AISNE (02),3,1,1
2,03,Auvergne Rhône Alpes,DELEGATION TERRITORIALE DE L'ALLIER (03),1,1,1
3,04,PACA Corse,DELEGATION TERRITORIALE DES ALPES-DE-HAUTE-PRO...,1,1,4
4,05,PACA Corse,DELEGATION TERRITORIALE DES HAUTES-ALPES (05),3,3,3
...,...,...,...,...,...,...
115,NORM,Normandie,"=""Région ""&B120",=FL17+FL29+FL52+FL63+FL78,=FM17+FM29+FM52+FM63+FM78,=FQ17+FQ29+FQ52+FQ63+FQ78
116,OCC,Occitanie,"=""Région ""&B121",=FL12+FL14+FL15+FL32+FL33+FL34+FL36+FL48+FL50+...,=FM12+FM14+FM15+FM32+FM33+FM34+FM36+FM48+FM50+...,=FQ12+FQ14+FQ15+FQ32+FQ33+FQ34+FQ36+FQ48+FQ50+...
117,PACAC,Provence Alpes Côte d'Azur - Corse,"=""Région ""&B122",=FL7+FL8+FL9+FL16+FL85+FL86+FL108+FL109,=FM7+FM8+FM9+FM16+FM85+FM86+FM108+FM109,=FQ7+FQ8+FQ9+FQ16+FQ85+FQ86+FQ108+FQ109
118,PDLL,Pays de la Loire,"=""Région ""&B123",=FL46+FL51+FL55+FL74+FL87,=FM46+FM51+FM55+FM74+FM87,=FQ46+FQ51+FQ55+FQ74+FQ87
119,OM,Outre Mer,"=""Région ""&B124",=FL98+FL99+FL100+FL101+FL102+FL103+FL104+FL105...,=FM98+FM99+FM100+FM101+FM102+FM103+FM104+FM105...,=FQ98+FQ99+FQ100+FQ101+FQ102+FQ103+FQ104+FQ105...

In [19]:
# repérer la première ligne non entièrement vide
first_valid_row = df_CAICHUCMCC.dropna(how="all").index[0]

# utiliser cette ligne comme header
df_CAICHUCMCC.columns = df_CAICHUCMCC.loc[first_valid_row]
df_CAICHUCMCC = df_CAICHUCMCC.loc[first_valid_row + 1:].reset_index(drop=True)

In [24]:
df_CAICHUCMCC2 = df_CAICHUCMCC[['Dépt', 'Région', 'Département', 'CAI 2023', 'CHU 2023', 'Lots CMCC 2023']]

## Préparation BDD Conventions

#CALCUL INDICATEURS DONNEES MANUELLES

## Calcul indicateur OCR (données manuelles)

In [ ]:
### TRAITEMENT DES DONNEES ###

df_OCR_Nb_deployees = df_OCR.copy()


# Filtre sur l'année et sur le statut
df_OCR_Nb_deployees = df_OCR_Nb_deployees[df_OCR_Nb_deployees["Statut"].isin(["En cours"])]
df_OCR_Nb_deployees = df_OCR_Nb_deployees[df_OCR_Nb_deployees["Année"] == "2025-2026"]

avant = [x for x in df_OCR_Nb_deployees['Structure CRf\n(Ville)'].drop_duplicates().values]

print(len(avant))

# Conservation des cols utiles
df_OCR_Nb_deployees = df_OCR_Nb_deployees[["Année","Statut","Nom du Département","N° Département", "Structure CRf\n(Ville)"]]

# Rapprochement avec l'annuaire structure quand possible
df_OCR_Nb_deployees = rapprochement_libelles(df_ref_structure, df_OCR_Nb_deployees, "Structure CRf\n(Ville)")


# display(df_OCR_Nb_deployees[(df_OCR_Nb_deployees['N_structure']=="") & (df_OCR_Nb_deployees['Structure CRf\n(Ville)']!="N/A") & (df_OCR_Nb_deployees['Structure CRf\n(Ville)']!="")])

# Utilisation du département quand impossible
# Pour toutes les lignes dans df_OCR_Nb_deployees où la structure ('N_structure') est vide (''),
# on essaie de compléter automatiquement cette information en utilisant un dictionnaire de correspondance
# entre numéro de département ('N° Département') et numéro de délégation territoriale ('N_structure') tiré de df_ref_structure.

mask = df_OCR_Nb_deployees['n_structure'] == ''
mapping_dict = df_ref_structure[df_ref_structure["type_structure"] == "DELEGATION TERRITORIALE - DT"].set_index('N_dept')['n_structure'].to_dict()

df_OCR_Nb_deployees.loc[mask, 'n_structure'] = df_OCR_Nb_deployees.loc[mask, 'N° Département'].map(mapping_dict)

# print("Pb : ", df_OCR_Nb_deployees["n_structure"].drop_duplicates().shape[0])

apres = [x for x in df_OCR_Nb_deployees['Structure CRf\n(Ville)'].drop_duplicates().values]

print(len(apres))
apres_n = [x for x in df_OCR_Nb_deployees['n_structure'].drop_duplicates().values]
print(len(apres_n))

display(df_OCR_Nb_deployees['n_structure'].duplicated)
display(df_OCR_Nb_deployees.sort_values(by='n_structure'))


# Effectuer un count sur 'structure_benevolat_id'
df_OCR_Nb_deployees = df_OCR_Nb_deployees['n_structure'].value_counts().reset_index()

df_OCR_Nb_deployees = df_OCR_Nb_deployees.rename(columns={'count': 'OCR Nb_deployees'})

### NETTOYAGE DES DONNEES ###

# Première vérification
verifier_colonne_structure(df_OCR_Nb_deployees, "n_structure", df_ref_structure)

df_OCR_Nb_deployees

30
30
27

<bound method Series.duplicated of 7      1013.0
8      1013.0
9      1013.0
10      400.0
11      400.0
60     2189.0
63      448.0
69       69.0
74     4700.0
98      600.0
99      600.0
102    4006.0
104    4006.0
107      34.0
109      61.0
129     500.0
131     384.0
132      33.0
134      33.0
135      33.0
140     230.0
174      48.0
175      74.0
178     883.0
179     883.0
180     886.0
181     886.0
182     886.0
183     886.0
184     886.0
185     886.0
186     886.0
187     886.0
188      74.0
189      74.0
234    4394.0
235      26.0
236     308.0
248     646.0
249    3966.0
250    3966.0
251    3966.0
252    3966.0
253    3966.0
254    3966.0
255    3966.0
256    3966.0
257    3966.0
258    3966.0
259    3966.0
260    3966.0
278    3667.0
347    4511.0
348     976.0
350     976.0
351     967.0
Name: n_structure, dtype: object>

,Année,Statut,Nom du Département,N° Département,Structure CRf\n(Ville),n_structure,nom_structure
235,2025-2026,En cours,Côte-d'Or,21,nan,26.0,
135,2025-2026,En cours,Eure-et-Loir,28,DT 28,33.0,
134,2025-2026,En cours,Eure-et-Loir,28,DT 28,33.0,
132,2025-2026,En cours,Eure-et-Loir,28,DT 28,33.0,
107,2025-2026,En cours,Finistère,29,DT29,34.0,
174,2025-2026,En cours,Haute-Loire,43,DT 43 ou AT Haut-Allier,48.0,
109,2025-2026,En cours,Morbihan,56,UL de Vannes,61.0,
69,2025-2026,En cours,Pyrénées-Atlantique,64,UL d'Orthez,69.0,
188,2025-2026,En cours,Rhône,69,UL Villefranche sur Saône,74.0,
175,2025-2026,En cours,Rhône,69,DT 69,74.0,
189,2025-2026,En cours,Rhône,69,UL Villefranche sur Saône,74.0,
140,2025-2026,En cours,Bouches-du-Rhône,13,UL Aix en Provence,230.0,UL D'AIX EN PROVENCE
236,2025-2026,En cours,Côte-d'Or,21,UL Montbard-Semur,308.0,UL DE MONTBARD SEMUR
131,2025-2026,En cours,Eure-et-Loir,28,UL de Chartres,384.0,UL DE CHARTRES
11,2025-2026,En cours,Gard,30,UL Terre d'Argence,400.0,UL DE TERRE D'ARGENCE
10,2025-2026,En cours,Gard,30,UL Terre d'Argence,400.0,UL DE TERRE D'ARGENCE
63,2025-2026,En cours,Gironde,33,UL Bordeaux,448.0,UL DE BORDEAUX
129,2025-2026,En cours,Indre-et-Loire,37,UL de Tours,500.0,UL DE TOURS PLUS
99,2025-2026,En cours,Maine-et-Loire,49,UL Angers,600.0,UL D'ANGERS
98,2025-2026,En cours,Maine-et-Loire,49,UL Angers,600.0,UL D'ANGERS
248,2025-2026,En cours,Meurthe-et-Moselle,54,UL de Nancy,646.0,UL DE NANCY
179,2025-2026,En cours,Haute-Savoie,74,UL Annecy,883.0,UL D'ANNECY
178,2025-2026,En cours,Haute-Savoie,74,UL Annecy,883.0,UL D'ANNECY
183,2025-2026,En cours,Haute-Savoie,74,UL La Roche-Reignier,886.0,UL DE LA ROCHE SUR FORON-REIGNIER
186,2025-2026,En cours,Haute-Savoie,74,UL La Roche-Reignier,886.0,UL DE LA ROCHE SUR FORON-REIGNIER
181,2025-2026,En cours,Haute-Savoie,74,UL La Roche-Reignier,886.0,UL DE LA ROCHE SUR FORON-REIGNIER
182,2025-2026,En cours,Haute-Savoie,74,UL La Roche-Reignier,886.0,UL DE LA ROCHE SUR FORON-REIGNIER
184,2025-2026,En cours,Haute-Savoie,74,UL La Roche-Reignier,886.0,UL DE LA ROCHE SUR FORON-REIGNIER
187,2025-2026,En cours,Haute-Savoie,74,UL La Roche - Reignier,886.0,UL DE LA ROCHE SUR FORON-REIGNIER
180,2025-2026,En cours,Haute-Savoie,74,UL La Roche-Reignier,886.0,UL DE LA ROCHE SUR FORON-REIGNIER
185,2025-2026,En cours,Haute-Savoie,74,UL La Roche-Reignier,886.0,UL DE LA ROCHE SUR FORON-REIGNIER
351,2025-2026,En cours,Yvelines,78,UL Les Mureaux,967.0,UL DES MUREAUX
348,2025-2026,En cours,Yvelines,78,UL de Saint Germain en Laye,976.0,UL DE SAINT GERMAIN EN LAYE
350,2025-2026,En cours,Yvelines,78,UL de St-Germain-en-Laye,976.0,UL DE SAINT GERMAIN EN LAYE
7,2025-2026,En cours,Tarn,81,UL de Lavaur,1013.0,UL DE LAVAUR
9,2025-2026,En cours,Tarn,81,UL de Lavaur,1013.0,UL DE LAVAUR
8,2025-2026,En cours,Tarn,81,UL de Lavaur,1013.0,UL DE LAVAUR
60,2025-2026,En cours,Gironde,33,UL Terres de Montesquieu,2189.0,UL TERRES DE MONTESQUIEU
278,2025-2026,En cours,Saint-Barthélémy,977,DT de St Barthélémy,3667.0,DT DE ST BARTHELEMY
260,2025-2026,En cours,Vosges,88,nan,3966.0,
259,2025-2026,En cours,Vosges,88,nan,3966.0,
258,2025-2026,En cours,Vosges,88,nan,3966.0,
257,2025-2026,En cours,Vosges,88,nan,3966.0,
256,2025-2026,En cours,Vosges,88,nan,3966.0,
255,2025-2026,En cours,Vosges,88,nan,3966.0,
253,2025-2026,En cours,Vosges,88,nan,3966.0,
252,2025-2026,En cours,Vosges,88,nan,3966.0,
251,2025-2026,En cours,Vosges,88,nan,3966.0,
250,2025-2026,En cours,Vosges,88,nan,3966.0,
249,2025-2026,En cours,Vosges,88,DT 88,3966.0,
254,2025-2026,En cours,Vosges,88,nan,3966.0,
102,2025-2026,En cours,Côtes d'Armor,22,Antenne de Saint-Brieuc,4006.0,AL DE SAINT BRIEUC
104,2025-2026,En cours,Côtes d'Armor,22,Antenne de Saint-Brieuc,4006.0,AL DE SAINT BRIEUC
234,2025-2026,En cours,Haute-Saône,70,DT 70,4394.0,
347,2025-2026,En cours,Seine et Marne,77,UL Moret Loing et Orvanne,4511.0,UL DE MORET LOING ET ORVANNE
74,2025-2026,En cours,Lot-et-Garonne,47,UL Albret,4700.0,UL DE L'ALBRET

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

    n_structure  OCR Nb_deployees
0        3966.0                12
1         886.0                 8
2        1013.0                 3
3          33.0                 3
4          74.0                 3
5         883.0                 2
6         976.0                 2
7        4006.0                 2
8         600.0                 2
9         400.0                 2
10       2189.0                 1
11        500.0                 1
12         61.0                 1
13         34.0                 1
14       4700.0                 1
15        448.0                 1
16         69.0                 1
17         48.0                 1
18        230.0                 1
19       4394.0                 1
20        384.0                 1
21        308.0                 1
22         26.0                 1
23        646.0                 1
24       3667.0                 1
25       4511.0                 1
26        967.0                 1

## Calcul indicateur PST (données manuelles)

In [ ]:
### TRAITEMENT DES DONNEES ###

df_Dispositifs_d_urgence_PST = df_PST.copy()

# Colonnes utiles
df_Dispositifs_d_urgence_PST = df_Dispositifs_d_urgence_PST[
    ["Territoire", "PST constitué", "Nom structure DT", "N° Département"]
]

df_Dispositifs_d_urgence_PST = rapprochement_libelles(
    df_ref_structure,
    df_Dispositifs_d_urgence_PST,
    "Nom structure DT"
)

# Utilisation du département quand impossible
# Pour toutes les lignes dans df_OCR_Nb_deployees où la structure ('N_structure') est vide (''),
# on essaie de compléter automatiquement cette information en utilisant un dictionnaire de correspondance
# entre numéro de département ('N° Département') et numéro de délégation territoriale ('N_structure') tiré de df_ref_structure.
mask = (
    df_Dispositifs_d_urgence_PST["n_structure"].isna()
    | (df_Dispositifs_d_urgence_PST["n_structure"] == "")
)

df_Dispositifs_d_urgence_PST["N° Département"] = (
    df_Dispositifs_d_urgence_PST["N° Département"].astype(str)
)
df_ref_structure["N_dept"] = df_ref_structure["N_dept"].astype(str)

mapping_dict = (
    df_ref_structure[
        df_ref_structure["type_structure"] == "DELEGATION TERRITORIALE - DT"
    ]
    .set_index("N_dept")["n_structure"]
    .to_dict()
)

df_Dispositifs_d_urgence_PST.loc[mask, "n_structure"] = (
    df_Dispositifs_d_urgence_PST.loc[mask, "N° Département"].map(mapping_dict)
)

# Nettoyage des valeurs PST
df_Dispositifs_d_urgence_PST["PST constitué"] = (
    df_Dispositifs_d_urgence_PST["PST constitué"]
    .astype(str)
    .str.strip()
    .str.lower()
)


def statut_pst(valeur):
    if valeur == "oui":
        return "oui"
    elif valeur == "en cours":
        return "en cours"
    else:
        return "non"

df_Dispositifs_d_urgence_PST["Dispositifs_d_urgence PST"] = (
    df_Dispositifs_d_urgence_PST["PST constitué"].apply(statut_pst)
)

df_Dispositifs_d_urgence_PST.loc[
    df_Dispositifs_d_urgence_PST['Territoire'] == 'DT  42 - Loire',
    ['n_structure', 'nom_structure']
] = [47, 'DT DE LA LOIRE']

### NETTOYAGE DES DONNES ###

# Première vérification
verifier_colonne_structure(df_Dispositifs_d_urgence_PST, "n_structure", df_ref_structure)

df_Dispositifs_d_urgence_PST

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

,Territoire,PST constitué,Nom structure DT,N° Département,n_structure,nom_structure,Dispositifs_d_urgence PST
0,DT 01 - Ain,oui,DT Ain,01,5.0,DT DE L'AIN,oui
1,DT 02 - Aisne,oui,DT Aisne,02,6.0,DT DE L'AISNE,oui
2,DT 03 - Allier,oui,DT Allier,03,7.0,DT DE L'ALLIER,oui
3,DT 04 - Alpes de Haute Provence,oui,DT Alpes de Haute Provence,04,3997.0,DT DES ALPES DE HAUTE PROVENCE,oui
4,DT 05 - Hautes Alpes,en cours,DT Hautes Alpes,05,9.0,DT DES HAUTES ALPES,en cours
...,...,...,...,...,...,...,...
101,DT 976 - Mayotte,non,DT Mayotte,976,1286.0,DT DE MAYOTTE,non
102,DT 977 - Saint-Barthélémy,oui,DT Saint-Barthélémy,977,3667.0,DT DE ST BARTHELEMY,oui
103,DT 978 - Saint-Martin,non,DT Saint-Martin,978,3668.0,DT DE ST MARTIN,non
104,DT 987 - Polynésie française,non,DT Polynésie française,987,1285.0,,non
105,DT 988 - Nouvelle Calédonie,non,DT Nouvelle Calédonie,988,104.0,DT DE NOUVELLE CALEDONIE,non

## Calcul indicateur Déclenchements (données manuelles)

In [ ]:
df_declenchement2['DT'] = df_declenchement2['DT'].astype(str)
df_declenchement2['N_dept'] = df_declenchement2['N_dept'].astype(str)


# Rapprochement avec l'annuaire structure quand possible
df_declenchement3 = rapprochement_libelles(df_ref_structure, df_declenchement2, "DT")

# Utilisation du département quand impossible
# Pour toutes les lignes dans df_declenchement2 où la structure ('N_structure') est vide (''),
# on essaie de compléter automatiquement cette information en utilisant un dictionnaire de correspondance
# entre numéro de département ('N° Département') et numéro de délégation territoriale ('N_structure') tiré de df_ref_structure.
mask = df_declenchement3['n_structure'] == ''
mapping_dict = df_ref_structure[df_ref_structure["type_structure"] == "DELEGATION TERRITORIALE - DT"].set_index('N_dept')['n_structure'].to_dict()
df_declenchement3.loc[mask, 'n_structure'] = df_declenchement3.loc[mask, 'N_dept'].map(mapping_dict)

df_declenchement3 = df_declenchement3.dropna(subset=['n_structure'])
df_declenchement3.loc[
    df_declenchement3['Département'] == '42 - Loire',
    ['n_structure', 'nom_structure']
] = [47, 'DT DE LA LOIRE']
df_declenchement3 = df_declenchement3.rename(columns={'nb_declenchements': 'Dispositifs_d_urgence Nb_declenchements'})

### NETTOYAGE DES DONNEES ###

# Première vérification
verifier_colonne_structure(df_declenchement3, "n_structure", df_ref_structure)

df_declenchement3

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

,Département,Etablissements,Exercice,Fonctionnement,Opérations,Grand Total,Dispositifs_d_urgence Nb_declenchements,N_dept,DT,n_structure,nom_structure
1,01 - Ain,NaN,0,1,3,4,4,01,DT Ain,5.0,DT DE L'AIN
2,02 - Aisne,NaN,0,1,NaN,1,1,02,DT Aisne,6.0,DT DE L'AISNE
3,03 - Allier,NaN,1,2,1,4,3,03,DT Allier,7.0,DT DE L'ALLIER
4,04 - Alpes de Hte Provence,NaN,1,1,NaN,2,1,04,DT Alpes de Hte Provence,3997.0,DT DES ALPES DE HAUTE PROVENCE
5,05 - Hautes-Alpes,NaN,0,2,NaN,2,2,05,DT Hautes-Alpes,9.0,DT DES HAUTES ALPES
...,...,...,...,...,...,...,...,...,...,...,...
92,974 - Réunion,NaN,0,2,NaN,2,2,974,DT Réunion,3959.0,DT DE LA REUNION
93,976 - Mayotte,NaN,2,2,NaN,4,2,976,DT Mayotte,1286.0,DT DE MAYOTTE
94,986 - Wallis,NaN,0,1,NaN,1,1,986,DT Wallis,4303.0,DT DE WALLIS
95,987 - Polynésie française,NaN,0,NaN,1,1,1,987,DT Polynésie française,1285.0,
96,988 - Nouvelle Calédonie,NaN,1,NaN,1,2,1,988,DT Nouvelle Calédonie,104.0,DT DE NOUVELLE CALEDONIE

## Calcul indicateur RedCall (données manuelles)

In [ ]:
# on garde seulement les colonnes utiles
df_redcall2 = df_RC_grouped[["ID de la structure", "Utilisation_Redcall"]]
#df_redcall2["ID de la structure"] = df_redcall2["ID de la structure"].astype(str)
df_redcall2["Utilisation_Redcall"] = df_redcall2["Utilisation_Redcall"].astype(str)

# Rapprochement avec l'annuaire structure quand possible
#df_redcall2 = rapprochement_libelles(df_ref_structure, df_redcall2, "ID de la structure")
df_redcall2.rename(columns={'ID de la structure': 'n_structure'}, inplace=True)
df_redcall2['n_structure'] = df_redcall2['n_structure'].astype(int)
df_redcall2['n_structure'] = pd.to_numeric(df_redcall2['n_structure'], errors='coerce')


# Création d'un dictionnaire de correspondance
dict_structure = df_ref_structure.set_index('n_structure')['nom_structure'].to_dict()

# Création de la nouvelle colonne dans df_redcall2
df_redcall2['nom_structure'] = df_redcall2['n_structure'].map(dict_structure)


# Effectuer un count sur 'structure_benevolat_id'
#df_redcall2 = df_redcall2['n_structure'].value_counts().reset_index()
df_redcall2 = df_redcall2.rename(columns={'Utilisation_Redcall': 'Dispositifs_d_urgence Utilisation_RedCall'})

### NETTOYAGE DES DONNEES ###

# Première vérification
verifier_colonne_structure(df_redcall2, "n_structure", df_ref_structure)

df_redcall2

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 419 code(s) non trouvés dans le référentiel : [np.int64(2), np.int64(3), np.int64(4), np.int64(8), np.int64(16), np.int64(22), np.int64(24), np.int64(27), np.int64(28), np.int64(29), np.int64(51), np.int64(60), np.int64(65), np.int64(66), np.int64(70), np.int64(75), np.int64(78), np.int64(84), np.int64(88), np.int64(93), np.int64(101), np.int64(105), np.int64(107), np.int64(108), np.int64(110), np.int64(111), np.int64(112), np.int64(113), np.int64(114), np.int64(115), np.int64(116), np.int64(117), np.int64(118), np.int64(119), np.int64(121), np.int64(122), np.int64(123), np.int64(124), np.int64(125), np.int64(126), np.int64(127), np.int64(129), np.int64(130), np.int64(131), np.int64(133), np.int64(138), np.int64(139), np.int64(140), np.int64(141), np.int64(142), np.int64(145), np.int64(146), np.int64(149), np.int64(150), np.int64(156), np.int64(157), np.int64(158), np.int64(159), np.int64(160), np.int64(161), np.int64(165), np.int64(167), np.int64(168), np.int64(169), np.int64(174), np.int64(178), np.int64(179), np.int64(181), np.int64(182), np.int64(184), np.int64(185), np.int64(186), np.int64(188), np.int64(189), np.int64(190), np.int64(191), np.int64(192), np.int64(194), np.int64(196), np.int64(199), np.int64(211), np.int64(214), np.int64(221), np.int64(223), np.int64(224), np.int64(226), np.int64(227), np.int64(268), np.int64(269), np.int64(285), np.int64(311), np.int64(312), np.int64(313), np.int64(314), np.int64(316), np.int64(317), np.int64(318), np.int64(319), np.int64(320), np.int64(321), np.int64(322), np.int64(323), np.int64(324), np.int64(326), np.int64(327), np.int64(328), np.int64(330), np.int64(334), np.int64(335), np.int64(336), np.int64(337), np.int64(338), np.int64(339), np.int64(340), np.int64(341), np.int64(347), np.int64(350), np.int64(352), np.int64(353), np.int64(355), np.int64(356), np.int64(362), np.int64(363), np.int64(364), np.int64(366), np.int64(367), np.int64(368), np.int64(369), np.int64(370), np.int64(372), np.int64(374), np.int64(375), np.int64(376), np.int64(378), np.int64(380), np.int64(382), np.int64(383), np.int64(394), np.int64(401), np.int64(402), np.int64(403), np.int64(405), np.int64(407), np.int64(414), np.int64(416), np.int64(417), np.int64(421), np.int64(423), np.int64(424), np.int64(434), np.int64(439), np.int64(441), np.int64(442), np.int64(443), np.int64(446), np.int64(447), np.int64(453), np.int64(460), np.int64(462), np.int64(463), np.int64(469), np.int64(472), np.int64(475), np.int64(477), np.int64(490), np.int64(494), np.int64(497), np.int64(499), np.int64(501), np.int64(504), np.int64(505), np.int64(533), np.int64(534), np.int64(537), np.int64(547), np.int64(559), np.int64(562), np.int64(567), np.int64(579), np.int64(594), np.int64(595), np.int64(601), np.int64(604), np.int64(620), np.int64(637), np.int64(654), np.int64(655), np.int64(657), np.int64(661), np.int64(663), np.int64(664), np.int64(672), np.int64(674), np.int64(682), np.int64(688), np.int64(692), np.int64(693), np.int64(696), np.int64(702), np.int64(704), np.int64(705), np.int64(706), np.int64(711), np.int64(716), np.int64(722), np.int64(723), np.int64(724), np.int64(726), np.int64(729), np.int64(732), np.int64(733), np.int64(734), np.int64(735), np.int64(737), np.int64(745), np.int64(751), np.int64(757), np.int64(768), np.int64(771), np.int64(796), np.int64(803), np.int64(808), np.int64(816), np.int64(834), np.int64(839), np.int64(843), np.int64(849), np.int64(850), np.int64(851), np.int64(864), np.int64(866), np.int64(871), np.int64(872), np.int64(874), np.int64(875), np.int64(876), np.int64(877), np.int64(878), np.int64(879), np.int64(880), np.int64(881), np.int64(882), np.int64(890), np.int64(891), np.int64(909), np.int64(910), np.int64(911), np.int64(912), np.int64(913), np.int64(915), np.int64(916), np.int64(917), np.int64(918), np.int64(919), np.int64(920), np.int64(921), np.int64(924), np.int64(925), np.int64(927), np.int64(929), np.int64(936), np.int64(938), np.int64(939), np.int64(940), np.int64(942), np.int64(948), np.int64(949), np.int64(951), np.int64(953), np.int64(954), np.int64(956), np.int64(957), np.int64(958), np.int64(959), np.int64(962), np.int64(964), np.int64(965), np.int64(968), np.int64(973), np.int64(981), np.int64(983), np.int64(984), np.int64(985), np.int64(986), np.int64(987), np.int64(988), np.int64(989), np.int64(994), np.int64(997), np.int64(1004), np.int64(1005), np.int64(1007), np.int64(1011), np.int64(1012), np.int64(1014), np.int64(1015), np.int64(1016), np.int64(1027), np.int64(1028), np.int64(1029), np.int64(1030), np.int64(1031), np.int64(1032), np.int64(1033), np.int64(1034), np.int64(1035), np.int64(1036), np.int64(1037), np.int64(1038), np.int64(1058), np.int64(1061), np.int64(1063), np.int64(1064), np.int64(1065), np.int64(1066), np.int64(1067), np.int64(1069), np.int64(1070), np.int64(1072), np.int64(1073), np.int64(1074), np.int64(1076), np.int64(1078), np.int64(1079), np.int64(1081), np.int64(1083), np.int64(1084), np.int64(1085), np.int64(1086), np.int64(1087), np.int64(1089), np.int64(1090), np.int64(1091), np.int64(1092), np.int64(1093), np.int64(1094), np.int64(1095), np.int64(1096), np.int64(1097), np.int64(1098), np.int64(1099), np.int64(1100), np.int64(1101), np.int64(1102), np.int64(1103), np.int64(1104), np.int64(1105), np.int64(1106), np.int64(1109), np.int64(1110), np.int64(1112), np.int64(1113), np.int64(1114), np.int64(1115), np.int64(1116), np.int64(1117), np.int64(1118), np.int64(1119), np.int64(1120), np.int64(1122), np.int64(1123), np.int64(1124), np.int64(1128), np.int64(1134), np.int64(1137), np.int64(1138), np.int64(1139), np.int64(1141), np.int64(1142), np.int64(1143), np.int64(1144), np.int64(1146), np.int64(1147), np.int64(1150), np.int64(1166), np.int64(1183), np.int64(1184), np.int64(1185), np.int64(1187), np.int64(1188), np.int64(1189), np.int64(1195), np.int64(1199), np.int64(1200), np.int64(1201), np.int64(1202), np.int64(1203), np.int64(1207), np.int64(1208), np.int64(1219), np.int64(1223), np.int64(1234), np.int64(1237), np.int64(1239), np.int64(1240), np.int64(1241), np.int64(1287), np.int64(1309), np.int64(1310), np.int64(1315), np.int64(1317), np.int64(1332), np.int64(1333), np.int64(1334), np.int64(1335), np.int64(1338), np.int64(1340), np.int64(1344), np.int64(1348), np.int64(1350), np.int64(1351), np.int64(1353), np.int64(1357), np.int64(1358), np.int64(1359), np.int64(1361), np.int64(1363), np.int64(1364), np.int64(1367)]

/tmp/ipython-input-2704293952.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_redcall2["Utilisation_Redcall"] = df_redcall2["Utilisation_Redcall"].astype(str)
/tmp/ipython-input-2704293952.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_redcall2.rename(columns={'ID de la structure': 'n_structure'}, inplace=True)
/tmp/ipython-input-2704293952.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_redcall2['n_structure'] = df_redcall2['n_structure'].astype(int)
/tmp/ipython-input-2704293952.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_redcall2['n_structure'] = pd.to_numeric(df_redcall2['n_structure'], errors='coerce')
/tmp/ipython-input-2704293952.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_redcall2['nom_structure'] = df_redcall2['n_structure'].map(dict_structure)

,n_structure,Dispositifs_d_urgence Utilisation_RedCall,nom_structure
0,1,Oui,INSTANCES NATIONALES
1,2,Oui,NaN
2,3,Oui,NaN
3,4,Oui,NaN
4,5,Oui,DT DE L'AIN
...,...,...,...
756,1359,Oui,NaN
757,1361,Oui,NaN
758,1363,Oui,NaN
759,1364,Oui,NaN
760,1367,Oui,NaN

In [ ]:
µ# 1️⃣ On garde seulement les colonnes utiles
df_redcall2 = df_RC_grouped[["ID de la structure", "Utilisation_Redcall"]]

# 2️⃣ On convertit en str
df_redcall2["ID de la structure"] = df_redcall2["ID de la structure"].astype(str)
df_redcall2["Utilisation_Redcall"] = df_redcall2["Utilisation_Redcall"].astype(str)

# 3️⃣ Renommer la colonne pour correspondre au df_ref_structure
df_redcall2.rename(columns={'ID de la structure': 'n_structure'}, inplace=True)

# 4️⃣ Rapprochement avec l'annuaire structure
df_ref_structure.rename(columns={'ID de la structure': 'n_structure'}, inplace=True)

# 5️⃣ Création d'un dictionnaire de correspondance
dict_structure = df_ref_structure.set_index('n_structure')['nom_structure'].to_dict()

# 6️⃣ Création de la nouvelle colonne nom_structure
df_redcall2['nom_structure'] = df_redcall2['n_structure'].map(dict_structure)

# 7️⃣ Renommer la colonne Utilisation_Redcall
df_redcall2 = df_redcall2.rename(columns={'Utilisation_Redcall': 'Dispositifs_d_urgence_Utilisation_RedCall'})

# 8️⃣ Vérification
verifier_colonne_structure(df_redcall2, "n_structure", df_ref_structure)

df_redcall2

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 761 code(s) non trouvés dans le référentiel : ['1.0', '10.0', '1000.0', '1001.0', '1002.0', '1004.0', '1005.0', '1007.0', '1008.0', '101.0', '1010.0', '1011.0', '1012.0', '1013.0', '1014.0', '1015.0', '1016.0', '1017.0', '1018.0', '1019.0', '1020.0', '1021.0', '1022.0', '1023.0', '1024.0', '1025.0', '1026.0', '1027.0', '1028.0', '1029.0', '1030.0', '1031.0', '1032.0', '1033.0', '1034.0', '1035.0', '1036.0', '1037.0', '1038.0', '1039.0', '1040.0', '1041.0', '1042.0', '1044.0', '1049.0', '105.0', '1050.0', '1051.0', '1052.0', '1053.0', '1054.0', '1055.0', '1056.0', '1058.0', '1059.0', '1060.0', '1061.0', '1062.0', '1063.0', '1064.0', '1065.0', '1066.0', '1067.0', '1068.0', '1069.0', '107.0', '1070.0', '1071.0', '1072.0', '1073.0', '1074.0', '1076.0', '1078.0', '1079.0', '108.0', '1080.0', '1081.0', '1083.0', '1084.0', '1085.0', '1086.0', '1087.0', '1089.0', '109.0', '1090.0', '1091.0', '1092.0', '1093.0', '1094.0', '1095.0', '1096.0', '1097.0', '1098.0', '1099.0', '110.0', '1100.0', '1101.0', '1102.0', '1103.0', '1104.0', '1105.0', '1106.0', '1107.0', '1108.0', '1109.0', '111.0', '1110.0', '1111.0', '1112.0', '1113.0', '1114.0', '1115.0', '1116.0', '1117.0', '1118.0', '1119.0', '112.0', '1120.0', '1121.0', '1122.0', '1123.0', '1124.0', '1126.0', '1128.0', '1129.0', '113.0', '1130.0', '1134.0', '1135.0', '1137.0', '1138.0', '1139.0', '114.0', '1141.0', '1142.0', '1143.0', '1144.0', '1145.0', '1146.0', '1147.0', '1148.0', '1149.0', '115.0', '1150.0', '1151.0', '1152.0', '1153.0', '1154.0', '1155.0', '1156.0', '1158.0', '1159.0', '116.0', '1160.0', '1161.0', '1162.0', '1163.0', '1164.0', '1165.0', '1166.0', '1167.0', '1168.0', '117.0', '1173.0', '1174.0', '1176.0', '1177.0', '1178.0', '1179.0', '118.0', '1180.0', '1181.0', '1183.0', '1184.0', '1185.0', '1187.0', '1188.0', '1189.0', '119.0', '1195.0', '1199.0', '12.0', '1200.0', '1201.0', '1202.0', '1203.0', '1207.0', '1208.0', '121.0', '1219.0', '122.0', '1221.0', '1222.0', '1223.0', '1226.0', '123.0', '1234.0', '1235.0', '1236.0', '1237.0', '1239.0', '124.0', '1240.0', '1241.0', '125.0', '126.0', '127.0', '1287.0', '129.0', '130.0', '1309.0', '131.0', '1310.0', '1315.0', '1317.0', '133.0', '1332.0', '1333.0', '1334.0', '1335.0', '1338.0', '1340.0', '1344.0', '1348.0', '1350.0', '1351.0', '1353.0', '1357.0', '1358.0', '1359.0', '1361.0', '1363.0', '1364.0', '1367.0', '138.0', '139.0', '14.0', '140.0', '141.0', '142.0', '143.0', '144.0', '145.0', '146.0', '147.0', '149.0', '15.0', '150.0', '152.0', '153.0', '155.0', '156.0', '157.0', '158.0', '159.0', '16.0', '160.0', '161.0', '162.0', '163.0', '164.0', '165.0', '166.0', '167.0', '168.0', '169.0', '170.0', '171.0', '172.0', '173.0', '174.0', '175.0', '178.0', '179.0', '180.0', '181.0', '182.0', '184.0', '185.0', '186.0', '188.0', '189.0', '19.0', '190.0', '191.0', '192.0', '193.0', '194.0', '195.0', '196.0', '197.0', '198.0', '199.0', '2.0', '20.0', '200.0', '201.0', '202.0', '203.0', '204.0', '205.0', '206.0', '207.0', '208.0', '21.0', '210.0', '211.0', '212.0', '213.0', '214.0', '215.0', '216.0', '217.0', '218.0', '219.0', '22.0', '220.0', '221.0', '223.0', '224.0', '226.0', '227.0', '23.0', '230.0', '231.0', '232.0', '234.0', '235.0', '236.0', '24.0', '26.0', '268.0', '269.0', '27.0', '28.0', '285.0', '29.0', '3.0', '30.0', '305.0', '31.0', '311.0', '312.0', '313.0', '314.0', '316.0', '317.0', '318.0', '319.0', '32.0', '320.0', '321.0', '322.0', '323.0', '324.0', '326.0', '327.0', '328.0', '33.0', '330.0', '334.0', '335.0', '336.0', '337.0', '338.0', '339.0', '340.0', '341.0', '344.0', '345.0', '346.0', '347.0', '349.0', '350.0', '351.0', '352.0', '353.0', '354.0', '355.0', '356.0', '359.0', '362.0', '363.0', '364.0', '365.0', '366.0', '367.0', '368.0', '369.0', '37.0', '370.0', '372.0', '373.0', '374.0', '375.0', '376.0', '377.0', '378.0', '379.0', '380.0', '382.0', '383.0', '384.0', '386.0', '388.0', '389.0', '39.0', '390.0', '391.0', '392.0', '393.0', '394.0', '395.0', '396.0', '397.0', '398.0', '4.0', '40.0', '401.0', '402.0', '403.0', '404.0', '405.0', '407.0', '409.0', '412.0', '413.0', '414.0', '415.0', '416.0', '417.0', '418.0', '419.0', '42.0', '420.0', '421.0', '422.0', '423.0', '424.0', '425.0', '43.0', '434.0', '439.0', '44.0', '440.0', '441.0', '442.0', '443.0', '444.0', '445.0', '446.0', '447.0', '448.0', '449.0', '450.0', '452.0', '453.0', '458.0', '459.0', '46.0', '460.0', '461.0', '462.0', '463.0', '469.0', '47.0', '472.0', '473.0', '474.0', '475.0', '476.0', '477.0', '478.0', '479.0', '480.0', '481.0', '482.0', '49.0', '490.0', '491.0', '494.0', '497.0', '499.0', '5.0', '50.0', '501.0', '502.0', '504.0', '505.0', '506.0', '507.0', '508.0', '509.0', '51.0', '510.0', '511.0', '512.0', '52.0', '522.0', '53.0', '530.0', '531.0', '532.0', '533.0', '534.0', '536.0', '537.0', '54.0', '540.0', '547.0', '55.0', '559.0', '56.0', '561.0', '562.0', '567.0', '57.0', '579.0', '58.0', '59.0', '594.0', '595.0', '6.0', '60.0', '601.0', '603.0', '604.0', '61.0', '611.0', '62.0', '620.0', '621.0', '63.0', '637.0', '64.0', '645.0', '646.0', '65.0', '654.0', '655.0', '657.0', '66.0', '661.0', '662.0', '663.0', '664.0', '67.0', '672.0', '674.0', '676.0', '678.0', '68.0', '682.0', '687.0', '688.0', '69.0', '692.0', '693.0', '696.0', '7.0', '70.0', '700.0', '702.0', '703.0', '704.0', '705.0', '706.0', '707.0', '71.0', '711.0', '716.0', '718.0', '72.0', '720.0', '721.0', '722.0', '723.0', '724.0', '725.0', '726.0', '727.0', '728.0', '729.0', '73.0', '730.0', '731.0', '732.0', '733.0', '734.0', '735.0', '737.0', '74.0', '745.0', '75.0', '751.0', '757.0', '758.0', '76.0', '768.0', '769.0', '77.0', '770.0', '771.0', '775.0', '78.0', '783.0', '785.0', '79.0', '796.0', '8.0', '80.0', '802.0', '803.0', '808.0', '809.0', '81.0', '815.0', '816.0', '817.0', '82.0', '823.0', '829.0', '83.0', '834.0', '835.0', '839.0', '84.0', '843.0', '849.0', '85.0', '850.0', '851.0', '853.0', '854.0', '855.0', '859.0', '86.0', '864.0', '865.0', '866.0', '867.0', '868.0', '869.0', '87.0', '870.0', '871.0', '872.0', '873.0', '874.0', '875.0', '876.0', '877.0', '878.0', '879.0', '88.0', '880.0', '881.0', '882.0', '883.0', '884.0', '886.0', '887.0', '888.0', '889.0', '89.0', '890.0', '891.0', '892.0', '893.0', '894.0', '895.0', '896.0', '897.0', '898.0', '9.0', '90.0', '900.0', '901.0', '902.0', '903.0', '904.0', '905.0', '906.0', '907.0', '908.0', '909.0', '91.0', '910.0', '911.0', '912.0', '913.0', '914.0', '915.0', '916.0', '917.0', '918.0', '919.0', '92.0', '920.0', '921.0', '922.0', '923.0', '924.0', '925.0', '926.0', '927.0', '929.0', '93.0', '934.0', '936.0', '937.0', '938.0', '939.0', '940.0', '941.0', '942.0', '948.0', '949.0', '950.0', '951.0', '952.0', '953.0', '954.0', '956.0', '957.0', '958.0', '959.0', '960.0', '961.0', '962.0', '964.0', '965.0', '966.0', '967.0', '968.0', '969.0', '970.0', '971.0', '972.0', '973.0', '974.0', '975.0', '981.0', '982.0', '983.0', '984.0', '985.0', '986.0', '987.0', '988.0', '989.0', '990.0', '991.0', '992.0', '993.0', '994.0', '995.0', '996.0', '997.0', '998.0', '999.0']

/tmp/ipython-input-3812561684.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_redcall2["ID de la structure"] = df_redcall2["ID de la structure"].astype(str)
/tmp/ipython-input-3812561684.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_redcall2["Utilisation_Redcall"] = df_redcall2["Utilisation_Redcall"].astype(str)
/tmp/ipython-input-3812561684.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_redcall2.rename(columns={'ID de la structure': 'n_structure'}, inplace=True)
/tmp/ipython-input-3812561684.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_redcall2['nom_structure'] = df_redcall2['n_structure'].map(dict_structure)

    n_structure Dispositifs_d_urgence_Utilisation_RedCall nom_structure
0           1.0                                       Oui           NaN
1           2.0                                       Oui           NaN
2           3.0                                       Oui           NaN
3           4.0                                       Oui           NaN
4           5.0                                       Oui           NaN
..          ...                                       ...           ...
756      1359.0                                       Oui           NaN
757      1361.0                                       Oui           NaN
758      1363.0                                       Oui           NaN
759      1364.0                                       Oui           NaN
760      1367.0                                       Oui           NaN

[761 rows x 3 columns]

## Calcul indicateurs CAI CHU CMCC

In [30]:
# Rapprochement avec l'annuaire structure quand possible
df_CAICHUCMCC2 = rapprochement_libelles(df_ref_structure, df_CAICHUCMCC2, "Département")

# 7️⃣ Renommer la colonne Utilisation_Redcall
df_CAICHUCMCC_VF = df_CAICHUCMCC2.rename(columns={ 'CAI 2023': 'Dispositifs_d_urgence Nb_lots_CAI',
                                                   'CHU 2023': 'Dispositifs_d_urgence Nb_lots_CHU',
                                                   'Lots CMCC 2023': 'Dispositifs_d_urgence Nb_lots_CMCC'})

# 8️⃣ Vérification
verifier_colonne_structure(df_CAICHUCMCC_VF, "n_structure", df_ref_structure)

/tmp/ipython-input-1744737330.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_traiter['n_structure'] = None
/tmp/ipython-input-1744737330.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_traiter['nom_structure'] = None

🔎 Vérification de la colonne 'n_structure'
   ❌ 14 valeur(s) manquante(s) ou vide(s) détectée(s).

UFuncTypeError: ufunc 'less' did not contain a loop with signature matching types (<class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.StrDType'>) -> None

In [31]:
df_CAICHUCMCC_VF

1,Dépt,Région,Département,Dispositifs_d_urgence Nb_lots_CAI,Dispositifs_d_urgence Nb_lots_CHU,Dispositifs_d_urgence Nb_lots_CMCC,n_structure,nom_structure
0,01,Auvergne Rhône Alpes,DELEGATION TERRITORIALE DE L'AIN (01),2,2,1,4736.0,EQUIPE TERRITORIALE DES MILLES LOGISTIQUE
1,02,HDF,DELEGATION TERRITORIALE DE L'AISNE (02),3,1,1,4074.0,EQUIPE LOCALE DE CRIQUETOT L'ESNEVAL
2,03,Auvergne Rhône Alpes,DELEGATION TERRITORIALE DE L'ALLIER (03),1,1,1,4557.0,EQUIPE TERRITORIALE DE FRESCATY
3,04,PACA Corse,DELEGATION TERRITORIALE DES ALPES-DE-HAUTE-PRO...,1,1,4,3997.0,DT DES ALPES DE HAUTE PROVENCE
4,05,PACA Corse,DELEGATION TERRITORIALE DES HAUTES-ALPES (05),3,3,3,9.0,DT DES HAUTES ALPES
...,...,...,...,...,...,...,...,...
115,NORM,Normandie,"=""Région ""&B120",=FL17+FL29+FL52+FL63+FL78,=FM17+FM29+FM52+FM63+FM78,=FQ17+FQ29+FQ52+FQ63+FQ78,,
116,OCC,Occitanie,"=""Région ""&B121",=FL12+FL14+FL15+FL32+FL33+FL34+FL36+FL48+FL50+...,=FM12+FM14+FM15+FM32+FM33+FM34+FM36+FM48+FM50+...,=FQ12+FQ14+FQ15+FQ32+FQ33+FQ34+FQ36+FQ48+FQ50+...,,
117,PACAC,Provence Alpes Côte d'Azur - Corse,"=""Région ""&B122",=FL7+FL8+FL9+FL16+FL85+FL86+FL108+FL109,=FM7+FM8+FM9+FM16+FM85+FM86+FM108+FM109,=FQ7+FQ8+FQ9+FQ16+FQ85+FQ86+FQ108+FQ109,,
118,PDLL,Pays de la Loire,"=""Région ""&B123",=FL46+FL51+FL55+FL74+FL87,=FM46+FM51+FM55+FM74+FM87,=FQ46+FQ51+FQ55+FQ74+FQ87,,
119,OM,Outre Mer,"=""Région ""&B124",=FL98+FL99+FL100+FL101+FL102+FL103+FL104+FL105...,=FM98+FM99+FM100+FM101+FM102+FM103+FM104+FM105...,=FQ98+FQ99+FQ100+FQ101+FQ102+FQ103+FQ104+FQ105...,,

## Calcul indicateurs Conventions