In [258]:
!git config --global user.email "clement.souk-aloun@croix-rouge.fr"
!git clone https://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@github.com/clementsouk-aloun-dot/Code-PAT.git

Cloning into 'Code-PAT'...
remote: Enumerating objects: 914, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 914 (delta 62), reused 36 (delta 34), pack-reused 782 (from 2)
Receiving objects: 100% (914/914), 2.46 MiB | 6.53 MiB/s, done.
Resolving deltas: 100% (568/568), done.

In [109]:
%cd Code-PAT
!git checkout pegass

/content/Code-PAT/Code-PAT
Branch 'pegass' set up to track remote branch 'pegass' from 'origin'.
Switched to a new branch 'pegass'

In [ ]:
!git add .

In [ ]:
!git commit -m "Intégration données manuelles"

[Données-manuelles-ACA 532bdb9] Intégration données manuelles
 6 files changed, 7 insertions(+), 7 deletions(-)
 create mode 100644 reference_embeddings.pt
 create mode 100644 scripts_data/__pycache__/manuelles.cpython-312.pyc

In [ ]:
!git fetch origin

remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (6/6), 85.70 KiB | 1.75 MiB/s, done.
From https://github.com/clementsouk-aloun-dot/Code-PAT
   87338f7..baeb842  Mobilité             -> origin/Mobilité
   ef769b4..19118fb  Données-manuelles-ACA -> origin/Données-manuelles-ACA

In [ ]:
!git config pull.rebase true

In [ ]:
!git pull

Successfully rebased and updated refs/heads/Mobilité.

In [ ]:
!git push

Enumerating objects: 17, done.
Counting objects: 100% (17/17), done.
Delta compression using up to 2 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (11/11), 1.64 MiB | 3.13 MiB/s, done.
Total 11 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/clementsouk-aloun-dot/Code-PAT.git
   54c119f..532bdb9  Données-manuelles-ACA -> Données-manuelles-ACA

#INSTALL PACKAGE

In [259]:
!pip install PyPDF2
!pip install reportlab
!pip install PyMuPDF tools
!pip install xlsxwriter

Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.12/dist-packages (3.0.1)
Requirement already satisfied: reportlab in /usr/local/lib/python3.12/dist-packages (4.4.9)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.4)
Requirement already satisfied: PyMuPDF in /usr/local/lib/python3.12/dist-packages (1.26.7)
Requirement already satisfied: tools in /usr/local/lib/python3.12/dist-packages (1.0.23)
Requirement already satisfied: xlsxwriter in /usr/local/lib/python3.12/dist-packages (3.2.9)

In [260]:
import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import sys
import io
import re
import shutil
import zipfile
from google.colab import drive, files

from google.colab import auth
from google.auth import default
import unicodedata
import re
import torch
from sentence_transformers import SentenceTransformer, util

Imports des fichiers .py

In [261]:
sys.path.append(os.path.abspath("/content/Code-PAT/scripts_data"))
sys.path.append(os.path.abspath("/content/Code-PAT"))

from pegass import *
from financier import *
from mobilite import *
from manuelles import *
from utils import *

#AUTHENTIFICATION

In [262]:
from google.colab import auth
!gcloud auth application-default login

from google.cloud import bigquery
import pandas as pd

PROJECT_ID = "crf-pat"
client = bigquery.Client(project=PROJECT_ID)





# Import



query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.crf_activite_ref_activite_benevole`
"""
df_ref_activite_benevole = client.query(query).to_dataframe()
df_ref_activite_benevole.head()


query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.crf_pat_2025_pegass_activite`
"""
df_pegass_activite = client.query(query).to_dataframe()
df_pegass_activite.head()

query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.crf_pat_2025_pegass_activite_seance`
"""
df_pegass_activite_seance = client.query(query).to_dataframe()
df_pegass_activite_seance.head()


query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.crf_pat_2025_pegass_activite_seance_inscription`
"""
df_pegass_activite_seance_inscription = client.query(query).to_dataframe()
df_pegass_activite_seance_inscription.head()

query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.Ref_structure`
"""

df_ref_structure = client.query(query).to_dataframe()
df_ref_structure.head()

#Preparation ref structure
ref_structure1 = df_ref_structure[(df_ref_structure['type_structure'] == "UNITE LOCALE - UL") | (df_ref_structure['type_structure'] == 'DELEGATION TERRITORIALE - DT')]

query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.rattachement_court`
"""

df_rattachement_court = client.query(query).to_dataframe()

Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=HlC1pTxDsZkIXPd4i8djDVyoKAePgm&prompt=consent&token_usage=remote&access_type=offline&code_challenge=u2vmg6LKq4f2fzw7ldlceh2aUEaUmC2NO1PCkx98Pa4&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0ASc3gC2br2sxDkOpRxxM_bQ87nNrqoaGMqmZb5M5sFaur_WH9xk7mpFpLTSXINQaYzKPug

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [263]:
#Preparation ref structure
ref_structure1 = df_ref_structure[(df_ref_structure['type_structure'] == "UNITE LOCALE - UL") | (df_ref_structure['type_structure'] == 'DELEGATION TERRITORIALE - DT')]

In [264]:
query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.crf_activite_ref_activite_benevole`
"""
df_ref_activite_benevole = client.query(query).to_dataframe()
df_ref_activite_benevole

,activite_benevole_id_pk,activite_benevole_libelle,action_id_fk
0,10027,Douche,4
1,10028,Laverie,4
2,11038,Douche et laverie,4
3,10032,Maraude de jour,6
4,10033,Maraude de podologie,6
...,...,...,...
347,11160,Environnement et reduction des risques,122
348,11161,Lutte contre les discriminations,122
349,11162,Premiers secours,122
350,11163,Sante globale,122
351,11164,Valeurs et solidarite,122

In [265]:
query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.crf_pat_2025_pegass_activite_seance_inscription`
"""
df_pegass_activite_seance_inscription = client.query(query).to_dataframe()
df_pegass_activite_seance_inscription

,PEGASS_ACTIVITE_ID_FK,PEGASS_ACTIVITE_SEANCE_ID_FK,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_ID_FK,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_DATE_DEBUT,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_HEURE_DEBUT,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_DATE_FIN,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_HEURE_FIN,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_NIVOL_ID_FK,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_TYPE_ID_FK,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_ROLE_ID_FK
0,656361,656333,6165539,2025-01-18,10:00:00,2025-01-18,12:00:00,1,eNozMDQ0MDAwNDI1t_QGAA8nAnY=,0,200
1,656361,656333,6165540,2025-01-18,10:00:00,2025-01-18,12:00:00,1,eNozMDAwMDIzt7AwNnYEAA94Anc=,0,200
2,656363,656335,6220538,2025-02-01,10:30:00,2025-02-01,12:30:00,1,eNozMDAwMDIzt7AwNnYEAA94Anc=,0,200
3,656363,656335,6220539,2025-02-01,10:30:00,2025-02-01,12:30:00,1,eNozMDQ0MDA0sTCyNHUHAA9MAnc=,0,200
4,656367,656339,6355115,2025-03-01,10:00:00,2025-03-01,12:00:00,1,eNozMDAwMDIzt7AwNnYEAA94Anc=,0,200
...,...,...,...,...,...,...,...,...,...,...,...
1161488,3531740,3549235,8239140,2025-12-05,09:00:00,2025-12-05,11:00:00,0,eNozMDQAAiNDY2NDbwAO-gJn,0,200
1161489,3531741,3549236,8239136,2025-12-12,09:00:00,2025-12-12,11:00:00,1,eNozMDQAAiNDY2NDbwAO-gJn,0,200
1161490,3531742,3549237,8239131,2025-12-19,09:00:00,2025-12-19,11:00:00,1,eNozMDQAAiNDY2NDbwAO-gJn,0,200
1161491,3531743,3549238,8239137,2025-12-26,09:00:00,2025-12-26,11:00:00,1,eNozMDQAAiNDY2NDbwAO-gJn,0,200
1161492,3531837,3549333,8239503,2025-01-30,16:00:00,2025-01-30,20:30:00,0,eNozMAABM0tzCyNHAA9GAnI=,0,200

In [266]:

query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.crf_as_ref_action_groupe_action`
"""
df_ref_action_groupe_action = client.query(query).to_dataframe()
df_ref_action_groupe_action.head()

df_ref_action_groupe_action.columns = ['action_id_fk', 'ACTION_LIBELLE', 'GROUPE_ACTION_ID_FK']

In [267]:
df_ref_action_groupe_action.columns

Index(['action_id_fk', 'ACTION_LIBELLE', 'GROUPE_ACTION_ID_FK'], dtype='object')

In [268]:
df_ref_action_groupe_action

,action_id_fk,ACTION_LIBELLE,GROUPE_ACTION_ID_FK
0,19,Postes de secours,1
1,21,Urgence et autres operations,1
2,65,Reseau de secours,1
3,74,Corps de Reserve de l'Urgence,1
4,4,Point Hygiene,2
5,6,Samu Social maraudes equipes mob. - Operations,2
6,8,Acces aux droits et aux services,2
7,9,Apprentissage des savoirs,2
8,27,Actions specifiques aupres des migrants,2
9,28,Actions aupres des personnes agees,2
10,29,Action prisons justice,2
11,39,Accueil et orientation,2
12,40,Accueil famille-enfant,2
13,51,Croix-Rouge Ecoute/Croix-Rouge Ecoute les detenus,2
14,61,Samu Social maraudes equipes mob. - Organisation,2
15,64,Aides financieres,2
16,69,Espace bebe parents,2
17,72,Microcredit Personnel,2
18,75,Action de retablissement des liens familiaux,2
19,76,Actions d'aide a la mobilite,2
20,95,Acces a la culture et aux loisirs,2
21,96,Acces aux soins et bien etre,2
22,97,Action itinerante d'aides sociales et materielles,2
23,98,Textile & Bric-a-Brac,2
24,99,Aide Alimentaire,2
25,100,Inclusion numerique,2
26,111,Conciergerie solidaire – la Croix-Rouge chez vous,2
27,112,Actions aupres des pers. en situation de handicap,2
28,113,Dispositifs de soutien psychosocial aux benevoles,2
29,115,Dispositif d'interv. campements/squats/bidonvi...,2
30,25,Administration et finance,3
31,46,Developpement associatif,3
32,47,Recrutement et integration,3
33,92,Pole sante,3
34,110,Action Logistique,3
35,101,Dynamique jeunesse,10
36,116,ERU - Formation,14
37,117,ERU - Operation,14
38,91,Action internationale decentralisee,16
39,93,Droit international humanitaire,16
40,114,Mission CMRPS,16
41,94,Formation Grand Public,17
42,104,Formation Interne,17
43,105,Reserve a l’application Formation,17
44,118,Mentorat,10
45,119,Prevention et education pour la sante,10
46,120,Option Croix-Rouge,10
47,121,Croix-Rouge Initiatives,10
48,122,Action educative ponctuelle,10

In [269]:
# 1) activité bénévole et action
df_ref_action_activite = pd.merge(df_ref_action_groupe_action, df_ref_activite_benevole, on="action_id_fk", how="left")

In [270]:
import pandas as pd
#Fonction de comparaison de 2 tables pour savoir qu'elles seront les lignes non mergées

def rows_not_in_merge(df_left: pd.DataFrame, df_right: pd.DataFrame, id_col: str, keep_cols_left=None, keep_cols_right=None):
    """
    Compare 2 tables sur id_col et retourne:
    - left_only: lignes de df_left dont l'id n'existe pas dans df_right
    - right_only: lignes de df_right dont l'id n'existe pas dans df_left

    keep_cols_left / keep_cols_right : liste de colonnes à conserver (optionnel).
    """
    left_ids = set(df_left[id_col].dropna().unique())
    right_ids = set(df_right[id_col].dropna().unique())

    left_only = df_left[df_left[id_col].isin(left_ids - right_ids)].copy()
    right_only = df_right[df_right[id_col].isin(right_ids - left_ids)].copy()

    if keep_cols_left is not None:
        left_only = left_only[[c for c in keep_cols_left if c in left_only.columns]]
    if keep_cols_right is not None:
        right_only = right_only[[c for c in keep_cols_right if c in right_only.columns]]

    return left_only, right_only

In [271]:
left_only, right_only = rows_not_in_merge(df_ref_action_groupe_action, df_ref_activite_benevole, "action_id_fk")

left_only.head()
right_only.head()

     activite_benevole_id_pk  activite_benevole_libelle  action_id_fk
146                    10005  Deploiement ERU - Support            82
147                    10003     Deploiement ERU - Wash            83
148                    10002   Deploiement ERU - Relief            84
149                    10001     Deploiement ERU - ECRC            85
150                    10004    Deploiement ERU - PSSiE            90

In [273]:
df_pegass_activite = df_pegass_activite.rename(columns={"PEGASS_ACTIVITE_ID_PK": "PEGASS_ACTIVITE_ID_FK"})

In [124]:
#Vérification : toutes les activités de Pegass séance sont bien référencées dans PEGASS activité
left_only, right_only = rows_not_in_merge(df_pegass_activite_seance, df_pegass_activite , "PEGASS_ACTIVITE_ID_FK")

left_only.head()
right_only.head()

Empty DataFrame
Columns: [PEGASS_ACTIVITE_ID_FK, PEGASS_ACTIVITE_DATE_DEBUT, PEGASS_ACTIVITE_HEURE_DEBUT, PEGASS_ACTIVITE_DATE_FIN, PEGASS_ACTIVITE_HEURE_FIN, PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK, PEGASS_ACTIVITE_STRUCTURE_ORGANISATRICE_ID_FK, ACTIVITE_BENEVOLE_ID_FK, ACTIVITE_BENEVOLE_EXTERNAL_ID_FK]
Index: []

##Comprendre la tablePEGASS

In [25]:
#Qu'est que ce "ACTIVITE_SEANCE_EXTERNAL_ID_FK"
df_pegass_activite_seance["ACTIVITE_SEANCE_EXTERNAL_ID_FK"].unique()

array([None, '0292024120008-0001', '0352024110001-0001', ...,
       '0452025110003-0001', '0142025110012-0001', '0452025110004-0001'],
      dtype=object)

In [26]:
s = df_pegass_activite_seance["ACTIVITE_SEANCE_EXTERNAL_ID_FK"]
print(s.isna().sum())

396110

In [27]:
d = df_pegass_activite["ACTIVITE_BENEVOLE_EXTERNAL_ID_FK"]
print(d.isna().sum())

396110

In [28]:
s = df_pegass_activite_seance["ACTIVITE_SEANCE_EXTERNAL_ID_FK"]

# Longueur (NaN -> chaîne vide)
lengths = s.fillna("").astype(str).str.len()

# Tableau: nb de cellules par longueur
table = (lengths.value_counts()
         .sort_index()
         .rename_axis("nb_caracteres")
         .reset_index(name="nb_cellules"))

print(table)

   nb_caracteres  nb_cellules
0              0       396110
1             18        16930

In [29]:
s = df_pegass_activite["ACTIVITE_BENEVOLE_EXTERNAL_ID_FK"]

# Longueur (NaN -> chaîne vide)
lengths = s.fillna("").astype(str).str.len()

# Tableau: nb de cellules par longueur
table = (lengths.value_counts()
         .sort_index()
         .rename_axis("nb_caracteres")
         .reset_index(name="nb_cellules"))

print(table)

   nb_caracteres  nb_cellules
0              0       396110
1             13        13305

In [ ]:
#On a donc pas le même nombre de caractères sur ACTIVITE_SEANCE_EXTERNAL_ID_FK entre séance et activité

In [30]:
test = df_pegass_activite_seance["ACTIVITE_SEANCE_EXTERNAL_ID_FK"].unique()

In [31]:
pd.DataFrame(test)

                        0
0                    None
1      0292024120008-0001
2      0352024110001-0001
3      0642024010026-0001
4      0742024090001-0001
...                   ...
16926  0142025110009-0001
16927  0142025110011-0001
16928  0452025110003-0001
16929  0142025110012-0001
16930  0452025110004-0001

[16931 rows x 1 columns]

In [32]:
# To count occurrences of 'None' in the NumPy array 'test':
# print(np.sum(test == None))
# To get the total number of elements in the array:
# print(len(test))
# Or, if you want to count a specific numeric value like 0, and assuming `test` contains numbers:
# print((test == 0).sum())

# Based on the previous output, 'test' contains 'None' and strings.
# If the intent was to count the non-None elements, you could do:
print(np.sum(test != None))

16930

In [34]:
print(np.sum(test == None))

1

##Préparation de la table

In [274]:
# 1) Join avec action sur PEGASS_ACTIVITE_ID_FK
df_pegass_activite_merge = pd.merge(df_pegass_activite_seance, df_pegass_activite, on="PEGASS_ACTIVITE_ID_FK", how="left")

In [275]:
# 1) préparation de la table pour le Nb de Bénévoles
df_pegass_ben_activite = pd.merge(df_pegass_activite, df_pegass_activite_seance_inscription, on="PEGASS_ACTIVITE_ID_FK", how="right")

#On ne garde que celle dont le statut est validé = celles DONT PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT' qui sont diff de zero
df_pegass_ben_activite = df_pegass_ben_activite[df_pegass_ben_activite['PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT'] != 0]

In [293]:
#On fait une base synthétique pour compter le nombre de bénévoles différents
df_pegass_ben_activite_synthétique = df_pegass_ben_activite[['PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK', 'ACTIVITE_BENEVOLE_ID_FK','PEGASS_ACTIVITE_SEANCE_INSCRIPTION_NIVOL_ID_FK']]

df_pegass_ben_activite_synthétique.drop_duplicates()

,PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK,ACTIVITE_BENEVOLE_ID_FK,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_NIVOL_ID_FK
0,903,10035,eNozMDQ0AAILczMjLwAPNQJ0
3,903,10035,eNozMDAwMDQ3tTAwMfQFAA9WAng=
6,903,10035,eNozMDQ0MDA0MDUzNfYFAA8rAnQ=
16,903,10035,eNozMDQ0MDA0NjQ2tfADAA8oAnY=
20,903,10035,eNozMDQ0MDA0MrGwNPMAAA9HAnk=
...,...,...,...
198278,35,10135,eNozMDQ0MDAwNjY2swwGAA81An4=
198279,35,10135,eNozMDQ0MDA0MjY3Mg8AAA8zAnk=
198284,541,10015,eNozMDQ0MDA0MjW0MHQFAA8gAmo=
198286,64,10135,eNozMDAwMDI0s7CwMHIFAA9gAnk=
198294,31,10135,eNozMAABQyNLC8tQAA8vAoM=

In [276]:
df_pegass_ben_activite.columns

Index(['PEGASS_ACTIVITE_ID_FK', 'PEGASS_ACTIVITE_DATE_DEBUT',
       'PEGASS_ACTIVITE_HEURE_DEBUT', 'PEGASS_ACTIVITE_DATE_FIN',
       'PEGASS_ACTIVITE_HEURE_FIN',
       'PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK',
       'PEGASS_ACTIVITE_STRUCTURE_ORGANISATRICE_ID_FK',
       'ACTIVITE_BENEVOLE_ID_FK', 'ACTIVITE_BENEVOLE_EXTERNAL_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_DATE_DEBUT',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_HEURE_DEBUT',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_DATE_FIN',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_HEURE_FIN',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_NIVOL_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_TYPE_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_ROLE_ID_FK'],
      dtype='object')

In [277]:
# #Filtres bases
# df_pegass_activite_merge = df_pegass_activite[['PEGASS_ACTIVITE_ID_FK', 'ACTIVITE_BENEVOLE_ID_FK', 'PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK', 'PEGASS_ACTIVITE_STRUCTURE_ORGANISATRICE_ID_FK', 'ACTIVITE_BENEVOLE_EXTERNAL_ID_FK']]

# df_pegass_activite_seance[['PEGASS_ACTIVITE_ID_FK', 'PEGASS_ACTIVITE_SEANCE_ID_FK',
#        'PEGASS_ACTIVITE_SEANCE_DATE_DEBUT',
#        'PEGASS_ACTIVITE_SEANCE_HEURE_DEBUT', 'PEGASS_ACTIVITE_SEANCE_DATE_FIN',
#        'PEGASS_ACTIVITE_SEANCE_HEURE_FIN', 'ACTIVITE_SEANCE_EXTERNAL_ID_FK']]

# df_pegass_activite_seance_inscription= df_pegass_activite_seance_inscription[['PEGASS_ACTIVITE_ID_FK', 'PEGASS_ACTIVITE_SEANCE_ID_FK',
#        'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_ID_FK',
#       #  'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_DATE_DEBUT',
#        'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_HEURE_DEBUT',
#        'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_DATE_FIN',
#        'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_HEURE_FIN',
#        'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT',
#        'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_NIVOL_ID_FK',
#        'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_TYPE_ID_FK',
#        'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_ROLE_ID_FK']]

In [278]:
df_pegass_activite_merge1.columns

Index(['PEGASS_ACTIVITE_ID_FK_x', 'PEGASS_ACTIVITE_SEANCE_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_DATE_DEBUT',
       'PEGASS_ACTIVITE_SEANCE_HEURE_DEBUT', 'PEGASS_ACTIVITE_SEANCE_DATE_FIN',
       'PEGASS_ACTIVITE_SEANCE_HEURE_FIN', 'ACTIVITE_SEANCE_EXTERNAL_ID_FK',
       'PEGASS_ACTIVITE_DATE_DEBUT', 'PEGASS_ACTIVITE_HEURE_DEBUT',
       'PEGASS_ACTIVITE_DATE_FIN', 'PEGASS_ACTIVITE_HEURE_FIN',
       'PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK',
       'PEGASS_ACTIVITE_STRUCTURE_ORGANISATRICE_ID_FK',
       'ACTIVITE_BENEVOLE_ID_FK', 'ACTIVITE_BENEVOLE_EXTERNAL_ID_FK',
       'PEGASS_ACTIVITE_ID_FK_y', 'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_DATE_DEBUT',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_HEURE_DEBUT',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_DATE_FIN',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_HEURE_FIN',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_NIVOL_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_TYPE_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_ROLE_ID_FK'],
      dtype='object')

In [279]:
df_pegass_activite_seance.columns

Index(['PEGASS_ACTIVITE_ID_FK', 'PEGASS_ACTIVITE_SEANCE_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_DATE_DEBUT',
       'PEGASS_ACTIVITE_SEANCE_HEURE_DEBUT', 'PEGASS_ACTIVITE_SEANCE_DATE_FIN',
       'PEGASS_ACTIVITE_SEANCE_HEURE_FIN', 'ACTIVITE_SEANCE_EXTERNAL_ID_FK'],
      dtype='object')

In [280]:
df_pegass_activite_seance_inscription

,PEGASS_ACTIVITE_ID_FK,PEGASS_ACTIVITE_SEANCE_ID_FK,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_ID_FK,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_DATE_DEBUT,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_HEURE_DEBUT,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_DATE_FIN,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_HEURE_FIN,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_NIVOL_ID_FK,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_TYPE_ID_FK,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_ROLE_ID_FK
0,656361,656333,6165539,2025-01-18,10:00:00,2025-01-18,12:00:00,1,eNozMDQ0MDAwNDI1t_QGAA8nAnY=,0,200
1,656361,656333,6165540,2025-01-18,10:00:00,2025-01-18,12:00:00,1,eNozMDAwMDIzt7AwNnYEAA94Anc=,0,200
2,656363,656335,6220538,2025-02-01,10:30:00,2025-02-01,12:30:00,1,eNozMDAwMDIzt7AwNnYEAA94Anc=,0,200
3,656363,656335,6220539,2025-02-01,10:30:00,2025-02-01,12:30:00,1,eNozMDQ0MDA0sTCyNHUHAA9MAnc=,0,200
4,656367,656339,6355115,2025-03-01,10:00:00,2025-03-01,12:00:00,1,eNozMDAwMDIzt7AwNnYEAA94Anc=,0,200
...,...,...,...,...,...,...,...,...,...,...,...
1161488,3531740,3549235,8239140,2025-12-05,09:00:00,2025-12-05,11:00:00,0,eNozMDQAAiNDY2NDbwAO-gJn,0,200
1161489,3531741,3549236,8239136,2025-12-12,09:00:00,2025-12-12,11:00:00,1,eNozMDQAAiNDY2NDbwAO-gJn,0,200
1161490,3531742,3549237,8239131,2025-12-19,09:00:00,2025-12-19,11:00:00,1,eNozMDQAAiNDY2NDbwAO-gJn,0,200
1161491,3531743,3549238,8239137,2025-12-26,09:00:00,2025-12-26,11:00:00,1,eNozMDQAAiNDY2NDbwAO-gJn,0,200
1161492,3531837,3549333,8239503,2025-01-30,16:00:00,2025-01-30,20:30:00,0,eNozMAABM0tzCyNHAA9GAnI=,0,200

##Vérification des merges

In [281]:
#Comparer les tables pour savoir si on a bien merge

import pandas as pd

def rows_not_in_merge(df_left: pd.DataFrame, df_right: pd.DataFrame, id_col: str, keep_cols_left=None, keep_cols_right=None):
    """
    Compare 2 tables sur id_col et retourne:
    - left_only: lignes de df_left dont l'id n'existe pas dans df_right
    - right_only: lignes de df_right dont l'id n'existe pas dans df_left

    keep_cols_left / keep_cols_right : liste de colonnes à conserver (optionnel).
    """
    left_ids = set(df_left[id_col].dropna().unique())
    right_ids = set(df_right[id_col].dropna().unique())

    left_only = df_left[df_left[id_col].isin(left_ids - right_ids)].copy()
    right_only = df_right[df_right[id_col].isin(right_ids - left_ids)].copy()

    if keep_cols_left is not None:
        left_only = left_only[[c for c in keep_cols_left if c in left_only.columns]]
    if keep_cols_right is not None:
        right_only = right_only[[c for c in keep_cols_right if c in right_only.columns]]

    return left_only, right_only

In [188]:
#vérification
df_pegass_activite_seance_inscription_verif_seance= df_pegass_activite_seance_inscription[[ 'PEGASS_ACTIVITE_SEANCE_ID_FK']]

df_pegass_activite_seance_verif_seance=df_pegass_activite_seance[['PEGASS_ACTIVITE_SEANCE_ID_FK']]


#Comparaison df_pegass_activite_merge et df_pegass_activite
left_only, right_only = rows_not_in_merge(df_pegass_activite_seance_inscription_verif_seance, df_pegass_activite_seance_verif_seance, 'PEGASS_ACTIVITE_SEANCE_ID_FK')

# - right_only: lignes de df_right dont l'id n'existe pas dans df_left
right_only.head()

   PEGASS_ACTIVITE_SEANCE_ID_FK
0                       1746186
1                       2171803
2                       2193317
4                       2223627
5                       2235263

In [189]:
right_only

#Il y'a plus de 59916 de séances qui ne sont pas présents dans

        PEGASS_ACTIVITE_SEANCE_ID_FK
0                            1746186
1                            2171803
2                            2193317
4                            2223627
5                            2235263
...                              ...
412998                       2884893
413003                       3081288
413008                       3181395
413030                       3356094
413039                       3085358

[59916 rows x 1 columns]

In [167]:
#Comparaison df_pegass_activite_merge et df_pegass_activite
left_only, right_only = rows_not_in_merge(df_pegass_activite_merge, df_pegass_activite, "PEGASS_ACTIVITE_ID_FK")

left_only.head()
right_only.head()

Empty DataFrame
Columns: [PEGASS_ACTIVITE_ID_FK, PEGASS_ACTIVITE_DATE_DEBUT, PEGASS_ACTIVITE_HEURE_DEBUT, PEGASS_ACTIVITE_DATE_FIN, PEGASS_ACTIVITE_HEURE_FIN, PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK, PEGASS_ACTIVITE_STRUCTURE_ORGANISATRICE_ID_FK, ACTIVITE_BENEVOLE_ID_FK, ACTIVITE_BENEVOLE_EXTERNAL_ID_FK]
Index: []

In [191]:
#Comparaison df_pegass_activite_merge et df_pegass_activite
left_only, right_only = rows_not_in_merge(df_pegass_activite_seance, df_pegass_activite_seance_inscription,  "PEGASS_ACTIVITE_SEANCE_ID_FK")


left_only.head()
#left_only: lignes de df_left dont l'id n'existe pas dans df_right
#Là il nous manque 59916 séances qui ne sont pas pris en compte dans PEGASS seance incription

#donc pour compter le nombre d'activités bénévoles on ne prends pas le merge1 mais le merge

,PEGASS_ACTIVITE_ID_FK,PEGASS_ACTIVITE_SEANCE_ID_FK,PEGASS_ACTIVITE_SEANCE_DATE_DEBUT,PEGASS_ACTIVITE_SEANCE_HEURE_DEBUT,PEGASS_ACTIVITE_SEANCE_DATE_FIN,PEGASS_ACTIVITE_SEANCE_HEURE_FIN,ACTIVITE_SEANCE_EXTERNAL_ID_FK
0,1746246,1746186,2025-01-01,08:15:00,2025-01-01,12:15:00,None
1,2171865,2171803,2025-01-01,10:00:00,2025-01-01,14:30:00,None
2,2193379,2193317,2024-12-31,23:00:00,2025-01-01,06:00:00,None
4,2223689,2223627,2025-01-01,13:50:00,2025-01-01,17:20:00,None
5,2235325,2235263,2024-12-31,00:00:00,2025-01-01,00:00:00,None

In [192]:
left_only

,PEGASS_ACTIVITE_ID_FK,PEGASS_ACTIVITE_SEANCE_ID_FK,PEGASS_ACTIVITE_SEANCE_DATE_DEBUT,PEGASS_ACTIVITE_SEANCE_HEURE_DEBUT,PEGASS_ACTIVITE_SEANCE_DATE_FIN,PEGASS_ACTIVITE_SEANCE_HEURE_FIN,ACTIVITE_SEANCE_EXTERNAL_ID_FK
0,1746246,1746186,2025-01-01,08:15:00,2025-01-01,12:15:00,None
1,2171865,2171803,2025-01-01,10:00:00,2025-01-01,14:30:00,None
2,2193379,2193317,2024-12-31,23:00:00,2025-01-01,06:00:00,None
4,2223689,2223627,2025-01-01,13:50:00,2025-01-01,17:20:00,None
5,2235325,2235263,2024-12-31,00:00:00,2025-01-01,00:00:00,None
...,...,...,...,...,...,...,...
412998,2885018,2884893,2025-12-30,20:00:00,2025-12-30,23:55:00,None
413003,3081448,3081288,2025-12-30,20:30:00,2025-12-30,23:55:00,None
413008,3181559,3181395,2025-12-30,18:30:00,2025-12-30,23:55:00,None
413030,3356258,3356094,2025-12-30,19:00:00,2025-12-30,23:55:00,None
413039,3085518,3085358,2025-12-29,00:05:00,2026-01-04,23:55:00,None

In [158]:
df_pegass_activite_merge1.columns

Index(['PEGASS_ACTIVITE_ID_FK_x', 'PEGASS_ACTIVITE_SEANCE_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_DATE_DEBUT',
       'PEGASS_ACTIVITE_SEANCE_HEURE_DEBUT', 'PEGASS_ACTIVITE_SEANCE_DATE_FIN',
       'PEGASS_ACTIVITE_SEANCE_HEURE_FIN', 'ACTIVITE_SEANCE_EXTERNAL_ID_FK',
       'PEGASS_ACTIVITE_DATE_DEBUT', 'PEGASS_ACTIVITE_HEURE_DEBUT',
       'PEGASS_ACTIVITE_DATE_FIN', 'PEGASS_ACTIVITE_HEURE_FIN',
       'PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK',
       'PEGASS_ACTIVITE_STRUCTURE_ORGANISATRICE_ID_FK',
       'ACTIVITE_BENEVOLE_ID_FK', 'ACTIVITE_BENEVOLE_EXTERNAL_ID_FK',
       'PEGASS_ACTIVITE_ID_FK_y', 'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_DATE_DEBUT',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_HEURE_DEBUT',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_DATE_FIN',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_HEURE_FIN',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_NIVOL_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_TYPE_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_INSCRIPTION_ROLE_ID_FK'],
      dtype='object')

In [143]:
df_pegass_activite_merge.columns

Index(['PEGASS_ACTIVITE_ID_FK', 'PEGASS_ACTIVITE_SEANCE_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_DATE_DEBUT',
       'PEGASS_ACTIVITE_SEANCE_HEURE_DEBUT', 'PEGASS_ACTIVITE_SEANCE_DATE_FIN',
       'PEGASS_ACTIVITE_SEANCE_HEURE_FIN', 'ACTIVITE_SEANCE_EXTERNAL_ID_FK',
       'PEGASS_ACTIVITE_DATE_DEBUT', 'PEGASS_ACTIVITE_HEURE_DEBUT',
       'PEGASS_ACTIVITE_DATE_FIN', 'PEGASS_ACTIVITE_HEURE_FIN',
       'PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK',
       'PEGASS_ACTIVITE_STRUCTURE_ORGANISATRICE_ID_FK',
       'ACTIVITE_BENEVOLE_ID_FK', 'ACTIVITE_BENEVOLE_EXTERNAL_ID_FK'],
      dtype='object')

In [126]:
df_pegass_activite_merge

,PEGASS_ACTIVITE_ID_FK,PEGASS_ACTIVITE_SEANCE_ID_FK,PEGASS_ACTIVITE_SEANCE_DATE_DEBUT,PEGASS_ACTIVITE_SEANCE_HEURE_DEBUT,PEGASS_ACTIVITE_SEANCE_DATE_FIN,PEGASS_ACTIVITE_SEANCE_HEURE_FIN,ACTIVITE_SEANCE_EXTERNAL_ID_FK,PEGASS_ACTIVITE_DATE_DEBUT,PEGASS_ACTIVITE_HEURE_DEBUT,PEGASS_ACTIVITE_DATE_FIN,PEGASS_ACTIVITE_HEURE_FIN,PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK,PEGASS_ACTIVITE_STRUCTURE_ORGANISATRICE_ID_FK,ACTIVITE_BENEVOLE_ID_FK,ACTIVITE_BENEVOLE_EXTERNAL_ID_FK
0,1746246,1746186,2025-01-01,08:15:00,2025-01-01,12:15:00,None,2025-01-01,08:15:00,2025-01-01,12:15:00,426,426,10027,None
1,2171865,2171803,2025-01-01,10:00:00,2025-01-01,14:30:00,None,2025-01-01,10:00:00,2025-01-01,14:30:00,2713,426,11066,None
2,2193379,2193317,2024-12-31,23:00:00,2025-01-01,06:00:00,None,2024-12-31,23:00:00,2025-01-01,06:00:00,2457,96,10114,None
3,2199513,2199451,2024-12-31,14:00:00,2025-01-01,05:00:00,None,2024-12-31,14:00:00,2025-01-01,05:00:00,4631,4631,10035,None
4,2223689,2223627,2025-01-01,13:50:00,2025-01-01,17:20:00,None,2025-01-01,13:50:00,2025-01-01,17:20:00,621,621,10070,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413035,3371673,3371509,2025-12-02,08:00:00,2025-12-31,23:55:00,None,2025-12-02,08:00:00,2025-12-31,23:55:00,57,57,10035,None
413036,3374790,3374626,2025-12-29,00:00:00,2025-12-31,23:55:00,None,2025-12-29,00:00:00,2025-12-31,23:55:00,74,74,10117,None
413037,2805941,2805816,2025-12-29,00:05:00,2026-01-04,23:55:00,None,2025-12-29,00:05:00,2026-01-04,23:55:00,85,85,10118,None
413038,2960512,2960373,2025-12-29,00:00:00,2026-01-04,23:55:00,None,2025-12-29,00:00:00,2026-01-04,23:55:00,67,67,10118,None
413039,3085518,3085358,2025-12-29,00:05:00,2026-01-04,23:55:00,None,2025-12-29,00:05:00,2026-01-04,23:55:00,13,13,10141,None

##Vérification des tables

In [37]:
#vérif

# 1. Vérification des NaN ou valeurs vides
lignes_vides = df_pegass_activite_merge[df_pegass_activite_merge["PEGASS_ACTIVITE_ID_FK"].isna() | (df_pegass_activite_merge["PEGASS_ACTIVITE_ID_FK"] == "")]
if not lignes_vides.empty:
        print(f"   ❌ {len(lignes_vides)} valeur(s) manquante(s) ou vide(s) détectée(s).")
else:
        print("   ✅ Aucun NaN ou valeur vide détecté.")

   ✅ Aucun NaN ou valeur vide détecté.

In [38]:
#vérif

# 1. Vérification des NaN ou valeurs vides
lignes_vides = df_pegass_activite_merge[df_pegass_activite_merge["ACTIVITE_BENEVOLE_ID_FK"].isna() | (df_pegass_activite_merge["ACTIVITE_BENEVOLE_ID_FK"] == "")]
if not lignes_vides.empty:
        print(f"   ❌ {len(lignes_vides)} valeur(s) manquante(s) ou vide(s) détectée(s).")
else:
        print("   ✅ Aucun NaN ou valeur vide détecté.")

   ✅ Aucun NaN ou valeur vide détecté.

In [39]:
#vérif sur les structures menant les activités de la table consolidée

# 1. Vérification des NaN ou valeurs vides
lignes_vides = df_pegass_activite_merge[df_pegass_activite_merge["PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK"].isna() | (df_pegass_activite_merge["PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK"] == "")]
if not lignes_vides.empty:
        print(f"   ❌ {len(lignes_vides)} valeur(s) manquante(s) ou vide(s) détectée(s).")
else:
        print("   ✅ Aucun NaN ou valeur vide détecté.")

   ❌ 5255 valeur(s) manquante(s) ou vide(s) détectée(s).

In [40]:
#vérif sur les structures menant les activités de la table pegass activité

# 1. Vérification des NaN ou valeurs vides
lignes_vides_source = df_pegass_activite[df_pegass_activite["PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK"].isna() | (df_pegass_activite["PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK"] == "")]
if not lignes_vides_source.empty:
        print(f"   ❌ {len(lignes_vides_source)} valeur(s) manquante(s) ou vide(s) détectée(s).")
else:
        print("   ✅ Aucun NaN ou valeur vide détecté.")

 #Problème détecté :  5255 ACTIVITES n'ont pas de structures organisatrices associées

   ❌ 5255 valeur(s) manquante(s) ou vide(s) détectée(s).

In [41]:
activite_sans_struct = lignes_vides["ACTIVITE_BENEVOLE_ID_FK"].unique()

In [42]:
activite_sans_struct2 = lignes_vides["ACTIVITE_BENEVOLE_ID_FK"]

In [43]:
activite_sans_struct2 = pd.DataFrame(activite_sans_struct2)
activite_sans_struct2.columns = ["activite_benevole_id_pk"]

In [44]:
activite_sans_struct2

        activite_benevole_id_pk
148                       10115
149                       10115
150                       10114
153                       10116
206                       10115
...                         ...
412641                    10035
412642                    10035
412903                    10035
412904                    10035
412905                    10035

[5255 rows x 1 columns]

In [45]:
df_count = (
    activite_sans_struct2["activite_benevole_id_pk"]
    .value_counts()
    .reset_index()
    #.rename(columns={"index": "activite_benevole_id_pk", "activite_benevole_id_pk": "nb_occurrences"})
)
df_count

    activite_benevole_id_pk  count
0                     10115   2395
1                     10116    730
2                     10114    617
3                     10035    431
4                     10072    313
5                     10147    305
6                     10023    120
7                     10141    103
8                     10124     46
9                     11110     40
10                    10070     34
11                    10051     34
12                    11054     30
13                    10032     30
14                    10172      9
15                    10156      9
16                    11158      6
17                    10037      3

In [46]:
df_count_activite_sans_struct = pd.merge(df_count, df_ref_action_activite, on="activite_benevole_id_pk", how="right")

In [47]:
df_count_activite_sans_struct

,activite_benevole_id_pk,count,action_id_fk,ACTION_LIBELLE,GROUPE_ACTION_ID_FK,activite_benevole_libelle
0,10104,<NA>,19,Postes de secours,1,Encadrement DPS ME-GE
1,10107,<NA>,19,Postes de secours,1,Logistique / ETIR
2,10108,<NA>,19,Postes de secours,1,Participation Grand Rassemblement
3,10109,<NA>,19,Postes de secours,1,Pre Inscription DPS
4,10112,<NA>,19,Postes de secours,1,Telecoms
...,...,...,...,...,...,...
329,11160,<NA>,122,Action educative ponctuelle,10,Environnement et reduction des risques
330,11161,<NA>,122,Action educative ponctuelle,10,Lutte contre les discriminations
331,11162,<NA>,122,Action educative ponctuelle,10,Premiers secours
332,11163,<NA>,122,Action educative ponctuelle,10,Sante globale
333,11164,<NA>,122,Action educative ponctuelle,10,Valeurs et solidarite

In [ ]:
df_count_activite_sans_struct.to_excel('df_count_activite_sans_struct.xlsx')
files.download("df_count_activite_sans_struct.xlsx")

In [ ]:
activite_sans_struct = pd.DataFrame(activite_sans_struct)
activite_sans_struct.columns = ["activite_benevole_id_pk"]

In [ ]:
activite_sans_struct.drop_duplicates()

In [ ]:
# 1) activité bénévole et action
df_nom_activite_sans_struct = pd.merge(activite_sans_struct, df_ref_action_activite, on="activite_benevole_id_pk", how="left")

In [ ]:
df_ref_action_activite.to_excel('df_ref_action_activite.xlsx')
files.download("df_ref_action_activite.xlsx")

In [ ]:
df_ref_action_activite.to_csv('df_ref_action_activite.csv')

In [ ]:
df_nom_activite_sans_struct

In [ ]:
lignes_vides

In [ ]:
if lignes_vides.empty

In [ ]:
df_ref_action_activite

,action_id_fk,ACTION_LIBELLE,GROUPE_ACTION_ID_FK,activite_benevole_id_pk,activite_benevole_libelle
0,19,Postes de secours,1,10104,Encadrement DPS ME-GE
1,19,Postes de secours,1,10107,Logistique / ETIR
2,19,Postes de secours,1,10108,Participation Grand Rassemblement
3,19,Postes de secours,1,10109,Pre Inscription DPS
4,19,Postes de secours,1,10112,Telecoms
...,...,...,...,...,...
329,122,Action educative ponctuelle,10,11160,Environnement et reduction des risques
330,122,Action educative ponctuelle,10,11161,Lutte contre les discriminations
331,122,Action educative ponctuelle,10,11162,Premiers secours
332,122,Action educative ponctuelle,10,11163,Sante globale
333,122,Action educative ponctuelle,10,11164,Valeurs et solidarite

##Merge

In [ ]:
"""10119
10122
10123
10125
10126
10127
10128
10129
10132
10133
10134
10135
10136
10137

10032
10033
10034
10035
11110


10015
10046
10047
11126"""

'10119\n10122\n10123\n10125\n10126\n10127\n10128\n10129\n10132\n10133\n10134\n10135\n10136\n10137\n\n10032\n10033\n10034\n10035\n11110\n\n\n10015\n10046\t\n10047\n11126'

In [282]:
#codes_activite_ben = [
#    10119, 10122, 10123, 10125, 10126, 10127, 10128, 10129,
#    10132, 10133, 10134, 10135, 10136, 10137,
#    10032, 10033, 10034, 10035, 11110,
#    10015, 10046, 10047, 11126
# 10104, 10107, 10108, 10109, 10112, 10113,10110,10106,10105,10111,11007,]




codes_activite_ben = [
    10119, 10122, 10123, 10125, 10126, 10127, 10128, 10129,
    10132, 10133, 10134, 10135, 10136, 10137,
    10032, 10033, 10034, 10035, 11110,
    10015, 10046, 10047, 11126,
    10105, 10106, 10108, 10113
]
df_ref_action_activite_filtre = df_ref_action_activite[df_ref_action_activite["activite_benevole_id_pk"].isin(codes_activite_ben)].copy()

In [283]:
# 1) Join avec action sur PEGASS_ACTIVITE_ID_FK
df_ref_action_activite_filtre = df_ref_action_activite_filtre.rename(columns={"activite_benevole_id_pk": "ACTIVITE_BENEVOLE_ID_FK"})
df_pegass_activite_merge2 = pd.merge(df_pegass_activite_merge1, df_ref_action_activite_filtre, on="ACTIVITE_BENEVOLE_ID_FK", how="inner")


#Join avec la table du nb bénévole
df_pegass_ben_activite= pd.merge(df_pegass_ben_activite, df_ref_action_activite_filtre, on="ACTIVITE_BENEVOLE_ID_FK", how="inner")

In [284]:
df_pegass_activite_merge2

,PEGASS_ACTIVITE_ID_FK_x,PEGASS_ACTIVITE_SEANCE_ID_FK,PEGASS_ACTIVITE_SEANCE_DATE_DEBUT,PEGASS_ACTIVITE_SEANCE_HEURE_DEBUT,PEGASS_ACTIVITE_SEANCE_DATE_FIN,PEGASS_ACTIVITE_SEANCE_HEURE_FIN,ACTIVITE_SEANCE_EXTERNAL_ID_FK,PEGASS_ACTIVITE_DATE_DEBUT,PEGASS_ACTIVITE_HEURE_DEBUT,PEGASS_ACTIVITE_DATE_FIN,...,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_DATE_FIN,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_HEURE_FIN,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_NIVOL_ID_FK,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_TYPE_ID_FK,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_ROLE_ID_FK,action_id_fk,ACTION_LIBELLE,GROUPE_ACTION_ID_FK,activite_benevole_libelle
0,690653,690625,2025-01-06,19:30:00,2025-01-06,23:30:00,None,2025-01-06,19:30:00,2025-01-06,...,2025-01-06,23:30:00,0,eNozMAACU3NLUxPLEAAPfAKM,0,239,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
1,690654,690626,2025-01-13,19:30:00,2025-01-13,23:30:00,None,2025-01-13,19:30:00,2025-01-13,...,2025-01-13,23:30:00,1,eNozMDQ0AAILczMjLwAPNQJ0,0,4,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
2,690654,690626,2025-01-13,19:30:00,2025-01-13,23:30:00,None,2025-01-13,19:30:00,2025-01-13,...,2025-01-13,23:30:00,0,eNozMDQ0MDA0MDYxtPQGAA8XAnA=,0,239,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
3,690655,690627,2025-01-20,19:30:00,2025-01-20,23:30:00,None,2025-01-20,19:30:00,2025-01-20,...,2025-01-20,23:30:00,1,eNozMDQ0AAILczMjLwAPNQJ0,0,4,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
4,690655,690627,2025-01-20,19:30:00,2025-01-20,23:30:00,None,2025-01-20,19:30:00,2025-01-20,...,2025-01-20,23:30:00,1,eNozMAACU3NLUxPLEAAPfAKM,0,239,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198296,3516223,3533639,2025-11-22,19:00:00,2025-11-22,22:30:00,None,2025-11-22,19:00:00,2025-11-22,...,2025-11-22,22:30:00,1,eNozMDQ0MDA0tjQ0sPABAA83AnU=,0,200,6,Samu Social maraudes equipes mob. - Operations,2,Maraude de soir
198297,3516223,3533639,2025-11-22,19:00:00,2025-11-22,22:30:00,None,2025-11-22,19:00:00,2025-11-22,...,2025-11-22,22:30:00,1,eNozMDQ0MDA0MTC2tHQHAA8wAnQ=,0,200,6,Samu Social maraudes equipes mob. - Operations,2,Maraude de soir
198298,3516223,3533639,2025-11-22,19:00:00,2025-11-22,22:30:00,None,2025-11-22,19:00:00,2025-11-22,...,2025-11-22,22:30:00,1,eNozMDQ0MDCwNLAws_QFAA9YAoA=,0,200,6,Samu Social maraudes equipes mob. - Operations,2,Maraude de soir
198299,3522861,3540331,2025-12-04,16:00:00,2025-12-04,18:00:00,None,2025-12-04,16:00:00,2025-12-04,...,2025-12-04,18:00:00,1,eNozMDAwMDQzMjM3MHUHAA9FAnM=,0,200,6,Samu Social maraudes equipes mob. - Operations,2,Maraude de jour
198300,3529274,3546764,2025-12-20,10:00:00,2025-12-20,11:30:00,None,2025-12-20,10:00:00,2025-12-20,...,2025-12-20,11:30:00,1,eNozMAACSwtjYwNLXwAPZQJ-,0,200,8,Acces aux droits et aux services,2,Domiciliation Administrative

In [285]:
#pas de doublons (même nb de lignes que sans drop duplicate)
df_pegass_activite_merge2.drop_duplicates("PEGASS_ACTIVITE_SEANCE_ID_FK")

,PEGASS_ACTIVITE_ID_FK_x,PEGASS_ACTIVITE_SEANCE_ID_FK,PEGASS_ACTIVITE_SEANCE_DATE_DEBUT,PEGASS_ACTIVITE_SEANCE_HEURE_DEBUT,PEGASS_ACTIVITE_SEANCE_DATE_FIN,PEGASS_ACTIVITE_SEANCE_HEURE_FIN,ACTIVITE_SEANCE_EXTERNAL_ID_FK,PEGASS_ACTIVITE_DATE_DEBUT,PEGASS_ACTIVITE_HEURE_DEBUT,PEGASS_ACTIVITE_DATE_FIN,...,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_DATE_FIN,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_HEURE_FIN,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_NIVOL_ID_FK,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_TYPE_ID_FK,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_ROLE_ID_FK,action_id_fk,ACTION_LIBELLE,GROUPE_ACTION_ID_FK,activite_benevole_libelle
0,690653,690625,2025-01-06,19:30:00,2025-01-06,23:30:00,None,2025-01-06,19:30:00,2025-01-06,...,2025-01-06,23:30:00,0,eNozMAACU3NLUxPLEAAPfAKM,0,239,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
1,690654,690626,2025-01-13,19:30:00,2025-01-13,23:30:00,None,2025-01-13,19:30:00,2025-01-13,...,2025-01-13,23:30:00,1,eNozMDQ0AAILczMjLwAPNQJ0,0,4,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
3,690655,690627,2025-01-20,19:30:00,2025-01-20,23:30:00,None,2025-01-20,19:30:00,2025-01-20,...,2025-01-20,23:30:00,1,eNozMDQ0AAILczMjLwAPNQJ0,0,4,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
5,690656,690628,2025-01-27,19:30:00,2025-01-27,23:30:00,None,2025-01-27,19:30:00,2025-01-27,...,2025-01-27,23:30:00,0,eNozMDQ0MDA0MDYxtPQGAA8XAnA=,0,239,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
8,690657,690629,2025-02-03,19:30:00,2025-02-03,23:30:00,None,2025-02-03,19:30:00,2025-02-03,...,2025-02-03,23:30:00,0,eNozMDAwMDQxszQwNnUCAA9GAm8=,0,4,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198290,3509284,3526673,2025-12-09,09:00:00,2025-12-09,12:00:00,None,2025-12-09,09:00:00,2025-12-09,...,2025-12-09,12:00:00,1,eNozMDAwMDQ3NzMwNI4AAA9eAoI=,0,200,8,Acces aux droits et aux services,2,Domiciliation Administrative
198291,3509285,3526674,2025-12-16,09:00:00,2025-12-16,12:00:00,None,2025-12-16,09:00:00,2025-12-16,...,2025-12-16,12:00:00,1,eNozMDAwMDQ3NzMwNI4AAA9eAoI=,0,200,8,Acces aux droits et aux services,2,Domiciliation Administrative
198292,3509286,3526675,2025-12-23,09:00:00,2025-12-23,12:00:00,None,2025-12-23,09:00:00,2025-12-23,...,2025-12-23,12:00:00,1,eNozMDAwMDQ3NzMwNI4AAA9eAoI=,0,200,8,Acces aux droits et aux services,2,Domiciliation Administrative
198294,3516220,3533636,2025-11-21,19:00:00,2025-11-21,22:30:00,None,2025-11-21,19:00:00,2025-11-21,...,2025-11-21,22:30:00,1,eNozMDQ0MDA0tjQ0sPABAA83AnU=,0,200,6,Samu Social maraudes equipes mob. - Operations,2,Maraude de soir
198296,3516223,3533639,2025-11-22,19:00:00,2025-11-22,22:30:00,None,2025-11-22,19:00:00,2025-11-22,...,2025-11-22,22:30:00,1,eNozMDQ0MDA0tjQ0sPABAA83AnU=,0,200,6,Samu Social maraudes equipes mob. - Operations,2,Maraude de soir

##Calcul des indicateurs

### Calcul indicateur NB de bénévoles

In [295]:
def calc_nb_benevole_activite_Pegass(
    df_prep,
    col_structure="PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK",
    col_activite="ACTIVITE_BENEVOLE_ID_FK",   # ta colonne "N° activité"
    out_structure="n_structure",
    out_activite="N° activité",
    out_count="nb_bénévoles",
    dropna=False,
    sort=True
):
    """
    Compte le nombre d'occurrences (lignes) par (structure, activité).

    Retourne un DataFrame avec 3 colonnes :
    - out_structure : identifiant structure
    - out_activite  : identifiant / n° activité
    - out_count     : nombre de lignes pour ce couple
    """

    # Groupby sur 2 colonnes = structure + activité
    df_out = (
        df_prep
        .groupby([col_structure, col_activite], dropna=dropna)
        .size()
        .reset_index(name=out_count)
        .rename(columns={
            col_structure: out_structure,
            col_activite: out_activite
        })
    )

    if sort:
        df_out = df_out.sort_values([out_structure, out_count], ascending=[True, False])

    return df_out

In [299]:
nb_benevole_activite_Pegass = calc_nb_benevole_activite_Pegass(df_pegass_ben_activite_synthétique)

In [302]:
nb_benevole_activite_Pegass

      n_structure  N° activité  nb_bénévoles
0               1        10119          1635
1               1        10125           158
2               1        10137            23
3               5        10113            37
4               5        10122            17
...           ...          ...           ...
1528         4920        10015             2
1531         4928        10135           175
1530         4928        10132            13
1532         4934        10113            43
1533         4934        10119            15

[1534 rows x 3 columns]

In [298]:
#Attention il faut faire les verifs pour voir si le nb bénévoles noté correspond bien au nb de ligne du fichier d'avant

In [301]:
#calcul NB bénévoles actifs maraudes_PEGASS
#Attention ça ne marche pas : il faut d'abord faire chaque DF puis supprimer les N°activités puis drop duplicate et enfin sommer

nb_ben_Maraude_Pegass = nb_benevole_activite_Pegass[nb_benevole_activite_Pegass["N° activité"].isin(Activite_maraude)]
nb_ben_Maraude_Pegass = nb_ben_Maraude_Pegass.rename(columns={"nb_bénévoles": "Maraude Nb_benevoles_actifs"})
#nb_ben_Maraude_Pegass = nb_ben_Maraude_Pegass.drop(columns=["N° activité"])
#nb_ben_Maraude_Pegass = nb_ben_Maraude_Pegass.groupby("n_structure", as_index=False)["nb_Maraude_Pegass"].sum()

In [303]:
nb_ben_Maraude_Pegass

      n_structure  N° activité  Maraude Nb_benevoles_actifs
10             10        10035                           26
14             10        11110                            2
16             12        10032                          140
21             12        11110                            9
54             23        11110                            1
...           ...          ...                          ...
1500         4642        11110                            7
1509         4674        11110                           12
1511         4676        11110                          344
1512         4677        10034                            5
1527         4884        11110                            4

[401 rows x 3 columns]

In [257]:
df_pegass_ben_activite['PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT'].unique()

<IntegerArray>
[0, 1, 2]
Length: 3, dtype: Int64

In [289]:
#On ne garde que celle dont le statut est validé = celles DONT PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT' qui sont diff de zero

df_pegass_ben_activite = df_pegass_ben_activite[df_pegass_ben_activite['PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT'] != 0]

In [ ]:
PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT

PEGASS_ACTIVITE_SEANCE_INSCRIPTION_TYPE_ID_FK

In [251]:
df_pegass_activite_merge2

,PEGASS_ACTIVITE_ID_FK,PEGASS_ACTIVITE_SEANCE_ID_FK,PEGASS_ACTIVITE_SEANCE_DATE_DEBUT,PEGASS_ACTIVITE_SEANCE_HEURE_DEBUT,PEGASS_ACTIVITE_SEANCE_DATE_FIN,PEGASS_ACTIVITE_SEANCE_HEURE_FIN,ACTIVITE_SEANCE_EXTERNAL_ID_FK,PEGASS_ACTIVITE_DATE_DEBUT,PEGASS_ACTIVITE_HEURE_DEBUT,PEGASS_ACTIVITE_DATE_FIN,PEGASS_ACTIVITE_HEURE_FIN,PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK,PEGASS_ACTIVITE_STRUCTURE_ORGANISATRICE_ID_FK,ACTIVITE_BENEVOLE_ID_FK,ACTIVITE_BENEVOLE_EXTERNAL_ID_FK,action_id_fk,ACTION_LIBELLE,GROUPE_ACTION_ID_FK,activite_benevole_libelle
0,2199513,2199451,2024-12-31,14:00:00,2025-01-01,05:00:00,None,2024-12-31,14:00:00,2025-01-01,05:00:00,4631,4631,10035,None,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
1,2667236,2667121,2025-01-01,18:15:00,2025-01-01,23:15:00,None,2025-01-01,18:15:00,2025-01-01,23:15:00,392,392,10035,None,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
2,2685656,2685541,2025-01-01,18:15:00,2025-01-01,23:15:00,None,2025-01-01,18:15:00,2025-01-01,23:15:00,1107,1107,11110,None,6,Samu Social maraudes equipes mob. - Operations,2,Maraude de soir
3,2698070,2697945,2024-12-31,18:30:00,2025-01-01,00:30:00,None,2024-12-31,18:30:00,2025-01-01,00:30:00,230,230,10035,None,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
4,2705941,2705816,2025-01-01,19:00:00,2025-01-01,21:15:00,None,2025-01-01,19:00:00,2025-01-01,21:15:00,3888,3888,11110,None,6,Samu Social maraudes equipes mob. - Operations,2,Maraude de soir
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59011,3310622,3310458,2025-12-30,19:00:00,2025-12-30,23:55:00,None,2025-12-30,19:00:00,2025-12-30,23:55:00,100,100,10119,None,21,Urgence et autres operations,1,Urgence et autres operations
59012,3310623,3310459,2025-12-30,08:00:00,2025-12-30,23:55:00,None,2025-12-30,08:00:00,2025-12-30,23:55:00,100,100,10135,None,21,Urgence et autres operations,1,Soutien aux populations - Hebergement d'urgence
59013,3310625,3310461,2025-12-30,18:00:00,2025-12-30,23:55:00,None,2025-12-30,18:00:00,2025-12-30,23:55:00,100,100,10119,None,21,Urgence et autres operations,1,Urgence et autres operations
59014,3356258,3356094,2025-12-30,19:00:00,2025-12-30,23:55:00,None,2025-12-30,19:00:00,2025-12-30,23:55:00,1253,1253,11110,None,6,Samu Social maraudes equipes mob. - Operations,2,Maraude de soir
59015,3371673,3371509,2025-12-02,08:00:00,2025-12-31,23:55:00,None,2025-12-02,08:00:00,2025-12-31,23:55:00,57,57,10035,None,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee

###Calcul des indicateurs NB d'activités menés

In [84]:
def calc_nb_activite_Pegass(df_prep,
                           col_structure="PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK",
                           col_id="ACTIVITE_BENEVOLE_ID_FK",
                           out_structure="n_structure",
                           out_count="Activite_nb_activite_Pegass"):
    df_out = df_prep.groupby(col_structure, as_index=False)[col_id].count()
    df_out.columns = [out_structure, out_count]
    return df_out

In [129]:
def calc_nb_activite_Pegass(
    df_prep,
    col_structure="PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK",
    col_activite="ACTIVITE_BENEVOLE_ID_FK",   # ta colonne "N° activité"
    out_structure="n_structure",
    out_activite="N° activité",
    out_count="nb_activite",
    dropna=False,
    sort=True
):
    """
    Compte le nombre d'occurrences (lignes) par (structure, activité).

    Retourne un DataFrame avec 3 colonnes :
    - out_structure : identifiant structure
    - out_activite  : identifiant / n° activité
    - out_count     : nombre de lignes pour ce couple
    """

    # Groupby sur 2 colonnes = structure + activité
    df_out = (
        df_prep
        .groupby([col_structure, col_activite], dropna=dropna)
        .size()
        .reset_index(name=out_count)
        .rename(columns={
            col_structure: out_structure,
            col_activite: out_activite
        })
    )

    if sort:
        df_out = df_out.sort_values([out_structure, out_count], ascending=[True, False])

    return df_out

In [130]:
nb_activite_Pegass = calc_nb_activite_Pegass(df_pegass_activite_merge2)

In [131]:
nb_activite_Pegass

      n_structure  N° activité  nb_activite
0               1        10119          246
3               1        10137            6
1               1        10125            5
2               1        10134            1
7               5        11110          230
...           ...          ...          ...
1683         4934        10113           35
1684         4934        10119            8
1686         <NA>        10035          431
1687         <NA>        11110           40
1685         <NA>        10032           30

[1688 rows x 3 columns]

In [132]:
#Filtres activités

Activite_maraude =  [10032, 10033, 10034, 10035, 10036, 10037,11110]

Nb_Exercice = [10122, 10123]

NB_operations = [10132, 10133, 10134, 10135, 10136, 10137, 10119, 10125, 10126, 10127, 10128, 10129]

AEO = [10015, 10046, 10047, 11126]

DPS = [10105, 10106, 10108, 10113]


    # Nb_Exercice 10122, 10123,
     #Opération de secours 10125, 10126, 10127, 10128, 10129
    #NB_opérations 10132, 10133, 10134, 10135, 10136, 10137, 10119,

    #Maraude 10032, 10033, 10034, 10035, 10036, 10037, 11110

    # AEO : 10015, 10046, 10047, 11126

In [133]:
#calcul NB Maraude Nb_maraudes_PEGASS
nb_Maraude_Pegass = nb_activite_Pegass[nb_activite_Pegass["N° activité"].isin(Activite_maraude)]
nb_Maraude_Pegass = nb_Maraude_Pegass.rename(columns={"nb_activite": "nb_Maraude_Pegass"})
nb_Maraude_Pegass = nb_Maraude_Pegass.drop(columns=["N° activité"])
nb_Maraude_Pegass1 = nb_Maraude_Pegass.groupby("n_structure", as_index=False)["nb_Maraude_Pegass"].sum()


#Calcul Nb opération PEGASS
nb_operations_Pegass = nb_activite_Pegass[nb_activite_Pegass["N° activité"].isin(NB_operations)]
nb_operations_Pegass = nb_operations_Pegass.rename(columns={"nb_activite": "Dispositifs_d_urgence Nb_operations"})
nb_operations_Pegass = nb_operations_Pegass.drop(columns=["N° activité"])
nb_operations_Pegass1 = nb_operations_Pegass.groupby("n_structure", as_index=False)["Dispositifs_d_urgence Nb_operations"].sum()

#Calcul Nb exercices PEGASS
nb_Exercice_Pegass = nb_activite_Pegass[nb_activite_Pegass["N° activité"].isin(Nb_Exercice)]
nb_Exercice_Pegass = nb_Exercice_Pegass.rename(columns={"nb_activite": "Dispositifs_d_urgence Nb_exercices"})
nb_Exercice_Pegass = nb_Exercice_Pegass.drop(columns=["N° activité"])
nb_Exercice_Pegass1 = nb_Exercice_Pegass.groupby("n_structure", as_index=False)["Dispositifs_d_urgence Nb_exercices"].sum()

In [ ]:
#Agrégation par structure

##Vérification

In [ ]:
#Vérifier pour chacun des 3 indiczateurs que somme de nb_operations_Pegass1 = somme de nb_operations_Pegass

#Vérifier que la somme des 3 indicateurs =

In [134]:
nb_Maraude_Pegass

      n_structure  nb_Maraude_Pegass
7               5                230
4               5                 72
14             10                  1
18             10                  1
20             12                197
...           ...                ...
1663         4677                  3
1678         4884                  2
1686         <NA>                431
1687         <NA>                 40
1685         <NA>                 30

[445 rows x 2 columns]

In [106]:
nb_Maraude_Pegass1

     n_structure  nb_Maraude_Pegass
0              5                302
1             10                  2
2             12                205
3             13                  2
4             23                 41
..           ...                ...
248         4642                 43
249         4674                  7
250         4676                109
251         4677                  3
252         4884                  2

[253 rows x 2 columns]

In [104]:
nb_Exercice_Pegass

      n_structure  Dispositifs_d_urgence Nb_exercices
6               5                                   1
10              7                                   1
23             12                                   1
33             17                                   1
40             18                                   1
...           ...                                 ...
1606         4396                                   1
1607         4396                                   1
1628         4631                                   6
1629         4631                                   2
1653         4649                                   2

[123 rows x 2 columns]

In [206]:
#A conserver pour les merge mais à mettre plus haut

ref_structure2 = ref_structure1[["n_structure", "DT_de_rattachement"]]

In [207]:
# 1) merge avec ref struct et structure de ratachement
nb_Maraude_Pegass1 = pd.merge(nb_Maraude_Pegass1, ref_structure2, on="n_structure", how="right")

In [210]:
nb_Maraude_Pegass1

     n_structure  nb_Maraude_Pegass           DT_de_rattachement
0             10                2.0  10 - DT DES ALPES MARITIMES
1            170                NaN  10 - DT DES ALPES MARITIMES
2            171                NaN  10 - DT DES ALPES MARITIMES
3            172                NaN  10 - DT DES ALPES MARITIMES
4            173                NaN  10 - DT DES ALPES MARITIMES
..           ...                ...                          ...
684          904               97.0             80 - DT DE PARIS
685          905              112.0             80 - DT DE PARIS
686          906              156.0             80 - DT DE PARIS
687          907               20.0             80 - DT DE PARIS
688          908               52.0             80 - DT DE PARIS

[689 rows x 3 columns]

In [211]:
#Création d'une fonction action menée


def add_statut_action(
    df,
    col_nb,
    out_col="activité menée",
    label_yes="Action menée",
    label_no="Action non menée",
    treat_zero_as_no=True,
    copy=True
):
    """
    Ajoute une colonne de statut basée sur une colonne de comptage.

    - Si col_nb contient une valeur numérique (et optionnellement != 0), => label_yes
    - Sinon (NaN / vide / non numérique) => label_no

    Params
    ------
    df : pd.DataFrame
    col_nb : str
        Nom de la colonne à tester (comptage / nb / etc.)
    out_col : str
        Nom de la colonne créée
    treat_zero_as_no : bool
        True => 0 => label_no ; False => 0 => label_yes
    copy : bool
        True => retourne une copie ; False => modifie df en place
    """
    df_out = df.copy() if copy else df

    nb = pd.to_numeric(df_out[col_nb], errors="coerce")

    if treat_zero_as_no:
        mask_yes = nb.notna() & (nb != 0)
    else:
        mask_yes = nb.notna()

    df_out[out_col] = np.where(mask_yes, label_yes, label_no)
    return df_out

In [219]:
#Calcul Action Menée et non menée pour chaque activités

nb_Maraude_Pegass1 = add_statut_action(nb_Maraude_Pegass1, col_nb="nb_Maraude_Pegass", out_col="Maraudes realisees", treat_zero_as_no=True)

nb_Exercice_Pegass1 = add_statut_action(nb_Exercice_Pegass1, col_nb="Dispositifs_d_urgence Nb_exercices", out_col="exercices_d_urgence realises", treat_zero_as_no=True)

nb_operations_Pegass1 = add_statut_action(nb_operations_Pegass1, col_nb="Dispositifs_d_urgence Nb_operations", out_col="Operations_d_urgence realisees", treat_zero_as_no=True)

In [225]:
nb_Maraude_Pegass1

,n_structure,nb_Maraude_Pegass,DT_de_rattachement,Maraude réalisée
0,10,2.0,10 - DT DES ALPES MARITIMES,Action menée
1,170,NaN,10 - DT DES ALPES MARITIMES,Action non menée
2,171,NaN,10 - DT DES ALPES MARITIMES,Action non menée
3,172,NaN,10 - DT DES ALPES MARITIMES,Action non menée
4,173,NaN,10 - DT DES ALPES MARITIMES,Action non menée
...,...,...,...,...
684,904,97.0,80 - DT DE PARIS,Action menée
685,905,112.0,80 - DT DE PARIS,Action menée
686,906,156.0,80 - DT DE PARIS,Action menée
687,907,20.0,80 - DT DE PARIS,Action menée
688,908,52.0,80 - DT DE PARIS,Action menée

In [221]:
nb_Exercice_Pegass1

,n_structure,Dispositifs_d_urgence Nb_exercices,exercices_d_urgence realises
0,5,1,Action menée
1,7,1,Action menée
2,12,1,Action menée
3,17,1,Action menée
4,18,1,Action menée
...,...,...,...
90,4394,1,Action menée
91,4395,1,Action menée
92,4396,2,Action menée
93,4631,8,Action menée
94,4649,2,Action menée

In [222]:
nb_operations_Pegass1

,n_structure,Dispositifs_d_urgence Nb_operations,Operations_d_urgence realisees
0,1,258,Action menée
1,6,2,Action menée
2,7,2,Action menée
3,9,1,Action menée
4,10,2,Action menée
...,...,...,...
244,4674,1,Action menée
245,4693,1,Action menée
246,4873,1,Action menée
247,4928,48,Action menée
248,4934,8,Action menée

In [238]:
#Merge global des 3 indicateurs

Indics_pegass = pd.merge(nb_Maraude_Pegass1, nb_operations_Pegass1, on="n_structure", how="left")
Indics_pegass_struct = pd.merge(Indics_pegass, nb_Exercice_Pegass1 , on="n_structure", how="left")

In [239]:
Indics_pegass_struct

,n_structure,nb_Maraude_Pegass,DT_de_rattachement,Maraude réalisée,Dispositifs_d_urgence Nb_operations,Operations_d_urgence realisees,Dispositifs_d_urgence Nb_exercices,exercices_d_urgence realises
0,10,2.0,10 - DT DES ALPES MARITIMES,Action menée,2.0,Action menée,NaN,NaN
1,170,NaN,10 - DT DES ALPES MARITIMES,Action non menée,NaN,NaN,NaN,NaN
2,171,NaN,10 - DT DES ALPES MARITIMES,Action non menée,NaN,NaN,NaN,NaN
3,172,NaN,10 - DT DES ALPES MARITIMES,Action non menée,NaN,NaN,NaN,NaN
4,173,NaN,10 - DT DES ALPES MARITIMES,Action non menée,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
684,904,97.0,80 - DT DE PARIS,Action menée,1.0,Action menée,NaN,NaN
685,905,112.0,80 - DT DE PARIS,Action menée,NaN,NaN,NaN,NaN
686,906,156.0,80 - DT DE PARIS,Action menée,NaN,NaN,NaN,NaN
687,907,20.0,80 - DT DE PARIS,Action menée,NaN,NaN,NaN,NaN
688,908,52.0,80 - DT DE PARIS,Action menée,1.0,Action menée,NaN,NaN

In [62]:
df_pegass_activite_merge2.columns

Index(['PEGASS_ACTIVITE_ID_FK', 'PEGASS_ACTIVITE_SEANCE_ID_FK',
       'PEGASS_ACTIVITE_SEANCE_DATE_DEBUT',
       'PEGASS_ACTIVITE_SEANCE_HEURE_DEBUT', 'PEGASS_ACTIVITE_SEANCE_DATE_FIN',
       'PEGASS_ACTIVITE_SEANCE_HEURE_FIN', 'ACTIVITE_SEANCE_EXTERNAL_ID_FK',
       'PEGASS_ACTIVITE_DATE_DEBUT', 'PEGASS_ACTIVITE_HEURE_DEBUT',
       'PEGASS_ACTIVITE_DATE_FIN', 'PEGASS_ACTIVITE_HEURE_FIN',
       'PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK',
       'PEGASS_ACTIVITE_STRUCTURE_ORGANISATRICE_ID_FK',
       'ACTIVITE_BENEVOLE_ID_FK', 'ACTIVITE_BENEVOLE_EXTERNAL_ID_FK',
       'action_id_fk', 'ACTION_LIBELLE', 'GROUPE_ACTION_ID_FK',
       'activite_benevole_libelle'],
      dtype='object')

In [ ]:
df_ref_action_activite_filtre

In [ ]:
df_ref_activite_benevole['activite_benevole_libelle'].unique()

In [ ]:
df_pegass_activite

In [ ]:
df_pegass_activite.columns

In [ ]:
df_pegass_activite.dtypes

In [ ]:
df_pegass_activite_seance

In [ ]:
df_pegass_activite_seance.columns

In [ ]:
df_pegass_activite_seance.dtypes

In [ ]:
df_pegass_activite_seance_inscription

In [ ]:
df_pegass_activite_seance_inscription.columns

In [ ]:
df_pegass_activite_seance_inscription.dtypes

#AUTHENTIFICATION

In [ ]:
# Etape 0 : Préparation de l'environnement

CREDENTIALS_JSON = """
{
  "type": "service_account",
  "project_id": "alexandrevalent",
  "private_key_id": "dba39c84ba4135ce5ede6479a186ad8cde499dee",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvGU4ZJFrBwCBb\nu8s4aPA5bQTOKDkPZEVdNyY//RneR6RC9JPrcbfVfIUaQU7A036sfdhDGFKJbw20\nTZ55fafcH9yCMiUO+Nzek0eogON4TXrXsh8UFtdw8BOuaVkFitU5yg8kFhTnEZtd\ntPfZHW3Aqhd/aDoTOBNgRuF/hVTKQ2ytbCbE77fL2/pz9kvpZ2Zrz3u1lmksSJls\nHIolNwX9R05YqmrkpZ/TMAULFk4bT0VRQng5pmN9AeB61eJLWhlLaEdeu79NWV4B\n7tZd6RzzTFors804aJkmXHM63VRtvGD0UlR0O7w1QlI3ymUxpy5hrjbz6n9bmpMI\nfebvydLnAgMBAAECggEADipn7RTJ2t7mP0WkHT4wIRU2zE7ovtwH2JC7oXWigB8f\npOMQjH24t6bJReR+sI7rspzDwDnZg5DedPXKml2WFPLm7gmMgfeUNtWHeJRk0rjB\n9W1NolxutY5WqUeQkig3M+Oq8epvano8LYqUepYs6OdZ207dU+y3dJSHbb+lqm9D\ntQZR2oBj7W1iZ8fJ+SQLSjU5BztS1CvWuayRd/tLd9Spp0NUn5uQFTKwel9Gazmz\n28IsPPm6SudplFhaGd4kCPvhcg0jGEKe61VYdgHoBzp+EXRWXUvQ+SbMafXtMvoB\nLoUH4X3creKzJQKXnjlDpAzRHMYhJTvHinHXaggdcQKBgQDcJszFOECfSovXFZNq\nMyQOWbesyDb2OQhJLFZCD2QraZm3jPaIPeMfFkmFAumcVal6EzpR5IE8g9jBuLo+\ng6j3NTo5jbGO9WEn4361yEotb+S8t3/DTHvWqXBK7HdUB/KHlyGtctm8yErdMZQB\nvzo03aTwwStNTeFG8GzT1Nd7JQKBgQDLnHIMbx9iAG3K21XCq0Dot2Q63hklJC26\nsJlrTkdXMOIlhpwJ6LTOJe2paHbR56IrKOHQCuLxQFhRd8Eidz1ahjO7D8fKr/TG\nS8/V32FrpONyxhKinLsccSb86S3vvpKCI265z5EEjk/1qnx3TOo6oqA/2DQLv0Q4\nYinmNSOeGwKBgHGjYY3n9IuE6lwy2e42ycTSkNoSWzSLyfgjd78PvNAf6WXy0IsR\nDvzL/1U2ZKn7GclWxYLiJce78xZEKXb9dSluA0kUF/RIO0dgydZBtfBwUq0LN1rz\nTvVGbx1tpEbu90UAQTUMFNK6vNIitliUghIp2usfex+jNMbuce6Cblw1AoGBAKDH\n1gtZiFeT7R7d2jfRkXzyrBQMI6D/k5izMULZ2l3QfROS2w68EmIi8yvuEL2qApXA\nP6hPoGtPGy6huQHlVK5yANF7IZI9JbWcUe8Z6MzetLiCDl8YEmzgMSBPZXXGb9yR\n7DKP5HzLf/qG+KggNWm913ry2A5ap506bsmZNpn3AoGBAM6vvI9tb+AcNfd4ewmY\nAWSb4GLliRTaBIGHYmotfyBEBWpXZq2/0JG32RRf3rYUJWWn/r7K+zrRUqeMwlD+\nz7GuSU+OaSDzYj7fwDyuxOwTJMLrh+AkKbUYBsMF7YH1qIRjBjKNdj1LOznASQMe\nu1E4sNa9RRRujbQw4AEP3Xjl\n-----END PRIVATE KEY-----\n",
  "client_email": "crf-slidemanager@alexandrevalent.iam.gserviceaccount.com",
  "client_id": "101959630014487618959",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/crf-slidemanager%40alexandrevalent.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly']


# Authentification
credentials = service_account.Credentials.from_service_account_info(json.loads(CREDENTIALS_JSON, strict=False), scopes=SCOPES)

# Initialisation des services
slides_service = build('slides', 'v1', credentials=credentials)
drive_service = build('drive', 'v3', credentials=credentials)
gspread_client  = gspread.authorize(credentials)

# Variables globales

In [ ]:
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

# CHARGEMENT DE TOUTES LES DONNEES PAR TABLE

# 0. Ref_structure

In [ ]:
df_ref_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw/').worksheet('Feuille 1'))

In [ ]:
df_ref_structure = renommer_par_nom_table(df_ref_structure, "AS_Informations_structures", mapping_df)
df_ref_structure['n_structure'] = df_ref_structure['n_structure'].astype(int).astype(str)
df_ref_structure.head()

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,Structure_de_rattachement,Rattachements_successifs,DT_de_rattachement,lon,lat
0,2615,ANTENNE LOCALE - AL,AL DE DELLE,90100.0,90033,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",90,2010-02-08 00:00:00,NaT,95 - DT DU TERRITOIRE DE BELFORT,AL 2615,95 - DT DU TERRITOIRE DE BELFORT,7.000705,47.506725
1,2669,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43220.0,43087,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2669,48 - DT DE LA HAUTE LOIRE,4.346423,45.214392
2,2670,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43600.0,43224,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2670,48 - DT DE LA HAUTE LOIRE,4.235474,45.242445
3,2671,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43300.0,43112,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2671,48 - DT DE LA HAUTE LOIRE,3.495645,45.098285
4,2672,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43000.0,43157,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2672,48 - DT DE LA HAUTE LOIRE,3.879748,45.044677

In [ ]:
df_ref_structure_DT = df_ref_structure[df_ref_structure['nom_structure'].str.contains('DT')].astype(str)

# 1. PEGASS

In [ ]:
# EXEMPLE :  Charger le DataFrame
# spreadsheet = gspread_client.open_by_url("https://docs.google.com/spreadsheets/d/1WEoWR3dnhy7NL5ISoD6o-58krsttfHkiqaJz30Vvg74/")
# worksheet = spreadsheet.worksheet("Feuille 1")
# df_raw = get_as_dataframe(worksheet)

## 1.1. rattachement_court

In [ ]:
rattachement_court = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU/edit?usp=sharing').worksheet('Feuille 1'))

## 1.2. Activité_benevole ref activité

In [ ]:
Ref_activité_benevole = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1rf1gXTylNEHEt72UfwZO62gIfgzf9eY8lPqhXLJ5hs8/edit').worksheet('Feuille 1'))

## 1.3. Pegass_activite / Activite

In [ ]:
Pegass_activite = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13Ygh1goryIgp2UCh19tKaTv3AWkfsSMInuS8-VMbmeU/edit').worksheet('Feuille 1'))

## 1.4. PegassInscription / Inscription

In [ ]:
Pegass_inscription = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1wCYPGwDVKZC6BBuMnOc7kB98agof5IMkdn9W7xn5UUg/edit').worksheet('Feuille 1'))

## 1.5. PREPARATION DE LA BASE DE DONNEES

In [ ]:
Pegass_inscription, Pegass_activite, Ref_activité_benevole = clean_pegass(Pegass_inscription,Pegass_activite,Ref_activité_benevole, mapping_df)

# 2. GAIA

## 2.1. GAIA_contact

In [ ]:
GAIA_contact = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1k4-nMZqUulcZBPMplZLWHcvSTvzISqF9uMnlITdikmI/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.2. GAIA_action

In [ ]:
GAIA_action = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1XvfYhne_YxMBVfgkDUzKhhOle9-bmEP3j0gpBYZsKuo/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.3. GAIA_rattachement_action

In [ ]:
GAIA_rattachement_action = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1vtC3hpxh6RIcmhMjifVFoi169uhdi0f9fpKXP9FqEd8/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.4 GAIA_act_str

In [ ]:
GAIA_act_str = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1PrK18aa8dllTjXOEyPHXMEgqP4gm1ZeJdnCmlUG78EA/edit?usp=drive_link').worksheet('Feuille 1'))

In [ ]:
GAIA_act_str.head()

## 2.5. GAIA_structure

In [ ]:
GAIA_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1forcw_rC0WCcwu6K8-AUhm1sur9pp5XZX_YTCKaBA6g/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.6. Preparation de la base

### 2.6.1. Renommer les variables

In [ ]:
GAIA_action = renommer_par_nom_table(GAIA_action, "GAIA_action", mapping_df)
GAIA_rattachement_action = renommer_par_nom_table(GAIA_rattachement_action, "GAIA_rattachement_action", mapping_df)
GAIA_contact = renommer_par_nom_table(GAIA_contact, "GAIA_contact", mapping_df)
GAIA_structure = renommer_par_nom_table(GAIA_structure, "GAIA_structure", mapping_df)
GAIA_act_str = renommer_par_nom_table(GAIA_act_str, "GAIA_act_str", mapping_df)

In [ ]:
GAIA_structure.head()

# 3. NOMINATION

## 3.1. NOMINATION_nomination

In [ ]:
NOMINATION_nomination = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ywCGFgW5eLONMNK64o4NZrQQzasqfEGnnQL6LfDXbbM/edit?gid=614834196').worksheet('NOMINATION_nomination'))

In [ ]:
NOMINATION_nomination.head()

## 3.2 NOMINATION_attribution_nomination

In [ ]:
NOMINATION_attribution_nomination = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1BzCcfO1NLM5oMmBD1cBELIuvBvVjucsK6Wm4zPTaO-Q/').worksheet('NOMINATION_attribution_nomination'))

In [ ]:
NOMINATION_attribution_nomination.head()

## 3.3. Préparation de la base

### 3.3.1. Renommer les variables

In [ ]:
NOMINATION_nomination = renommer_par_nom_table(NOMINATION_nomination, "nomination", mapping_df)
NOMINATION_attribution_nomination = renommer_par_nom_table(NOMINATION_attribution_nomination, "attribution_nomination", mapping_df)

# 4. IMPACT

## 4.1 Impact_indicateurs

In [ ]:
IMPACT_indicateurs = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.2 Impact_indicateur_value

In [ ]:
IMPACT_indicateur_value = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.3 Impact_donnees_activite

In [ ]:
IMPACT_donnees_activite = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.4 Impact_abstract_donnees_activite

In [ ]:
IMPACT_abstract_donnees_activite = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.5. Preparation de la base

### 4.5.1. Renommer les variables

In [ ]:
IMPACT_indicateurs = renommer_par_nom_table(IMPACT_indicateurs, "IMPACT_indicateurs", mapping_df)
IMPACT_indicateur_value = renommer_par_nom_table(IMPACT_indicateur_value, "IMPACT_indicateur_value", mapping_df)
IMPACT_donnees_activite = renommer_par_nom_table(IMPACT_donnees_activite, "IMPACT_donnees_activite", mapping_df)
IMPACT_abstract_donnees_activite = renommer_par_nom_table(IMPACT_abstract_donnees_activite, "IMPACT_abstract_donnees_activite", mapping_df)

# 5. Données financières

In [ ]:
financier = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c')

In [ ]:
dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute, dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute = import_clean_donnees_financieres(financier,df_ref_structure,mapping_df)

# 6. Mobilité

In [ ]:
mobilite = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1dvxT58WR-FqdT-4r-A9ca4vaA9FG7IXHJJaTbnjio8A/')

In [ ]:
df_mobilite = filtres_mobilite(mobilite,mapping_df)

# 7. Données manuelles

## 7.1 OCR

In [ ]:
df_OCR = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ccRoyPycFDwvQvacvmHjfE87LtnlzUgtoRbITkC0pVQ/').worksheet('Feuille 1'))

## 7.2 PST

In [ ]:
df_PST = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1yifNna4Hsn5RihkRg50g9h1yKjuRjfolrjsWonEHnrQ').worksheet('Données'))

## 7.3 Déclenchements

In [ ]:
df_declenchement = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1y9jehT5fStcEWCF0pxAP7BdiI62VY3JM_hQzFftbcZA').worksheet('Feuille 1'))

## 7.4 Redcall

In [ ]:
df_redcall = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1EQzq0K8RY2Liyq-jtggX0bTlnOk9cwUTmf4t6c5_CiI').worksheet('structure-stats_2025-01-01_2025-12-31_min-1 (1)'))

## 7.5 CHAI CHU CMCC

In [ ]:
df_CAICHUCMCC = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/12nZY2leRCMn71NGAEUUtA0Pes598gOfeufDStxSCcnY').worksheet('Toutes données'))

## 7.6 Conventions

In [ ]:
df_conventions = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1OYSSkUhWwVpWne9EygH1EEz8EJnFjSeAOEpQQe9utiM').worksheet('Feuille 1'))

## 7.7 Préparation

In [ ]:
df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions = clean_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement, df_redcall, df_CAICHUCMCC, df_conventions)

/content/Code-PAT/scripts_data/manuelles.py:103: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['Grand Total', 'Exercice']] = df[['Grand Total', 'Exercice']].fillna(0)
/content/Code-PAT/scripts_data/manuelles.py:156: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Département"] = df["Département"].str.replace(
/content/Code-PAT/scripts_data/manuelles.py:192: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Departement"] = df["Departement"].str.replace(
/content/Code-PAT/scripts_data/manuelles.py:213: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[colonnes_oui_non] = df[colonnes_oui_non].applymap(
/content/Code-PAT/scripts_data/manuelles.py:213: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[colonnes_oui_non] = df[colonnes_oui_non].applymap(
/content/Code-PAT/scripts_data/manuelles.py:217: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Dispositifs_d_urgence Nb_conventions_operateurs'] = (

# FUSION DES TABLES

## 1. Fusion PEGASS activité, inscription, ref_activité_bénévole, rattachement_court

### 1.1 Filtres généraux à appliquer

In [ ]:
df2 = fusion_pegass(Pegass_inscription, Pegass_activite, Ref_activité_benevole)

## 2. Fusion GAIA rattachement_action, action, act_str, structure

### 2.1. Filtres généraux à appliquer

In [ ]:
#FTILRE SUR ANNEE NULLE OU FIN EN 2025

# Vérification que la colonne est au format datetime
GAIA_act_str['date_fin_activite_struct'] = pd.to_datetime(GAIA_act_str['date_fin_activite_struct'], errors='coerce')

# Filtrage : date nulle ou année = 2025
GAIA_act_str = GAIA_act_str[
    GAIA_act_str['date_fin_activite_struct'].isna() | (GAIA_act_str['date_fin_activite_struct'].dt.year == 2025)
]

### 2.2. Fusion des tables

In [ ]:
# left = pd.merge(df1, df2, on="id", how="left")

# 1) Join avec action sur act_id
df_GAIA = pd.merge(GAIA_rattachement_action, GAIA_action, on="n_action_ben", how="left")

# 2) Join avec rattachement_action sur act_id + str_id
df_GAIA = pd.merge(df_GAIA, GAIA_act_str, on="n_action_ben", how="left")

# 3) Join avec contact sur cob_idrp
df_GAIA = pd.merge(df_GAIA, GAIA_structure, on="id_structure", how="left")

# df final disponible dans df_GAIA
df_GAIA.head()

## 3. Fusion NOMINATION nomination, attribution_nomination

### 3.1. Filtres généraux à appliquer

In [ ]:
#FTILRE SUR ANNEE NULLE OU FIN EN 2025

# Vérification que la colonne est au format datetime
NOMINATION_attribution_nomination['date_fin_nomination'] = pd.to_datetime(NOMINATION_attribution_nomination['date_fin_nomination'], errors='coerce')
NOMINATION_attribution_nomination['date_debut_nomination'] = pd.to_datetime(NOMINATION_attribution_nomination['date_debut_nomination'], errors='coerce')

# Filtrage : date nulle ou année = 2025
NOMINATION_attribution_nomination = NOMINATION_attribution_nomination[
    NOMINATION_attribution_nomination['date_fin_nomination'].isna() | (NOMINATION_attribution_nomination['date_fin_nomination'].dt.year == 2025)
]

### 3.2. Fusion des tables

In [ ]:
# left join (tous les id de df1, et ce qu'on trouve dans df2)
# left = pd.merge(df1, df2, on="id", how="left")

df_NOMINATION = pd.merge(NOMINATION_nomination, NOMINATION_attribution_nomination,on="nomination_id", how="left") #VERIFIER LA FOREIGN KEY!

## 4. Fusion IMPACT indicateurs, indicateurs_value, donnees_activite, abstract_donnes_activite

### 4.1. Filtres généraux à appliquer

In [ ]:
#FTILRE SUR ANNEE 2025

# Vérification que la colonne est au format datetime
IMPACT_donnees_activite['date_fin_activite'] = pd.to_datetime(IMPACT_donnees_activite['date_fin_activite'], errors='coerce')
IMPACT_donnees_activite['date_debut_activite'] = pd.to_datetime(IMPACT_donnees_activite['date_debut_activite'], errors='coerce')

# Filtrage : date nulle ou année = 2025
IMPACT_donnees_activite = IMPACT_donnees_activite[ (IMPACT_donnees_activite['date_debut_activite'].dt.year == 2025)]

### 4.2. Fusion des tables

In [ ]:
# left = pd.merge(df1, df2, on="id", how="left")

# 1) Join avec action sur act_id
df_IMPACT = pd.merge(IMPACT_indicateur_value, IMPACT_indicateurs, on="n_indicateurs", how="left")

# 2) Join avec rattachement_action sur act_id + str_id
df_IMPACT = pd.merge(df_IMPACT, IMPACT_donnees_activite, on="id_activite", how="left")

# 3) Join avec contact sur cob_idrp
df_IMPACT = pd.merge(df_IMPACT, IMPACT_abstract_donnees_activite, on="id_activite", how="left")

# df final disponible dans df_GAIA
df_IMPACT.head()

## 5. Fusion Données financières

### 5.1 Fusion des tables

In [ ]:
df_financier_DT, df_financier_DT_UL = fusion_donnees_financieres(dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute,dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute)

### 5.2 Vérifications

In [ ]:
verifier_n_dept(df_financier_DT,df_ref_structure)

 ✅ Aucun doublon
 ✅ Pas de département manquant

In [ ]:
verifier_colonne_structure(df_financier_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

# Calcul des indicateurs

# Indicateurs PEGASS

- Nombre de bénévoles par activité benevole

## Nombre de bénévoles par activité benevole

In [ ]:
 Nb_benevoles_distincts, Nb_benevoles_Distribution_alimentaire, Nb_benevoles_Distribution_alimentaire1, Nb_benevoles_Distribution_alimentaire2, Nb_benevoles_Distribution_alimentaire3, Nb_benevoles_Distribution_alimentaire4 = indicateurs_pegass(df2)

# Indicateurs GAIA

## Nombre de bénévoles déclarés sur une activitée

### 10.1. Calcul nb de volontaires de l'urgence

In [ ]:
# Filtre sur le libelle approprié
df_urgence = df_GAIA[df_GAIA["libelle_action_ben"] == "Urgences et autres opérations"]

In [ ]:
# On compte le nb de volontaires de l'urgence
NbBeneDecla_GAIA = (df_urgence.groupby('n_structure_x')['id_gaia'].nunique())

In [ ]:
NbBeneDecla_GAIA.head()

Series([], Name: id_gaia, dtype: int64)

## 3. RTAEO & RLAEO

In [ ]:
# Filtre sur le libelle approprié
referents_AEO = df_NOMINATION[df_NOMINATION["libelle_nomination"] == "RTAEO"]

# Filtre sur le libelle approprié
referents_OCR = df_NOMINATION[df_NOMINATION["libelle_nomination"] == "RTOCR"]

In [ ]:
# On compte le nb de RTAEO & RLAEO
referents_AEO = (referents_AEO.groupby('structure_id')['libelle_nomination'].nunique())

In [ ]:
referents_AEO

Series([], Name: libelle_nomination, dtype: int64)

In [ ]:
# DF par mois
annee = 2025

# Mois de l'année
mois = pd.date_range(
    start=f"{annee}-01-01",
    end=f"{annee}-12-01",
    freq="MS"
)

resultats = []

for m in mois:
    debut_mois = m
    fin_mois = m + pd.offsets.MonthEnd(1)

    actifs = referents_AEO[
        (referents_AEO["date_debut_nomination"] <= fin_mois) &
        (referents_AEO["date_fin_nomination"] >= debut_mois)
    ]

    comptage = (
        actifs
        .groupby("structure")
        .size()
        .reset_index(name="nb")
    )

    comptage["mois"] = m.strftime("%Y-%m")
    resultats.append(comptage)

# Concaténation
referents_AEO_mois = pd.concat(resultats)

# Tableau croisé
referents_AEO_mois = referents_AEO_mois.pivot(
    index="structure_id",
    columns="mois",
    values="nb"
).fillna(0).astype(int)

print(pivot)

## 4. RTOCR & RLOCR

In [ ]:
# On compte le nb de RTAEO & RLAeo
referents_OCR = (referents_OCR.groupby('structure_id')['libelle_nomination'].nunique())

KeyError: 'Column not found: nom'

In [ ]:
# DF par mois
annee = 2025

# Mois de l'année
mois = pd.date_range(
    start=f"{annee}-01-01",
    end=f"{annee}-12-01",
    freq="MS"
)

resultats = []

for m in mois:
    debut_mois = m
    fin_mois = m + pd.offsets.MonthEnd(1)

    actifs = referents_OCR[
        (referents_OCR["date_debut_nomination"] <= fin_mois) &
        (referents_OCR["date_fin_nomination"] >= debut_mois)
    ]

    comptage = (
        actifs
        .groupby("structure")
        .size()
        .reset_index(name="nb")
    )

    comptage["mois"] = m.strftime("%Y-%m")
    resultats.append(comptage)

# Concaténation
referents_OCR_mois = pd.concat(resultats)

# Tableau croisé
referents_OCR_mois = referents_OCR_mois.pivot(
    index="structure_id",
    columns="mois",
    values="nb"
).fillna(0).astype(int)

print(pivot)

##  Nombre d'agréments territoriaux (Dispos d'urgence)

## Nombre de personnes prises en charge (Dispos d'urgence)

## Mobilité


Indicateurs qui nécessitent seulement les données mobilité :

- Nb de structures menant une activité AEO/AAD mobile
- Nombre de personnes accompagnées par des dispositifs AEO/AAD mobiles
<br>
Indicateurs qui nécessitent une fusion avec données AEO/AAD :

- Nombre de bénévoles impliqués dans les activités AEO ou AAD
- Nombre de bénévoles impliqués dans les activités AEO ou AAD

In [ ]:
df_mobilite_DT = indicateurs_mobilite(df_mobilite, df_ref_structure, 'DT_de_rattachement')
df_mobilite_DT_UL = indicateurs_mobilite(df_mobilite, df_ref_structure, 'n_structure')

In [ ]:
verifier_colonne_structure(df_mobilite_DT, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [ ]:
verifier_colonne_structure(df_mobilite_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## Données manuelles

In [ ]:
df_OCR_Nb_deployees, df_Dispositifs_d_urgence_PST, df_declenchement3, df_redcall2, df_CAICHUCMCC_VF, df_conventions2 = indicateurs_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions, df_ref_structure)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [ ]:
verifier_colonne_structure(df_OCR_Nb_deployees, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Dispositifs_d_urgence_PST, "n_structure", df_ref_structure)
verifier_colonne_structure(df_declenchement3, "n_structure", df_ref_structure)
verifier_colonne_structure(df_redcall2, "n_structure", df_ref_structure)
verifier_colonne_structure(df_CAICHUCMCC_VF, "n_structure", df_ref_structure)
verifier_colonne_structure(df_conventions2, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 1 code(s) non trouvés dans le référentiel : [47]

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 1 code(s) non trouvés dans le référentiel : [47]

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 761 code(s) non trouvés dans le référentiel : ['1.0', '10.0', '1000.0', '1001.0', '1002.0', '1004.0', '1005.0', '1007.0', '1008.0', '101.0', '1010.0', '1011.0', '1012.0', '1013.0', '1014.0', '1015.0', '1016.0', '1017.0', '1018.0', '1019.0', '1020.0', '1021.0', '1022.0', '1023.0', '1024.0', '1025.0', '1026.0', '1027.0', '1028.0', '1029.0', '1030.0', '1031.0', '1032.0', '1033.0', '1034.0', '1035.0', '1036.0', '1037.0', '1038.0', '1039.0', '1040.0', '1041.0', '1042.0', '1044.0', '1049.0', '105.0', '1050.0', '1051.0', '1052.0', '1053.0', '1054.0', '1055.0', '1056.0', '1058.0', '1059.0', '1060.0', '1061.0', '1062.0', '1063.0', '1064.0', '1065.0', '1066.0', '1067.0', '1068.0', '1069.0', '107.0', '1070.0', '1071.0', '1072.0', '1073.0', '1074.0', '1076.0', '1078.0', '1079.0', '108.0', '1080.0', '1081.0', '1083.0', '1084.0', '1085.0', '1086.0', '1087.0', '1089.0', '109.0', '1090.0', '1091.0', '1092.0', '1093.0', '1094.0', '1095.0', '1096.0', '1097.0', '1098.0', '1099.0', '110.0', '1100.0', '1101.0', '1102.0', '1103.0', '1104.0', '1105.0', '1106.0', '1107.0', '1108.0', '1109.0', '111.0', '1110.0', '1111.0', '1112.0', '1113.0', '1114.0', '1115.0', '1116.0', '1117.0', '1118.0', '1119.0', '112.0', '1120.0', '1121.0', '1122.0', '1123.0', '1124.0', '1126.0', '1128.0', '1129.0', '113.0', '1130.0', '1134.0', '1135.0', '1137.0', '1138.0', '1139.0', '114.0', '1141.0', '1142.0', '1143.0', '1144.0', '1145.0', '1146.0', '1147.0', '1148.0', '1149.0', '115.0', '1150.0', '1151.0', '1152.0', '1153.0', '1154.0', '1155.0', '1156.0', '1158.0', '1159.0', '116.0', '1160.0', '1161.0', '1162.0', '1163.0', '1164.0', '1165.0', '1166.0', '1167.0', '1168.0', '117.0', '1173.0', '1174.0', '1176.0', '1177.0', '1178.0', '1179.0', '118.0', '1180.0', '1181.0', '1183.0', '1184.0', '1185.0', '1187.0', '1188.0', '1189.0', '119.0', '1195.0', '1199.0', '12.0', '1200.0', '1201.0', '1202.0', '1203.0', '1207.0', '1208.0', '121.0', '1219.0', '122.0', '1221.0', '1222.0', '1223.0', '1226.0', '123.0', '1234.0', '1235.0', '1236.0', '1237.0', '1239.0', '124.0', '1240.0', '1241.0', '125.0', '126.0', '127.0', '1287.0', '129.0', '130.0', '1309.0', '131.0', '1310.0', '1315.0', '1317.0', '133.0', '1332.0', '1333.0', '1334.0', '1335.0', '1338.0', '1340.0', '1344.0', '1348.0', '1350.0', '1351.0', '1353.0', '1357.0', '1358.0', '1359.0', '1361.0', '1363.0', '1364.0', '1367.0', '138.0', '139.0', '14.0', '140.0', '141.0', '142.0', '143.0', '144.0', '145.0', '146.0', '147.0', '149.0', '15.0', '150.0', '152.0', '153.0', '155.0', '156.0', '157.0', '158.0', '159.0', '16.0', '160.0', '161.0', '162.0', '163.0', '164.0', '165.0', '166.0', '167.0', '168.0', '169.0', '170.0', '171.0', '172.0', '173.0', '174.0', '175.0', '178.0', '179.0', '180.0', '181.0', '182.0', '184.0', '185.0', '186.0', '188.0', '189.0', '19.0', '190.0', '191.0', '192.0', '193.0', '194.0', '195.0', '196.0', '197.0', '198.0', '199.0', '2.0', '20.0', '200.0', '201.0', '202.0', '203.0', '204.0', '205.0', '206.0', '207.0', '208.0', '21.0', '210.0', '211.0', '212.0', '213.0', '214.0', '215.0', '216.0', '217.0', '218.0', '219.0', '22.0', '220.0', '221.0', '223.0', '224.0', '226.0', '227.0', '23.0', '230.0', '231.0', '232.0', '234.0', '235.0', '236.0', '24.0', '26.0', '268.0', '269.0', '27.0', '28.0', '285.0', '29.0', '3.0', '30.0', '305.0', '31.0', '311.0', '312.0', '313.0', '314.0', '316.0', '317.0', '318.0', '319.0', '32.0', '320.0', '321.0', '322.0', '323.0', '324.0', '326.0', '327.0', '328.0', '33.0', '330.0', '334.0', '335.0', '336.0', '337.0', '338.0', '339.0', '340.0', '341.0', '344.0', '345.0', '346.0', '347.0', '349.0', '350.0', '351.0', '352.0', '353.0', '354.0', '355.0', '356.0', '359.0', '362.0', '363.0', '364.0', '365.0', '366.0', '367.0', '368.0', '369.0', '37.0', '370.0', '372.0', '373.0', '374.0', '375.0', '376.0', '377.0', '378.0', '379.0', '380.0', '382.0', '383.0', '384.0', '386.0', '388.0', '389.0', '39.0', '390.0', '391.0', '392.0', '393.0', '394.0', '395.0', '396.0', '397.0', '398.0', '4.0', '40.0', '401.0', '402.0', '403.0', '404.0', '405.0', '407.0', '409.0', '412.0', '413.0', '414.0', '415.0', '416.0', '417.0', '418.0', '419.0', '42.0', '420.0', '421.0', '422.0', '423.0', '424.0', '425.0', '43.0', '434.0', '439.0', '44.0', '440.0', '441.0', '442.0', '443.0', '444.0', '445.0', '446.0', '447.0', '448.0', '449.0', '450.0', '452.0', '453.0', '458.0', '459.0', '46.0', '460.0', '461.0', '462.0', '463.0', '469.0', '47.0', '472.0', '473.0', '474.0', '475.0', '476.0', '477.0', '478.0', '479.0', '480.0', '481.0', '482.0', '49.0', '490.0', '491.0', '494.0', '497.0', '499.0', '5.0', '50.0', '501.0', '502.0', '504.0', '505.0', '506.0', '507.0', '508.0', '509.0', '51.0', '510.0', '511.0', '512.0', '52.0', '522.0', '53.0', '530.0', '531.0', '532.0', '533.0', '534.0', '536.0', '537.0', '54.0', '540.0', '547.0', '55.0', '559.0', '56.0', '561.0', '562.0', '567.0', '57.0', '579.0', '58.0', '59.0', '594.0', '595.0', '6.0', '60.0', '601.0', '603.0', '604.0', '61.0', '611.0', '62.0', '620.0', '621.0', '63.0', '637.0', '64.0', '645.0', '646.0', '65.0', '654.0', '655.0', '657.0', '66.0', '661.0', '662.0', '663.0', '664.0', '67.0', '672.0', '674.0', '676.0', '678.0', '68.0', '682.0', '687.0', '688.0', '69.0', '692.0', '693.0', '696.0', '7.0', '70.0', '700.0', '702.0', '703.0', '704.0', '705.0', '706.0', '707.0', '71.0', '711.0', '716.0', '718.0', '72.0', '720.0', '721.0', '722.0', '723.0', '724.0', '725.0', '726.0', '727.0', '728.0', '729.0', '73.0', '730.0', '731.0', '732.0', '733.0', '734.0', '735.0', '737.0', '74.0', '745.0', '75.0', '751.0', '757.0', '758.0', '76.0', '768.0', '769.0', '77.0', '770.0', '771.0', '775.0', '78.0', '783.0', '785.0', '79.0', '796.0', '8.0', '80.0', '802.0', '803.0', '808.0', '809.0', '81.0', '815.0', '816.0', '817.0', '82.0', '823.0', '829.0', '83.0', '834.0', '835.0', '839.0', '84.0', '843.0', '849.0', '85.0', '850.0', '851.0', '853.0', '854.0', '855.0', '859.0', '86.0', '864.0', '865.0', '866.0', '867.0', '868.0', '869.0', '87.0', '870.0', '871.0', '872.0', '873.0', '874.0', '875.0', '876.0', '877.0', '878.0', '879.0', '88.0', '880.0', '881.0', '882.0', '883.0', '884.0', '886.0', '887.0', '888.0', '889.0', '89.0', '890.0', '891.0', '892.0', '893.0', '894.0', '895.0', '896.0', '897.0', '898.0', '9.0', '90.0', '900.0', '901.0', '902.0', '903.0', '904.0', '905.0', '906.0', '907.0', '908.0', '909.0', '91.0', '910.0', '911.0', '912.0', '913.0', '914.0', '915.0', '916.0', '917.0', '918.0', '919.0', '92.0', '920.0', '921.0', '922.0', '923.0', '924.0', '925.0', '926.0', '927.0', '929.0', '93.0', '934.0', '936.0', '937.0', '938.0', '939.0', '940.0', '941.0', '942.0', '948.0', '949.0', '950.0', '951.0', '952.0', '953.0', '954.0', '956.0', '957.0', '958.0', '959.0', '960.0', '961.0', '962.0', '964.0', '965.0', '966.0', '967.0', '968.0', '969.0', '970.0', '971.0', '972.0', '973.0', '974.0', '975.0', '981.0', '982.0', '983.0', '984.0', '985.0', '986.0', '987.0', '988.0', '989.0', '990.0', '991.0', '992.0', '993.0', '994.0', '995.0', '996.0', '997.0', '998.0', '999.0']

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

# Enregistrement des données

In [ ]:
# Entregistrement du DataFrame
# save_dataframe_to_sheet("1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw", client, df_structure)
# save_dataframe_to_sheet("1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU", client, df_rattachement_court)