In [234]:
!git config --global user.email "clement.souk-aloun@croix-rouge.fr"
!git clone https://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@github.com/clementsouk-aloun-dot/Code-PAT.git

Cloning into 'Code-PAT'...
remote: Enumerating objects: 979, done.
remote: Counting objects: 100% (201/201), done.
remote: Compressing objects: 100% (155/155), done.
remote: Total 979 (delta 104), reused 64 (delta 46), pack-reused 778 (from 2)
Receiving objects: 100% (979/979), 2.58 MiB | 9.95 MiB/s, done.
Resolving deltas: 100% (610/610), done.

In [2]:
%cd Code-PAT
!git checkout pegass

/content/Code-PAT
Branch 'pegass' set up to track remote branch 'pegass' from 'origin'.
Switched to a new branch 'pegass'

In [ ]:
!git add .

In [ ]:
!git commit -m "Intégration données manuelles"

[Données-manuelles-ACA 532bdb9] Intégration données manuelles
 6 files changed, 7 insertions(+), 7 deletions(-)
 create mode 100644 reference_embeddings.pt
 create mode 100644 scripts_data/__pycache__/manuelles.cpython-312.pyc

In [ ]:
!git fetch origin

remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (6/6), 85.70 KiB | 1.75 MiB/s, done.
From https://github.com/clementsouk-aloun-dot/Code-PAT
   87338f7..baeb842  Mobilité             -> origin/Mobilité
   ef769b4..19118fb  Données-manuelles-ACA -> origin/Données-manuelles-ACA

In [ ]:
!git config pull.rebase true

In [ ]:
!git pull

Successfully rebased and updated refs/heads/Mobilité.

In [ ]:
!git push

Enumerating objects: 17, done.
Counting objects: 100% (17/17), done.
Delta compression using up to 2 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (11/11), 1.64 MiB | 3.13 MiB/s, done.
Total 11 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/clementsouk-aloun-dot/Code-PAT.git
   54c119f..532bdb9  Données-manuelles-ACA -> Données-manuelles-ACA

#INSTALL PACKAGE

In [235]:
!pip install PyPDF2
!pip install reportlab
!pip install PyMuPDF tools
!pip install xlsxwriter

Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.12/dist-packages (3.0.1)
Requirement already satisfied: reportlab in /usr/local/lib/python3.12/dist-packages (4.4.9)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.4)
Requirement already satisfied: PyMuPDF in /usr/local/lib/python3.12/dist-packages (1.26.7)
Requirement already satisfied: tools in /usr/local/lib/python3.12/dist-packages (1.0.23)
Requirement already satisfied: xlsxwriter in /usr/local/lib/python3.12/dist-packages (3.2.9)

In [236]:
import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import sys
import io
import re
import shutil
import zipfile
from google.colab import drive, files

from google.colab import auth
from google.auth import default
import unicodedata
import re
import torch
from sentence_transformers import SentenceTransformer, util

Imports des fichiers .py

In [237]:
sys.path.append(os.path.abspath("/content/Code-PAT/scripts_data"))
sys.path.append(os.path.abspath("/content/Code-PAT"))

from pegass import *
from financier import *
from mobilite import *
from manuelles import *
from utils import *

#AUTHENTIFICATION

In [238]:
from google.colab import auth
!gcloud auth application-default login

from google.cloud import bigquery
import pandas as pd

PROJECT_ID = "crf-pat"
client = bigquery.Client(project=PROJECT_ID)





# Import



query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.crf_activite_ref_activite_benevole`
"""
df_ref_activite_benevole = client.query(query).to_dataframe()
df_ref_activite_benevole.head()


query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.crf_pat_2025_pegass_activite`
"""
df_pegass_activite = client.query(query).to_dataframe()
df_pegass_activite.head()

query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.crf_pat_2025_pegass_activite_seance`
"""
df_pegass_activite_seance = client.query(query).to_dataframe()
df_pegass_activite_seance.head()


query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.crf_pat_2025_pegass_activite_seance_inscription`
"""
df_pegass_activite_seance_inscription = client.query(query).to_dataframe()
df_pegass_activite_seance_inscription.head()

query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.Ref_structure`
"""

df_ref_structure = client.query(query).to_dataframe()
df_ref_structure.head()

#Preparation ref structure
ref_structure1 = df_ref_structure[(df_ref_structure['type_structure'] == "UNITE LOCALE - UL") | (df_ref_structure['type_structure'] == 'DELEGATION TERRITORIALE - DT')]

query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.rattachement_court`
"""

df_rattachement_court = client.query(query).to_dataframe()

query = """
SELECT *
FROM `crf-pat.dataset_PAT_2025.crf_as_ref_action_groupe_action`
"""
df_ref_action_groupe_action = client.query(query).to_dataframe()
df_ref_action_groupe_action.head()

df_ref_action_groupe_action.columns = ['action_id_fk', 'ACTION_LIBELLE', 'GROUPE_ACTION_ID_FK']

Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=wuz4eLMAHGR85PevbsohNkmS5Ke2uI&prompt=consent&token_usage=remote&access_type=offline&code_challenge=tFX7nAq7Rn_gq9Z2J3ENv0qaGNoSnHAPun49ldpRqt8&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0ASc3gC2aSQC3IxJsj-yUAFeAVy0Nm3D9mgJxIHhjXYhbaRQvGh77BWwnL6BB14x8kHfCBA

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

#Merge des tables

In [243]:
#Preparation ref structure
ref_structure1 = df_ref_structure[(df_ref_structure['type_structure'] == "UNITE LOCALE - UL") | (df_ref_structure['type_structure'] == 'DELEGATION TERRITORIALE - DT')]

In [244]:
# 1) activité bénévole et action
df_ref_action_activite = pd.merge(df_ref_action_groupe_action, df_ref_activite_benevole, on="action_id_fk", how="left")

In [246]:
df_pegass_activite = df_pegass_activite.rename(columns={"PEGASS_ACTIVITE_ID_PK": "PEGASS_ACTIVITE_ID_FK"})

##Filtres sur les tables mergées

In [289]:

#Liste des codes activités bénévoles à garder

codes_activite_ben = [
    10119, 10122, 10123, 10125, 10126, 10127, 10128, 10129,
    10132, 10133, 10134, 10135, 10136, 10137,
    10032, 10033, 10034, 10035, 11110,
    10015, 10046, 10047, 11126,
    10105, 10106, 10108, 10113
]


#Lien avec le ref activité
df_ref_action_activite_filtre = df_ref_action_activite[df_ref_action_activite["activite_benevole_id_pk"].isin(codes_activite_ben)].copy()

In [293]:
#Filtres activités

Activite_maraude =  [10032, 10033, 10034, 10035, 10036, 10037,11110]

Nb_Exercice = [10122, 10123]

NB_operations = [10132, 10133, 10134, 10135, 10136, 10137, 10119, 10125, 10126, 10127, 10128, 10129]

AEO = [10015, 10046, 10047, 11126]

DPS = [10105, 10106, 10108, 10113]

IS_actifs = [10105, 10106, 10108, 10113,10114, 10115, 10116]

    # Nb_Exercice 10122, 10123,
     #Opération de secours 10125, 10126, 10127, 10128, 10129
    #NB_opérations 10132, 10133, 10134, 10135, 10136, 10137, 10119,

    #Maraude 10032, 10033, 10034, 10035, 10036, 10037, 11110

    # AEO : 10015, 10046, 10047, 11126

    #réseau de secours 10114, 10115, 10116

In [290]:
# 1) Join avec action sur PEGASS_ACTIVITE_ID_FK
df_ref_action_activite_filtre = df_ref_action_activite_filtre.rename(columns={"activite_benevole_id_pk": "ACTIVITE_BENEVOLE_ID_FK"})
df_pegass_activite_merge2 = pd.merge(df_pegass_activite_merge, df_ref_action_activite_filtre, on="ACTIVITE_BENEVOLE_ID_FK", how="inner")


#Join avec la table du nb bénévole
df_pegass_ben_activite= pd.merge(df_pegass_ben_activite, df_ref_action_activite_filtre, on="ACTIVITE_BENEVOLE_ID_FK", how="inner")

In [292]:
#pas de doublons (même nb de lignes que sans drop duplicate)
df_pegass_activite_merge2.drop_duplicates("PEGASS_ACTIVITE_SEANCE_ID_FK")

,PEGASS_ACTIVITE_ID_FK,PEGASS_ACTIVITE_SEANCE_ID_FK,PEGASS_ACTIVITE_SEANCE_DATE_DEBUT,PEGASS_ACTIVITE_SEANCE_HEURE_DEBUT,PEGASS_ACTIVITE_SEANCE_DATE_FIN,PEGASS_ACTIVITE_SEANCE_HEURE_FIN,ACTIVITE_SEANCE_EXTERNAL_ID_FK,PEGASS_ACTIVITE_DATE_DEBUT,PEGASS_ACTIVITE_HEURE_DEBUT,PEGASS_ACTIVITE_DATE_FIN,PEGASS_ACTIVITE_HEURE_FIN,PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK,PEGASS_ACTIVITE_STRUCTURE_ORGANISATRICE_ID_FK,ACTIVITE_BENEVOLE_ID_FK,ACTIVITE_BENEVOLE_EXTERNAL_ID_FK,action_id_fk,ACTION_LIBELLE,GROUPE_ACTION_ID_FK,activite_benevole_libelle
0,2199513,2199451,2024-12-31,14:00:00,2025-01-01,05:00:00,None,2024-12-31,14:00:00,2025-01-01,05:00:00,4631,4631,10035,None,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
1,2667236,2667121,2025-01-01,18:15:00,2025-01-01,23:15:00,None,2025-01-01,18:15:00,2025-01-01,23:15:00,392,392,10035,None,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
2,2685656,2685541,2025-01-01,18:15:00,2025-01-01,23:15:00,None,2025-01-01,18:15:00,2025-01-01,23:15:00,1107,1107,11110,None,6,Samu Social maraudes equipes mob. - Operations,2,Maraude de soir
3,2698070,2697945,2024-12-31,18:30:00,2025-01-01,00:30:00,None,2024-12-31,18:30:00,2025-01-01,00:30:00,230,230,10035,None,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee
4,2705941,2705816,2025-01-01,19:00:00,2025-01-01,21:15:00,None,2025-01-01,19:00:00,2025-01-01,21:15:00,3888,3888,11110,None,6,Samu Social maraudes equipes mob. - Operations,2,Maraude de soir
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59011,3310622,3310458,2025-12-30,19:00:00,2025-12-30,23:55:00,None,2025-12-30,19:00:00,2025-12-30,23:55:00,100,100,10119,None,21,Urgence et autres operations,1,Urgence et autres operations
59012,3310623,3310459,2025-12-30,08:00:00,2025-12-30,23:55:00,None,2025-12-30,08:00:00,2025-12-30,23:55:00,100,100,10135,None,21,Urgence et autres operations,1,Soutien aux populations - Hebergement d'urgence
59013,3310625,3310461,2025-12-30,18:00:00,2025-12-30,23:55:00,None,2025-12-30,18:00:00,2025-12-30,23:55:00,100,100,10119,None,21,Urgence et autres operations,1,Urgence et autres operations
59014,3356258,3356094,2025-12-30,19:00:00,2025-12-30,23:55:00,None,2025-12-30,19:00:00,2025-12-30,23:55:00,1253,1253,11110,None,6,Samu Social maraudes equipes mob. - Operations,2,Maraude de soir
59015,3371673,3371509,2025-12-02,08:00:00,2025-12-31,23:55:00,None,2025-12-02,08:00:00,2025-12-31,23:55:00,57,57,10035,None,6,Samu Social maraudes equipes mob. - Operations,2,Maraude vehiculee

##Création de la table qui permettra de compter le nombre d'*activité*

In [260]:
# 1) Join avec action sur PEGASS_ACTIVITE_ID_FK
df_pegass_activite_merge = pd.merge(df_pegass_activite_seance, df_pegass_activite, on="PEGASS_ACTIVITE_ID_FK", how="left")

## Création de la table qui permettra le comptage des bénévoles par activités

In [262]:
# 1) préparation de la table pour le Nb de Bénévoles
df_pegass_ben_activite = pd.merge(df_pegass_activite, df_pegass_activite_seance_inscription, on="PEGASS_ACTIVITE_ID_FK", how="right")

#On ne garde que celle dont le statut est validé = celles DONT PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT' qui sont validé
df_pegass_ben_activite = df_pegass_ben_activite[df_pegass_ben_activite['PEGASS_ACTIVITE_SEANCE_INSCRIPTION_STATUT'] == "Valide"]

In [263]:
#On fait une base synthétique pour compter le nombre de bénévoles différents
df_pegass_ben_activite_synthétique = df_pegass_ben_activite[['PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK', 'ACTIVITE_BENEVOLE_ID_FK','PEGASS_ACTIVITE_SEANCE_INSCRIPTION_NIVOL_ID_FK']]

df_pegass_ben_activite_synthétique.drop_duplicates()

,PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK,ACTIVITE_BENEVOLE_ID_FK,PEGASS_ACTIVITE_SEANCE_INSCRIPTION_NIVOL_ID_FK
0,2474,10070,eNozMDQ0MDAwNDI1t_QGAA8nAnY=
1,2474,10070,eNozMDAwMDIzt7AwNnYEAA94Anc=
3,2474,10070,eNozMDQ0MDA0sTCyNHUHAA9MAnc=
5,903,10035,eNozMDQ0AAILczMjLwAPNQJ0
8,903,10035,eNozMDAwMDQ3tTAwMfQFAA9WAng=
...,...,...,...
1161775,<NA>,<NA>,eNozMDQ0MDA0NTEwMQwGAA8rAnU=
1161777,<NA>,<NA>,eNozMDQ0MDAwNDK0NPMBAA8YAnI=
1161794,<NA>,<NA>,eNozMDQ0MDA0MrYwMgsBAA85An0=
1161795,<NA>,<NA>,eNozMDQ0MDA0NTU0tXQHAA87AnQ=
1161798,<NA>,<NA>,eNozMDQ0MDCwNDcxNQoDAA9jAoQ=

##VERIFICATION TABLES

###Comprendre la table PEGASS

In [250]:
#Qu'est que ce "ACTIVITE_SEANCE_EXTERNAL_ID_FK"
df_pegass_activite_seance["ACTIVITE_SEANCE_EXTERNAL_ID_FK"].unique()

array([None, '0292024120008-0001', '0352024110001-0001', ...,
       '0452025110003-0001', '0142025110012-0001', '0452025110004-0001'],
      dtype=object)

In [251]:
s = df_pegass_activite_seance["ACTIVITE_SEANCE_EXTERNAL_ID_FK"]
print(s.isna().sum())

396110

In [252]:
d = df_pegass_activite["ACTIVITE_BENEVOLE_EXTERNAL_ID_FK"]
print(d.isna().sum())

396110

In [253]:
s = df_pegass_activite_seance["ACTIVITE_SEANCE_EXTERNAL_ID_FK"]

# Longueur (NaN -> chaîne vide)
lengths = s.fillna("").astype(str).str.len()

# Tableau: nb de cellules par longueur
table = (lengths.value_counts()
         .sort_index()
         .rename_axis("nb_caracteres")
         .reset_index(name="nb_cellules"))

print(table)

   nb_caracteres  nb_cellules
0              0       396110
1             18        16930

In [254]:
s = df_pegass_activite["ACTIVITE_BENEVOLE_EXTERNAL_ID_FK"]

# Longueur (NaN -> chaîne vide)
lengths = s.fillna("").astype(str).str.len()

# Tableau: nb de cellules par longueur
table = (lengths.value_counts()
         .sort_index()
         .rename_axis("nb_caracteres")
         .reset_index(name="nb_cellules"))

print(table)

   nb_caracteres  nb_cellules
0              0       396110
1             13        13305

In [255]:
#On a donc pas le même nombre de caractères sur ACTIVITE_SEANCE_EXTERNAL_ID_FK entre séance et activité

In [256]:
test = df_pegass_activite_seance["ACTIVITE_SEANCE_EXTERNAL_ID_FK"].unique()

In [257]:
pd.DataFrame(test)

                        0
0                    None
1      0292024120008-0001
2      0352024110001-0001
3      0642024010026-0001
4      0742024090001-0001
...                   ...
16926  0142025110009-0001
16927  0142025110011-0001
16928  0452025110003-0001
16929  0142025110012-0001
16930  0452025110004-0001

[16931 rows x 1 columns]

In [258]:

print(np.sum(test != None))

16930

In [259]:
print(np.sum(test == None))

1

###Vérification des merge de tables

In [247]:
import pandas as pd
#Fonction de comparaison de 2 tables pour savoir qu'elles seront les lignes non mergées

def rows_not_in_merge(df_left: pd.DataFrame, df_right: pd.DataFrame, id_col: str, keep_cols_left=None, keep_cols_right=None):
    """
    Compare 2 tables sur id_col et retourne:
    - left_only: lignes de df_left dont l'id n'existe pas dans df_right
    - right_only: lignes de df_right dont l'id n'existe pas dans df_left

    keep_cols_left / keep_cols_right : liste de colonnes à conserver (optionnel).
    """
    left_ids = set(df_left[id_col].dropna().unique())
    right_ids = set(df_right[id_col].dropna().unique())

    left_only = df_left[df_left[id_col].isin(left_ids - right_ids)].copy()
    right_only = df_right[df_right[id_col].isin(right_ids - left_ids)].copy()

    if keep_cols_left is not None:
        left_only = left_only[[c for c in keep_cols_left if c in left_only.columns]]
    if keep_cols_right is not None:
        right_only = right_only[[c for c in keep_cols_right if c in right_only.columns]]

    return left_only, right_only

###Vérification des tables sources (big query)

In [266]:
#Vérifier que l'on a bien toutes les activités bénévoles entre le ref groupe action et le ref activité bénévole

left_only, right_only = rows_not_in_merge(df_ref_action_groupe_action, df_ref_activite_benevole, "action_id_fk")

left_only.head()
right_only.head()

     activite_benevole_id_pk  activite_benevole_libelle  action_id_fk
146                    10005  Deploiement ERU - Support            82
147                    10003     Deploiement ERU - Wash            83
148                    10002   Deploiement ERU - Relief            84
149                    10001     Deploiement ERU - ECRC            85
150                    10004    Deploiement ERU - PSSiE            90

In [267]:
right_only
#Ce n'est pas le cas = l'ensemble de ces activités bénévoles n'ont pas de liens à un groupe action : c'est problématique dans l'absolu mais pas pour nous car ces codes activités ne nous interessent pas

,activite_benevole_id_pk,activite_benevole_libelle,action_id_fk
146,10005,Deploiement ERU - Support,82
147,10003,Deploiement ERU - Wash,83
148,10002,Deploiement ERU - Relief,84
149,10001,Deploiement ERU - ECRC,85
150,10004,Deploiement ERU - PSSiE,90
271,10101,Divers,102
272,10097,Estime de soi,102
273,10096,Prevention des addictions,102
274,10098,Sante et bien-etre,102
275,11034,"Option \""Croix-Rouge\""",102
276,10099,Conference/Stand/Expo en milieu scolaire ou ex...,102
277,10100,Diffusion des valeurs humanitaires,102
278,11178,test creation activite octobre 2025,102
279,10102,Mesure de responsabilisations,103
284,10006,Deploiement ERU - Rapid Response,106
285,10007,Operation PIROI,107
286,10008,Operation PIRAC,108
287,10009,Operation d'urgence bilaterale,109

In [268]:
#Vérification : toutes les activités de Pegass séance sont bien référencées dans PEGASS activité
left_only, right_only = rows_not_in_merge(df_pegass_activite_seance, df_pegass_activite , "PEGASS_ACTIVITE_ID_FK")

left_only.head()
right_only.head()

#c'est le cas

Empty DataFrame
Columns: [PEGASS_ACTIVITE_ID_FK, PEGASS_ACTIVITE_DATE_DEBUT, PEGASS_ACTIVITE_HEURE_DEBUT, PEGASS_ACTIVITE_DATE_FIN, PEGASS_ACTIVITE_HEURE_FIN, PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK, PEGASS_ACTIVITE_STRUCTURE_ORGANISATRICE_ID_FK, ACTIVITE_BENEVOLE_ID_FK, ACTIVITE_BENEVOLE_EXTERNAL_ID_FK]
Index: []

In [273]:
#Comparaison df_pegass_activite_seance et df_pegass_activite
left_only, right_only = rows_not_in_merge(df_pegass_activite_seance, df_pegass_activite_seance_inscription,  "PEGASS_ACTIVITE_SEANCE_ID_FK")


left_only
#left_only: lignes de df_left dont l'id n'existe pas dans df_right
#Là il nous manque 59916 séances qui ne sont pas pris en compte dans PEGASS seance incription
#cela signifie qu'il y'a des séances qui sont crées mais qui n'ont pas de personnes inscrites dessus
#Réponse d'ELouan  :
#Dans la mécanique de Pegass la création d'activité/séance est complètement décorrélée de la partie inscriptions,
#il est donc tout à fait probable que des activités n'aient aucune inscription
#---> soit l'activité n'a pas eu lieu, soit elle a eu lieu mais les inscriptions n'ont pas été régularisées

,PEGASS_ACTIVITE_ID_FK,PEGASS_ACTIVITE_SEANCE_ID_FK,PEGASS_ACTIVITE_SEANCE_DATE_DEBUT,PEGASS_ACTIVITE_SEANCE_HEURE_DEBUT,PEGASS_ACTIVITE_SEANCE_DATE_FIN,PEGASS_ACTIVITE_SEANCE_HEURE_FIN,ACTIVITE_SEANCE_EXTERNAL_ID_FK
0,1746246,1746186,2025-01-01,08:15:00,2025-01-01,12:15:00,None
1,2171865,2171803,2025-01-01,10:00:00,2025-01-01,14:30:00,None
2,2193379,2193317,2024-12-31,23:00:00,2025-01-01,06:00:00,None
4,2223689,2223627,2025-01-01,13:50:00,2025-01-01,17:20:00,None
5,2235325,2235263,2024-12-31,00:00:00,2025-01-01,00:00:00,None
...,...,...,...,...,...,...,...
412998,2885018,2884893,2025-12-30,20:00:00,2025-12-30,23:55:00,None
413003,3081448,3081288,2025-12-30,20:30:00,2025-12-30,23:55:00,None
413008,3181559,3181395,2025-12-30,18:30:00,2025-12-30,23:55:00,None
413030,3356258,3356094,2025-12-30,19:00:00,2025-12-30,23:55:00,None
413039,3085518,3085358,2025-12-29,00:05:00,2026-01-04,23:55:00,None

###Vérification des tables mergée

In [269]:
#vérification
df_pegass_activite_seance_inscription_verif_seance= df_pegass_activite_seance_inscription[[ 'PEGASS_ACTIVITE_SEANCE_ID_FK']]

df_pegass_activite_seance_verif_seance=df_pegass_activite_seance[['PEGASS_ACTIVITE_SEANCE_ID_FK']]


#Comparaison df_pegass_activite_merge et df_pegass_activite
left_only, right_only = rows_not_in_merge(df_pegass_activite_seance_inscription_verif_seance, df_pegass_activite_seance_verif_seance, 'PEGASS_ACTIVITE_SEANCE_ID_FK')

# - right_only: lignes de df_right dont l'id n'existe pas dans df_left
right_only.head()

   PEGASS_ACTIVITE_SEANCE_ID_FK
0                       1746186
1                       2171803
2                       2193317
4                       2223627
5                       2235263

In [270]:
right_only

#Il y'a plus de 59916 de séances qui ne sont pas présents dans la table = cohérent avec ce qui été vu précedemment

        PEGASS_ACTIVITE_SEANCE_ID_FK
0                            1746186
1                            2171803
2                            2193317
4                            2223627
5                            2235263
...                              ...
412998                       2884893
413003                       3081288
413008                       3181395
413030                       3356094
413039                       3085358

[59985 rows x 1 columns]

In [92]:
#Comparaison df_pegass_activite_merge et df_pegass_activite
left_only, right_only = rows_not_in_merge(df_pegass_activite_merge, df_pegass_activite, "PEGASS_ACTIVITE_ID_FK")

left_only.head()
right_only.head()

#OK

Empty DataFrame
Columns: [PEGASS_ACTIVITE_ID_FK, PEGASS_ACTIVITE_DATE_DEBUT, PEGASS_ACTIVITE_HEURE_DEBUT, PEGASS_ACTIVITE_DATE_FIN, PEGASS_ACTIVITE_HEURE_FIN, PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK, PEGASS_ACTIVITE_STRUCTURE_ORGANISATRICE_ID_FK, ACTIVITE_BENEVOLE_ID_FK, ACTIVITE_BENEVOLE_EXTERNAL_ID_FK]
Index: []

###Vérification des tables

In [274]:
#vérif

# 1. Vérification des NaN ou valeurs vides sur PEGASS_ACTIVITE_ID_FK
lignes_vides = df_pegass_activite_merge[df_pegass_activite_merge["PEGASS_ACTIVITE_ID_FK"].isna() | (df_pegass_activite_merge["PEGASS_ACTIVITE_ID_FK"] == "")]
if not lignes_vides.empty:
        print(f"   ❌ {len(lignes_vides)} valeur(s) manquante(s) ou vide(s) détectée(s).")
else:
        print("   ✅ Aucun NaN ou valeur vide détecté.")

   ✅ Aucun NaN ou valeur vide détecté.

In [275]:
#vérif

# 1. Vérification des NaN ou valeurs vides sur ACTIVITE_BENEVOLE_ID_FK
lignes_vides = df_pegass_activite_merge[df_pegass_activite_merge["ACTIVITE_BENEVOLE_ID_FK"].isna() | (df_pegass_activite_merge["ACTIVITE_BENEVOLE_ID_FK"] == "")]
if not lignes_vides.empty:
        print(f"   ❌ {len(lignes_vides)} valeur(s) manquante(s) ou vide(s) détectée(s).")
else:
        print("   ✅ Aucun NaN ou valeur vide détecté.")

   ✅ Aucun NaN ou valeur vide détecté.

In [276]:
#vérif sur les structures menant les activités de la table consolidée

# 1. Vérification des NaN ou valeurs vides sur PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK
lignes_vides = df_pegass_activite_merge[df_pegass_activite_merge["PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK"].isna() | (df_pegass_activite_merge["PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK"] == "")]
if not lignes_vides.empty:
        print(f"   ❌ {len(lignes_vides)} valeur(s) manquante(s) ou vide(s) détectée(s).")
else:
        print("   ✅ Aucun NaN ou valeur vide détecté.")

#PBR de valeurs manquantes on va regarder sur la table de base

   ❌ 5255 valeur(s) manquante(s) ou vide(s) détectée(s).

In [281]:
#vérif sur les structures menant les activités de la table pegass activité

# 1. Vérification des NaN ou valeurs vides
lignes_vides_source = df_pegass_activite[df_pegass_activite["PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK"].isna() | (df_pegass_activite["PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK"] == "")]
if not lignes_vides_source.empty:
        print(f"   ❌ {len(lignes_vides_source)} valeur(s) manquante(s) ou vide(s) détectée(s).")
else:
        print("   ✅ Aucun NaN ou valeur vide détecté.")

 #Problème détecté :  5255 ACTIVITES n'ont pas de structures organisatrices associées

 #Réponse d'Elouan
print("Ces séances sont spécifiques à la fonctionnalité de planning hebdomadaire territorial dans pegass. C'est à dire qu'une DT crée des activités en masse : par exemple créneau de réseau de secours, de maraudes etc. puis affecte ensuite unitairement l'activité à une structure. En attendant que la structure soit affectée, la structure menant l'activité (et la structure organisatrice) ne sont pas renseignées. Seule la structure créatrice est alors renseignée. Dans les faits, ces activités ont été planifiées initialement mais n'ont jamais eu lieu réellement, tu peux les ignorer dans tes stats. ")

   ❌ 5255 valeur(s) manquante(s) ou vide(s) détectée(s).
Ces séances sont spécifiques à la fonctionnalité de planning hebdomadaire territorial dans pegass. C'est à dire qu'une DT crée des activités en masse : par exemple créneau de réseau de secours, de maraudes etc. puis affecte ensuite unitairement l'activité à une structure. En attendant que la structure soit affectée, la structure menant l'activité (et la structure organisatrice) ne sont pas renseignées. Seule la structure créatrice est alors renseignée. Dans les faits, ces activités ont été planifiées initialement mais n'ont jamais eu lieu réellement, tu peux les ignorer dans tes stats.

### Imprimmer la liste des données manquantes

In [282]:
activite_sans_struct = lignes_vides["ACTIVITE_BENEVOLE_ID_FK"].unique()

In [283]:
activite_sans_struct2 = lignes_vides["ACTIVITE_BENEVOLE_ID_FK"]

In [284]:
activite_sans_struct2 = pd.DataFrame(activite_sans_struct2)
activite_sans_struct2.columns = ["activite_benevole_id_pk"]

In [285]:
activite_sans_struct2

        activite_benevole_id_pk
148                       10115
149                       10115
150                       10114
153                       10116
206                       10115
...                         ...
412641                    10035
412642                    10035
412903                    10035
412904                    10035
412905                    10035

[5255 rows x 1 columns]

In [286]:
df_count = (
    activite_sans_struct2["activite_benevole_id_pk"]
    .value_counts()
    .reset_index()
    #.rename(columns={"index": "activite_benevole_id_pk", "activite_benevole_id_pk": "nb_occurrences"})
)
df_count

    activite_benevole_id_pk  count
0                     10115   2395
1                     10116    730
2                     10114    617
3                     10035    431
4                     10072    313
5                     10147    305
6                     10023    120
7                     10141    103
8                     10124     46
9                     11110     40
10                    10070     34
11                    10051     34
12                    11054     30
13                    10032     30
14                    10172      9
15                    10156      9
16                    11158      6
17                    10037      3

In [287]:
df_count_activite_sans_struct = pd.merge(df_count, df_ref_action_activite, on="activite_benevole_id_pk", how="right")

In [ ]:
df_count_activite_sans_struct.to_excel('df_count_activite_sans_struct.xlsx')
files.download("df_count_activite_sans_struct.xlsx")

##Calcul des indicateurs

### Calcul indicateur NB de bénévoles

In [294]:
#Def pour compter le nombre de ligne par structutre ( peut être qu'il a déjà été crée ? )

def count_ben_structure(
    df,
    col_structure="PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK",
    out_structure="n_structure",
    out_count="nb_benevoles"
):
    """
    Compte le nombre de lignes par structure (groupby + size).
    """
    df_out = (
        df.groupby(col_structure, as_index=False)
          .size()
          .rename(columns={col_structure: out_structure, "size": out_count})
    )
    return df_out

In [295]:
#Création des dfs pour chaque activités spécifiques

#NB bénévole Maraude
df_ben_Maraude_Pegass = df_pegass_ben_activite_synthétique[df_pegass_ben_activite_synthétique["ACTIVITE_BENEVOLE_ID_FK"].isin(Activite_maraude)]
#nb_ben_Maraude_Pegass = nb_ben_Maraude_Pegass.rename(columns={"nb_bénévoles": "Maraude Nb_benevoles_actifs"})
df_ben_Maraude_Pegass = df_ben_Maraude_Pegass.drop(columns=["ACTIVITE_BENEVOLE_ID_FK"])
df_ben_Maraude_Pegass = df_ben_Maraude_Pegass.drop_duplicates()

#NB volontaires  IS actifs
df_ben_IS_Pegass = df_pegass_ben_activite_synthétique[df_pegass_ben_activite_synthétique["ACTIVITE_BENEVOLE_ID_FK"].isin(IS_actifs)]
df_ben_IS_Pegass = df_ben_IS_Pegass.drop(columns=["ACTIVITE_BENEVOLE_ID_FK"])
df_ben_IS_Pegass  = df_ben_IS_Pegass.drop_duplicates()


# NB benevoles AEO ou AAD
df_ben_AEO_Pegass = df_pegass_ben_activite_synthétique[df_pegass_ben_activite_synthétique["ACTIVITE_BENEVOLE_ID_FK"].isin(AEO)]
df_ben_AEO_Pegass = df_ben_AEO_Pegass.drop(columns=["ACTIVITE_BENEVOLE_ID_FK"])
df_ben_AEO_Pegass = df_ben_AEO_Pegass.drop_duplicates()

In [297]:
#Calcul indicateur Nb volontaires
nb_ben_Maraude_Pegass = count_ben_structure(df_ben_Maraude_Pegass)
nb_ben_Maraude_Pegass = nb_ben_Maraude_Pegass.rename(columns={"nb_benevoles": "Maraude Nb_benevoles_actifs"})

nb_ben_AEO_Pegass = count_ben_structure(df_ben_AEO_Pegass)
nb_ben_AEO_Pegass = nb_ben_AEO_Pegass.rename(columns={"nb_benevoles": "AEO Nb_benevoles_actifs"})
nb_ben_IS_Pegass = count_ben_structure(df_ben_IS_Pegass)
nb_ben_IS_Pegass  = nb_ben_IS_Pegass.rename(columns={"nb_benevoles": "IS Nb_benevoles_actifs"})

In [300]:
#Vérifier que le nb ligne est égal à la somme pour les 3 indicateurs #a FAIRE
nb_ben_Maraude_Pegass["nb_benevoles"].sum()

KeyError: 'nb_benevoles'

In [ ]:
#Attention il faut faire les verifs pour voir si le nb bénévoles noté correspond bien au nb de ligne du fichier d'avant

###Calcul des indicateurs NB d'activités menés

In [301]:
def calc_nb_activite_Pegass(df_prep,
                           col_structure="PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK",
                           col_id="ACTIVITE_BENEVOLE_ID_FK",
                           out_structure="n_structure",
                           out_count="Activite_nb_activite_Pegass"):
    df_out = df_prep.groupby(col_structure, as_index=False)[col_id].count()
    df_out.columns = [out_structure, out_count]
    return df_out

In [302]:
def calc_nb_activite_Pegass(
    df_prep,
    col_structure="PEGASS_ACTIVITE_STRUCTURE_MENANT_ACTIVITE_ID_FK",
    col_activite="ACTIVITE_BENEVOLE_ID_FK",   # ta colonne "N° activité"
    out_structure="n_structure",
    out_activite="N° activité",
    out_count="nb_activite",
    dropna=False,
    sort=True
):
    """
    Compte le nombre d'occurrences (lignes) par (structure, activité).

    Retourne un DataFrame avec 3 colonnes :
    - out_structure : identifiant structure
    - out_activite  : identifiant / n° activité
    - out_count     : nombre de lignes pour ce couple
    """

    # Groupby sur 2 colonnes = structure + activité
    df_out = (
        df_prep
        .groupby([col_structure, col_activite], dropna=dropna)
        .size()
        .reset_index(name=out_count)
        .rename(columns={
            col_structure: out_structure,
            col_activite: out_activite
        })
    )

    if sort:
        df_out = df_out.sort_values([out_structure, out_count], ascending=[True, False])

    return df_out

In [303]:
nb_activite_Pegass = calc_nb_activite_Pegass(df_pegass_activite_merge2)

In [304]:
nb_activite_Pegass

      n_structure  N° activité  nb_activite
0               1        10119          246
3               1        10137            6
1               1        10125            5
2               1        10134            1
7               5        11110          230
...           ...          ...          ...
1683         4934        10113           35
1684         4934        10119            8
1686         <NA>        10035          431
1687         <NA>        11110           40
1685         <NA>        10032           30

[1688 rows x 3 columns]

In [305]:
#calcul NB Maraude Nb_maraudes_PEGASS
nb_Maraude_Pegass = nb_activite_Pegass[nb_activite_Pegass["N° activité"].isin(Activite_maraude)]
nb_Maraude_Pegass = nb_Maraude_Pegass.rename(columns={"nb_activite": "nb_Maraude_Pegass"})
nb_Maraude_Pegass = nb_Maraude_Pegass.drop(columns=["N° activité"])
nb_Maraude_Pegass1 = nb_Maraude_Pegass.groupby("n_structure", as_index=False)["nb_Maraude_Pegass"].sum()


#Calcul Nb opération PEGASS
nb_operations_Pegass = nb_activite_Pegass[nb_activite_Pegass["N° activité"].isin(NB_operations)]
nb_operations_Pegass = nb_operations_Pegass.rename(columns={"nb_activite": "Dispositifs_d_urgence Nb_operations"})
nb_operations_Pegass = nb_operations_Pegass.drop(columns=["N° activité"])
nb_operations_Pegass1 = nb_operations_Pegass.groupby("n_structure", as_index=False)["Dispositifs_d_urgence Nb_operations"].sum()

#Calcul Nb exercices PEGASS
nb_Exercice_Pegass = nb_activite_Pegass[nb_activite_Pegass["N° activité"].isin(Nb_Exercice)]
nb_Exercice_Pegass = nb_Exercice_Pegass.rename(columns={"nb_activite": "Dispositifs_d_urgence Nb_exercices"})
nb_Exercice_Pegass = nb_Exercice_Pegass.drop(columns=["N° activité"])
nb_Exercice_Pegass1 = nb_Exercice_Pegass.groupby("n_structure", as_index=False)["Dispositifs_d_urgence Nb_exercices"].sum()

#Calcul Nb AEO AAD PEGASS
nb_AEO_Pegass = nb_activite_Pegass[nb_activite_Pegass["N° activité"].isin(AEO)]
nb_AEO_Pegass = nb_AEO_Pegass.rename(columns={"nb_activite": "nb_activite_AEO"})
nb_AEO_Pegass = nb_AEO_Pegass.drop(columns=["N° activité"])
nb_AEO_Pegass1 = nb_AEO_Pegass.groupby("n_structure", as_index=False)["nb_activite_AEO"].sum()

In [198]:
#Agrégation par structure

##Vérification

In [215]:
#Vérifier pour chacun des 3 indiczateurs que somme de nb_operations_Pegass1 = somme de nb_operations_Pegass

#Vérifier que la somme des 3 indicateurs =

In [200]:
nb_Maraude_Pegass

      n_structure  nb_Maraude_Pegass
7               5                230
4               5                 72
14             10                  1
18             10                  1
20             12                197
...           ...                ...
1663         4677                  3
1678         4884                  2
1686         <NA>                431
1687         <NA>                 40
1685         <NA>                 30

[445 rows x 2 columns]

In [201]:
nb_Maraude_Pegass1

     n_structure  nb_Maraude_Pegass
0              5                302
1             10                  2
2             12                205
3             13                  2
4             23                 41
..           ...                ...
248         4642                 43
249         4674                  7
250         4676                109
251         4677                  3
252         4884                  2

[253 rows x 2 columns]

In [202]:
nb_Exercice_Pegass1

    n_structure  Dispositifs_d_urgence Nb_exercices
0             5                                   1
1             7                                   1
2            12                                   1
3            17                                   1
4            18                                   1
..          ...                                 ...
90         4394                                   1
91         4395                                   1
92         4396                                   2
93         4631                                   8
94         4649                                   2

[95 rows x 2 columns]

In [307]:
#A conserver pour les merge mais à mettre plus haut

ref_structure2 = ref_structure1[["n_structure", "DT_de_rattachement"]]

In [308]:
# 1) merge avec ref struct et structure de ratachement
nb_Maraude_Pegass1 = pd.merge(nb_Maraude_Pegass1, ref_structure2, on="n_structure", how="right")

In [310]:
nb_Maraude_Pegass1["Maraude Nb_maraudes_PEGASS"] = nb_Maraude_Pegass1["nb_Maraude_Pegass"].fillna("Action non menée")

In [312]:
#Création d'une fonction action menée


def add_statut_action(
    df,
    col_nb,
    out_col="activité menée",
    label_yes="Action menée",
    label_no="Action non menée",
    treat_zero_as_no=True,
    copy=True
):
    """
    Ajoute une colonne de statut basée sur une colonne de comptage.

    - Si col_nb contient une valeur numérique (et optionnellement != 0), => label_yes
    - Sinon (NaN / vide / non numérique) => label_no

    Params
    ------
    df : pd.DataFrame
    col_nb : str
        Nom de la colonne à tester (comptage / nb / etc.)
    out_col : str
        Nom de la colonne créée
    treat_zero_as_no : bool
        True => 0 => label_no ; False => 0 => label_yes
    copy : bool
        True => retourne une copie ; False => modifie df en place
    """
    df_out = df.copy() if copy else df

    nb = pd.to_numeric(df_out[col_nb], errors="coerce")

    if treat_zero_as_no:
        mask_yes = nb.notna() & (nb != 0)
    else:
        mask_yes = nb.notna()

    df_out[out_col] = np.where(mask_yes, label_yes, label_no)
    return df_out

In [313]:
#Calcul Action Menée et non menée pour chaque activités

#nb_Maraude_Pegass1 = add_statut_action(nb_Maraude_Pegass1, col_nb="nb_Maraude_Pegass", out_col="Maraudes realisees", treat_zero_as_no=True)

#Nb exercice et NB operations on en besoin qu'à l'échelle DT => Pas besoin
#nb_Exercice_Pegass1 = add_statut_action(nb_Exercice_Pegass1, col_nb="Dispositifs_d_urgence Nb_exercices", out_col="exercices_d_urgence realises", treat_zero_as_no=True)

#nb_operations_Pegass1 = add_statut_action(nb_operations_Pegass1, col_nb="Dispositifs_d_urgence Nb_operations", out_col="Operations_d_urgence realisees", treat_zero_as_no=True)

nb_AEO_Pegass1 = add_statut_action(nb_AEO_Pegass1, col_nb="nb_activite_AEO" , out_col="AEO Structure_activite_fixe", label_yes="Activités AEO/AAD menée en fixe", treat_zero_as_no=True)

In [314]:
#Merge global des 3 indicateurs

Indics_pegass = pd.merge(nb_Maraude_Pegass1, nb_operations_Pegass1, on="n_structure", how="left")

Indics_pegass = pd.merge(Indics_pegass , nb_Exercice_Pegass1, on="n_structure", how="left")

Indics_pegass_struct = pd.merge(Indics_pegass, nb_AEO_Pegass1 , on="n_structure", how="left")

In [315]:


Indics_pegass_struct

,n_structure,nb_Maraude_Pegass,DT_de_rattachement,Maraude Nb_maraudes_PEGASS,Dispositifs_d_urgence Nb_operations,Dispositifs_d_urgence Nb_exercices,nb_activite_AEO,AEO Structure_activite_fixe
0,10,2.0,10 - DT DES ALPES MARITIMES,2.0,2.0,NaN,NaN,NaN
1,170,NaN,10 - DT DES ALPES MARITIMES,Action non menée,NaN,NaN,NaN,NaN
2,171,NaN,10 - DT DES ALPES MARITIMES,Action non menée,NaN,NaN,NaN,NaN
3,172,NaN,10 - DT DES ALPES MARITIMES,Action non menée,NaN,NaN,NaN,NaN
4,173,NaN,10 - DT DES ALPES MARITIMES,Action non menée,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
684,904,97.0,80 - DT DE PARIS,97.0,1.0,NaN,4.0,Activités AEO/AAD menée en fixe
685,905,112.0,80 - DT DE PARIS,112.0,NaN,NaN,5.0,Activités AEO/AAD menée en fixe
686,906,156.0,80 - DT DE PARIS,156.0,NaN,NaN,1.0,Activités AEO/AAD menée en fixe
687,907,20.0,80 - DT DE PARIS,20.0,NaN,NaN,NaN,NaN
688,908,52.0,80 - DT DE PARIS,52.0,1.0,NaN,51.0,Activités AEO/AAD menée en fixe

In [316]:
Indics_pegass_struct.columns

Index(['n_structure', 'nb_Maraude_Pegass', 'DT_de_rattachement',
       'Maraude Nb_maraudes_PEGASS', 'Dispositifs_d_urgence Nb_operations',
       'Dispositifs_d_urgence Nb_exercices', 'nb_activite_AEO',
       'AEO Structure_activite_fixe'],
      dtype='object')

In [333]:
#Calcul DT
Indics_pegass_DT =Indics_pegass_struct[['DT_de_rattachement','nb_Maraude_Pegass',  'Dispositifs_d_urgence Nb_operations', 'Dispositifs_d_urgence Nb_exercices', 'nb_activite_AEO']]

Indics_pegass_DT =   (Indics_pegass_DT.groupby("DT_de_rattachement", as_index=False).sum(numeric_only=True))
Indics_pegass_DT  = Indics_pegass_DT .rename(columns={"nb_activite_AEO": "AEO Structure_activite_fixe"})

In [341]:
#netoyage DF structure
Indics_pegass_struct= Indics_pegass_struct [['n_structure', 'nb_Maraude_Pegass', 'DT_de_rattachement',
       'Maraude Nb_maraudes_PEGASS', 'Dispositifs_d_urgence Nb_operations',
       'Dispositifs_d_urgence Nb_exercices',
       'AEO Structure_activite_fixe']]

### A partir d'ici c'est inutile

# Variables globales

In [ ]:
mapping_df = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1kqRn5NjquzkYW2u4YpSKlBSHzQCNK_piQRq9pPpcVGM/edit?gid=221060687#gid=221060687').worksheet('Liste détaillée des variables à extraire'))

# CHARGEMENT DE TOUTES LES DONNEES PAR TABLE

# 0. Ref_structure

In [ ]:
df_ref_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw/').worksheet('Feuille 1'))

In [ ]:
df_ref_structure = renommer_par_nom_table(df_ref_structure, "AS_Informations_structures", mapping_df)
df_ref_structure['n_structure'] = df_ref_structure['n_structure'].astype(int).astype(str)
df_ref_structure.head()

,n_structure,type_structure,nom_structure,adresse_physique_cp,code_insee,adresse_physique_commune,adresse_complete,n_dept,date_demarrage_activite_ben_struct,date_arret_activite_struct,Structure_de_rattachement,Rattachements_successifs,DT_de_rattachement,lon,lat
0,2615,ANTENNE LOCALE - AL,AL DE DELLE,90100.0,90033,DELLE,"1 Résidence LOUIS CLERC, 90100 DELLE",90,2010-02-08 00:00:00,NaT,95 - DT DU TERRITOIRE DE BELFORT,AL 2615,95 - DT DU TERRITOIRE DE BELFORT,7.000705,47.506725
1,2669,ANTENNE LOCALE - AL,AL PAYS DE MONTFAUCON ET DU HAUT LIGNON,43220.0,43087,DUNIERES,"3 Rue Traversière, 43220 DUNIERES",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2669,48 - DT DE LA HAUTE LOIRE,4.346423,45.214392
2,2670,ANTENNE LOCALE - AL,AL LA PORTE DU VELAY,43600.0,43224,STE SIGOLENE,"12 Rue Notre Dame des Anges, 43600 STE SIGOLENE",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2670,48 - DT DE LA HAUTE LOIRE,4.235474,45.242445
3,2671,ANTENNE LOCALE - AL,AL LE HAUT ALLIER,43300.0,43112,LANGEAC,"4 Rue Dumas, 43300 LANGEAC",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2671,48 - DT DE LA HAUTE LOIRE,3.495645,45.098285
4,2672,ANTENNE LOCALE - AL,AL LE PUY EN VELAY,43000.0,43157,LE PUY EN VELAY,"3 Rue CHARLES VII, 43000 LE PUY EN VELAY",43,2011-01-01 00:00:00,NaT,48 - DT DE LA HAUTE LOIRE,AL 2672,48 - DT DE LA HAUTE LOIRE,3.879748,45.044677

In [ ]:
df_ref_structure_DT = df_ref_structure[df_ref_structure['nom_structure'].str.contains('DT')].astype(str)

# 1. PEGASS

In [ ]:
# EXEMPLE :  Charger le DataFrame
# spreadsheet = gspread_client.open_by_url("https://docs.google.com/spreadsheets/d/1WEoWR3dnhy7NL5ISoD6o-58krsttfHkiqaJz30Vvg74/")
# worksheet = spreadsheet.worksheet("Feuille 1")
# df_raw = get_as_dataframe(worksheet)

## 1.1. rattachement_court

In [ ]:
rattachement_court = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU/edit?usp=sharing').worksheet('Feuille 1'))

## 1.2. Activité_benevole ref activité

In [ ]:
Ref_activité_benevole = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1rf1gXTylNEHEt72UfwZO62gIfgzf9eY8lPqhXLJ5hs8/edit').worksheet('Feuille 1'))

## 1.3. Pegass_activite / Activite

In [ ]:
Pegass_activite = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/13Ygh1goryIgp2UCh19tKaTv3AWkfsSMInuS8-VMbmeU/edit').worksheet('Feuille 1'))

## 1.4. PegassInscription / Inscription

In [ ]:
Pegass_inscription = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1wCYPGwDVKZC6BBuMnOc7kB98agof5IMkdn9W7xn5UUg/edit').worksheet('Feuille 1'))

## 1.5. PREPARATION DE LA BASE DE DONNEES

In [ ]:
Pegass_inscription, Pegass_activite, Ref_activité_benevole = clean_pegass(Pegass_inscription,Pegass_activite,Ref_activité_benevole, mapping_df)

# 2. GAIA

## 2.1. GAIA_contact

In [ ]:
GAIA_contact = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1k4-nMZqUulcZBPMplZLWHcvSTvzISqF9uMnlITdikmI/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.2. GAIA_action

In [ ]:
GAIA_action = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1XvfYhne_YxMBVfgkDUzKhhOle9-bmEP3j0gpBYZsKuo/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.3. GAIA_rattachement_action

In [ ]:
GAIA_rattachement_action = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1vtC3hpxh6RIcmhMjifVFoi169uhdi0f9fpKXP9FqEd8/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.4 GAIA_act_str

In [ ]:
GAIA_act_str = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1PrK18aa8dllTjXOEyPHXMEgqP4gm1ZeJdnCmlUG78EA/edit?usp=drive_link').worksheet('Feuille 1'))

In [ ]:
GAIA_act_str.head()

## 2.5. GAIA_structure

In [ ]:
GAIA_structure = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1forcw_rC0WCcwu6K8-AUhm1sur9pp5XZX_YTCKaBA6g/edit?usp=drive_link').worksheet('Feuille 1'))

## 2.6. Preparation de la base

### 2.6.1. Renommer les variables

In [ ]:
GAIA_action = renommer_par_nom_table(GAIA_action, "GAIA_action", mapping_df)
GAIA_rattachement_action = renommer_par_nom_table(GAIA_rattachement_action, "GAIA_rattachement_action", mapping_df)
GAIA_contact = renommer_par_nom_table(GAIA_contact, "GAIA_contact", mapping_df)
GAIA_structure = renommer_par_nom_table(GAIA_structure, "GAIA_structure", mapping_df)
GAIA_act_str = renommer_par_nom_table(GAIA_act_str, "GAIA_act_str", mapping_df)

In [ ]:
GAIA_structure.head()

# 3. NOMINATION

## 3.1. NOMINATION_nomination

In [ ]:
NOMINATION_nomination = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ywCGFgW5eLONMNK64o4NZrQQzasqfEGnnQL6LfDXbbM/edit?gid=614834196').worksheet('NOMINATION_nomination'))

In [ ]:
NOMINATION_nomination.head()

## 3.2 NOMINATION_attribution_nomination

In [ ]:
NOMINATION_attribution_nomination = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1BzCcfO1NLM5oMmBD1cBELIuvBvVjucsK6Wm4zPTaO-Q/').worksheet('NOMINATION_attribution_nomination'))

In [ ]:
NOMINATION_attribution_nomination.head()

## 3.3. Préparation de la base

### 3.3.1. Renommer les variables

In [ ]:
NOMINATION_nomination = renommer_par_nom_table(NOMINATION_nomination, "nomination", mapping_df)
NOMINATION_attribution_nomination = renommer_par_nom_table(NOMINATION_attribution_nomination, "attribution_nomination", mapping_df)

# 4. IMPACT

## 4.1 Impact_indicateurs

In [ ]:
IMPACT_indicateurs = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.2 Impact_indicateur_value

In [ ]:
IMPACT_indicateur_value = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.3 Impact_donnees_activite

In [ ]:
IMPACT_donnees_activite = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.4 Impact_abstract_donnees_activite

In [ ]:
IMPACT_abstract_donnees_activite = get_as_dataframe(gspread_client.open_by_url('...').worksheet('Feuille 1'))

## 4.5. Preparation de la base

### 4.5.1. Renommer les variables

In [ ]:
IMPACT_indicateurs = renommer_par_nom_table(IMPACT_indicateurs, "IMPACT_indicateurs", mapping_df)
IMPACT_indicateur_value = renommer_par_nom_table(IMPACT_indicateur_value, "IMPACT_indicateur_value", mapping_df)
IMPACT_donnees_activite = renommer_par_nom_table(IMPACT_donnees_activite, "IMPACT_donnees_activite", mapping_df)
IMPACT_abstract_donnees_activite = renommer_par_nom_table(IMPACT_abstract_donnees_activite, "IMPACT_abstract_donnees_activite", mapping_df)

# 5. Données financières

In [ ]:
financier = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c')

In [ ]:
dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute, dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute = import_clean_donnees_financieres(financier,df_ref_structure,mapping_df)

# 6. Mobilité

In [ ]:
mobilite = gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1dvxT58WR-FqdT-4r-A9ca4vaA9FG7IXHJJaTbnjio8A/')

In [ ]:
df_mobilite = filtres_mobilite(mobilite,mapping_df)

# 7. Données manuelles

## 7.1 OCR

In [ ]:
df_OCR = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1ccRoyPycFDwvQvacvmHjfE87LtnlzUgtoRbITkC0pVQ/').worksheet('Feuille 1'))

## 7.2 PST

In [ ]:
df_PST = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1yifNna4Hsn5RihkRg50g9h1yKjuRjfolrjsWonEHnrQ').worksheet('Données'))

## 7.3 Déclenchements

In [ ]:
df_declenchement = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1y9jehT5fStcEWCF0pxAP7BdiI62VY3JM_hQzFftbcZA').worksheet('Feuille 1'))

## 7.4 Redcall

In [ ]:
df_redcall = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1EQzq0K8RY2Liyq-jtggX0bTlnOk9cwUTmf4t6c5_CiI').worksheet('structure-stats_2025-01-01_2025-12-31_min-1 (1)'))

## 7.5 CHAI CHU CMCC

In [ ]:
df_CAICHUCMCC = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/12nZY2leRCMn71NGAEUUtA0Pes598gOfeufDStxSCcnY').worksheet('Toutes données'))

## 7.6 Conventions

In [ ]:
df_conventions = get_as_dataframe(gspread_client.open_by_url('https://docs.google.com/spreadsheets/d/1OYSSkUhWwVpWne9EygH1EEz8EJnFjSeAOEpQQe9utiM').worksheet('Feuille 1'))

## 7.7 Préparation

In [ ]:
df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions = clean_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement, df_redcall, df_CAICHUCMCC, df_conventions)

/content/Code-PAT/scripts_data/manuelles.py:103: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['Grand Total', 'Exercice']] = df[['Grand Total', 'Exercice']].fillna(0)
/content/Code-PAT/scripts_data/manuelles.py:156: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Département"] = df["Département"].str.replace(
/content/Code-PAT/scripts_data/manuelles.py:192: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Departement"] = df["Departement"].str.replace(
/content/Code-PAT/scripts_data/manuelles.py:213: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[colonnes_oui_non] = df[colonnes_oui_non].applymap(
/content/Code-PAT/scripts_data/manuelles.py:213: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[colonnes_oui_non] = df[colonnes_oui_non].applymap(
/content/Code-PAT/scripts_data/manuelles.py:217: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Dispositifs_d_urgence Nb_conventions_operateurs'] = (

# FUSION DES TABLES

## 1. Fusion PEGASS activité, inscription, ref_activité_bénévole, rattachement_court

### 1.1 Filtres généraux à appliquer

In [ ]:
df2 = fusion_pegass(Pegass_inscription, Pegass_activite, Ref_activité_benevole)

## 2. Fusion GAIA rattachement_action, action, act_str, structure

### 2.1. Filtres généraux à appliquer

In [ ]:
#FTILRE SUR ANNEE NULLE OU FIN EN 2025

# Vérification que la colonne est au format datetime
GAIA_act_str['date_fin_activite_struct'] = pd.to_datetime(GAIA_act_str['date_fin_activite_struct'], errors='coerce')

# Filtrage : date nulle ou année = 2025
GAIA_act_str = GAIA_act_str[
    GAIA_act_str['date_fin_activite_struct'].isna() | (GAIA_act_str['date_fin_activite_struct'].dt.year == 2025)
]

### 2.2. Fusion des tables

In [ ]:
# left = pd.merge(df1, df2, on="id", how="left")

# 1) Join avec action sur act_id
df_GAIA = pd.merge(GAIA_rattachement_action, GAIA_action, on="n_action_ben", how="left")

# 2) Join avec rattachement_action sur act_id + str_id
df_GAIA = pd.merge(df_GAIA, GAIA_act_str, on="n_action_ben", how="left")

# 3) Join avec contact sur cob_idrp
df_GAIA = pd.merge(df_GAIA, GAIA_structure, on="id_structure", how="left")

# df final disponible dans df_GAIA
df_GAIA.head()

## 3. Fusion NOMINATION nomination, attribution_nomination

### 3.1. Filtres généraux à appliquer

In [ ]:
#FTILRE SUR ANNEE NULLE OU FIN EN 2025

# Vérification que la colonne est au format datetime
NOMINATION_attribution_nomination['date_fin_nomination'] = pd.to_datetime(NOMINATION_attribution_nomination['date_fin_nomination'], errors='coerce')
NOMINATION_attribution_nomination['date_debut_nomination'] = pd.to_datetime(NOMINATION_attribution_nomination['date_debut_nomination'], errors='coerce')

# Filtrage : date nulle ou année = 2025
NOMINATION_attribution_nomination = NOMINATION_attribution_nomination[
    NOMINATION_attribution_nomination['date_fin_nomination'].isna() | (NOMINATION_attribution_nomination['date_fin_nomination'].dt.year == 2025)
]

### 3.2. Fusion des tables

In [ ]:
# left join (tous les id de df1, et ce qu'on trouve dans df2)
# left = pd.merge(df1, df2, on="id", how="left")

df_NOMINATION = pd.merge(NOMINATION_nomination, NOMINATION_attribution_nomination,on="nomination_id", how="left") #VERIFIER LA FOREIGN KEY!

## 4. Fusion IMPACT indicateurs, indicateurs_value, donnees_activite, abstract_donnes_activite

### 4.1. Filtres généraux à appliquer

In [ ]:
#FTILRE SUR ANNEE 2025

# Vérification que la colonne est au format datetime
IMPACT_donnees_activite['date_fin_activite'] = pd.to_datetime(IMPACT_donnees_activite['date_fin_activite'], errors='coerce')
IMPACT_donnees_activite['date_debut_activite'] = pd.to_datetime(IMPACT_donnees_activite['date_debut_activite'], errors='coerce')

# Filtrage : date nulle ou année = 2025
IMPACT_donnees_activite = IMPACT_donnees_activite[ (IMPACT_donnees_activite['date_debut_activite'].dt.year == 2025)]

### 4.2. Fusion des tables

In [ ]:
# left = pd.merge(df1, df2, on="id", how="left")

# 1) Join avec action sur act_id
df_IMPACT = pd.merge(IMPACT_indicateur_value, IMPACT_indicateurs, on="n_indicateurs", how="left")

# 2) Join avec rattachement_action sur act_id + str_id
df_IMPACT = pd.merge(df_IMPACT, IMPACT_donnees_activite, on="id_activite", how="left")

# 3) Join avec contact sur cob_idrp
df_IMPACT = pd.merge(df_IMPACT, IMPACT_abstract_donnees_activite, on="id_activite", how="left")

# df final disponible dans df_GAIA
df_IMPACT.head()

## 5. Fusion Données financières

### 5.1 Fusion des tables

In [ ]:
df_financier_DT, df_financier_DT_UL = fusion_donnees_financieres(dt_prod, dt_resnet, dt_resnet_corr_prod, dt_treso_brute,dt_ul_ant_prod, dt_ul_ant_res_net, dt_ul_res_net_corr_prod, dt_ul_treso_brute)

### 5.2 Vérifications

In [ ]:
verifier_n_dept(df_financier_DT,df_ref_structure)

 ✅ Aucun doublon
 ✅ Pas de département manquant

In [ ]:
verifier_colonne_structure(df_financier_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

# Calcul des indicateurs

# Indicateurs PEGASS

- Nombre de bénévoles par activité benevole

## Nombre de bénévoles par activité benevole

In [ ]:
 Nb_benevoles_distincts, Nb_benevoles_Distribution_alimentaire, Nb_benevoles_Distribution_alimentaire1, Nb_benevoles_Distribution_alimentaire2, Nb_benevoles_Distribution_alimentaire3, Nb_benevoles_Distribution_alimentaire4 = indicateurs_pegass(df2)

# Indicateurs GAIA

## Nombre de bénévoles déclarés sur une activitée

### 10.1. Calcul nb de volontaires de l'urgence

In [ ]:
# Filtre sur le libelle approprié
df_urgence = df_GAIA[df_GAIA["libelle_action_ben"] == "Urgences et autres opérations"]

In [ ]:
# On compte le nb de volontaires de l'urgence
NbBeneDecla_GAIA = (df_urgence.groupby('n_structure_x')['id_gaia'].nunique())

In [ ]:
NbBeneDecla_GAIA.head()

Series([], Name: id_gaia, dtype: int64)

## 3. RTAEO & RLAEO

In [ ]:
# Filtre sur le libelle approprié
referents_AEO = df_NOMINATION[df_NOMINATION["libelle_nomination"] == "RTAEO"]

# Filtre sur le libelle approprié
referents_OCR = df_NOMINATION[df_NOMINATION["libelle_nomination"] == "RTOCR"]

In [ ]:
# On compte le nb de RTAEO & RLAEO
referents_AEO = (referents_AEO.groupby('structure_id')['libelle_nomination'].nunique())

In [ ]:
referents_AEO

Series([], Name: libelle_nomination, dtype: int64)

In [ ]:
# DF par mois
annee = 2025

# Mois de l'année
mois = pd.date_range(
    start=f"{annee}-01-01",
    end=f"{annee}-12-01",
    freq="MS"
)

resultats = []

for m in mois:
    debut_mois = m
    fin_mois = m + pd.offsets.MonthEnd(1)

    actifs = referents_AEO[
        (referents_AEO["date_debut_nomination"] <= fin_mois) &
        (referents_AEO["date_fin_nomination"] >= debut_mois)
    ]

    comptage = (
        actifs
        .groupby("structure")
        .size()
        .reset_index(name="nb")
    )

    comptage["mois"] = m.strftime("%Y-%m")
    resultats.append(comptage)

# Concaténation
referents_AEO_mois = pd.concat(resultats)

# Tableau croisé
referents_AEO_mois = referents_AEO_mois.pivot(
    index="structure_id",
    columns="mois",
    values="nb"
).fillna(0).astype(int)

print(pivot)

## 4. RTOCR & RLOCR

In [ ]:
# On compte le nb de RTAEO & RLAeo
referents_OCR = (referents_OCR.groupby('structure_id')['libelle_nomination'].nunique())

KeyError: 'Column not found: nom'

In [ ]:
# DF par mois
annee = 2025

# Mois de l'année
mois = pd.date_range(
    start=f"{annee}-01-01",
    end=f"{annee}-12-01",
    freq="MS"
)

resultats = []

for m in mois:
    debut_mois = m
    fin_mois = m + pd.offsets.MonthEnd(1)

    actifs = referents_OCR[
        (referents_OCR["date_debut_nomination"] <= fin_mois) &
        (referents_OCR["date_fin_nomination"] >= debut_mois)
    ]

    comptage = (
        actifs
        .groupby("structure")
        .size()
        .reset_index(name="nb")
    )

    comptage["mois"] = m.strftime("%Y-%m")
    resultats.append(comptage)

# Concaténation
referents_OCR_mois = pd.concat(resultats)

# Tableau croisé
referents_OCR_mois = referents_OCR_mois.pivot(
    index="structure_id",
    columns="mois",
    values="nb"
).fillna(0).astype(int)

print(pivot)

##  Nombre d'agréments territoriaux (Dispos d'urgence)

## Nombre de personnes prises en charge (Dispos d'urgence)

## Mobilité


Indicateurs qui nécessitent seulement les données mobilité :

- Nb de structures menant une activité AEO/AAD mobile
- Nombre de personnes accompagnées par des dispositifs AEO/AAD mobiles
<br>
Indicateurs qui nécessitent une fusion avec données AEO/AAD :

- Nombre de bénévoles impliqués dans les activités AEO ou AAD
- Nombre de bénévoles impliqués dans les activités AEO ou AAD

In [ ]:
df_mobilite_DT = indicateurs_mobilite(df_mobilite, df_ref_structure, 'DT_de_rattachement')
df_mobilite_DT_UL = indicateurs_mobilite(df_mobilite, df_ref_structure, 'n_structure')

In [ ]:
verifier_colonne_structure(df_mobilite_DT, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

In [ ]:
verifier_colonne_structure(df_mobilite_DT_UL, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

## Données manuelles

In [ ]:
df_OCR_Nb_deployees, df_Dispositifs_d_urgence_PST, df_declenchement3, df_redcall2, df_CAICHUCMCC_VF, df_conventions2 = indicateurs_OCR_PST_DEC_RED_CAI_CONV(df_OCR, df_PST, df_declenchement2, df_RC_grouped, df_CAICHUCMCC2, df_conventions, df_ref_structure)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [ ]:
verifier_colonne_structure(df_OCR_Nb_deployees, "n_structure", df_ref_structure)
verifier_colonne_structure(df_Dispositifs_d_urgence_PST, "n_structure", df_ref_structure)
verifier_colonne_structure(df_declenchement3, "n_structure", df_ref_structure)
verifier_colonne_structure(df_redcall2, "n_structure", df_ref_structure)
verifier_colonne_structure(df_CAICHUCMCC_VF, "n_structure", df_ref_structure)
verifier_colonne_structure(df_conventions2, "n_structure", df_ref_structure)

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 1 code(s) non trouvés dans le référentiel : [47]

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 1 code(s) non trouvés dans le référentiel : [47]

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ❌ 761 code(s) non trouvés dans le référentiel : ['1.0', '10.0', '1000.0', '1001.0', '1002.0', '1004.0', '1005.0', '1007.0', '1008.0', '101.0', '1010.0', '1011.0', '1012.0', '1013.0', '1014.0', '1015.0', '1016.0', '1017.0', '1018.0', '1019.0', '1020.0', '1021.0', '1022.0', '1023.0', '1024.0', '1025.0', '1026.0', '1027.0', '1028.0', '1029.0', '1030.0', '1031.0', '1032.0', '1033.0', '1034.0', '1035.0', '1036.0', '1037.0', '1038.0', '1039.0', '1040.0', '1041.0', '1042.0', '1044.0', '1049.0', '105.0', '1050.0', '1051.0', '1052.0', '1053.0', '1054.0', '1055.0', '1056.0', '1058.0', '1059.0', '1060.0', '1061.0', '1062.0', '1063.0', '1064.0', '1065.0', '1066.0', '1067.0', '1068.0', '1069.0', '107.0', '1070.0', '1071.0', '1072.0', '1073.0', '1074.0', '1076.0', '1078.0', '1079.0', '108.0', '1080.0', '1081.0', '1083.0', '1084.0', '1085.0', '1086.0', '1087.0', '1089.0', '109.0', '1090.0', '1091.0', '1092.0', '1093.0', '1094.0', '1095.0', '1096.0', '1097.0', '1098.0', '1099.0', '110.0', '1100.0', '1101.0', '1102.0', '1103.0', '1104.0', '1105.0', '1106.0', '1107.0', '1108.0', '1109.0', '111.0', '1110.0', '1111.0', '1112.0', '1113.0', '1114.0', '1115.0', '1116.0', '1117.0', '1118.0', '1119.0', '112.0', '1120.0', '1121.0', '1122.0', '1123.0', '1124.0', '1126.0', '1128.0', '1129.0', '113.0', '1130.0', '1134.0', '1135.0', '1137.0', '1138.0', '1139.0', '114.0', '1141.0', '1142.0', '1143.0', '1144.0', '1145.0', '1146.0', '1147.0', '1148.0', '1149.0', '115.0', '1150.0', '1151.0', '1152.0', '1153.0', '1154.0', '1155.0', '1156.0', '1158.0', '1159.0', '116.0', '1160.0', '1161.0', '1162.0', '1163.0', '1164.0', '1165.0', '1166.0', '1167.0', '1168.0', '117.0', '1173.0', '1174.0', '1176.0', '1177.0', '1178.0', '1179.0', '118.0', '1180.0', '1181.0', '1183.0', '1184.0', '1185.0', '1187.0', '1188.0', '1189.0', '119.0', '1195.0', '1199.0', '12.0', '1200.0', '1201.0', '1202.0', '1203.0', '1207.0', '1208.0', '121.0', '1219.0', '122.0', '1221.0', '1222.0', '1223.0', '1226.0', '123.0', '1234.0', '1235.0', '1236.0', '1237.0', '1239.0', '124.0', '1240.0', '1241.0', '125.0', '126.0', '127.0', '1287.0', '129.0', '130.0', '1309.0', '131.0', '1310.0', '1315.0', '1317.0', '133.0', '1332.0', '1333.0', '1334.0', '1335.0', '1338.0', '1340.0', '1344.0', '1348.0', '1350.0', '1351.0', '1353.0', '1357.0', '1358.0', '1359.0', '1361.0', '1363.0', '1364.0', '1367.0', '138.0', '139.0', '14.0', '140.0', '141.0', '142.0', '143.0', '144.0', '145.0', '146.0', '147.0', '149.0', '15.0', '150.0', '152.0', '153.0', '155.0', '156.0', '157.0', '158.0', '159.0', '16.0', '160.0', '161.0', '162.0', '163.0', '164.0', '165.0', '166.0', '167.0', '168.0', '169.0', '170.0', '171.0', '172.0', '173.0', '174.0', '175.0', '178.0', '179.0', '180.0', '181.0', '182.0', '184.0', '185.0', '186.0', '188.0', '189.0', '19.0', '190.0', '191.0', '192.0', '193.0', '194.0', '195.0', '196.0', '197.0', '198.0', '199.0', '2.0', '20.0', '200.0', '201.0', '202.0', '203.0', '204.0', '205.0', '206.0', '207.0', '208.0', '21.0', '210.0', '211.0', '212.0', '213.0', '214.0', '215.0', '216.0', '217.0', '218.0', '219.0', '22.0', '220.0', '221.0', '223.0', '224.0', '226.0', '227.0', '23.0', '230.0', '231.0', '232.0', '234.0', '235.0', '236.0', '24.0', '26.0', '268.0', '269.0', '27.0', '28.0', '285.0', '29.0', '3.0', '30.0', '305.0', '31.0', '311.0', '312.0', '313.0', '314.0', '316.0', '317.0', '318.0', '319.0', '32.0', '320.0', '321.0', '322.0', '323.0', '324.0', '326.0', '327.0', '328.0', '33.0', '330.0', '334.0', '335.0', '336.0', '337.0', '338.0', '339.0', '340.0', '341.0', '344.0', '345.0', '346.0', '347.0', '349.0', '350.0', '351.0', '352.0', '353.0', '354.0', '355.0', '356.0', '359.0', '362.0', '363.0', '364.0', '365.0', '366.0', '367.0', '368.0', '369.0', '37.0', '370.0', '372.0', '373.0', '374.0', '375.0', '376.0', '377.0', '378.0', '379.0', '380.0', '382.0', '383.0', '384.0', '386.0', '388.0', '389.0', '39.0', '390.0', '391.0', '392.0', '393.0', '394.0', '395.0', '396.0', '397.0', '398.0', '4.0', '40.0', '401.0', '402.0', '403.0', '404.0', '405.0', '407.0', '409.0', '412.0', '413.0', '414.0', '415.0', '416.0', '417.0', '418.0', '419.0', '42.0', '420.0', '421.0', '422.0', '423.0', '424.0', '425.0', '43.0', '434.0', '439.0', '44.0', '440.0', '441.0', '442.0', '443.0', '444.0', '445.0', '446.0', '447.0', '448.0', '449.0', '450.0', '452.0', '453.0', '458.0', '459.0', '46.0', '460.0', '461.0', '462.0', '463.0', '469.0', '47.0', '472.0', '473.0', '474.0', '475.0', '476.0', '477.0', '478.0', '479.0', '480.0', '481.0', '482.0', '49.0', '490.0', '491.0', '494.0', '497.0', '499.0', '5.0', '50.0', '501.0', '502.0', '504.0', '505.0', '506.0', '507.0', '508.0', '509.0', '51.0', '510.0', '511.0', '512.0', '52.0', '522.0', '53.0', '530.0', '531.0', '532.0', '533.0', '534.0', '536.0', '537.0', '54.0', '540.0', '547.0', '55.0', '559.0', '56.0', '561.0', '562.0', '567.0', '57.0', '579.0', '58.0', '59.0', '594.0', '595.0', '6.0', '60.0', '601.0', '603.0', '604.0', '61.0', '611.0', '62.0', '620.0', '621.0', '63.0', '637.0', '64.0', '645.0', '646.0', '65.0', '654.0', '655.0', '657.0', '66.0', '661.0', '662.0', '663.0', '664.0', '67.0', '672.0', '674.0', '676.0', '678.0', '68.0', '682.0', '687.0', '688.0', '69.0', '692.0', '693.0', '696.0', '7.0', '70.0', '700.0', '702.0', '703.0', '704.0', '705.0', '706.0', '707.0', '71.0', '711.0', '716.0', '718.0', '72.0', '720.0', '721.0', '722.0', '723.0', '724.0', '725.0', '726.0', '727.0', '728.0', '729.0', '73.0', '730.0', '731.0', '732.0', '733.0', '734.0', '735.0', '737.0', '74.0', '745.0', '75.0', '751.0', '757.0', '758.0', '76.0', '768.0', '769.0', '77.0', '770.0', '771.0', '775.0', '78.0', '783.0', '785.0', '79.0', '796.0', '8.0', '80.0', '802.0', '803.0', '808.0', '809.0', '81.0', '815.0', '816.0', '817.0', '82.0', '823.0', '829.0', '83.0', '834.0', '835.0', '839.0', '84.0', '843.0', '849.0', '85.0', '850.0', '851.0', '853.0', '854.0', '855.0', '859.0', '86.0', '864.0', '865.0', '866.0', '867.0', '868.0', '869.0', '87.0', '870.0', '871.0', '872.0', '873.0', '874.0', '875.0', '876.0', '877.0', '878.0', '879.0', '88.0', '880.0', '881.0', '882.0', '883.0', '884.0', '886.0', '887.0', '888.0', '889.0', '89.0', '890.0', '891.0', '892.0', '893.0', '894.0', '895.0', '896.0', '897.0', '898.0', '9.0', '90.0', '900.0', '901.0', '902.0', '903.0', '904.0', '905.0', '906.0', '907.0', '908.0', '909.0', '91.0', '910.0', '911.0', '912.0', '913.0', '914.0', '915.0', '916.0', '917.0', '918.0', '919.0', '92.0', '920.0', '921.0', '922.0', '923.0', '924.0', '925.0', '926.0', '927.0', '929.0', '93.0', '934.0', '936.0', '937.0', '938.0', '939.0', '940.0', '941.0', '942.0', '948.0', '949.0', '950.0', '951.0', '952.0', '953.0', '954.0', '956.0', '957.0', '958.0', '959.0', '960.0', '961.0', '962.0', '964.0', '965.0', '966.0', '967.0', '968.0', '969.0', '970.0', '971.0', '972.0', '973.0', '974.0', '975.0', '981.0', '982.0', '983.0', '984.0', '985.0', '986.0', '987.0', '988.0', '989.0', '990.0', '991.0', '992.0', '993.0', '994.0', '995.0', '996.0', '997.0', '998.0', '999.0']

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

🔎 Vérification de la colonne 'n_structure'
   ✅ Aucun NaN ou valeur vide détecté.
   ✅ Aucun doublon détecté.
   ✅ Tous les codes sont présents dans le référentiel.

# Enregistrement des données

In [ ]:
# Entregistrement du DataFrame
# save_dataframe_to_sheet("1zIlZZE_Z6P6T-5TPk-YPLr3XM5ME6wFvX1jC7FH6LPw", client, df_structure)
# save_dataframe_to_sheet("1MzeiuxTDCUBxDQHzGFJUCxY_2qve0J9xxnHA_roC2MU", client, df_rattachement_court)