# Import

In [1]:
!pip install PyPDF2
!pip install reportlab
!pip install PyMuPDF tools
!pip install xlsxwriter

import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import io
import re
import shutil
import zipfile
from google.colab import drive, files

Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.12/dist-packages (3.0.1)
Requirement already satisfied: reportlab in /usr/local/lib/python3.12/dist-packages (4.4.7)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.4)
Requirement already satisfied: PyMuPDF in /usr/local/lib/python3.12/dist-packages (1.26.7)
Requirement already satisfied: tools in /usr/local/lib/python3.12/dist-packages (1.0.17)
Requirement already satisfied: xlsxwriter in /usr/local/lib/python3.12/dist-packages (3.2.9)

# Variables utiles

In [2]:
# Couleurs

bleu = '#b7ddf4'
jaune = "#fdf68f"
vert = "#68c2c5"#13d3aa"#"#b7f4d2"
violet = '#cebfff'

Couleurs = {8: bleu, 11: violet, 14: violet, 16: violet, 18: violet, 20: violet, 24: jaune, 25: jaune, 27: jaune, 30: jaune, 34: jaune, 35: jaune, 36: jaune, 39: jaune, 45: vert, 43: vert}

# Fonctions utiles

In [3]:
from google.colab import auth
from google.auth import default

def get_google_client():
    """
    Authentifie l'utilisateur et renvoie un client Google Sheets pour interagir avec les feuilles de calcul.

    Cette fonction configure l'environnement pour désactiver l'authentification éphémère,
    authentifie l'utilisateur à l'aide de l'API de Google Colab et initialise un client Google Sheets autorisé.

    Returns:
        gspread.Client: Une instance de gspread.Client autorisée, permettant l'interaction avec Google Sheets.
    """

    # Désactive l'authentification éphémère
    os.environ['USE_AUTH_EPHEM'] = '0'

    # Authentifie l'utilisateur
    auth.authenticate_user()

    # Obtient les informations d'identification par défaut
    creds, _ = default()

    # Crée et retourne le client Google Sheets autorisé
    client = gspread.authorize(creds)

    print("🌐 Connexion au client Google réalisée")

    return client

In [4]:
def export_to_excel_download(dataframe, file_name='data.xlsx'):
    """
    Exporte un DataFrame en fichier Excel et le télécharge depuis Google Colab.

    Parameters:
        dataframe (pd.DataFrame): Le DataFrame à exporter.
        file_name (str): Le nom du fichier Excel à télécharger (par défaut 'data.xlsx').
    """
    dataframe.to_excel(file_name, index=False)
    files.download(file_name)

In [5]:
def sheet_to_dataframe(client, url, sheet_index=0, sheet_name=None, header_row=1):
    """
    Ouvre une feuille Google Sheets et crée un DataFrame Pandas à partir de ses données.

    Cette fonction prend en entrée l'URL de la feuille Google Sheets, un client Google Sheets autorisé,
    l'index de la page souhaitée ou le nom de la feuille, et la ligne utilisée comme en-tête. Elle renvoie les données de la
    feuille sous forme de DataFrame Pandas.

    Args:
        url (str): L'URL de la feuille Google Sheets.
        client (gspread.Client): Client Google Sheets autorisé.
        sheet_index (int, optional): L'index de la page à ouvrir dans la feuille. Par défaut, 0 (première page).
        sheet_name (str, optional): Le nom de la feuille à ouvrir. Si fourni, prioritaire sur sheet_index.
        header_row (int, optional): Le numéro de la ligne à utiliser comme en-têtes de colonnes pour le DataFrame.
                                   Par défaut, 1 (la première ligne de données après l'en-tête de feuille).

    Returns:
        pd.DataFrame: Un DataFrame Pandas contenant les données de la feuille avec la première ligne spécifiée
                      comme en-tête des colonnes.
    """

    # Ouvre la feuille Google Sheets à partir de l'URL
    sheet = client.open_by_url(url)

    # Sélectionne la page (worksheet) souhaitée
    if sheet_name:
        worksheet = sheet.worksheet(sheet_name)
    else:
        worksheet = sheet.get_worksheet(sheet_index)

    # Récupère toutes les valeurs de la page
    data = worksheet.get_all_values()

    # Crée le DataFrame en utilisant la ligne spécifiée comme en-tête
    df = pd.DataFrame(data[header_row:], columns=data[header_row - 1])

    print(f"✅ Chargement des données réalisées")
    print(f"    Sheet : {sheet.title}")
    print(f"    Feuille {sheet_index + 1 if not sheet_name else ''} : {worksheet.title} ({len(data) - header_row} lignes et {len(data[header_row - 1])} colonnes)\n")

    return df

In [6]:
def duplicate_slides(presentation_id, slide_ids):
    """Duplicate each slide and move the duplicates to the beginning of the presentation."""
    requests = []
    duplicated_slide_ids = []

    # Étape 1 : Dupliquer les diapositives (elles seront insérées immédiatement après les originales)
    for slide_id in slide_ids:
        requests.append({
            'duplicateObject': {
                'objectId': slide_id
            }
        })

    # Batch update pour dupliquer les diapositives
    body = {'requests': requests}
    response = slides_service.presentations().batchUpdate(presentationId=presentation_id, body=body).execute()

    # Collecter les IDs des diapositives dupliquées
    duplicated_slide_ids = [reply['duplicateObject']['objectId'] for reply in response.get('replies', [])]

    # Étape 2 : Réorganiser les diapositives dupliquées en haut de la présentation
    requests = []
    for i, duplicated_slide_id in enumerate(duplicated_slide_ids):
        requests.append({
            'updateSlidesPosition': {
                'slideObjectIds': [duplicated_slide_id],
                'insertionIndex': i  # Placer au début, en conservant l’ordre des duplicatas
            }
        })

    # Batch update pour réorganiser les diapositives
    body = {'requests': requests}
    slides_service.presentations().batchUpdate(presentationId=presentation_id, body=body).execute()

    return duplicated_slide_ids


def batch_replace_text_on_slides(presentation_id, slide_ids, replacements):
    """
    Effectue plusieurs remplacements de texte sur des diapositives spécifiques dans une seule requête.

    :param presentation_id: ID de la présentation Google Slides
    :param slide_ids: Liste des IDs de diapositives à modifier
    :param replacements: Liste de tuples (texte_à_remplacer, texte_de_remplacement)
    """
    requests = []
    for text_to_replace, replacement_text in replacements:
        requests.append({
            'replaceAllText': {
                'containsText': {
                    'text': text_to_replace,
                    'matchCase': True
                },
                'replaceText': str(replacement_text),
                'pageObjectIds': slide_ids
            }
        })

    body = {'requests': requests}
    slides_service.presentations().batchUpdate(
        presentationId=presentation_id,
        body=body
    ).execute()


def export_to_pdf(presentation_id, output_file):
    """Export the entire presentation to a PDF."""
    request = drive_service.files().export_media(fileId=presentation_id, mimeType='application/pdf')
    fh = io.FileIO(output_file, 'wb')
    downloader = MediaIoBaseDownload(fh, request)
    done = False
    while not done:
        status, done = downloader.next_chunk()

def remove_unwanted_pages(input_pdf, output_pdf, pages_to_keep):
    """Remove unwanted pages from a PDF file."""
    reader = PdfReader(input_pdf)
    writer = PdfWriter()

    # Add only the specified pages
    for page_number in pages_to_keep:
        writer.add_page(reader.pages[page_number])

    # Save the modified PDF
    with open(output_pdf, 'wb') as output_file:
        writer.write(output_file)


def delete_slides(presentation_id, slide_ids):
    """Delete slides by their IDs."""
    requests = [{'deleteObject': {'objectId': slide_id}} for slide_id in slide_ids]
    body = {'requests': requests}
    slides_service.presentations().batchUpdate(presentationId=presentation_id, body=body).execute()

In [7]:
def generate_image_from_dataframe(filtered_df, output_filename='dataframe_image.png',color='#D9C9FF'):
    """
    Génère une image à partir d'un DataFrame avec une mise en forme lisible,
    en ajustant automatiquement la taille et en augmentant la hauteur de l'en-tête.
    """

    # === 1. Préparation du DataFrame ===
    df_temp = filtered_df.copy().fillna("")

    if "Nom" in df_temp.columns:
        df_temp["Nom"] = df_temp["Nom"].apply(
            lambda x: f"   {x}" if isinstance(x, str) and (x.startswith("UL") or x.startswith("AL")) else x
        )


    # === 2. Définition des paramètres ===
    dpi = 75
    n_rows, n_cols = df_temp.shape

    # Longueur max pour ajuster largeur
    max_col_len = max(
        [df_temp[col].astype(str).map(len).max() for col in df_temp.columns] +
        [len(c) for c in df_temp.columns]
    )

    base_fontsize = max(6, 12 - n_rows // 20)
    row_height = 0.4  # en pouces
    header_height = row_height * 2
    col_width = 0.45 + (max_col_len / 30)

    fig_height = header_height + n_rows * row_height
    fig_width = max(3, n_cols * col_width)

    # === 3. Création de la figure ===
    fig = Figure(figsize=(fig_width, fig_height), dpi=dpi)
    canvas = FigureCanvas(fig)
    ax = fig.add_subplot(111)
    ax.axis('off')

    # === 4. Création du tableau ===
    table = ax.table(
        cellText=df_temp.values,
        colLabels=df_temp.columns,
        cellLoc='center',
        loc='center',
        colColours=["#D9C9FF"] * n_cols
    )

    table.auto_set_font_size(False)
    table.set_fontsize(base_fontsize)

    # Ajustement largeur
    for i in range(n_cols):
        table.auto_set_column_width(i)

    # === 5. Ajustement des cellules ===
    for (row, col), cell in table.get_celld().items():
        cell.set_edgecolor('black')
        cell.set_linewidth(0.3)
        cell.PAD = 0.08

        if row == 0:  # Header
            cell.set_facecolor(color)
            cell.get_text().set_color('black')
            cell.get_text().set_fontweight('bold')
            cell.get_text().set_fontsize(base_fontsize + 2)
            cell.set_height(header_height*2 / fig_height)
            cell.get_text().set_ha('center')
        else:
            cell.set_facecolor('white')
            cell.set_height(row_height / fig_height)
            if col == 0:
                cell.get_text().set_ha('left')

    # === 6. Sauvegarde ===
    img_buffer = io.BytesIO()
    fig.savefig(img_buffer, format="png", dpi=dpi, bbox_inches='tight', pad_inches=0.01)
    img_buffer.seek(0)

    with open(output_filename, "wb") as f:
        f.write(img_buffer.getvalue())


def generer_graphique_financier(df, nom_dt, output_filename, dpi=150):
    """
    Génère un graphique financier pour une DT donnée, et le sauvegarde en image PNG.

    Paramètres :
    - df : DataFrame contenant les colonnes de production et de résultat net pour les années 2022 à 2024.
    - nom_dt : nom de la DT à traiter (doit être une valeur dans la colonne 'DT').
    - output_filename : chemin de sauvegarde de l'image PNG.
    - dpi : résolution de l'image (défaut = 300).
    """
    # === 1. Filtrage de la DT ===
    ligne = df[df["nom_structure"] == nom_dt].iloc[0]  # On suppose que chaque DT est unique

    # === 2. Création du DataFrame ===
    data = pd.DataFrame({
        'Année': ['2022', '2023', '2024'],
        'CA (€)': [
            ligne["Financier Prod_2022"],
            ligne["Financier Prod_2023"],
            ligne["Financier Prod_2024"]
        ],
        'Résultat Net (€)': [
            ligne["Financier ResNet_2022"],
            ligne["Financier ResNet_2023"],
            ligne["Financier ResNet_2024"]
        ],
        'Proportion (%)': [
            ligne["Financier ResCorrProd_2022"] * 100,
            ligne["Financier ResCorrProd_2023"] * 100,
            ligne["Financier ResCorrProd_2024"] * 100
        ]
    })

    # === 3. Style ===
    sns.set_style("whitegrid")
    palette = sns.color_palette("pastel")

    # === 4. Figure ===
    fig, ax = plt.subplots(figsize=(6, 3.5))
    width = 0.35
    x = range(len(data))

    bars1 = ax.bar([i - width/2 for i in x], data['CA (€)'], width=width, color=palette[0])
    bars2 = ax.bar([i + width/2 for i in x], data['Résultat Net (€)'], width=width, color=palette[2])

    ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f'{int(x):,}'.replace(",", " ")))

    # Nouvelle gestion de l’axe y pour inclure les négatifs
    min_y = min(data['Résultat Net (€)'].min(), 0)
    max_y = max(data['CA (€)'].max(), data['Résultat Net (€)'].max())
    ax.set_ylim(min_y * 1.1, max_y * 1.1)

    ax.set_xticks(x)
    ax.set_xticklabels(data['Année'], fontsize=12)

    for i, (res_net, pct) in enumerate(zip(data['Résultat Net (€)'], data['Proportion (%)'])):
        offset = max_y * 0.01 if res_net >= 0 else -max_y * 0.06
        ax.text(i + width/2, res_net + offset, f"{pct:.1f}%",
                color='black', ha='center', fontsize=10)

    legend_elements = [
        Patch(facecolor=palette[0], label='CA (€)'),
        Patch(facecolor=palette[2], label='Résultat Net (€ et % du CA)'),
    ]
    fig.legend(handles=legend_elements, loc='lower center', ncol=3, fontsize=11, frameon=False)

    fig.tight_layout(rect=[0, 0.05, 1, 1])

    # === 5. Sauvegarde ===
    img_buffer = io.BytesIO()
    fig.savefig(img_buffer, format="png", dpi=dpi, bbox_inches='tight', pad_inches=0.01)
    img_buffer.seek(0)

    with open(output_filename, "wb") as f:
        f.write(img_buffer.getvalue())

    plt.close(fig)  # Pour éviter l'affichage dans les notebooks



def ajouter_image_dans_pdf(pdf,page_numero,image_path,hauteur_pt,centre_x,centre_y):
    """
    Ajoute une image sur une page d'un PDF existant.
    La hauteur de l'image dépend du nombre de lignes du dataframe fourni.
    La largeur est ajustée automatiquement pour conserver les proportions de l'image d'origine.

    Args:
        pdf (obj): Le PDF d'entrée.
        page_numero (int): Numéro de la page (1-based).
        image_path (str): Chemin vers l'image à insérer.
        hauteur_pt : Hauteur de l'image.
        centre_x (float): Coordonnée X du centre de l'image (points).
        centre_y (float): Coordonnée Y du centre de l'image (points).
    """
    page = pdf[page_numero - 1]

    # Taille réelle de l'image (pixels)
    image = PILImage.open(image_path)
    width_px, height_px = image.size
    ratio = width_px / height_px  # largeur / hauteur

    # Calcul des dimensions en points
    hauteur_pt = min(hauteur_pt, 340)  # Hauteur maximale en points pour ne pas dépasser si format hori
    largeur_pt = hauteur_pt * ratio

    # Coordonnées du coin supérieur gauche
    x0 = centre_x - largeur_pt / 2
    y0 = centre_y - hauteur_pt / 2
    rect = fitz.Rect(x0, y0, x0 + largeur_pt, y0 + hauteur_pt)

    # Ajout de l'image à la page
    page.insert_image(rect, filename=image_path)

    return pdf

# Authentification

In [8]:
# Etape 0 : Préparation de l'environnement

CREDENTIALS_JSON = """
{
  "type": "service_account",
  "project_id": "alexandrevalent",
  "private_key_id": "dba39c84ba4135ce5ede6479a186ad8cde499dee",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvGU4ZJFrBwCBb\nu8s4aPA5bQTOKDkPZEVdNyY//RneR6RC9JPrcbfVfIUaQU7A036sfdhDGFKJbw20\nTZ55fafcH9yCMiUO+Nzek0eogON4TXrXsh8UFtdw8BOuaVkFitU5yg8kFhTnEZtd\ntPfZHW3Aqhd/aDoTOBNgRuF/hVTKQ2ytbCbE77fL2/pz9kvpZ2Zrz3u1lmksSJls\nHIolNwX9R05YqmrkpZ/TMAULFk4bT0VRQng5pmN9AeB61eJLWhlLaEdeu79NWV4B\n7tZd6RzzTFors804aJkmXHM63VRtvGD0UlR0O7w1QlI3ymUxpy5hrjbz6n9bmpMI\nfebvydLnAgMBAAECggEADipn7RTJ2t7mP0WkHT4wIRU2zE7ovtwH2JC7oXWigB8f\npOMQjH24t6bJReR+sI7rspzDwDnZg5DedPXKml2WFPLm7gmMgfeUNtWHeJRk0rjB\n9W1NolxutY5WqUeQkig3M+Oq8epvano8LYqUepYs6OdZ207dU+y3dJSHbb+lqm9D\ntQZR2oBj7W1iZ8fJ+SQLSjU5BztS1CvWuayRd/tLd9Spp0NUn5uQFTKwel9Gazmz\n28IsPPm6SudplFhaGd4kCPvhcg0jGEKe61VYdgHoBzp+EXRWXUvQ+SbMafXtMvoB\nLoUH4X3creKzJQKXnjlDpAzRHMYhJTvHinHXaggdcQKBgQDcJszFOECfSovXFZNq\nMyQOWbesyDb2OQhJLFZCD2QraZm3jPaIPeMfFkmFAumcVal6EzpR5IE8g9jBuLo+\ng6j3NTo5jbGO9WEn4361yEotb+S8t3/DTHvWqXBK7HdUB/KHlyGtctm8yErdMZQB\nvzo03aTwwStNTeFG8GzT1Nd7JQKBgQDLnHIMbx9iAG3K21XCq0Dot2Q63hklJC26\nsJlrTkdXMOIlhpwJ6LTOJe2paHbR56IrKOHQCuLxQFhRd8Eidz1ahjO7D8fKr/TG\nS8/V32FrpONyxhKinLsccSb86S3vvpKCI265z5EEjk/1qnx3TOo6oqA/2DQLv0Q4\nYinmNSOeGwKBgHGjYY3n9IuE6lwy2e42ycTSkNoSWzSLyfgjd78PvNAf6WXy0IsR\nDvzL/1U2ZKn7GclWxYLiJce78xZEKXb9dSluA0kUF/RIO0dgydZBtfBwUq0LN1rz\nTvVGbx1tpEbu90UAQTUMFNK6vNIitliUghIp2usfex+jNMbuce6Cblw1AoGBAKDH\n1gtZiFeT7R7d2jfRkXzyrBQMI6D/k5izMULZ2l3QfROS2w68EmIi8yvuEL2qApXA\nP6hPoGtPGy6huQHlVK5yANF7IZI9JbWcUe8Z6MzetLiCDl8YEmzgMSBPZXXGb9yR\n7DKP5HzLf/qG+KggNWm913ry2A5ap506bsmZNpn3AoGBAM6vvI9tb+AcNfd4ewmY\nAWSb4GLliRTaBIGHYmotfyBEBWpXZq2/0JG32RRf3rYUJWWn/r7K+zrRUqeMwlD+\nz7GuSU+OaSDzYj7fwDyuxOwTJMLrh+AkKbUYBsMF7YH1qIRjBjKNdj1LOznASQMe\nu1E4sNa9RRRujbQw4AEP3Xjl\n-----END PRIVATE KEY-----\n",
  "client_email": "crf-slidemanager@alexandrevalent.iam.gserviceaccount.com",
  "client_id": "101959630014487618959",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/crf-slidemanager%40alexandrevalent.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
SCOPES = ['https://www.googleapis.com/auth/presentations', 'https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets.readonly']


# Authentification
credentials = service_account.Credentials.from_service_account_info(json.loads(CREDENTIALS_JSON, strict=False), scopes=SCOPES)

# Initialisation des services
slides_service = build('slides', 'v1', credentials=credentials)
drive_service = build('drive', 'v3', credentials=credentials)
gspread_client  = gspread.authorize(credentials)

# Chargement des données financières (à supprimer plus tard)

In [9]:
# Charger la Sheet
spreadsheet = gspread_client.open_by_url("https://docs.google.com/spreadsheets/d/1MTmIyho3XoDAhooTEMsab_tVxjGZxzqHymTRsANGj9c/")

In [10]:
# PRODUIT 2024
worksheet = spreadsheet.worksheet("DT_Prod")
df_prod = get_as_dataframe(worksheet)

# Transformer la 2e ligne (index 1) en en-têtes
df_prod.columns = df_prod.iloc[1]  # Ligne 2 devient les en-têtes
df_prod = df_prod.iloc[2:]

# Supprimer les deux dernières lignes
df_prod = df_prod.iloc[:-2]

# Modification du nom de la colonne utile
df_prod = df_prod.rename(columns={"Réalisé 2024 Total Année": "Financier Prod_2024",
                                  "Réalisé 2023 Total Année": "Financier Prod_2023",
                                  "Réalisé 2022 Total Année": "Financier Prod_2022",
                                  })

# Récupération des Département
df_prod["N Département"] = df_prod["N° Structure"].apply(lambda x: x.lstrip("0"))

# Sélection des colonnes
df_prod = df_prod[["N Département","Financier Prod_2022","Financier Prod_2023","Financier Prod_2024"]]

df_prod

2   N Département Financier Prod_2022 Financier Prod_2023 Financier Prod_2024
3               1           959737.28           881847.34           869883.02
4               3           242334.13            274750.7           281212.64
5               7           243465.22           179073.48           250747.99
6              15            50073.56             42236.3            98744.62
7              26          1163770.36          1061919.22          1060115.15
..            ...                 ...                 ...                 ...
105            44          1210929.25          1256753.76          1325582.95
106            49            369035.5           457155.24           552394.31
107            53           338528.21           339095.64           395031.88
108            72           2127549.9          2086597.24          2215727.76
109            85           909276.26           572137.51           719197.19

[107 rows x 4 columns]

In [11]:
# RES NET 2024
worksheet = spreadsheet.worksheet("DT_Res Net")
df_resnet = get_as_dataframe(worksheet)

# Transformer la 2e ligne (index 1) en en-têtes
df_resnet.columns = df_resnet.iloc[1]  # Ligne 2 devient les en-têtes
df_resnet = df_resnet.iloc[2:]

# Supprimer les deux dernières lignes
df_resnet = df_resnet.iloc[:-2]

# Modification du nom de la colonne utile
df_resnet = df_resnet.rename(columns={"Réalisé 2024 Total Année": "Financier ResNet_2024",
                                      "Réalisé 2023 Total Année": "Financier ResNet_2023",
                                      "Réalisé 2022 Total Année": "Financier ResNet_2022"})

# Récupération des Département
df_resnet["N Département"] = df_resnet["N° Structure"].apply(lambda x: x.lstrip("0"))

# Sélection des colonnes
df_resnet = df_resnet[["N Département","Financier ResNet_2022","Financier ResNet_2023","Financier ResNet_2024"]]

df_resnet

2,N Département,Financier ResNet_2022,Financier ResNet_2023,Financier ResNet_2024
3,1,146820.39,120441.98,69803.5
4,3,16027.98,-22595.97,-13687.53
5,7,25929.7,-47265.83,3324.23
6,15,-247.35,-6588.05,2034.92
7,26,181771.18,91493.37,61579.15
...,...,...,...,...
105,44,283221.99,345172.44,225959.58
106,49,7776.62,-11053.8,106952.66
107,53,61796.43,46173.0,569.94
108,72,94569.78,152577.92,104009.9
109,85,19702.26,22239.49,74813.66

In [12]:
# RES NET COR PROD 2024
worksheet = spreadsheet.worksheet("DT_Res corrélé Prod")
df_resnetcorprod = get_as_dataframe(worksheet, evaluate_formulas=True)

# Transformer la 2e ligne (index 1) en en-têtes
df_resnetcorprod.columns = df_resnetcorprod.iloc[1]  # Ligne 2 devient les en-têtes
df_resnetcorprod = df_resnetcorprod.iloc[2:]

# Supprimer les deux dernières lignes
df_resnetcorprod = df_resnetcorprod.iloc[:-2]

# Modification du nom de la colonne utile
df_resnetcorprod = df_resnetcorprod.rename(columns={"Réalisé 2024 Total Année": "Financier ResCorrProd_2024",
                                                    "Réalisé 2023 Total Année": "Financier ResCorrProd_2023",
                                                    "Réalisé 2022 Total Année": "Financier ResCorrProd_2022"})

# Récupération des Département
df_resnetcorprod["N Département"] = df_resnetcorprod["N° Structure"].apply(lambda x: x.lstrip("0"))

# Sélection des colonnes
df_resnetcorprod = df_resnetcorprod[["N Département","Financier ResCorrProd_2022","Financier ResCorrProd_2023","Financier ResCorrProd_2024"]]

df_resnetcorprod

2,N Département,Financier ResCorrProd_2022,Financier ResCorrProd_2023,Financier ResCorrProd_2024
3,1,0.15298,0.136579,0.080245
4,3,0.06614,-0.082242,-0.048673
5,7,0.106503,-0.263947,0.013257
6,15,-0.00494,-0.155981,0.020608
7,26,0.156192,0.086159,0.058087
...,...,...,...,...
105,44,0.233888,0.274654,0.170461
106,49,0.021073,-0.02418,0.193617
107,53,0.182544,0.136165,0.001443
108,72,0.04445,0.073123,0.046942
109,85,0.021668,0.038871,0.104024

In [13]:
# TRESO 2024
worksheet = spreadsheet.worksheet("DT_Trés brute")
df_treso = get_as_dataframe(worksheet)

# Transformer la 2e ligne (index 1) en en-têtes
df_treso.columns = df_treso.iloc[1]  # Ligne 2 devient les en-têtes
df_treso = df_treso.iloc[2:]

# Supprimer les deux dernières lignes
df_treso = df_treso.iloc[:-2]

# Modification du nom de la colonne utile
df_treso = df_treso.rename(columns={"31/12/2024": "Financier TresoBrute_2024",
                                                    })
df_treso.columns.values[10] = "Financier Mois_AvanceTreso_2024" # Obligatoire car plusieurs col au meme noms

# Récupération des Département
df_treso["N Département"] = df_treso["N° Structure"].apply(lambda x: x.lstrip("0"))

# Sélection des colonnes
df_treso = df_treso[["N Département","Financier TresoBrute_2024","Financier Mois_AvanceTreso_2024"]]

df_treso

2   N Département Financier TresoBrute_2024 Financier Mois_AvanceTreso_2024
3               1                2349996.53                       32.863518
4               3                 656815.92                       25.579687
5               7                 481073.45                       22.484103
6              15                 125079.95                       15.256254
7              26                1662079.36                       19.079702
..            ...                       ...                             ...
105            44                4061139.12                        41.06654
106            49                 796406.93                       20.772122
107            53                 456458.02                       13.509127
108            72                2095771.97                       11.803771
109            85                1760099.08                       31.138845

[107 rows x 3 columns]

In [14]:
# FUSION DES DF

df_all_financier = pd.merge(df_prod, df_resnet, on="N Département", how="outer")
df_all_financier = pd.merge(df_all_financier, df_resnetcorprod, on="N Département", how="outer")
df_all_financier = pd.merge(df_all_financier, df_treso, on="N Département", how="outer")

df_all_financier

2,N Département,Financier Prod_2022,Financier Prod_2023,Financier Prod_2024,Financier ResNet_2022,Financier ResNet_2023,Financier ResNet_2024,Financier ResCorrProd_2022,Financier ResCorrProd_2023,Financier ResCorrProd_2024,Financier TresoBrute_2024,Financier Mois_AvanceTreso_2024
0,1,959737.28,881847.34,869883.02,146820.39,120441.98,69803.5,0.15298,0.136579,0.080245,2349996.53,32.863518
1,10,1001143.18,993786.33,1021781.8,93971.22,-62505.73,-13670.71,0.093864,-0.062897,-0.013379,565535.69,6.520543
2,11,509832.03,391942.07,509219.8,178365.84,57739.29,125181.47,0.349852,0.147316,0.24583,1052505.09,30.366622
3,12,266820.91,271984.6,332599.51,31133.28,18372.84,49588.1,0.116682,0.067551,0.149093,483186.82,19.9344
4,13,2731407.17,2908617.24,2882188.55,448381.77,226594.43,-51368.29,0.164158,0.077905,-0.017823,5135836.84,20.417004
...,...,...,...,...,...,...,...,...,...,...,...,...
102,977,85780.31,114053.21,97164.52,64435.55,92677.2,85010.49,0.751169,0.812579,0.874913,658799.43,319.504656
103,978,42387.4,46096,47911.07,-19556.26,-42353.11,-38465.34,-0.46137,-0.918802,-0.802849,80740.87,11.271673
104,986,0,0,3196.08,0,0,2776.14,NaN,NaN,0.868608,2008.14,4.488718
105,987,0,1099046.67,910442.87,0,338856.99,24007.08,NaN,0.308319,0.026369,848571,11.65799
106,988,0,754292.18,1136238,0,1736.38002,-764.1,NaN,0.002302,-0.000672,370481.28,3.835414

# Chargement et agrégation des données

In [15]:
# Fonction générique pour calculer la somme d'une colonne numérique
def calculate_sum_column(df, col_name):
    # Calculer la somme de la colonne spécifiée
    sum_column = df[col_name].sum()
    return str(int(sum_column))

# Fonction pour calculer la proportion de "" dans une colonne
def calculate_prop_column(df, col_name, string):
    # Calculer la somme de la colonne spécifiée
    prop = df[col_name].value_counts(normalize=True).get(string, 0)
    prop = int(prop * 100)
    prop = f"{prop}%"
    return prop

# Fonction pour calculer le nombre de pilier
def calculate_nb_piliers(df):
    piliers_cols = ["Atteinte_pilier_1_CNAC", "Atteinte_pilier_2_CNAC", "Atteinte_pilier_3_CNAC"]
    # Garder uniquement les valeurs "Oui" et "Non", mettre le reste à NaN
    df_valid = df[piliers_cols].where(df[piliers_cols].isin(["Oui", "Non"]))
    # Compter les "Oui" par ligne
    nb_piliers_atteints = (df_valid == "Oui").sum(axis=1)
    # Garder les lignes où au moins une valeur est "Oui" ou "Non"
    lignes_valides = df_valid.notna().any(axis=1)
    # Calculer la moyenne uniquement sur ces lignes
    avg_piliers_atteints = round(nb_piliers_atteints[lignes_valides].mean(), 1)
    return str(avg_piliers_atteints)


# Fonction pour compter le nombre de fois où la mention "Menée" apparaît dans une colonne
def count_mention_menee(df, col_name):
    # Compter le nombre de fois où "Menée" apparaît dans la colonne spécifiée
    count_menee = df[col_name].value_counts().get("Menée", 0)
    return str(int(count_menee))



# Fonction pour compater la vision CNAC et consolidée
def indice_confiance(df,activite):
    col_cnac = f"{activite} Activite_CNAC"
    col_conso = f"{activite} Activite_Conso"

    df_temp = df.copy()

    df_temp = df_temp[df_temp["type_structure"] != "DELEGATION TERRITORIALE - DT"]

    nb_identiques = (df_temp[col_cnac] == df_temp[col_conso]).sum()
    pourcentage = nb_identiques / (len(df_temp))

    return pourcentage



def compter_menees_conso_allcol(df):
    # Sélection des colonnes ciblées
    colonnes_concernees = [col for col in df.columns if col.endswith("Activite_Conso")]

    # Comptage des "Menée" dans ces colonnes
    total_menees = (df[colonnes_concernees] == "Menée").sum().sum()

    return int(total_menees)

In [16]:
# Charger le DataFrame
spreadsheet = gspread_client.open_by_url("https://docs.google.com/spreadsheets/d/12209rdIzFFO0TeWzNl8pylpxaEHppcwfKelYGMCqe4M/")
worksheet = spreadsheet.worksheet("Agrégation par structure")
df_raw = get_as_dataframe(worksheet)

In [17]:
df = df_raw.copy()

# Filtrer le DataFrame sur le bon type de structure et exclure l'outre mer
df = df[
    df["type_structure"].isin(["DELEGATION TERRITORIALE - DT", "UNITE LOCALE - UL", "ANTENNE LOCALE - AL"])
    & ~df["N_dept"].str.startswith(("97", "98"))
]

# Liste des DT à traiter
DT_TO_DO = df [df["type_structure"] == "DELEGATION TERRITORIALE - DT"]["nom_structure"].tolist()

In [18]:
df_agg = get_as_dataframe(gspread_client.open_by_url("https://docs.google.com/spreadsheets/d/12209rdIzFFO0TeWzNl8pylpxaEHppcwfKelYGMCqe4M/").worksheet("Agrégation par DT"))

# Retirer les .0
df_agg = df_agg.applymap(
    lambda x: int(x) if isinstance(x, float) and x.is_integer() else x
)

/tmp/ipython-input-1573514771.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_agg = df_agg.applymap(

In [19]:
# Ajout des données financières A SUPPRIMER
df_agg = pd.merge(df_agg, df_all_financier, left_on="N_dept", right_on="N Département", how="left" )

# Remplace les nan par des"-"
df_agg = df_agg.fillna("-")

df_agg = df_agg.rename(columns={'DT': 'Rattachement'})

df_agg["Rattachement"] = df_agg["Rattachement"].str.replace(r"^\d+\s*-\s*", "", regex=True)

df_agg = df_agg.sort_values(by="Rattachement")


df_agg

/tmp/ipython-input-3095916913.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_agg = df_agg.fillna("-")

,Rattachement,code_insee,N_dept,nom_structure,adresse_complete,lon,lat,Structure Taux_nvx_formes_CRB_2025,Structure Taux_formation_CRB,Structure Nb_Benevoles,...,Financier Prod_2023,Financier Prod_2024,Financier ResNet_2022,Financier ResNet_2023,Financier ResNet_2024,Financier ResCorrProd_2022,Financier ResCorrProd_2023,Financier ResCorrProd_2024,Financier TresoBrute_2024,Financier Mois_AvanceTreso_2024
24,DT D'EURE ET LOIR,28085,28,DT D'EURE ET LOIR,"38 Avenue D'ORLEANS, 28000 CHARTRES",1.508136,48.433208,192.111,259.452,143,...,501432.10,508765.48,-127792.87,-81893.46,-31268.47,-0.344178,-0.163319,-0.061459,762827.24,17.446061
47,DT D'INDRE ET LOIRE,37261,37,DT D'INDRE ET LOIRE,"169 bis Rue des Douets, 37100 TOURS",0.686287,47.432069,1300.683,986.477,1432,...,1368424.26,1586851.26,133373.69,794090.67,216113.49,0.102412,0.580296,0.136190,2458450.78,20.880372
16,DT DE CHARENTE MARITIME,17300,17,DT DE CHARENTE MARITIME,"37 Rue PHILIPPE VINCENT, 17000 LA ROCHELLE",-1.175222,46.153874,327.960,312.511,270,...,610262.18,596001.69,90363.36,77094.90,74171.95,0.13781,0.126331,0.124449,821826.15,17.610589
32,DT DE FUTUNA,-,986,DT DE FUTUNA,", 98610 ALO",-,-,43.255,78.925,17,...,0.00,3196.08,0.00,0.00,2776.14,-,-,0.868608,2008.14,4.488718
27,DT DE HAUTE GARONNE,31555,31,DT DE HAUTE GARONNE,"71 Chemin DES CAPELLES, 31300 TOULOUSE",1.430371,43.598166,629.447,939.954,775,...,1182540.44,1686997.31,-20521.14,-100565.45,126486.27,-0.019936,-0.085042,0.074977,1794588.84,13.790926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,DT DU TERRITOIRE DE BELFORT,90010,90,DT DU TERRITOIRE DE BELFORT,"15 Avenue du Général Sarrail, 90000 BELFORT",6.862228,47.63539,199.488,205.873,221,...,471795.11,371153.13,88298.61,136316.37,5174.82,0.278571,0.288931,0.013943,429993.95,13.890856
1,DT DU VAL D'OISE,95229,95,DT DU VAL D'OISE,"1 bis Rue Henri Dunant, 95460 EZANVILLE",2.343581,49.034773,519.039,789.539,709,...,1398883.88,1493196.98,93404.33,170988.14,-124741.48,0.059968,0.122232,-0.083540,2361842.03,17.038343
107,DT DU VAL DE MARNE,94044,94,DT DU VAL DE MARNE,"2 Rue ALBERT GARRY, 94450 LIMEIL BREVANNES",2.477818,48.754182,925.959,1014.951,939,...,1327073.44,1235949.97,243186.91,223907.77,-152720.48,0.163414,0.168723,-0.123565,2624300.00,21.799823
45,DT DU VAR,83090,83,DT DU VAR,"201 Chemin DE FAVEYROLLES, 83190 OLLIOULES",5.875984,43.130635,557.818,728.767,772,...,909918.46,905735.01,266200.82,272786.07,230550.49,0.318262,0.299792,0.254545,3872449.78,57.542136
98,DT DU VAUCLUSE,84007,84,DT DU VAUCLUSE,"20 Boulevard HENRY DUNANT, 84000 AVIGNON",4.820061,43.942145,431.003,532.763,356,...,548108.86,630694.06,30509.59,-29305.60,39593.70,0.052656,-0.053467,0.062778,1344170.25,26.140249

In [20]:
regions_departements = {
    "AUVERGNE RHONE ALPES": ["1", "3", "7", "15", "26", "38", "42", "43", "63", "69", "73", "74"],
    "BOURGOGNE FRANCHE COMTE": ["21", "25", "39", "58", "70", "71", "89", "90"],
    "BRETAGNE": ["22", "29", "35", "56"],
    "CENTRE VAL DE LOIRE": ["18", "28", "36", "37", "41", "45"],
    "GRAND EST": ["8", "10", "51", "52", "54", "55", "57", "67", "68", "88"],
    "HAUTS DE FRANCE": ["2", "59", "60", "62", "80"],
    "ILE DE FRANCE": ["75", "77", "78", "91", "92", "93", "94", "95"],
    "NORMANDIE": ["14", "27", "50", "61", "76"],
    "NOUVELLE AQUITAINE": ["16", "17", "19", "23", "24", "33", "40", "47", "64", "79", "86", "87"],
    "OCCITANIE": ["9", "11", "12", "30", "31", "32", "34", "46", "48", "65", "66", "81", "82"],
    "PAYS DE LA LOIRE": ["44", "49", "53", "72", "85"],
    "PROVENCE ALPES COTE D'AZUR CORSE": ["4", "5", "6", "13", "83", "84", "2 A", "2 B", "2A", "2B"]
}

In [21]:
df_struct_agg = df.copy()

In [22]:
# Ajout des données financières A SUPPRIMER
df_struct_agg = pd.merge(df_struct_agg, df_all_financier, left_on="N_dept", right_on="N Département", how="left" )

In [23]:
df_struct_agg["Financier ResCorrProd_2022"] = (
    pd.to_numeric(df_struct_agg["Financier ResNet_2022"], errors="coerce") /
    pd.to_numeric(df_struct_agg["Financier Prod_2022"], errors="coerce")
)

df_struct_agg["Financier ResCorrProd_2023"] = (
    pd.to_numeric(df_struct_agg["Financier ResNet_2023"], errors="coerce") /
    pd.to_numeric(df_struct_agg["Financier Prod_2023"], errors="coerce")
)

df_struct_agg["Financier ResCorrProd_2024"] = (
    pd.to_numeric(df_struct_agg["Financier ResNet_2024"], errors="coerce") /
    pd.to_numeric(df_struct_agg["Financier Prod_2024"], errors="coerce")
)

df_struct_agg[["Financier ResCorrProd_2022", "Financier ResCorrProd_2023", "Financier ResCorrProd_2024"]]

,Financier ResCorrProd_2022,Financier ResCorrProd_2023,Financier ResCorrProd_2024
0,0.278571,0.288931,0.013943
1,0.204894,0.109193,0.078048
2,0.204894,0.109193,0.078048
3,0.204894,0.109193,0.078048
4,0.204894,0.109193,0.078048
...,...,...,...
826,0.010032,0.072379,0.120155
827,0.010032,0.072379,0.120155
828,0.010032,0.072379,0.120155
829,0.010032,0.072379,0.120155
830,0.010032,0.072379,0.120155

# Réalisation des rapports

## Config tableaux

In [24]:
config_pages = [

      {"nom" : "Financier",
       "page" : 8,
       "col" : ["nom_structure",'Financier Prod_2024','Financier ResNet_2024','Financier ResCorrProd_2024','Financier TresoBrute_2024','Financier Mois_AvanceTreso_2024'],
       "rename_dict" : {"nom_structure":"Nom",
                        'Financier Prod_2024' : "Produit\n2024",
                        'Financier ResNet_2024' : "Résultat\nNet 2024",
                       # 'Financier ResCorrProd_2024' : "Rapport\nResNet/Prod",
                        "Financier TresoBrute_2024": "Trésorerie\nBrute 2024",
                       # "Financier Mois_AvanceTreso_2024": "Mois d'avancede\nde trésorerie",
                        },
       "color" : Couleurs[8]
       },


      {"nom" : "Priorité Mouvement - Cadre de l'action",
       "page" : 11,
       "col" : ["nom_structure", 'Structure Nb_Benevoles', 'Structure Nb_Adherents', 'Structure Nb_formes_CRB_2025', 'Structure Taux_nvx_formes_CRB_2025', 'Structure Taux_formation_CRB', 'Structure Nb_formes_TCAS_2025'],
       "rename_dict" : {"nom_structure":"Nom",
                        'Structure Nb_Benevoles' : "Nb de\nbenevoles",
                        'Structure Nb_Adherents' : "Nb d'adherents",
                        'Structure Nb_formes_CRB_2025' : "Nb formés CRB",
                        'Structure Taux_nvx_formes_CRB_2025' : "Nb nouveaux*\nbénévoles\nformés CRB",
                        'Structure Taux_formation_CRB' : "Taux bénévoles\nformés CRB",
                        'Structure Nb_formes_TCAS_2025' : "Nb formés TCAS",
                        },
       "color" : Couleurs[11]
       },



      {"nom" : "Priorité Crise - Cadre de l'action",
       "page" : 14,
       "col" : ["nom_structure",'Dispositifs_d_urgence Nb_conventions_prefecture','Dispositifs_d_urgence Nb_conventions_operateurs', 'Dispositifs_d_urgence Nb_agrements'],
       "rename_dict" : {"nom_structure":"Nom",
                        'Dispositifs_d_urgence Nb_conventions_prefecture' : "Nb de\ndéclinaison\nDGSCGC",
                        'Dispositifs_d_urgence Nb_conventions_operateurs' : "Nb de\nconventions",
                        'Dispositifs_d_urgence Nb_agrements' : "Nb d'agréments\nterritoriaux\nA, B et AB",
                        },
       "color" : Couleurs[14]
       },



            {"nom" : "Priorité Crise - Schémas opérationnels",
       "page" : 16,
       "col" : ["nom_structure",'Dispositifs_d_urgence Nb_declenchements','Dispositifs_d_urgence Nb_operations', 'Dispositifs_d_urgence Nb_personnes_prises_charge'],
       "rename_dict" : {"nom_structure":"Nom",
                        'Dispositifs_d_urgence Nb_declenchements' : "Nb de\ndéclenchement",
                        'Dispositifs_d_urgence Nb_operations' : "Nb\nd'opérations",
                        'Dispositifs_d_urgence Nb_personnes_prises_charge' : "Nb de\npersonnes\nprises en charge",
                        },
       "color" : Couleurs[16]
       },



       {"nom" : "Priorité Crise - Moyens matériels",
       "page" : 18,
       "col" : ["nom_structure",'Dispositifs_d_urgence Nb_lots_CAI','Dispositifs_d_urgence Nb_lots_CHU', 'Dispositifs_d_urgence Nb_lots_CMCC', 'Dispositifs_d_urgence Utilisation_RedCall', 'Dispositifs_d_urgence Utilisation_Minutis'],
       "rename_dict" : {"nom_structure":"Nom",
                        'Dispositifs_d_urgence Nb_lots_CAI' : "Nb de lots CAI",
                        'Dispositifs_d_urgence Nb_lots_CHU' : "Nb de lots CHU",
                        'Dispositifs_d_urgence Nb_lots_CMCC' : "Nb de lots CMCC",
                        'Dispositifs_d_urgence Utilisation_RedCall' : "Utilisation de\nRedCall",
                        'Dispositifs_d_urgence Utilisation_Minutis' : "Utilisation de\nMinutis",
                        },
       "color" : Couleurs[18]
       },



       {"nom" : "Priorité Crise - Préparation des acteurs",
       "page" : 20,
       "col" : ["nom_structure",'Dispositifs_d_urgence Nb_exercices','Dispositifs_d_urgence PST', 'Dispositifs_d_urgence Taux_formation_TCAU_2025', 'Dispositifs_d_urgence Taux_formation_PSP_2025', 'Dispositifs_d_urgence Taux_formation_GQS_2025', 'Dispositifs_d_urgence Nb_volontaires_urgence', 'Dispositifs_d_urgence Taux_formation_TCEO_2025', 'Dispositifs_d_urgence Taux_formation_IRR_2025'],
       "rename_dict" : {"nom_structure":"Nom",
                        'Dispositifs_d_urgence Nb_exercices' : "Nb d'\nexercices'",
                        'Dispositifs_d_urgence PST' : "Existence\nPST",
                        'Dispositifs_d_urgence Taux_formation_TCAU_2025' : "Taux de\nformation TCAU\n volontaires\nde l'urgence",
                        'Dispositifs_d_urgence Taux_formation_PSP_2025' : "Taux de\nformation PSP\n volontaires\nde l'urgence",
                        'Dispositifs_d_urgence Taux_formation_GQS_2025' : "Taux de\nformation GQS\n volontaires\nde l'urgence",
                        'Dispositifs_d_urgence Nb_volontaires_urgence' : "Nb\n volontaires\nde l'urgence",
                        'Dispositifs_d_urgence Taux_formation_TCEO_2025' : "Taux de\nformation TCEO\n volontaires\nde l'urgence",
                        'Dispositifs_d_urgence Taux_formation_IRR_2025' : "Taux de\nformation IRR\n volontaires\nde l'urgence",
                        },
       "color" : Couleurs[20]
       },




      {"nom" : "Formation Grand Public",
       "page" : 24,
       "col" : ["nom_structure",'Formation_grand_public Activite_Conso',"Formation_grand_public Nb_formes_PSC_2025", "Formation_grand_public Nb_formes_GQS_2025", "Formation_grand_public Nb_sessions_PSC_2025", "Formation_grand_public Nb_sessions_GQS_2025", "Formation_grand_public Taux_reussite_PSC_2025", "Formation_grand_public Taux_reussite_GQS_2025", "Formation_grand_public Nb_FPSC", "Formation_grand_public Nb_AGQS"],
       "rename_dict" : {"nom_structure":"Nom",
                        'Formation_grand_public Activite_Conso' : "Vision\nconsolidée*",
                        'Formation_grand_public Nb_formes_PSC_2025' : "Nb formés\nPSC",
                        "Formation_grand_public Nb_formes_GQS_2025" : "Nb formés\nGQS",
                        "Formation_grand_public Nb_sessions_PSC_2025" : "Nb sessions\nPSC",
                        "Formation_grand_public Nb_sessions_GQS_2025" : "Nb sessions\nGQS",
                        "Formation_grand_public Taux_reussite_PSC_2025" : "Taux\nréussite\nPSC",
                        "Formation_grand_public Taux_reussite_GQS_2025" : "Taux\nréussite\nGQS",
                        "Formation_grand_public Nb_FPSC" : "Nb\nformateurs\nPSC",
                        "Formation_grand_public Nb_AGQS" : "Nb\nformateurs\nGQS",
                        },
       "color" : Couleurs[24]
       },


       {"nom" : "Formation Grand Public",
       "page" : 25,
       "col" : ["nom_structure", 'Formation_grand_public Activite_Conso',"Formation_grand_public Nb_formes_IPSEN_2025", "Formation_grand_public Nb_formes_IPS_2025", "Formation_grand_public Nb_formes_PREVIC_2025", "Formation_grand_public Nb_sessions_IPSEN_2025", "Formation_grand_public Nb_sessions_IPS_2025", "Formation_grand_public Nb_sessions_PREVIC_2025", "Formation_grand_public Taux_reussite_IPSEN_2025", "Formation_grand_public Nb_FIPSEN"],
       "rename_dict" : {"nom_structure":"Nom",
                        'Formation_grand_public Activite_Conso' : "Vision\nconsolidée*",
                        'Formation_grand_public Nb_formes_IPSEN_2025' : "Nb formés\nIPSEN",
                        "Formation_grand_public Nb_formes_IPS_2025" : "Nb formés\nIPS",
                        'Formation_grand_public Nb_formes_PREVIC_2025' : "Nb formés\nPREVIC",
                        "Formation_grand_public Nb_sessions_IPSEN_2025" : "Nb sessions\nIPSEN",
                        "Formation_grand_public Nb_sessions_IPS_2025" : "Nb sessions\nIPS",
                        "Formation_grand_public Nb_sessions_PREVIC_2025" : "Nb sessions\nPREVIC",
                        "Formation_grand_public Taux_reussite_IPSEN_2025" : "Taux\nréussite\nIPSEN",
                        "Formation_grand_public Nb_FIPSEN" : "Nb\nformateurs\nIPSEN",
                        },
       "color" : Couleurs[25]
       },


      {"nom" : "Option Croix-Rouge",
       "page" : 27,
       "col" : ["nom_structure",'OCR Nb_deployees','OCR Nb_referents'],
       "rename_dict" : {"nom_structure":"Nom",
                        'OCR Nb_deployees' : "Nb d'OCR\ndéployées",
                        'OCR Nb_referents' : "Nb\nréférents",
                        },
       "color" : Couleurs[27]
       },



      {"nom" : "Maraudes",
       "page" : 30,
       "col" : ["nom_structure","Maraude Nb_maraudes_PEGASS", "Maraude Nb_maraudes_SIGMA", "Maraude Nb_benevoles_actifs", "Maraude Nb_SOLIDAR", "Maraude Nb_contacts", "Maraude Nb_personnes_rencontrees"],
       "rename_dict" : {"nom_structure":"Nom",
                        "Maraude Nb_maraudes_PEGASS":"Nb maraudes\nréalisées",
                        "Maraude Nb_maraudes_SIGMA":"Nb maraudes\nsaisies \ndans SIGMA",
                        "Maraude Nb_benevoles_actifs":"Nb volontaires\nmobilisés\nactions maraudes",
                        "Maraude Nb_SOLIDAR":"Nb volontaires\nformés SOLIDAR",
                        "Maraude Nb_contacts":"Nb personnes\nrencontrées\n(contacts)",
                        "Maraude Nb_personnes_rencontrees":"Nb total\npersonnes\nrencontrées",
                        },
       "color" : Couleurs[30]
       },



      {"nom" : "Secours",
       "page" : 34,
       "col" : ["nom_structure","Secours Activite_Conso","Secours Nb_PSE1", "Secours Nb_PSE2", "Secours Nb_CI", "Secours Taux_recy26_PSE1", "Secours Taux_recy26_PSE2", "Secours Taux_recy26_CI", "Secours Taux_ren25_PSE1", "Secours Taux_ren25_PSE2", "Secours Taux_ren25_CI"],
       "rename_dict" : {"nom_structure":"Nom",
                        'Secours Activite_Conso' : "Vision\nconsolidée\nformation*",
                        'Secours Nb_PSE1' : "Nb\nPSE1",
                        'Secours Nb_PSE2' : "Nb\nPSE2",
                        'Secours Nb_CI' : "Nb CI",
                        'Secours Taux_recy26_PSE1' : "% de PSE1\nrecyclés\npour 2026",
                        'Secours Taux_recy26_PSE2' : "% de PSE2\nrecyclés\npour 2026",
                        'Secours Taux_recy26_CI' : "% de CI\nrecyclés\npour 2026",
                        'Secours Taux_ren25_PSE1' : "% nouveaux\n formés PSE1\nen 2025",
                        'Secours Taux_ren25_PSE2' : "% nouveaux\n formés PSE2\nen 2025",
                        'Secours Taux_ren25_CI' : "% nouveaux\n formés CI\nen 2025",
                        },
       "color" : Couleurs[34]
       },


        {"nom" : "Secours",
       "page" : 35,
       "col" : ["nom_structure", "Secours Activite_Conso", "Secours Nb_sessions_PSE", "Secours Nb_sessions_CI", "Secours Nb_sessions_FPSE"],
       "rename_dict" : {"nom_structure":"Nom",
                        'Secours Activite_Conso' : "Vision\nconsolidée\nformation*",
                        'Secours Nb_sessions_PSE' : "Nb sessions\nformation\nPSE",
                        'Secours Nb_sessions_CI' : "Nb sessions\nformation\nCI",
                        'Secours Nb_sessions_FPSE' : "Nb sessions\nformation\nFPSE",
                        },
       "color" : Couleurs[35]
       },


      {"nom" : "Secours",
       "page" : 36,
       "col" : ["nom_structure", "Secours Activite_Conso","Secours Taux_IS_actifs", "Secours Nb_DPS_2025", "Secours Nb_PAPS_2025", "Secours Nb_DPS_PE_2025", "Secours Nb_DPS_ME_2025", "Secours Nb_DPS_GE_2025", "Secours Nb_agrements_DPS_2025", "Secours Produits_DPS_2025"],
       "rename_dict" : {"nom_structure":"Nom",
                        'Secours Activite_Conso' : "Vision\nconsolidée\nactivité*", # Différencier cet indicateur avec page 32
                        'Secours Taux_IS_actifs' : "Taux IS\nactifs",
                        'Secours Nb_DPS_2025' : "Nb DPS\n2025",
                        'Secours Nb_PAPS_2025' : "Nb PAPS\n2025",
                        'Secours Nb_DPS_PE_2025' : "Nb DPS\nPE 2025",
                        'Secours Nb_DPS_ME_2025' : "Nb DPS\nME 2025",
                        'Secours Nb_DPS_GE_2025' : "Nb DPS\nGE 2025",
                        'Secours Nb_agrements_DPS_2025' : "Nb agréments\nDPS 2025",
                        'Secours Produits_DPS_2025' : "Produits\nDPS 2025",
                        },
       "color" : Couleurs[36]
       },



      {"nom" : "AEO",
       "page" : 39,
       "col" : ["nom_structure",'AEO Activite_Conso','AEO Structure_activite_fixe', 'AEO Structure_activite_mobile', 'AEO Nb_benevoles_actifs', 'AEO Nb_responsables', 'AEO Nb_AAD', 'AEO Nb_PA_AEO_AAD', 'AEO Nb_personnes_domiciliees_crf', 'AEO Nb_PA_dispos_mobiles'],
       "rename_dict" : {"nom_structure":"Nom",
                        'AEO Activite_Conso' : "Vision\nconsolidée*",
                        'AEO Structure_activite_fixe' : "Activité\nfixe",
                        'AEO Structure_activite_mobile' : "Activité\nmobile",
                        'AEO Nb_benevoles_actifs' : "Nb\nbénevoles\nactifs",
                        'AEO Nb_responsables' : "Nb\nresponsables\nAEO",
                        'AEO Nb_AAD' : "Nb\nvolontaires\nformés AAD",
                        'AEO Nb_PA_AEO_AAD' : "Nb personnes\naccompagnées\npar AEO/AAD",
                        'AEO Nb_personnes_domiciliees_crf' : "Nb\npersonnes\ndomiciliées\nà la CRf",
                        'AEO Nb_PA_dispos_mobiles' : "Nb personnes\naccompagnées par\ndispositifs mobiles",
                        },
       "color" : Couleurs[39]
       },



      {"nom" : "Aide_alimentaire",
       "page" : 45,
       "col" : ["nom_structure",'Aide_alimentaire Nb_U2A', 'Aide_alimentaire Nb_Centre_distribution_alimentaire', 'Aide_alimentaire Nb_epiceries_sociales'],
       "rename_dict" : {"nom_structure":"Nom",
                        'Aide_alimentaire Nb_U2A' : "Nb U2A",
                        'Aide_alimentaire Nb_Centre_distribution_alimentaire' : "Centre de distribution\nalimentaire",
                        'Aide_alimentaire Nb_epiceries_sociales' : "Epiceries sociales"
                        },
       "color" : Couleurs[45]
       },



      {"nom" : "Textile",
       "page" : 43,
       "col" : ["nom_structure",'Textile Nb_dispositifs', 'Textile Produit_2025', 'Textile Resultat_2025'],
       "rename_dict" : {"nom_structure":"Nom",
                        'Textile Nb_dispositifs' : "Nb\ndispositifs",
                        'Textile Produit_2025' : "Produit d'exploitation\n2025",
                        'Textile Resultat_2025' : "Résultat d'exploitation\n2025",
                        },
       "color" : Couleurs[43]
       },

]

## Config Remplacement textes

In [25]:
def format_int(x):
  """Permet de passer de float à entier au format string"""
  try:
      if x == "-":
          return "-"
      else:
          x_int = str(int(x))
          return x_int
  except:
      print("   Erreur transcription en entier de : ",x)
      return x


def format_euro(nombre):
    """Formate un nombre (positif ou négatif) en euros sans décimales, avec des espaces pour les milliers."""
    try:
        if nombre == "-":
            return "-"
        else:
            signe = "-" if nombre < 0 else ""
            nombre_abs = abs(int(nombre))
            return f"{signe} {nombre_abs:,}".replace(",", " ") + " €"
    except:
        print("   Erreur transcription en nombre de : ",nombre)
        return nombre



def format_pourcentage(nombre):
    """Transforme un float (comme -0.0860127) en pourcentage français avec 1 décimale."""
    valeur = round(nombre * 100, 1)
    signe = "- " if valeur < 0 else ""
    valeur_abs = abs(valeur)
    entier, decimal = str(f"{valeur_abs:.1f}").split(".")
    return f"{signe} {entier},{decimal} %"


def format_mois(nombre):
    """Arrondit un nombre à l'entier le plus proche et ajoute 'mois'."""
    return f"{round(nombre)} mois"


def make_replacements_textes(DT):

  replacements_textes = [
      ('{nom_dt}', DT),

      ('{p.béné}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Structure Nb_Benevoles"].iloc[0])),
      ('{p.adhé}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Structure Nb_Adherents"].iloc[0])),
      ('{p.crb}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Structure Nb_formes_CRB_2025"].iloc[0])),
      ('{p.nb.crb}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Structure Taux_nvx_formes_CRB_2025"].iloc[0])),
      ('{p.tcrb}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Structure Taux_formation_CRB"].iloc[0])),
      ('{p.tcas}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Structure Nb_formes_TCAS_2025"].iloc[0])),

      ('{f.pex}', format_euro (df_agg.loc[df_agg["nom_structure"] == DT]["Financier Prod_2025"].iloc[0])),
      ('{f.rnet}', format_euro(df_agg.loc[df_agg["nom_structure"] == DT]["Financier ResNet_2025"].iloc[0])),
    #  ('{f.rap}', format_pourcentage(df_agg.loc[df_agg["nom_structure"] == DT]["Financier ResCorrProd_2024"].iloc[0])),
      ('{f.tres}', format_euro(df_agg.loc[df_agg["nom_structure"] == DT]["Financier TresoBrute_2025"].iloc[0])),
    #  ('{f.mav}', format_mois(df_agg.loc[df_agg["nom_structure"] == DT]["Financier Mois_AvanceTreso_2024"].iloc[0])),

      ('{fgp.fpsc}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Nb_FPSC"].iloc[0]),
      ('{fgp.agqs}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Nb_AGQS"].iloc[0]),
      ('{fgp.fipsen}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Nb_FIPSEN"].iloc[0]),
      ('{fgp.psc}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Nb_formes_PSC_2025"].iloc[0]),
      ('{fgp.r.psc}', format_pourcentage(df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Taux_reussite_PSC_2025"].iloc[0])),
      ('{fgp.gqs}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Nb_formes_GQS_2025"].iloc[0]),
      ('{fgp.r.gqs}', format_pourcentage(df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Taux_reussite_GQS_2025"].iloc[0])),
      ('{fgp.ip}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Nb_formes_IPSEN_2025"].iloc[0]),
      ('{fgp.r.ipsen}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Taux_reussite_IPSEN_2025"].iloc[0]),
      ('{fgp.ips}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Nb_formes_IPS_2025"].iloc[0]),
      ('{fgp.pr}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Nb_formes_PREVIC_2025"].iloc[0]),
      ('{fgp.f.p}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Nb_sessions_PSC_2025"].iloc[0]),
      ('{fgp.f.g}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Nb_sessions_GQS_2025"].iloc[0]),
      ('{fgp.f.ip}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Nb_sessions_IPSEN_2025"].iloc[0]),
      ('{fgp.f.i}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Nb_sessions_IPS_2025"].iloc[0]),
      ('{fgp.f.pr}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Nb_sessions_PREVIC_2025"].iloc[0]),
      ('{fgp.sa}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Structures_menant_activite"].iloc[0]),
      ('{fgp.ca}', df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Produits_2025"].iloc[0]),
      #('{fgp.conf}', format_pourcentage (df_agg.loc[df_agg["nom_structure"] == DT]["Formation_grand_public Indice_confiance"].iloc[0])),

      ('{ocr.sa}', df_agg.loc[df_agg["nom_structure"] == DT]["OCR Structures_menant_activite"].iloc[0]),
      ('{ocr.dep}', df_agg.loc[df_agg["nom_structure"] == DT][ "OCR Nb_deployees"].iloc[0]),
      ('{ocr.resp}', df_agg.loc[df_agg["nom_structure"] == DT][ "OCR Nb_referents"].iloc[0]),
      #('{ocr.conf}', format_pourcentage (df_agg.loc[df_agg["nom_structure"] == DT]["OCR Indice_confiance"].iloc[0])),

      ('{s.pse1}', format_int(df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Nb_PSE1"].iloc[0])),
      ('{s.rc.pse1}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Taux_recy26_PSE1"].iloc[0]),
      ('{s.rn.pse1}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Taux_ren25_PSE1"].iloc[0]),
      ('{s.pse2}', format_int(df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Nb_PSE2"].iloc[0])),
      ('{s.rc.pse2}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Taux_recy26_PSE2"].iloc[0]),
      ('{s.rn.pse2}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Taux_ren25_PSE2"].iloc[0]),
      ('{s.ci}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Secours Nb_CI"].iloc[0])),
      ('{s.rc.ci}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Taux_recy26_CI"].iloc[0]),
      ('{s.rn.ci}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Taux_ren25_CI"].iloc[0]),
      ('{s.isa}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Taux_IS_actifs"].iloc[0]),
      ('{s.fpse}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Nb_sessions_PSE"].iloc[0]),
      ('{s.fci}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Nb_sessions_CI"].iloc[0]),
      ('{s.ffpse}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Nb_sessions_FPSE"].iloc[0]),
      ('{s.dps}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Nb_DPS_2025"].iloc[0]),
      ('{s.paps}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Nb_PAPS_2025"].iloc[0]),
      ('{s.dpspe}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Nb_DPS_PE_2025"].iloc[0]),
      ('{s.dpsme}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Nb_DPS_ME_2025"].iloc[0]),
      ('{s.dpsge}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Nb_DPS_GE_2025"].iloc[0]),
      ('{s.adps}', df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Nb_agrements_DPS_2025"].iloc[0]),
      ('{s.ca}', format_euro(df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Produits_DPS_2025"].iloc[0])),
      ('{s.sa}', format_euro(df_agg.loc[df_agg["nom_structure"] == DT][ "Secours Structures_menant_activite"].iloc[0])),
      #('{s.conf}', format_pourcentage (df_agg.loc[df_agg["nom_structure"] == DT]["Secours Indice_confiance"].iloc[0])),

      ('{m.pegass}', df_agg.loc[df_agg["nom_structure"] == DT][ "Maraude Nb_maraudes_PEGASS"].iloc[0]),
      ('{m.sigma}', df_agg.loc[df_agg["nom_structure"] == DT][ "Maraude Nb_maraudes_SIGMA"].iloc[0]),
      ('{m.solidar}', df_agg.loc[df_agg["nom_structure"] == DT][ "Maraude Nb_SOLIDAR"].iloc[0]),
      ('{m.solidar2020}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Maraude Nb_SOLIDAR2020"].iloc[0])),
      ('{m.pdr}', df_agg.loc[df_agg["nom_structure"] == DT][ "Maraude Nb_personnes_rencontrees"].iloc[0]),
      ('{m.prc}', df_agg.loc[df_agg["nom_structure"] == DT][ "Maraude Nb_contacts"].iloc[0]),
      ('{m.bénéa}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Maraude Nb_benevoles_actifs"].iloc[0])),
      ('{m.fbénéa}', df_agg.loc[df_agg["nom_structure"] == DT][ "Maraude Nb_benevoles_actifs_formes"].iloc[0]),
      ('{m.sa}', df_agg.loc[df_agg["nom_structure"] == DT][ "Maraude Structures_menant_activite"].iloc[0]),
      #('{m.conf}', format_pourcentage (df_agg.loc[df_agg["nom_structure"] == DT]["Maraude Indice_confiance"].iloc[0])),

      ('{aeo.sa}', df_agg.loc[df_agg["nom_structure"] == DT]["AEO Structures_menant_activite"].iloc[0]),
      ('{aeo.fixe}', df_agg.loc[df_agg["nom_structure"] == DT]["AEO Structure_activite_fixe"].iloc[0]),
      ('{aeo.mob}', df_agg.loc[df_agg["nom_structure"] == DT]["AEO Structure_activite_mobile"].iloc[0]),
      ('{aeo.bénéa}', df_agg.loc[df_agg["nom_structure"] == DT]["AEO Nb_benevoles_actifs"].iloc[0]),
      ('{aeo.resp}', df_agg.loc[df_agg["nom_structure"] == DT]["AEO Nb_responsables"].iloc[0]),
      ('{aeo.aad}', df_agg.loc[df_agg["nom_structure"] == DT]["AEO Nb_AAD"].iloc[0]),
      ('{aeo.faad}', df_agg.loc[df_agg["nom_structure"] == DT]["AEO Nb_FAAD"].iloc[0]),
      ('{aeo.pa}', df_agg.loc[df_agg["nom_structure"] == DT]["AEO Nb_PA_AEO_AAD"].iloc[0]),
      ('{aeo.pdom}', df_agg.loc[df_agg["nom_structure"] == DT]["AEO Nb_personnes_domiciliees_crf"].iloc[0]),
      ('{aeo.pamob}', df_agg.loc[df_agg["nom_structure"] == DT]["AEO Nb_PA_dispos_mobiles"].iloc[0]),
      #('{aeo.conf}', format_pourcentage (df_agg.loc[df_agg["nom_structure"] == DT]["ALSO Indice_confiance"].iloc[0])),

      ('{tex.nb}', df_agg.loc[df_agg["nom_structure"] == DT]["Textile Nb_dispositifs"].iloc[0]),
      ('{tex.prod}', format_euro(df_agg.loc[df_agg["nom_structure"] == DT]["Textile Produit_2025"].iloc[0])),
      ('{tex.res}', format_euro(df_agg.loc[df_agg["nom_structure"] == DT]["Textile Resultat_2025"].iloc[0])),
      #('{tex.conf}', format_pourcentage (df_agg.loc[df_agg["nom_structure"] == DT]["Textile Indice_confiance"].iloc[0])),


      ('{du.satcau}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Structures_menant_activite_TCAU"].iloc[0])),
      ('{du.sapsp}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Structures_menant_activite_PSP"].iloc[0])),
      ('{du.sagqs}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Structures_menant_activite_GQS"].iloc[0])),
      ('{du.dgscgc}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Nb_conventions_prefecture"].iloc[0])),
      ('{du.c}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Nb_conventions_operateurs"].iloc[0])),
      ('{du.a}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Nb_agrements"].iloc[0])),
      ('{du.de}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Nb_declenchements"].iloc[0])),
      ('{du.ope}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Nb_operations"].iloc[0])),
      ('{du.ppc}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Nb_personnes_prises_charge"].iloc[0])),
      ('{du.cai}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Nb_lots_CAI"].iloc[0])),
      ('{du.chu}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Nb_lots_CHU"].iloc[0])),
      ('{du.cmcc}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Nb_lots_CMCC"].iloc[0])),
      ('{du.red}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Utilisation_RedCall"].iloc[0])),
      ('{du.min}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Utilisation_Minutis"].iloc[0])),
      ('{du.ex}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Nb_exercices"].iloc[0])),
      ('{du.pst}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence PST"].iloc[0])),
      ('{du.ttcau}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Taux_formation_TCAU_2025"].iloc[0])),
      ('{du.tpsp}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Taux_formation_PSP_2025"].iloc[0])),
      ('{du.tgqs}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Taux_formation_GQS_2025"].iloc[0])),
      ('{du.vurg}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Nb_volontaires_urgence"].iloc[0])),
      ('{du.ttceo}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Taux_formation_TCEO_2025"].iloc[0])),
      ('{du.tirr}', format_int(df_agg.loc[df_agg["nom_structure"] == DT]["Dispositifs_d_urgence Taux_formation_IRR_2025"].iloc[0])),

      ('{lupa.u2a}', df_agg.loc[df_agg["nom_structure"] == DT]["Aide_alimentaire Nb_U2A"].iloc[0]),
      ('{lupa.cda}', df_agg.loc[df_agg["nom_structure"] == DT]["Aide_alimentaire Nb_Centre_distribution_alimentaire"].iloc[0]),
      ('{lupa.epis}', df_agg.loc[df_agg["nom_structure"] == DT]["Aide_alimentaire Nb_epiceries_sociales"].iloc[0]),
      #('{lupa.conf}', format_pourcentage (df_agg.loc[df_agg["nom_structure"] == DT]["Aide_alimentaire Indice_confiance"].iloc[0])),


      ]

  return replacements_textes

In [26]:
# # ECRASE LA VALEUR AVEC TOUTES LES DT : A mettre en commentaire pour la réalisation des 96 rapports
# DT_TO_DO = [
#     "DT DE LA COTE D'OR",
#     "DT DE PARIS",
#     "DT DES BOUCHES DU RHONE",
#     "DT DE L'AIN"
#     ]

In [27]:
# Pour enlever les données 2024 qui ne serviront pas, à supprimer quand on aura les vrai données
for column in df_agg.columns:
    if "2024" in column :
      df_agg.rename(columns={column: column.replace("2024","2025")}, inplace=True)
    elif "2023" in column :
      df_agg.drop(column, axis=1, inplace=True)

In [28]:
# Suppression des pdf pour repartir à 0
def supprimer_pdfs(dossier):
    for fichier in os.listdir(dossier):
        if fichier.endswith(".pdf"):
            chemin_complet = os.path.join(dossier, fichier)
            os.remove(chemin_complet)
            print(f"🗑️ Supprimé : {chemin_complet}")

supprimer_pdfs('.')  # Pour le dossier courant

🗑️ Supprimé : ./temp.pdf
🗑️ Supprimé : ./DT DE L'ARDECHE.pdf
🗑️ Supprimé : ./RAPPORT DT DE L'ARDECHE.pdf
🗑️ Supprimé : ./DT DU VAL D'OISE.pdf
🗑️ Supprimé : ./RAPPORT DT DES ALPES MARITIMES.pdf
🗑️ Supprimé : ./RAPPORT DT DU VAL D'OISE.pdf
🗑️ Supprimé : ./DT DES ALPES MARITIMES.pdf

## Remplacement textes

In [29]:
###########################################
# ETAPE 1 : CREATION DES PDF AVEC G SLIDE #
###########################################

# Identification les diapositives originales
# TEMPLATE_ID = "1Y9_MEmyZ3N24hPguqcm01xAkNtapuQBzOhBhe8V3z_g" # Template v2
TEMPLATE_ID = "1g2_HMuJ9L0pcsVOU0JPmc9C7NFUNT5BEQ-Yc90CSVZE" # Doc Technique
presentation = slides_service.presentations().get(presentationId=TEMPLATE_ID, fields='slides').execute()
original_slide_ids = [slide['objectId'] for slide in presentation.get('slides')]

# Ittération sur l'ensemble des DT à traiter
for DT in DT_TO_DO[:3]:
    print(f"\n🏢 Traitement de la {DT}")

    # Vérifier si le fichier existe
    output_filename = f'{DT}.pdf'
    if os.path.exists(output_filename):
        print(f"    PDF '{output_filename}' déjà existant, traitement ignoré.")
        continue

    # Dupliquer chaque diapositive
    duplicated_slide_ids = duplicate_slides(TEMPLATE_ID, original_slide_ids)

    try:

        # Identifier les pages à conserver dans le PDF
        pages_to_keep = list(range(len(duplicated_slide_ids)))

        # Etape 1 : Filtrer sur la bonne DT
        df_filteredDT = df[(df['nom_structure'] == DT) | (df['Structure_de_rattachement'].str.endswith(DT))]
        print(f"    Filtration du DataFrame, {len(df_filteredDT)} lignes conservées")

        # Etape 2 : Gestion du Google Slide
        batch_replace_text_on_slides(TEMPLATE_ID, duplicated_slide_ids, make_replacements_textes(DT))

        # Exporter toutes les diapositives en PDF
        export_to_pdf(TEMPLATE_ID, 'temp.pdf')

        # Supprimer les pages inutiles
        remove_unwanted_pages('temp.pdf', output_filename, pages_to_keep)
        print(f"    Création du pdf à partir du Template")

        # Suprimer les slides dupliquées
        delete_slides(TEMPLATE_ID, duplicated_slide_ids)

    except Exception as e:
        print("Une erreur est survenue :")
        traceback.print_exc()

        # Suprimer les slides dupliquées
        delete_slides(TEMPLATE_ID, duplicated_slide_ids)

        break

🏢 Traitement de la DT DES ALPES MARITIMES
    Filtration du DataFrame, 11 lignes conservées
    Création du pdf à partir du Template

🏢 Traitement de la DT DU VAL D'OISE
    Filtration du DataFrame, 13 lignes conservées
    Création du pdf à partir du Template

🏢 Traitement de la DT DE L'ARDECHE
    Filtration du DataFrame, 8 lignes conservées
    Création du pdf à partir du Template

## Graphs et Tableaux

In [30]:
#########################################
# ETAPE 2 : AJOUT DES GRAPH ET TABLEAUX #
#########################################
df = df_struct_agg

full_download = False # Pour télécharger sur son PC tous les rapports

# Ittération sur l'ensemble des DT à traiter
for DT in DT_TO_DO[:3]:
    print(f"\n🏢 Traitement de la {DT}")

    # Vérifier si le fichier existe
    pdf_sortie_name = f"RAPPORT {DT}.pdf"
    if os.path.exists(pdf_sortie_name):
        print(f"    PDF '{pdf_sortie_name}' déjà existant, traitement ignoré.")
        continue

    # Etape 1 : Filtrer sur la bonne DT
    df_filteredDT = df[(df['nom_structure'] == DT) | (df['Structure_de_rattachement'].str.endswith(DT))].copy()
    print(f"    Filtration du DataFrame, {len(df_filteredDT)} lignes conservées")


    # Etape 2 : Ajout des DataFrame et des graphiques
    # Ouverture du pdf associé à la DT
    pdf_source_name = f"{DT}.pdf"
    pdf_sortie = fitz.open(pdf_source_name)

    # Création et intégration du graphique
    generer_graphique_financier(df_struct_agg, DT, "graphique_financier.png")


    # Modification pour faciliter l'affichage
    df_filteredDT = df_filteredDT.fillna("")
    df_filteredDT = df_filteredDT.astype(str)
    df_filteredDT = df_filteredDT.map(lambda x: re.sub(r'^(\d+)\.0$', r'\1', x))

    for config_page in config_pages:
        # Filtrer le DataFrame
        df_filtered = df_filteredDT[config_page["col"]]
        df_filtered = df_filtered.rename(columns=config_page["rename_dict"])
        # Génération de l'image temporaire
        generate_image_from_dataframe(df_filtered, output_filename='temp.png',color=config_page["color"])

        # Ajout du graphique si config_page liée aux données financières
        if config_page["nom"] == "Financier":
            pdf_sortie = ajouter_image_dans_pdf(pdf=pdf_sortie,page_numero=config_page["page"] -1 ,image_path="graphique_financier.png",
                                            hauteur_pt=160,centre_x=200,centre_y=295)

        pdf_sortie = ajouter_image_dans_pdf(pdf=pdf_sortie,page_numero=config_page["page"],image_path="temp.png",
                                        hauteur_pt= 15 * (len(df_filtered) + 1),centre_x=720/2,centre_y=405/2 + 30)


    print(f"    Ajout des DataFrames et graphiques")

    # Enregistrement
    pdf_sortie.save(pdf_sortie_name)
    pdf_sortie.close()

    # Téléchargement dans Colab
    if full_download:
        try:
            files.download(pdf_sortie_name)
        except ImportError:
            pass

🏢 Traitement de la DT DES ALPES MARITIMES
    Filtration du DataFrame, 11 lignes conservées

/tmp/ipython-input-264195369.py:33: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filteredDT = df_filteredDT.fillna("")

    Ajout des DataFrames et graphiques

🏢 Traitement de la DT DU VAL D'OISE
    Filtration du DataFrame, 13 lignes conservées

/tmp/ipython-input-264195369.py:33: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filteredDT = df_filteredDT.fillna("")

    Ajout des DataFrames et graphiques

🏢 Traitement de la DT DE L'ARDECHE
    Filtration du DataFrame, 8 lignes conservées

/tmp/ipython-input-264195369.py:33: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filteredDT = df_filteredDT.fillna("")

    Ajout des DataFrames et graphiques

## Téléchargement

In [31]:
#######################################
# ETAPE 3 : TELECHARGEMENT FORMAT ZIP #
#######################################

make_zip = True # Pour télécharger le .zip sur son PC

if make_zip:
    # 1. Compter le nombre de fichier
    pdf_rapport_count = 0
    for root, dirs, files_list in os.walk("."):
        for file in files_list:
            if file.lower().endswith(".pdf") and "rapport" in file.lower():
                pdf_rapport_count += 1
    print(f"Nombre de fichiers PDF contenant 'RAPPORT' : {pdf_rapport_count}")

    # 2. Dossier source à modifier selon ton Drive
    source_folder = "."
    temp_folder = "/content/rapport_temp"
    zip_path = "/content/rapports.zip"

    # Nettoyage
    if os.path.exists(temp_folder):
        shutil.rmtree(temp_folder)
    if os.path.exists(zip_path):
        os.remove(zip_path)

    # 3. Créer un dossier temporaire pour copier les rapports
    os.makedirs(temp_folder, exist_ok=True)

    # 4. Chercher et copier les PDF contenant "RAPPORT"
    for root, dirs, files_list in os.walk(source_folder):
        # Empêcher os.walk de descendre dans le dossier temporaire
        dirs[:] = [d for d in dirs if os.path.join(root, d) != temp_folder]
        for file in files_list:
            if file.lower().endswith(".pdf") and "rapport" in file.lower():
                full_path = os.path.join(root, file)
                dest_path = os.path.join(temp_folder, file)
                if os.path.abspath(full_path) != os.path.abspath(dest_path):
                    shutil.copy(full_path, dest_path)


    # 5. Créer le fichier ZIP
    with zipfile.ZipFile(zip_path, "w") as zipf:
        for file in os.listdir(temp_folder):
            file_path = os.path.join(temp_folder, file)
            zipf.write(file_path, arcname=file)

    # 6. Télécharger le ZIP
    files.download(zip_path)

    # 7. Nettoyage du dossier temporaire (optionnel)
    shutil.rmtree(temp_folder)

Nombre de fichiers PDF contenant 'RAPPORT' : 3